Disable create service account button if no policy
minio/console pull request #1006
Opened 2021-09-02 19:49 UTC by adfost

<img width="1043" alt="Screen Shot 2021-09-02 at 12 49 06 PM" src="https://user-images.githubusercontent.com/15642172/131907009-7354f21b-d793-4de7-81f4-1d799b233aea.png">

2021-09-03 20:25 UTC, dvaldivia requested changes

2021-09-03 20:25 UTC, dvaldivia commented on portal-ui/src/screens/Console/Users/UserServiceAccountsPanel.tsx
> +      api
why are you making this call twice? here and on line 87? you can merge them

2021-09-03 20:48 UTC, adfost commented on portal-ui/src/screens/Console/Users/UserServiceAccountsPanel.tsx
> +      api
Just fixed this

2021-09-03 21:14 UTC, dvaldivia approved these changes
Tested. LGTM.

2021-09-07 17:16 UTC, bexsoft approved these changes
LGTM, It would be a nice to have, if we show a message explaining why the button is disabled in service accounts page

2021-09-07 22:02 UTC, merged