Share Icon updated
minio/console pull request #1008
Opened 2021-09-03 19:41 UTC by dvaldivia

<img width="128" alt="Screen Shot 2021-09-03 at 12 32 40 PM" src="https://user-images.githubusercontent.com/18384552/132058107-f3f9bb85-1af1-463c-8ce2-1534a6366e00.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-09-03 21:33 UTC, adfost submitted a review, later dismissed

2021-09-06 17:51 UTC, bexsoft requested changes
There is an issue with the active prop inside `TableActionButton.tsx:67`, please either remove  the prop or add it in ShareIcon.tsx

Beside of that works & looks good

2021-09-07 22:44 UTC, bexsoft approved these changes
LGTM

2021-09-07 22:46 UTC, Alevsk approved these changes

2021-09-07 22:48 UTC, merged