Integration Test
minio/console pull request #1012
Opened 2021-09-07 20:01 UTC by dvaldivia

Integration tests meant to be run with a live MinIO server

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-09-07 20:18 UTC, harshavardhana requested changes
Make sure to run these tests as part of GitHub CI/CD, we should be able to run MinIO server locally by just running how our SDKs do the tests.

https://github.com/minio/minio-go/blob/master/.github/workflows/go.yml#L41

2021-09-07 20:18 UTC, dvaldivia commented
@harshavardhana yes! that's the plan, I'm still making some updates to this PR

2021-09-13 17:45 UTC, dvaldivia commented
@harshavardhana done

2021-09-13 17:54 UTC, jinapurapu submitted a review, later dismissed

2021-09-13 19:42 UTC, bexsoft approved these changes

2021-09-13 19:44 UTC, Alevsk approved these changes

2021-09-13 19:45 UTC, merged