Added version card to BasicDashboard
minio/console pull request #1013
Opened 2021-09-07 21:52 UTC by jinapurapu

![Screenshot from 2021-09-07 14-47-48](https://user-images.githubusercontent.com/65002498/132415251-48169575-b90c-4733-90b9-f6582114b94e.png)

2021-09-07 22:12 UTC, dvaldivia requested changes

2021-09-07 22:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx
> +                  subheader={usage ? usage.servers[0].version : 0}
you should not display this card if `usage.servers.length === 0` since, that would cause an NPE if this is shown and there's no servers

2021-09-07 23:15 UTC, jinapurapu commented on portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx
> +                  subheader={usage ? usage.servers[0].version : 0}
I added the length check to the card

2021-09-07 23:35 UTC, dvaldivia approved these changes

2021-09-08 17:59 UTC, Alevsk approved these changes

2021-09-08 18:38 UTC, merged

2021-09-08 18:39 UTC, bexsoft approved these changes
LGTM