Adding volumes page to tenants
minio/console pull request #1019
Opened 2021-09-09 16:40 UTC by adfost

<img width="1048" alt="Screen Shot 2021-09-09 at 9 40 20 AM" src="https://user-images.githubusercontent.com/15642172/132727190-1a93fdf7-644a-4bdf-a1e0-2f9a05aaf81e.png">
Adds a page showing volumes for a tenant.

2021-09-09 19:33 UTC, dvaldivia requested changes

2021-09-09 19:33 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/VolumesSummary.tsx
> +              label: "Tenant",
This column is redundant, please remove it

2021-09-09 19:33 UTC, dvaldivia commented on swagger-operator.yml
> +  /namespaces/{namespace}/tenants/{tenant}/list-pvcs:
the verb `GET` implies listing, and this endpoint is about the `pvc` resource, can you rename it to `/namespaces/{namespace}/tenants/{tenant}/pvcs`

2021-09-09 19:34 UTC, dvaldivia requested changes

2021-09-09 19:34 UTC, dvaldivia commented on operatorapi/operator_volumes.go
> +	listAllPvcs, err2 := clientset.CoreV1().PersistentVolumeClaims("").List(ctx, listOpts)
you can actually filter by namespace here

2021-09-09 23:34 UTC, bexsoft requested changes

2021-09-09 23:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/VolumesSummary.tsx
> +    },
Not sure if this action is needed as you are in the tenant and only redirects you to summary page

2021-09-10 19:06 UTC, dvaldivia requested changes
Make sure you are on prettier `2.3.2`
```
prettier --version
2.3.2
```
and format your files.

2021-09-10 19:06 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/VolumesSummary.tsx
> +    },
+1 this action doesn't make sense for this listing, let's remove it

2021-09-10 23:24 UTC, bexsoft approved these changes
LGTM

2021-09-11 03:45 UTC, dvaldivia approved these changes

2021-09-11 04:13 UTC, merged