Fix Users with + in the name
minio/console pull request #1045
Opened 2021-09-14 17:19 UTC by dvaldivia

Fixes https://github.com/minio/console/issues/1044
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-09-14 17:38 UTC, Alevsk requested changes

2021-09-14 17:38 UTC, Alevsk commented on restapi/admin_users.go
> +		}
this can be moved to the `errors.go` file in where we handle all the errors

2021-09-14 17:57 UTC, dvaldivia commented on restapi/admin_users.go
> +		}
@Alevsk we already handle that error there, and we return a `401` which logsout the user, I'm explicitely handling it here, to avoid a `401` and return a `404`

2021-09-14 18:15 UTC, Alevsk approved these changes

2021-09-14 22:20 UTC, bexsoft approved these changes

2021-09-14 22:23 UTC, merged

2021-09-14 23:41 UTC, soudhaf commented on restapi/admin_users.go
> +		}
@dvaldivia  401 doesn't actually logout the user, at least for this example, you might want to check it
it just redirects you to /login, I can still access the console if I type the address
you get the logout illusion because /login doesn't work as intended check #1050

2021-09-14 23:44 UTC, dvaldivia commented on restapi/admin_users.go
> +		}
the API code on the client side, redirects you to login if it gets a `401` from the server, thus I'm preventing it here for `not found` users

2021-09-15 00:09 UTC, soudhaf commented on restapi/admin_users.go
> +		}
I was saying that 401 doesn't technically losgout users (session is still valid) just a redirect, since this is by design it's all good