List buckets re-design
minio/console pull request #1058
Opened 2021-09-18 01:57 UTC by dvaldivia

New Reactive design 

<img width="1329" alt="Screen Shot 2021-09-17 at 6 55 41 PM" src="https://user-images.githubusercontent.com/18384552/133868508-604a476b-ea53-4163-8b60-1f866fd61116.png">
![2021-09-17 18-55-13 2021-09-17 18_56_38](https://user-images.githubusercontent.com/18384552/133868512-ab535ec9-6f40-490d-bdd0-f20646f9a083.gif)

2021-09-18 02:05 UTC, adfost submitted a review, later dismissed

2021-09-18 02:22 UTC, adfost submitted a review, later dismissed

2021-09-20 16:50 UTC, bexsoft requested changes
Please review TextField component usage under ListBuckets

2021-09-20 16:50 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +              justifyContent="flex-end"
This is not a valid property for mui Grid

2021-09-20 16:50 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +                    labelWidth={0}
This is not a valid property for this component

2021-09-20 17:48 UTC, bexsoft approved these changes
LGTM, Need to delete node_modules & make `yarn install` again to run this.

2021-09-20 18:13 UTC, Alevsk approved these changes

2021-09-20 18:13 UTC, merged