Configure logging
minio/console pull request #1140
Opened 2021-10-22 19:09 UTC by adfost

Add Tenant Logs view and edit modal
<img width="976" alt="Screen Shot 2021-10-28 at 1 25 56 PM" src="https://user-images.githubusercontent.com/15642172/139330358-527e9690-d84d-47ec-806e-321f10092552.png">

2021-11-04 21:53 UTC, jinapurapu commented
GET is being called twice when loading Logs tab
![Screenshot from 2021-11-04 14-51-59](https://user-images.githubusercontent.com/65002498/140425350-99800be4-f79e-497e-a930-3937de59517a.png)

2021-11-09 00:12 UTC, dvaldivia requested changes

2021-11-09 03:28 UTC, adfost commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +      case "tenantLogs":
fixed

2021-11-12 02:50 UTC, dvaldivia submitted a review, later dismissed

2021-11-12 05:37 UTC, bexsoft requested changes
Please review all warnings in yarn server.

2021-11-15 19:44 UTC, dvaldivia requested changes

2021-11-15 19:44 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantLogsModal.tsx
> +    tenantLogValidation = [...tenantLogValidation];
This doesn't make any sense, remove it

2021-11-15 19:44 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +    console.log(error);
Remove this console log

2021-11-15 22:00 UTC, adfost commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +    console.log(error);
done

2021-11-15 22:00 UTC, adfost commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantLogsModal.tsx
> +    tenantLogValidation = [...tenantLogValidation];
done

2021-11-30 05:03 UTC, bexsoft approved these changes

2021-11-30 19:15 UTC, dvaldivia commented
it doesn't let me create a three character service account called `uno` which kubernetes does let me create, thus it's a valid `sa` name

<img width="376" alt="Screen Shot 2021-11-30 at 11 14 17 AM" src="https://user-images.githubusercontent.com/18384552/144112682-468e5f5c-7600-4bd3-95d9-71b5d8f1b46b.png">
<img width="261" alt="Screen Shot 2021-11-30 at 11 13 26 AM" src="https://user-images.githubusercontent.com/18384552/144112685-c1c46cb2-2dc1-4af2-a472-5f902b3dec70.png">

2021-11-30 19:19 UTC, dvaldivia requested changes

2021-11-30 19:19 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantLogs.tsx
> +                        <h4>Labels</h4>
`Warning: validateDOMNesting(...): <h4> cannot appear as a child of <tbody>.`

2021-11-30 19:19 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantLogs.tsx
> +                        <h4>Labels</h4>
all these html elements must be inside a column, it's invalid html if they are inside the body of the table

2021-11-30 19:20 UTC, dvaldivia commented
Please fix all this browser warnings
<img width="525" alt="Screen Shot 2021-11-30 at 11 19 40 AM" src="https://user-images.githubusercontent.com/18384552/144113441-167a7b3f-cd3d-4093-b833-c0fec465b65c.png">
<img width="532" alt="Screen Shot 2021-11-30 at 11 19 49 AM" src="https://user-images.githubusercontent.com/18384552/144113446-9eaac1f2-72d1-40c5-b1f4-36bd74b388e3.png">
<img width="523" alt="Screen Shot 2021-11-30 at 11 19 46 AM" src="https://user-images.githubusercontent.com/18384552/144113448-54d99a10-5a5c-4a53-b907-8c4b90716d82.png">

2021-11-30 19:33 UTC, bexsoft requested changes
It would be nice if delete button gets disabled when only one option is set
<img width="698" alt="Screen Shot 2021-11-30 at 13 28 43" src="https://user-images.githubusercontent.com/33497058/144115154-32a9ce11-b01d-4071-9def-74d4c042ca19.png">

Also found another issue, when you type fast in these fields, DOM gets frozen for a couple of seconds and then all the text appears suddenly


https://user-images.githubusercontent.com/33497058/144115258-3c99bbb8-3a1d-4bb1-97a3-d440c5a6b2e6.mp4


:

2021-11-30 22:06 UTC, Alevsk commented
@adfost please check why the request is triggering twice when someone click on the logs menu

<img width="555" alt="Screen Shot 2021-11-30 at 14 05 33" src="https://user-images.githubusercontent.com/1795553/144135690-7fd7b37e-527f-4eb0-bbc7-19a932b99d67.png">

I have seen a similar behavior on other sections of the application, we are doing exactly the same request twice

2021-11-30 22:34 UTC, Alevsk requested changes

2021-11-30 22:34 UTC, Alevsk commented on operatorapi/operator_tenants.go
> +
```suggestion
	if minTenant.Spec.Log.Image == "" {
		minTenant.Spec.Log.Image = miniov2.DefaultLogSearchAPIImage
	}

	if minTenant.Spec.Log.Db.Image == "" {
		minTenant.Spec.Log.Db.Image = miniov2.LogPgImage
	}
```

Make sure to display the default logSearchApi and Postgres image if the user didn't defined custom images

2021-11-30 22:34 UTC, Alevsk commented
When logsearchApi and Postgres are enabled but user didn't defined an image explicitly we are displaying a blank value in the UI

<img width="911" alt="Screen Shot 2021-11-29 at 20 38 36" src="https://user-images.githubusercontent.com/1795553/144138080-f357ba21-7839-4672-b2cb-f9ffca083f2a.png">
<img width="643" alt="Screen Shot 2021-11-30 at 14 24 51" src="https://user-images.githubusercontent.com/1795553/144138088-e8936588-2221-4c78-85a6-fc1bf89b3b50.png">

We should display display the default

2021-11-30 22:41 UTC, Alevsk commented on operatorapi/operator_tenants.go
> +
With this change now the image version is displayed:

<img width="703" alt="Screen Shot 2021-11-30 at 14 40 21" src="https://user-images.githubusercontent.com/1795553/144139785-8f01aea1-c1ea-4824-8e8c-6a517e7936e3.png">
<img width="627" alt="Screen Shot 2021-11-30 at 14 40 28" src="https://user-images.githubusercontent.com/1795553/144139782-7da23acc-8c6a-4a62-a22f-7676cafd4eed.png">
<img width="646" alt="Screen Shot 2021-11-30 at 14 40 31" src="https://user-images.githubusercontent.com/1795553/144139784-7f000112-e77e-4cc5-ac51-1678016fc925.png">

Besides that the feature works fine.

2022-01-04 00:36 UTC, dvaldivia commented
my tenant doesn't specify a log search image, if I edit and save, the default image is stored in the tenant CR, it shouldn't so that this version is updated with the operator

```
  log:
    audit:
      diskCapacityGB: 5
    db:
      resources: {}
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          name: videos-log
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "5368709120"
          storageClassName: standard
        status: {}
    resources: {}
```

2022-01-11 20:12 UTC, dvaldivia approved these changes

2022-01-11 20:15 UTC, bexsoft approved these changes

2022-01-11 23:18 UTC, merged