Groups page ux update
minio/console pull request #1171
Opened 2021-11-01 06:52 UTC by prakashsvmx

Fixes:
https://github.com/miniohq/engineering/issues/120

UX Link:
https://xd.adobe.com/view/4c56f281-5936-4ad2-9019-b2e230dfc8b4-1905/screen/897d44cb-47ab-4ccf-bac7-d549bd12c59f/specs/

Refactor Groups page as per UX.
- Add/Edit Group
- Assign policies to Groups
- Delete Group

2021-11-01 16:17 UTC, dvaldivia approved these changes

2021-11-01 19:23 UTC, bexsoft requested changes

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/GroupHelpBox.tsx
> +// This file is part of MinIO Console Server
This file is not necessary as HelpBox is only called once with this configuration

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/GroupPageHeader.tsx
> +// This file is part of MinIO Console Server
This file is not necessary as PageHeader is only called once with this configuration

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/GroupPolicies.tsx
> +  const dispatch = useDispatch();
Same case, please lets use HOC instead of calling useDispatch like this

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/ReturnToGroups.tsx
> +// This file is part of MinIO Console Server
This component is not necessary as we already have a component called BackLink. Please use that one instead

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/Styles.tsx
> +// This file is part of MinIO Console Server
These styles can be added into styleLibrary.ts

2021-11-01 19:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/SearchInput.tsx
> +// This file is part of MinIO Console Server
Can we make this component more generic, so we can send the entity name and the onChange function. This way we can implement it in other parts of the application

2021-11-01 19:23 UTC, bexsoft requested changes
Please review groups saving, as we should get redirected to main groups page after saving

2021-11-02 03:17 UTC, prakashsvmx commented
@bexsoft Thank you for the review.
I will be re working on this to make it similar to Users Page.

2021-11-03 11:10 UTC, prakashsvmx commented
Closing this in favour of PR #1183. Since the changes here are no more required.

2021-11-03 11:10 UTC, closed without merging