Optimized List objects v2 for metadata
minio/console pull request #1175
Opened 2021-11-01 20:35 UTC by dvaldivia

We no longer need this check on the APIs.

Updated the Message when creating a bucket in `fs mode`

<img width="791" alt="139634927-8ed1a016-dc2e-417d-bd2f-23623fc347d1" src="https://user-images.githubusercontent.com/18384552/139738341-f4bfcd29-641b-4231-bc16-6e0d8ed2601d.png">
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-11-01 20:36 UTC, harshavardhana approved these changes

2021-11-02 00:11 UTC, bexsoft requested changes

2021-11-02 00:11 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket.tsx
> +                      Distributed Model
```suggestion
                      Distributed Mode
```

2021-11-02 00:42 UTC, bexsoft approved these changes
LGTM

2021-11-02 01:08 UTC, Alevsk approved these changes

2021-11-02 01:33 UTC, harshavardhana approved these changes

2021-11-02 01:34 UTC, merged