Add tags for bucket in console
minio/console pull request #1193
Opened 2021-11-06 03:18 UTC by adfost

Allows users to view/add/delete tags for buckets in console.

<img width="1150" alt="Screen Shot 2021-11-05 at 8 17 54 PM" src="https://user-images.githubusercontent.com/15642172/140596208-ef51fc12-295f-446c-9252-7ae34e5cde97.png">

2021-11-09 03:28 UTC, prakashsvmx commented
Observations:

1. When  tags are set with mc it removes the tags added through UI. (it does not reset if tags are added from UI after setting through mc)
2. We can add spacing ( margin right) for each tag 
![spacing_missing](https://user-images.githubusercontent.com/23444145/140855988-758f48b7-38c5-453e-9f49-ea3b60e92882.png)
3. In UI, the tags are auto capitalized while display. (so looks like inconsistent with mc ) 
![auto_first_letter_capital](https://user-images.githubusercontent.com/23444145/140856547-ccfaeb78-02f4-4d8c-b7c9-00f3a1c92bdc.png)

2021-11-09 03:38 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +          if (res != null && res.details != null) {
Line: 377
this can be simplified with typescript optional chaining.
```javascript
if(res?.details)
```
similarly for line 380
```javascript
if(res?.details?.tags)
```

2021-11-09 03:41 UTC, prakashsvmx reviewed
minor comment

2021-11-09 09:41 UTC, adfost commented
I think the first part of Prakash's commit may be intentional, as mc will take an array of tags and set the list of tags to that, while the UI will append individual tags. 

I resolved the rest of Prakash's comments.

2021-11-10 18:53 UTC, bexsoft requested changes

2021-11-10 18:53 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +
There is an issue with this request, error 500 is shown
<img width="1534" alt="Screen Shot 2021-11-10 at 12 46 45" src="https://user-images.githubusercontent.com/33497058/141175305-8dfcbf87-3748-4777-9f6d-f26990e66ee9.png">
<img width="1511" alt="Screen Shot 2021-11-10 at 12 46 36" src="https://user-images.githubusercontent.com/33497058/141175310-cf61ffa5-64c9-4ba7-a6ad-2a6c41eaefc6.png">

2021-11-10 18:55 UTC, dvaldivia requested changes

2021-11-10 18:55 UTC, dvaldivia commented on restapi/user_buckets.go
> +	bucketTags, _ := client.GetBucketTagging(ctx, bucketName)
you are ignoring the error, please handle it, if there's no tags, `bucketTags` is `nil` and it causes an NPE crashing the whole request

2021-11-10 18:55 UTC, dvaldivia commented on restapi/user_buckets.go
> +		Details:        &models.BucketDetails{Tags: bucketTags.ToMap()},
this causes an NPE if `bucketTags` is nil, make this assignment more defensive

2021-11-10 22:03 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +
after rebase, this is fixed

2021-11-10 22:04 UTC, dvaldivia requested changes

2021-11-10 22:04 UTC, dvaldivia commented on integration/buckets_test.go
> +	request, err = http.NewRequest("GET", "http://localhost:9090/api/v1/buckets", bytes.NewReader([]byte("")))
this is not the right call

2021-11-10 23:32 UTC, dvaldivia commented on integration/buckets_test.go
> +	request, err = http.NewRequest("GET", "http://localhost:9090/api/v1/buckets/test3", bytes.NewReader([]byte("")))
```suggestion
	request, err = http.NewRequest("GET", "http://localhost:9090/api/v1/buckets/test3", nil)
```

2021-11-11 06:41 UTC, harshavardhana commented
> I think the first part of Prakash's commit may be intentional, as mc will take an array of tags and set the list of tags to that, while the UI will append individual tags.
> 

It is added such that tags are not abused, otherwise appending as a logic makes it easy for them to quickly run out of tags - there is a top-level limit on it and it can quickly get confusing. 

But for UI it makes sense to have it appended since it's interactive.

2021-11-11 21:12 UTC, dvaldivia requested changes

2021-11-11 21:12 UTC, dvaldivia commented on restapi/user_buckets.go
> +	// set bucket policy
fix this comment

2021-11-11 21:22 UTC, dvaldivia requested changes

2021-11-11 21:22 UTC, dvaldivia commented on swagger-console.yml
> +        - name: version_id
buckets don't have `version_id` remove this

2021-11-11 22:40 UTC, dvaldivia requested changes

2021-11-11 22:40 UTC, dvaldivia commented on integration/buckets_test.go
> +func formatRequest(r *http.Request) string {
remove this

2021-11-11 22:40 UTC, dvaldivia commented on integration/buckets_test.go
> +func TestGetBucketTags(t *testing.T) {
```suggestion
func TestSetBucketTags(t *testing.T) {
```

2021-11-11 22:40 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/DeleteBucketTagModal.tsx
> +      .invoke("PUT", `/api/v1/buckets/${bucketName}/tags?version_id=${verID}`, {
remove `version_id`

2021-11-11 22:40 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/DeleteBucketTagModal.tsx
> +    const verID = distributedSetup ? versionId : "null";
buckets don't have `versionId`

2021-11-11 22:40 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +          versionId={null}
you never pass a real value to `versionId` remove the prop from the component

2021-11-12 02:14 UTC, bexsoft approved these changes
Works fine, Will create a new ticket to create a new tag component.

2021-11-12 02:36 UTC, dvaldivia approved these changes

2021-11-12 02:36 UTC, merged