Update Box Button Style and move Icons to the Right
minio/console pull request #1199
Opened 2021-11-08 23:38 UTC by dvaldivia

<img width="354" alt="Screen Shot 2021-11-08 at 3 37 54 PM" src="https://user-images.githubusercontent.com/18384552/140835342-767a0d8d-34d3-427d-b949-a733db8d81b2.png">

<img width="269" alt="Screen Shot 2021-11-08 at 3 37 42 PM" src="https://user-images.githubusercontent.com/18384552/140835340-10163a3d-a357-4e96-842b-b886d480eb9d.png">
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-11-08 23:42 UTC, bexsoft requested changes

2021-11-08 23:42 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +                        <a
This needs to be a button as anchor requires an href per ESLint rules

2021-11-08 23:42 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
>                            className={classes.link}
Text size must be added in link class

2021-11-08 23:42 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
> +                              <a
Same case with this anchor

2021-11-08 23:46 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +                        <a
this causes the underlying text to look small o_o

2021-11-08 23:58 UTC, bexsoft approved these changes
LGTM

2021-11-09 00:03 UTC, Alevsk approved these changes

2021-11-09 00:09 UTC, merged