STS session token and console session cookie have same duration
minio/console pull request #1202
Opened 2021-11-09 00:31 UTC by Alevsk

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2021-11-09 17:38 UTC, harshavardhana approved these changes

2021-11-09 18:28 UTC, dvaldivia commented on restapi/utils.go
> +	expiresAt := time.Duration(int64(time.Second) * int64(ranx.Int31n(int32(sessionDuration))))
This random can cause the sessions to expire in 1 second (or a few seconds) up to session duration, do we really need this? we should have a floor

2021-11-09 19:02 UTC, Alevsk commented on restapi/utils.go
> +	expiresAt := time.Duration(int64(time.Second) * int64(ranx.Int31n(int32(sessionDuration))))
This is not random, it will give you always the same session duration time based on the env variable, ie: https://play.golang.org/p/KtJtS9oRQXq

2021-11-09 21:07 UTC, harshavardhana requested changes

2021-11-09 21:07 UTC, harshavardhana commented on restapi/utils.go
> +	expiresAt := time.Duration(int64(time.Second) * int64(ranx.Int31n(int32(sessionDuration))))
This looks wrong in-fact this should be quite simply already in duration when returning.  The value can change if the console is restarted or server is restarted.

2021-11-09 21:07 UTC, harshavardhana commented on restapi/config.go
> +
```suggestion
// GetConsoleCookieDuration returns the default session duration for the console cookie in seconds (defaults to 1h)
func GetConsoleCookieDuration() time.Duration {
	duration, err := time.ParseDuration(env.Get(ConsoleSTSDurationSeconds, "1h"))
	if err != nil {
		duration = 1 * time.hour
	}
	return duration
}
```

It is better done this way @Alevsk we can break away from the current implementation.

2021-11-09 21:07 UTC, harshavardhana commented on restapi/utils.go
> +		Expires:  time.Now().Add(expiresAt * time.Second),
```suggestion
		MaxAge: int(sessionDuration.Seconds()),
		Expires:  time.Now().Add(sessionDuration),
```

Also we can only set one we don't need to set both

```
   If a cookie has both the Max-Age and the Expires attribute, the Max-
   Age attribute has precedence and controls the expiration date of the
   cookie.  If a cookie has neither the Max-Age nor the Expires
   attribute, the user agent will retain the cookie until "the current
   session is over" (as defined by the user agent).
```

https://datatracker.ietf.org/doc/html/rfc6265

2021-11-09 21:10 UTC, adfost commented on restapi/utils.go
> +	expiresAt := time.Duration(int64(time.Second) * int64(ranx.Int31n(int32(sessionDuration))))
Is it best though to use a pseudorandom number generator here? It just doesn't seem like good practice

2021-11-09 21:11 UTC, harshavardhana commented on restapi/utils.go
> +	expiresAt := time.Duration(int64(time.Second) * int64(ranx.Int31n(int32(sessionDuration))))
No it is not @adfost

2021-11-10 03:36 UTC, harshavardhana approved these changes

2021-11-10 03:43 UTC, dvaldivia approved these changes

2021-11-10 05:41 UTC, merged

2021-11-10 08:06 UTC, harshavardhana commented
An integration test has failed after this PR was merged.