New Vertical Tab UX refactor
minio/console pull request #1210
Opened 2021-11-10 11:39 UTC by prakashsvmx

Issue Description:
https://github.com/miniohq/engineering/issues/306

How does it look ? some screens:
---------------------------
![user_details](https://user-images.githubusercontent.com/23444145/141106051-1f08701a-906d-4c24-8eb5-118cb8a8a627.png)

![Object_details_new](https://user-images.githubusercontent.com/23444145/141106057-a1dea237-8108-4962-89af-93e1b14f14ea.png)

![policy_details](https://user-images.githubusercontent.com/23444145/141106062-de02c5c4-d06f-4320-837c-0cf928bd5851.png)

![bucket_details](https://user-images.githubusercontent.com/23444145/141106064-486b4719-2191-4f05-9fc4-bc9c95583f7d.png)

![iam_policy_list](https://user-images.githubusercontent.com/23444145/141106070-0d55d26d-72b5-4b81-9d53-a33b8b81823b.png)

Note:
Icons, and other listing screens will be updated in subsequent PR.

2021-11-11 00:53 UTC, dvaldivia commented
after rebase, the tests should pass @prakashsvmx

2021-11-11 00:58 UTC, dvaldivia commented
Do you think we can make the component expand to the bottom of the screen? to fill all this remaining space

<img width="1392" alt="Screen Shot 2021-11-10 at 4 58 06 PM" src="https://user-images.githubusercontent.com/18384552/141217789-6cbd858b-6561-417b-8183-fad7989d8998.png">

2021-11-11 04:47 UTC, prakashsvmx commented
@dvaldivia 
the tab content area is designed with 100% height that, it will shrink/grow based on the content.
for example: ( the summary section height is larger than available view port height)

![image](https://user-images.githubusercontent.com/23444145/141238791-ed073988-806a-4cc4-a979-4341e6a9d0d3.png)

2021-11-11 13:38 UTC, prakashsvmx commented
@dvaldivia @bexsoft @adfost @Alevsk @jinapurapu  - This is ready for review. PTAL

Impacted Screens:
- MinIO Console
  - Buckets -> New Bucket -> Manage
  - Buckets -> Browse -> Upload Object -> Object Details
  - Users -> User Details
  - Groups -> Group Details
  - IAM Policies -> Policy Details
- Operator Console
  -  Tenant details
  -  Storage

2021-11-11 22:36 UTC, dvaldivia approved these changes
tested. lgtm

2021-11-11 23:18 UTC, bexsoft requested changes
There is an issue in collaved view, tabs container are not center aligned & there is a missing border at the bottom of the container
<img width="574" alt="Screen Shot 2021-11-11 at 15 06 56 copy" src="https://user-images.githubusercontent.com/33497058/141382557-090d4851-eac0-4dbd-92e3-09abda26e572.png">
:

2021-11-11 23:18 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/VolumesSummary.tsx
> +      height: "450px",
This had a calc to make the container full height size

2021-11-11 23:18 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> +      minHeight: "450px",
```suggestion
      minHeight: 450,
```

2021-11-11 23:18 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/UserDetails.tsx
> +      height: "400px",
```suggestion
      height: 400,
```

Please review table sizes, as I see that these values are hardcoded heights.

2021-11-12 02:12 UTC, adfost submitted a review, later dismissed
Handle merge conflicts.

2021-11-12 05:50 UTC, prakashsvmx commented
@bexsoft  Thank you for the detailed review. I have addressed the comments. PTAL.

Quick summary:
1. https://github.com/minio/console/pull/1210#pullrequestreview-804219064 - this is due to the short text. if the text is few characters long, it looks fine.
2. table height has been removed. ( calc is not a viable solution as we have tables at different levels). so iit has been left to the defaults of the `TableWrapper`.

2021-11-12 20:12 UTC, dvaldivia approved these changes
Tested. LGTM.

2021-11-12 20:26 UTC, bexsoft approved these changes
LGTM

2021-11-12 20:26 UTC, merged