Recover Icon. Add Tooltip support for TableActionButton
minio/console pull request #1215
Opened 2021-11-10 22:00 UTC by dvaldivia

<img width="784" alt="Screen Shot 2021-11-10 at 2 00 42 PM" src="https://user-images.githubusercontent.com/18384552/141200720-0b38e2a9-85c9-4fca-9296-efe107cfa136.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-11-10 23:54 UTC, bexsoft requested changes

2021-11-10 23:54 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/TableWrapper/TableWrapper.tsx
>    type: string;
There is a missing change here to support the icon types.
<img width="1058" alt="Screen Shot 2021-11-10 at 17 53 36" src="https://user-images.githubusercontent.com/33497058/141212147-5a1838dc-e8d6-4a83-a299-1baf9dfc1855.png">

2021-11-11 00:43 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/TableWrapper/TableWrapper.tsx
>    type: string;
fixed

2021-11-11 00:47 UTC, bexsoft approved these changes

2021-11-11 00:47 UTC, bexsoft approved these changes
LGTM

2021-11-11 00:57 UTC, bexsoft approved these changes

2021-11-11 06:37 UTC, harshavardhana approved these changes

2021-11-11 06:38 UTC, merged