Bug: Policy statement has trailing slash on bucket name
minio/console pull request #1226
Opened 2021-11-14 03:46 UTC by dvaldivia

Fixes https://github.com/minio/console/issues/1218

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-11-14 04:33 UTC, harshavardhana commented
does this fix #1209 as well?

2021-11-15 04:05 UTC, dvaldivia commented
added a temporary fix for #1209

2021-11-15 17:20 UTC, harshavardhana requested changes

2021-11-15 17:20 UTC, harshavardhana commented on go.mod
> +
looks like a bug @dvaldivia - you are duplicating `require()`

2021-11-15 17:24 UTC, dvaldivia commented on go.mod
> +
removed

2021-11-15 17:36 UTC, Alevsk approved these changes

2021-11-15 17:59 UTC, Alevsk approved these changes

2021-11-15 18:02 UTC, bexsoft approved these changes
LGTM

2021-11-15 20:24 UTC, harshavardhana approved these changes

2021-11-15 20:24 UTC, merged