SecureComponent in React
minio/console pull request #1234
Opened 2021-11-17 09:24 UTC by Alevsk

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2021-11-17 16:43 UTC, harshavardhana requested changes

2021-11-17 16:43 UTC, harshavardhana commented on restapi/user_session.go
> +	}
This entire logic should go to `minio/pkg`  @Alevsk can you explain what do you really want here? why are we not passing the correct bucket names etc.?

2021-11-17 18:27 UTC, Alevsk commented on restapi/user_session.go
> +	}
@harshavardhana based on a policy, i want to get a hashmap containing resources and allowed actions, without having to ask bucket by bucket, ie:

```
{
  "Version": "2012-10-17",
  "Statement": [{
      "Effect": "Deny",
      "Action": [
        "admin:CreateUser"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-readonly/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-admin/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetObject",
        "s3:PutEncryptionConfiguration",
        "s3:GetEncryptionConfiguration"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-encryption/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObjectTagging",
        "s3:GetBucketPolicy",
        "s3:ListBucket",
        "s3:GetObject",
        "s3:GetEncryptionConfiguration",
        "s3:GetReplicationConfiguration",
        "s3:GetBucketObjectLockConfiguration",
        "s3:GetBucketVersioning",
        "s3:GetObjectRetention",
        "s3:GetBucketNotification",
        "s3:GetLifecycleConfiguration"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-readonly-admin/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "admin:ListUserPolicies",
        "admin:ListUsers",
        "admin:ListGroups",
        "admin:GetPolicy"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-readonly-admin/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketPolicy",
        "s3:GetEncryptionConfiguration",
        "s3:GetReplicationConfiguration",
        "s3:GetBucketObjectLockConfiguration"
      ],
      "Resource": [
        "arn:aws:s3:::mybucket-readonly-admin-no-browser/*"
      ]
    },
            {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-write-only-bucket/*"
            ]
        }
  ]
}
```

to

```
{
		"arn:aws:s3:::my-write-only-bucket/*": ["admin:GetPolicy", "admin:ListUsers", "admin:ListUserPolicies", "admin:CreateServiceAccount", "admin:ListGroups", "s3:PutObject"],
		"arn:aws:s3:::mybucket-admin/*": ["admin:GetPolicy", "admin:ListUsers", "admin:ListUserPolicies", "s3:*", "admin:CreateServiceAccount", "admin:ListGroups"],
		"arn:aws:s3:::mybucket-encryption/*": ["admin:ListUsers", "admin:CreateServiceAccount", "s3:GetObject", "s3:ListBucket", "s3:PutEncryptionConfiguration", "admin:GetPolicy", "admin:ListUserPolicies", "admin:ListGroups", "s3:GetEncryptionConfiguration"],
		"arn:aws:s3:::mybucket-readonly-admin-no-browser/*": ["admin:ListUsers", "s3:GetBucketObjectLockConfiguration", "s3:GetBucketPolicy", "s3:GetReplicationConfiguration", "s3:ListBucket", "admin:GetPolicy", "admin:ListUserPolicies", "admin:CreateServiceAccount", "admin:ListGroups", "s3:GetEncryptionConfiguration"],
		"arn:aws:s3:::mybucket-readonly-admin/*": ["admin:ListGroups", "s3:GetReplicationConfiguration", "admin:CreateServiceAccount", "s3:GetBucketObjectLockConfiguration", "admin:GetPolicy", "s3:GetBucketVersioning", "admin:ListUserPolicies", "s3:GetBucketPolicy", "s3:GetObject", "s3:GetEncryptionConfiguration", "s3:GetObjectTagging", "s3:ListBucket", "admin:ListUsers", "s3:GetObjectRetention", "s3:GetBucketNotification", "s3:GetLifecycleConfiguration"],
		"arn:aws:s3:::mybucket-readonly/*": ["admin:CreateServiceAccount", "s3:GetObject", "s3:ListBucket", "admin:ListGroups", "admin:GetPolicy", "admin:ListUsers", "admin:ListUserPolicies"],
		"console-ui": ["admin:GetPolicy", "admin:ListUsers", "admin:ListUserPolicies", "admin:CreateServiceAccount", "admin:ListGroups"]
	}
```

2021-11-17 18:29 UTC, harshavardhana commented on restapi/user_session.go
> +	}
This is something `minio/pkg` should do @Alevsk so that you don't duplicate this code into console.

2021-11-17 20:00 UTC, dvaldivia approved these changes

2021-11-18 16:23 UTC, harshavardhana approved these changes

2021-11-18 16:25 UTC, merged