Adding Download Directory to Console
minio/console pull request #1235
Opened 2021-11-18 00:00 UTC by adfost

Allows directories to be downloaded as zip files from console.

2021-11-18 00:38 UTC, Alevsk requested changes

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> +		fmt.Println(folders)
this can be removed

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> -	if params.Prefix != "" {
Why are we not validating for an empty params.Prefix?

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> +			s3Client, err := newS3BucketClient(session, params.BucketName, objects[i].Name)
Do we need a new s3 client for every object we want to download? why if there are 100,000 objects? check if is possible to reuse 1 client

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> +			}
Validate the other way around, currently your code is swallowing errors

```suggestion
			if err != nil {
                             return nil, prepareError(err)
			}
			buf := new(bytes.Buffer)
			buf.ReadFrom(object)
			f.Write(buf.Bytes())
```

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> +				f.Write(buf.Bytes())
```suggestion
				objectBytes, err := ioutil.ReadAll(object)
				if err != nil {
                                     return nil, prepareError(err)
			        }
				f.Write(objectBytes)
```

2021-11-18 00:38 UTC, Alevsk commented on restapi/user_objects.go
> +		return object, nil
There's no need on duplicating code here, I think your logic can be refactored and just add the special `IsFolder` case inside the existing `if params.Prefix != "" {` code

2021-11-18 00:49 UTC, Alevsk submitted a review, later dismissed

2021-11-18 00:49 UTC, Alevsk commented on restapi/user_objects.go
> +		decodedPrefix, err := base64.StdEncoding.DecodeString(encodedPrefix)
You need to check here `if params.Prefix != "" {` as well, prefix can be empty and in this case the line above

```
name := folder + objects[i].Name[len(prefix)-1:]
```

May cause `NPE`, I think you can refactor your code and just add special logic to either produce a zip file or return a single object, both of them are type `io.ReadCloser` so there should not be a problem

2021-11-18 01:18 UTC, adfost commented on restapi/user_objects.go
> +				f.Write(buf.Bytes())
causes an error, reverting this

2021-11-18 01:25 UTC, adfost commented on restapi/user_objects.go
> +			s3Client, err := newS3BucketClient(session, params.BucketName, objects[i].Name)
Not sure, couldn't find a function to do this?

2021-11-18 01:50 UTC, bexsoft requested changes

2021-11-18 01:50 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    }
This can be rewritten as follows:

```suggestion
    if (object.size > 104857600) {
        // If file is bigger than 100MB we show a notification
        setSnackBarMessage(
          "Download process started, it may take a few moments to complete"
        );
      }

      download(
        bucketName,
        encodeFileName(object.name),
        object.version_id,
        object.name.endsWith("/")
      );
```

2021-11-18 17:52 UTC, dvaldivia requested changes

2021-11-18 17:52 UTC, dvaldivia commented on swagger-console.yml
> +        - name: isFolder
this can be discovered by the server, no need for the client to indicate it, else we have an undefined behavior if someone downloads an object passing `isFolder=true`

2021-11-18 17:54 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    }
fixed

2021-11-18 23:27 UTC, dvaldivia requested changes

2021-11-18 23:27 UTC, dvaldivia commented on restapi/user_objects.go
> +			object, err := downloadObject(ctx, mcClient, params.VersionID)
Not all objects have the same `versionID`

2021-11-18 23:55 UTC, adfost commented on restapi/user_objects.go
> +			object, err := downloadObject(ctx, mcClient, params.VersionID)
outdated

2021-11-18 23:55 UTC, adfost commented on swagger-console.yml
> +        - name: isFolder
done

2021-11-18 23:55 UTC, adfost commented on restapi/user_objects.go
> +			s3Client, err := newS3BucketClient(session, params.BucketName, objects[i].Name)
Fixed

2021-11-23 04:37 UTC, bexsoft commented
Waiting for #1247 to get merged so we can test on 9090

2021-11-23 19:03 UTC, bexsoft requested changes
This works fine with folders, but now when I try to download a single file, I get an empty file 
<img width="260" alt="Screen Shot 2021-11-23 at 13 07 38" src="https://user-images.githubusercontent.com/33497058/143088194-c7739bf0-ca13-4176-bb5f-ce4c7e55f21e.png">

2021-11-23 19:35 UTC, adfost commented
> This works fine with folders, but now when I try to download a single file, I get an empty file <img alt="Screen Shot 2021-11-23 at 13 07 38" width="260" src="https://user-images.githubusercontent.com/33497058/143088194-c7739bf0-ca13-4176-bb5f-ce4c7e55f21e.png">

Thought this was working and tested this but I'll check again.

2021-11-23 21:26 UTC, bexsoft approved these changes
LGTM

2021-11-24 06:02 UTC, prakashsvmx commented
When i click on download at a prefix or any file, it redirects to dashboard: ( Do i need any special setting/env variable to make it work ?) Ubuntu/Chrome


![image](https://user-images.githubusercontent.com/23444145/143182542-3f09eca7-bfa5-4ab4-9b5b-c5577dc9c017.png)


E.g: this is the url when i click on download on a prefix: http://localhost:5005/api/v1/buckets/testbucket/objects/download?prefix=bXktcHJlZml4Lw==

2021-11-24 06:04 UTC, dvaldivia commented
@prakashsvmx make assets and test on port 9090

2021-11-24 06:16 UTC, prakashsvmx approved these changes
Tested 
Single File download
Folder (Prefix) Download

Changes look good to me.

2021-11-25 04:00 UTC, dvaldivia approved these changes

2021-11-25 04:08 UTC, merged

2021-11-30 07:39 UTC, ppizzo commented
Are there any plans for multiple file download inside the same directory? My team is widely using this feature with the old version of the console and the lack of this feature in the new one is preventing us from upgrading.

Many thanks for your support.