Securizing bucket tags
minio/console pull request #1249
Opened 2021-11-22 20:49 UTC by adfost

Bucket tags and/or edit/delete bucket tags disappear when user does not have those permissions.

2021-11-22 23:16 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +                        errorProps={{ disabled: true }}
```suggestion
```

Tested, works fine, just delete `errorProps` from here so this button completely disappears.

2021-11-23 00:15 UTC, Alevsk approved these changes
Tested, works fine

2021-11-23 02:45 UTC, bexsoft requested changes
Would you please help us to remove this warning?
<img width="803" alt="Screen Shot 2021-11-22 at 20 45 07" src="https://user-images.githubusercontent.com/33497058/142964042-3e6ef23b-05c9-42de-a33b-066b282a7046.png">

Beside of that comment, LGTM

2021-11-23 02:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +                                  key={`chip-${index}`}
Please move this key to Secure Component
```suggestion
```

2021-11-23 02:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +                                scopes={[IAM_SCOPES.S3_PUT_BUCKET_TAGGING]}
```suggestion
                                key={`chip-${index}`}
                                scopes={[IAM_SCOPES.S3_PUT_BUCKET_TAGGING]}
```

2021-11-23 02:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +                                scopes={[IAM_SCOPES.S3_PUT_BUCKET_TAGGING]}
<img width="875" alt="Screen Shot 2021-11-22 at 20 46 10" src="https://user-images.githubusercontent.com/33497058/142964146-1617ed9b-3ab2-41d8-8f4c-07007f5a1a0a.png">

2021-11-23 11:47 UTC, prakashsvmx approved these changes
Verified with policies for a user:
- Deny Tagging  ( No Read/Write)
- Read only Tagging ( Read)
- Full Tagging ( Read/Write)

2021-11-23 17:52 UTC, bexsoft approved these changes
LGTM

2021-11-23 17:52 UTC, merged