Configure tenant monitoring tab
minio/console pull request #1254
Opened 2021-11-25 00:11 UTC by jinapurapu

**What does this do?**
Adds Monitoring tab to Tenant Details screen, on which user can enable and disable Prometheus monitoring, and configure the image, database size and service account name. 

Upcoming PRs to add confirmation dialog, additional configuration fields and field validation.

**What does it look like?**
![Screenshot from 2021-11-24 15-36-56](https://user-images.githubusercontent.com/65002498/143327867-29dbb299-04ce-4b6d-9f57-ff5be1f4966c.png)

![Screenshot from 2021-11-24 15-37-15](https://user-images.githubusercontent.com/65002498/143327873-79ea71aa-5826-42e7-8d80-0d57e333d433.png)
![Screenshot from 2021-11-24 15-37-46](https://user-images.githubusercontent.com/65002498/143327882-aedc67d0-0016-438e-b7e5-cb9c2c50f26f.png)
![Screenshot from 2021-11-24 15-38-05](https://user-images.githubusercontent.com/65002498/143327888-8c7aa210-d5a8-4039-ae96-d939c718be26.png)

2021-11-25 04:16 UTC, prakashsvmx commented
@jinapurapu  could you please resolve conflicts ?

2021-11-26 03:00 UTC, dvaldivia requested changes

2021-11-26 03:00 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/MonitoringDetails.tsx
> +              "Prometheus Monitoring Enabled",
use `Enabled` and `Disabled` only, the rest is redundant

2021-11-26 03:00 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/MonitoringDetails.tsx
> +          <FormSwitchWrapper
Add a label for `Prometheus Monitoring`

2021-11-30 05:15 UTC, bexsoft requested changes

2021-11-30 05:15 UTC, bexsoft commented on operatorapi/operator_tenants.go
> +			//StorageClassName:   minInst.Spec.Prometheus.StorageClassName,
Please remove this
```suggestion
```

2021-11-30 05:15 UTC, bexsoft commented on operatorapi/operator_tenants.go
> +	//clientSet, err := cluster.K8sClient(session.STSSessionToken)
Please remove this
```suggestion
```

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +            setNewDiskCapacityGB(event.target.value as any as number);
This can be avoided by converting the value to an integer:
```suggestion
            setNewDiskCapacityGB(parseInt(event.target.value));
```

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +            setNewDiskCapacityGB(event.target.value as any as number);
Another option would be to set `newDiskCapacityGB` state as a string

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +          value={newDiskCapacityGB as any as string}
This can be set as
```suggestion
          value={newDiskCapacityGB.toString()}
```

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +  const [newDiskCapacityGB, setNewDiskCapacityGB] =
This can be stored here in the state as string, then on line 135 you can make just one conversion to number

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +    },
Please review styles list as some of these are not required in this component

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +    },
Please review styles list as some of these are not required in this component

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +            }}
This can be set as a separated function outside the return, this way this function won't be redefined on each re-render

2021-11-30 05:15 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/MonitoringDetails.tsx
> +              "Prometheus Monitoring Disabled",
```suggestion
              "Enabled",
              "Disabled",
```

2021-12-06 10:33 UTC, prakashsvmx commented
@jinapurapu  Could you please resolve the conflicts ?

2021-12-07 20:36 UTC, closed without merging