UX Tiers screen
minio/console pull request #1258
Opened 2021-11-25 12:01 UTC by prakashsvmx

UX Tiers screen

Cosmetic changes for consistency

2021-11-25 22:04 UTC, dvaldivia submitted a review, later dismissed
Tested. LGTM

2021-11-26 05:30 UTC, bexsoft requested changes

2021-11-26 05:30 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
> +        classes={classes}
Please remove this
```suggestion
```

2021-11-26 05:30 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
> +        classes={classes}
Beside of that LGTM

2021-11-26 06:05 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Common/FormComponents/FileSelector/FileSelector.tsx
> +        classes={classes}
Thank you. I have updated.

2021-11-26 17:47 UTC, bexsoft approved these changes
LGTM

2021-11-28 07:13 UTC, dvaldivia approved these changes

2021-11-28 07:13 UTC, merged