Disallow folders to share the same name as existing files.
minio/console pull request #1279
Opened 2021-12-02 03:21 UTC by adfost

Errors if a folder is created that shares the same name as a file. (Fixes https://github.com/minio/console/issues/755) Also fixes a bug where creating a folder with a substring of a file would go to the file: eg if you create a folder with name "tes", and there is already "test.txt", user would be routed to test.txt.

2021-12-02 04:34 UTC, dvaldivia requested changes

2021-12-02 04:34 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/CreateFolderModal.tsx
> +    console.log("here");
Remove

2021-12-06 19:51 UTC, bexsoft requested changes

2021-12-06 19:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/CreateFolderModal.tsx
> +      }
Please do not iterate over all the list of objects to retrieve this, in case user has 1M objects it will take too long and may lead to a crash. Please use ES6 find instead

2021-12-06 19:52 UTC, dvaldivia requested changes

2021-12-06 19:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +  const [fileNames, setFileNames] = useState<string[]>([]);
this is wasting memory, `records` already has this information

2021-12-06 19:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                newFileNames.push(splitPath[splitPath.length - 1]);
this also ignores other folders with the same name ( `name collision`)

2021-12-06 19:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                      let found = false;
add comments explaining what this logic does

2021-12-07 19:21 UTC, dvaldivia commented
In other modals we show the error at the top of the modal itself, instead of the page, can you match this behavior
<img width="803" alt="Screen Shot 2021-12-07 at 11 21 21 AM" src="https://user-images.githubusercontent.com/18384552/145092666-269c02d6-b3a0-4df9-af66-fd158af82d7b.png">
<img width="856" alt="Screen Shot 2021-12-07 at 11 21 09 AM" src="https://user-images.githubusercontent.com/18384552/145092670-524db9ca-ae69-4e87-97ca-d48465f873f1.png">

2021-12-07 20:18 UTC, dvaldivia approved these changes

2021-12-07 20:18 UTC, dvaldivia commented
Tested. LGTM.

2021-12-07 20:33 UTC, bexsoft approved these changes
LGTM

2021-12-07 20:33 UTC, merged