Configure tenant monitoring tab
minio/console pull request #1295
Opened 2021-12-06 20:46 UTC by jinapurapu

Replaces 1254

Adds tab to Tenant Details screen to allow user configuration of Prometheus monitoring.
![Screenshot from 2021-12-06 12-35-46](https://user-images.githubusercontent.com/65002498/144919593-3679a774-4634-4e4c-93ed-80b14aca8bf1.png)
![Screenshot from 2021-12-06 12-36-31](https://user-images.githubusercontent.com/65002498/144919624-795634c9-d9d9-4426-a382-464a0e87bd7b.png)
![Screenshot from 2021-12-06 12-36-49](https://user-images.githubusercontent.com/65002498/144919642-013b04b1-f7cf-4737-8f3f-bb04a05ac05f.png)
![Screenshot from 2021-12-06 12-42-21](https://user-images.githubusercontent.com/65002498/144919661-44c372fb-0bcb-46b9-aaf4-85ddf1ad5f3e.png)

2021-12-07 14:21 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantMonitoring.tsx
> +  const [loadingTenantLogs, setLoadingTenantLogs] = useState<boolean>(false);
`setLoadingTenantLogs`  is not called/used whereas `loadingTenantLogs` state variable is used.

2021-12-07 14:28 UTC, prakashsvmx requested changes
`yarn start` 

warnings could be fixed.

2021-12-08 07:52 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantMonitoring.tsx
> +import { IKeyValue } from "../ListTenants/types";
this unused import could  be removed.

2021-12-08 07:52 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantMonitoring.tsx
> +import { Button, CircularProgress, Divider } from "@mui/material";
`Divider` import is unused. could be removed.

2021-12-08 07:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +  const cleanValidation = (fieldName: string) => {
`cleanValidation` function is unused

2021-12-08 08:00 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +      let err: ErrorResponseHandler = {
could you revisit the statements after return ? because it would never be called.

2021-12-08 08:02 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +  // keyPattern: RegExp;
please clean up commented code

2021-12-08 08:07 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +import React, { useState, Fragment, useEffect } from "react";
`useState` is unused and can be cleaned up.

2021-12-08 08:07 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +  const removeEntry = (index: number) => {
`removeEntry` is unused so it could be removed.

2021-12-08 08:08 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/KeyPairEdit.tsx
> +                if (newValues.length == 1) {
```suggestion
                if (newValues.length ===1) {
```

2021-12-08 08:25 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantMonitoring.tsx
> +import ConfirmationDialog from "./ConfirmationDialog";
Please rebase with master and use `ConfirmDialog` for ux consistency 
```suggestion
import ConfirmDialog from "../../Common/ModalWrapper/ConfirmDialog";
```

2021-12-08 08:26 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantMonitoring.tsx
> +      {confirmOpen && (
based on the new import:
```suggestion
     {confirmOpen && (
        <ConfirmDialog
          isOpen={confirmOpen}
          title={
            prometheusMonitoringEnabled
              ? "Disable Prometheus monitoring?"
              : "Enable Prometheus monitoring?"
          }
          confirmText={prometheusMonitoringEnabled ? "Disable" : "Enable"}
          cancelText="Cancel"
          onClose={() => setConfirmOpen(false)}
          onConfirm={togglePrometheus}
          confirmationContent={
            <DialogContentText>
              {prometheusMonitoringEnabled
                ? "Disabling monitoring will erase any custom values you have used to configure Prometheus monitoring"
                : "Prometheus monitoring will be enabled with default values"}
            </DialogContentText>
          }
        />
      )}
```

2021-12-29 08:22 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/ConfirmationDialog.tsx
> +import React, { useState } from "react";
This file can be removed as in master. as it is not used any more.

2021-12-29 10:46 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Console.tsx
> +    {
Please remove this if it is a duplicate entry.

2021-12-29 10:46 UTC, prakashsvmx approved these changes
The Monitoring option can be above the License.

minor comments. otherwise looks good to me. :+1:

2022-01-04 00:43 UTC, dvaldivia approved these changes

2022-01-04 00:43 UTC, merged