Rewind mode list directory bug fix
minio/console pull request #1297
Opened 2021-12-06 22:59 UTC by adfost

2021-12-06 23:34 UTC, bexsoft commented on restapi/client.go
> +		if strings.HasSuffix(elem[len(elem)-1], "/") {
This is not necessary, HasSuffix returns true of false for the whole string, you don't need to get the lat character for this, https://go.dev/play/p/BlT26DEoXXN

 ```suggestion
		if strings.HasSuffix(elem, "/") {
```

2021-12-06 23:35 UTC, bexsoft requested changes
Please review comments

2021-12-06 23:53 UTC, harshavardhana commented on restapi/client.go
> +		if strings.HasSuffix(elem[len(elem)-1], "/") {
It is an optimization @bexsoft to avoid through the entire string - look for only what you are interested

2021-12-06 23:53 UTC, harshavardhana requested changes

2021-12-06 23:53 UTC, harshavardhana commented on restapi/client.go
> +			return path.Join(elem...) + "/"
```suggestion
			return path.Join(elem...) + slashSeparator
```

Prefer more constants as I mentioned before

2021-12-07 18:41 UTC, dvaldivia requested changes

2021-12-07 18:41 UTC, dvaldivia commented on restapi/client.go
> +		if strings.HasSuffix(elem[len(elem)-1], SlashSeparator) {
this is incorrect, it's a very complciatd `"/" == "/"` or last character, it should be `strings.HasSuffic(elem,SlashSeparator)`

2021-12-07 19:37 UTC, adfost commented on restapi/client.go
> +		if strings.HasSuffix(elem[len(elem)-1], SlashSeparator) {
elem is an array of strings right?

2021-12-07 20:20 UTC, dvaldivia commented on restapi/client.go
> +		if strings.HasSuffix(elem[len(elem)-1], SlashSeparator) {
oh that's right

2021-12-07 21:53 UTC, dvaldivia approved these changes

2021-12-07 23:59 UTC, bexsoft approved these changes
LGTM

2021-12-08 02:01 UTC, merged