UX bucket and object modals
minio/console pull request #1307
Opened 2021-12-08 16:55 UTC by prakashsvmx

UX bucket and object modals

2021-12-09 23:51 UTC, bexsoft requested changes
There are some missing fonts and some labels look inconsistent across pages:
<img width="361" alt="Screen Shot 2021-12-09 at 17 43 31" src="https://user-images.githubusercontent.com/33497058/145493654-06870a00-4f64-4307-ad35-cf7b5bea5ca5.png">
<img width="812" alt="Screen Shot 2021-12-09 at 17 45 12" src="https://user-images.githubusercontent.com/33497058/145493657-a7a4c425-32e1-4957-a759-204c709a7942.png">
<img width="789" alt="Screen Shot 2021-12-09 at 17 45 17" src="https://user-images.githubusercontent.com/33497058/145493660-0e16e1ea-2af9-4a75-8702-3ed4fbd7b0ea.png">
<img width="810" alt="Screen Shot 2021-12-09 at 17 45 31" src="https://user-images.githubusercontent.com/33497058/145493662-cf7f46dd-e316-49ea-a1b3-b939e7c23c5d.png">
<img width="863" alt="Screen Shot 2021-12-09 at 17 42 58" src="https://user-images.githubusercontent.com/33497058/145493666-23201bec-b087-4767-aa39-58f760b2d08f.png">
<img width="840" alt="Screen Shot 2021-12-09 at 17 48 28" src="https://user-images.githubusercontent.com/33497058/145493668-181bda72-46eb-41cc-83ba-c94d9ccb7ab2.png">
<img width="275" alt="Screen Shot 2021-12-09 at 17 43 39" src="https://user-images.githubusercontent.com/33497058/145493670-feee55b9-8ba2-4b8f-9e14-a52e903f2741.png">

Beside of these small details, LGTM

2021-12-10 12:52 UTC, prakashsvmx commented
@bexsoft  thank you for the review and feedback. I have addressed the same . PTAL

2021-12-10 19:57 UTC, bexsoft approved these changes
LGTM

2021-12-10 20:11 UTC, dvaldivia approved these changes

2021-12-10 20:12 UTC, merged