Drag file upload in Object Browser
minio/console pull request #1331
Opened 2021-12-17 23:18 UTC by jinapurapu

**What does it do:** Files dropped into the Object Browser are uploaded to the server.
**How does it look:**

![Screenshot from 2021-12-17 15-15-27](https://user-images.githubusercontent.com/65002498/146618345-812c17cc-a71b-48a4-8f5f-919962376b95.png)
 ![Screenshot from 2021-12-17 15-15-38](https://user-images.githubusercontent.com/65002498/146618344-7f89ae89-4d4d-45bf-8455-80f9d65d04bd.png)

#1053

2021-12-20 11:58 UTC, prakashsvmx submitted a review, later dismissed

2021-12-20 11:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +import {useDropzone} from 'react-dropzone'
`react-dropzone` - Please update/commit `package.json`

2021-12-20 11:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +
Please remove extra blank line.

2021-12-20 11:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    newFiles.push(e.target.files[i])
When we drag and drop a Folder with nested folders it only uploads the files. 
Should the folder structure be preserved ? ( Prefix )

2021-12-20 11:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  onChange={(e) => handleUploadButton(e)}
```suggestion
                  onChange={handleUploadButton}
```
the arguments are same. so an extra function can be avoided

2021-12-20 11:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  onChange={(e) => handleUploadButton(e)}
```suggestion
                  onChange={handleUploadButton}
```
the arguments are same. so an extra function can be avoided

2021-12-20 12:04 UTC, prakashsvmx commented
Please fix the `yarn start` warning 

`src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
  Line 259:6:  React Hook React.useCallback has a missing dependency: 'uploadObject'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

2021-12-20 16:11 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    newFiles.push(e.target.files[i])
this is a great point, perhaps we should add the folder name as a prefix to all the files

2021-12-23 05:45 UTC, dvaldivia requested changes
<img width="309" alt="Screen Shot 2021-12-22 at 9 44 58 PM" src="https://user-images.githubusercontent.com/18384552/147194008-d25e6c46-fa8e-4b55-8e95-4be420d78c5b.png">

There's some weird double slash, I think it can be fixed easily

2021-12-24 05:06 UTC, dvaldivia approved these changes

2021-12-27 04:32 UTC, prakashsvmx commented
@jinapurapu  

- [x] the nested folder gets uploaded as expected with prefix.
- [ ] the `//` is displayed Please check this. 
![image](https://user-images.githubusercontent.com/23444145/147434371-54cdbf3c-ff27-4083-b851-6cfa4c8e7ce5.png)

2021-12-30 18:48 UTC, bexsoft requested changes
There is an issue with folders drag and drop, after I try to do it it seems like files get uploaded but application becomes non responsive and don't show any information about uploads in upload manager. If I stop and start the server again I am able to see the files.

<img width="1717" alt="Screen Shot 2021-12-30 at 12 43 54" src="https://user-images.githubusercontent.com/33497058/147779980-aafd142e-0cc3-4771-93d8-97115a656230.png">

2021-12-30 21:43 UTC, bexsoft approved these changes
Comments will be handled in another PR. LGTM then

2021-12-30 21:43 UTC, merged