Custom Policies for Buckets
minio/console pull request #1332
Opened 2021-12-17 23:21 UTC by adfost

Allow custom policies for buckets in console UI.

<img width="938" alt="Screen Shot 2021-12-17 at 3 21 09 PM" src="https://user-images.githubusercontent.com/15642172/146618636-77235d8a-7964-40d5-9029-bed1c96257ed.png">

2021-12-20 12:20 UTC, prakashsvmx requested changes
Setting Custom policy reverts back to the previous once the modal is closed. So Please take a look.

2021-12-20 12:20 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/BucketSummaryPanel.tsx
> +    console.log(bucketInfo.definition);
Please remove the `console.log`

2021-12-20 12:20 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/SetAccessPolicy.tsx
>  const styles = (theme: Theme) =>
```suggestion
const styles = (theme: Theme) =>
  createStyles({
    codeMirrorContainer: {
      marginBottom: 20,
      paddingLeft: 15,
      "&:nth-child(2) .MuiGrid-root:nth-child(3)": {
        border: "1px solid #EAEAEA",
      },
      "& label": {
        marginBottom: ".5rem",
      },
      "& label + div": {
        display: "none",
      },
    },
    ...modalStyleUtils,
    ...spacingUtils,
  });
```
`codeMirrorContainer`  style needs to be defined. to get a border around it.

2021-12-24 07:31 UTC, kannappanr commented on restapi/user_buckets.go
> +	err = client.setBucketPolicyWithContext(ctx, bucketName, string(policyJSON))
this change is not needed

2021-12-24 10:54 UTC, adfost commented on restapi/user_buckets.go
> +	err = client.setBucketPolicyWithContext(ctx, bucketName, string(policyJSON))
fixed

2021-12-27 04:57 UTC, prakashsvmx submitted a review, later dismissed
LGTM.

2021-12-28 21:19 UTC, bexsoft requested changes

2021-12-28 21:19 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/SetAccessPolicy.tsx
> +    setPolicyDefinition(actualDefinition);
```suggestion
    setPolicyDefinition(actualDefinition);
    setPolicyDefinition(
        actualDefinition ? JSON.stringify(JSON.parse(actualDefinition), null, 4) : ""
      );
```

2021-12-28 21:19 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/SetAccessPolicy.tsx
> +                  value={policyDefinition}
Text formatting needs to be applied:

<img width="952" alt="Screen Shot 2021-12-28 at 15 14 47" src="https://user-images.githubusercontent.com/33497058/147607654-2a35c6ae-b8ab-4df7-be3b-dbd586496ee8.png">

2021-12-28 23:48 UTC, bexsoft approved these changes
LGTM

2021-12-29 01:37 UTC, prakashsvmx approved these changes

2021-12-29 02:21 UTC, merged