Solve the problem of garbled file names when downloading Chinese files
minio/console pull request #1336
Opened 2021-12-20 02:35 UTC by mulzhang

Add file name coding to solve the problem of downloading Chinese file names

2021-12-20 02:46 UTC, harshavardhana approved these changes

2021-12-20 02:53 UTC, mulzhang commented
Import required "net/url"

2021-12-20 02:56 UTC, mulzhang commented
@harshavardhana， Please enter the merge code

2021-12-30 04:15 UTC, harshavardhana requested changes

2021-12-30 04:15 UTC, harshavardhana commented on restapi/user_objects.go
> +			rw.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"%s\"", url.QueryEscape(filename)))
This should be url.PathEscape

2022-01-11 23:13 UTC, harshavardhana commented
Fixed by #1366

2022-01-11 23:13 UTC, closed without merging