Use default MinIO image when no prefered image is given
minio/console pull request #1342
Opened 2021-12-25 14:49 UTC by vadmeste

Do not select the latest MinIO image when deploying a new image, but use
operator's hardcoded instead.

2021-12-26 19:47 UTC, harshavardhana approved these changes

2021-12-27 04:31 UTC, dvaldivia requested changes
I think it's better to control this via environment variable since we definitively want to encourage people to use the latest minio version when they create a new tenant, also if there's no fixed minio image we expose them to unwanted upgrades (upon upgrade of the operator) or unwanted downgrades

2021-12-27 09:14 UTC, vadmeste commented
> I think it's better to control this via environment variable since we definitively want to encourage people to use the latest minio version when they create a new tenant, 

That's not always good. Users will see issues when they create a new tenant and latest MinIO has a breaking change.

The thing is that, what we want is a stable environment whatever happens

> also if there's no fixed minio image we expose them to unwanted upgrades (upon upgrade of the operator) or unwanted downgrades

This looks like Operator issue and not Console.

2021-12-30 21:52 UTC, dvaldivia commented
closed in favor of `CONSOLE_MINIO_IMAGE`

2021-12-30 21:52 UTC, closed without merging