[WIP]Added initial AWS Marketplace support to operator console
minio/console pull request #1347
Opened 2021-12-28 16:48 UTC by bexsoft

## What does this do?

Added initial AWS Marketplace support to operator console

**NOTE:** This requires `CONSOLE_OPERATOR_MP_MODE=aws` env variable to work, if it's not set then default screen will be shown

## How does it look?
<img width="1479" alt="Screen Shot 2021-12-28 at 10 46 23" src="https://user-images.githubusercontent.com/33497058/147588313-f9a8ee39-e31e-42d1-9995-3fa84ac78e9e.png">
<img width="1470" alt="Screen Shot 2021-12-28 at 10 46 16" src="https://user-images.githubusercontent.com/33497058/147588319-69959cca-3b45-4fc0-9fdd-b5439f0b2026.png">

2021-12-28 22:28 UTC, harshavardhana requested changes

2021-12-28 22:28 UTC, harshavardhana commented on operatorapi/consts.go
> +	ConsoleMPMode          = "CONSOLE_OPERATOR_MP_MODE"
```suggestion
	ConsoleMPMode          = "CONSOLE_OPERATOR_MARKETPLACE"
```

Is enough there is no need for MP_MODE

2021-12-28 22:28 UTC, harshavardhana commented on operatorapi/operator_tenants.go
> +			}
we should error out of `val` is `0` @bexsoft and not ignore those cases.

2021-12-28 22:28 UTC, harshavardhana commented on portal-ui/src/common/utils.ts
> +  const k = k8s ? 1000 : 1024;
We do not use 1000 anywhere in on pricing - not sure why this needs to be 1024

2021-12-28 22:28 UTC, harshavardhana commented on portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
> +                : prometheusSelectedStorageClass,
This storage class should default to "MinIO" tenants storageClass if not specifically configured - instead of using "default" ?

2021-12-28 23:12 UTC, dvaldivia commented on operatorapi/operator_tenants.go
> +			}
the thing is the default of int64 is 0

2021-12-28 23:12 UTC, dvaldivia commented on portal-ui/src/common/utils.ts
> +  const k = k8s ? 1000 : 1024;
yeah, we need to make sure verything is base 1024

2021-12-28 23:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
> +                : prometheusSelectedStorageClass,
we are moving away from that, since the storage class from minio might be local volumes

2021-12-28 23:21 UTC, bexsoft commented on portal-ui/src/common/utils.ts
> +  const k = k8s ? 1000 : 1024;
Removed 1000 values

2021-12-29 00:03 UTC, harshavardhana commented on portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
> +                : prometheusSelectedStorageClass,
why is that a problem? @dvaldivia - we are actively promoting directpv now for all applications including databases. Using a different storage class will simply cause confusion here.

2021-12-29 00:04 UTC, harshavardhana commented on operatorapi/operator_tenants.go
> +			}
Then we need to see why we are passing `val=0`  for the Resources.Limits otherwise Resources.Limits should be an empty slice when it is not configured @dvaldivia

2021-12-29 06:56 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/TenantSizeMK.tsx
> +const mapState = (state: AppState) => ({
Destructing can be used to simplify the repetition.

<summary> Example <summary>

<details>

```
 const {
    memoryNode,
    ecParityChoices,
    distribution,
    cleanECChoices,
    sizeFactor,
    ecParity,
    cpuToUse,
    integrationSelection,
    resourcesSize,
    drivesPerServer,
    maxCPUsUse,
    ecParityCalc,
    volumeSize,
    nodes,
  } = state.tenants.createTenant.fields.tenantSize;
  return {
    volumeSize: volumeSize,
    sizeFactor: sizeFactor,
    drivesPerServer: drivesPerServer,
    nodes: nodes,
    memoryNode: memoryNode,
    ecParity: ecParity,
    ecParityChoices: ecParityChoices,
    cleanECChoices: cleanECChoices,
    resourcesSize: resourcesSize,
    distribution: distribution,
    ecParityCalc: ecParityCalc,
    limitSize: state.tenants.createTenant.limitSize,
    selectedStorageType:
      state.tenants.createTenant.fields.nameTenant.selectedStorageType,
    cpuToUse: cpuToUse,
    maxCPUsUse: maxCPUsUse,
    integrationSelection: integrationSelection,
  };
```

<details>

2021-12-29 07:02 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/utils.tsx
> +export interface iDriveSizing {
Since it is an interface type, this can be renamed to start with upper case
`IDriveSizing`

2021-12-29 07:06 UTC, prakashsvmx reviewed
The EC value resets if navigated to another tab. Please have a look. 
otherwise looks good to me. 

( could not test the creating and making a new tenant come alive). any guidance/steps to test would be of great help.

2021-12-29 17:44 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/utils.tsx
> +export interface iDriveSizing {
reminds me of the iPod hahaha

2021-12-29 18:28 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
> +                : prometheusSelectedStorageClass,
it causes problems for setups with multiple storage classes where they might not want to use a local persistent volume for the database, in AWS for example it's better to use the EBS backed PV, same story for Rancher users

2021-12-29 20:50 UTC, harshavardhana commented on portal-ui/src/screens/Console/Tenants/AddTenant/AddTenant.tsx
> +                : prometheusSelectedStorageClass,
@dvaldivia can we discuss this?

2021-12-29 20:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/utils.tsx
> +export interface iDriveSizing {
Changed

2021-12-29 21:23 UTC, bexsoft commented on operatorapi/operator_tenants.go
> +			}
Removed this validation, removed value from request object in case values are not set from the form

2021-12-30 21:52 UTC, dvaldivia approved these changes

2021-12-31 00:43 UTC, harshavardhana approved these changes

2021-12-31 00:43 UTC, merged

2021-12-31 00:44 UTC, harshavardhana commented on operatorapi/config.go
> +}
Its not mode anymore btw @bexsoft  - you can fix the naming in another PR.