Fail PR if Warnings are present in React Code
minio/console pull request #1348
Opened 2021-12-28 20:53 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-12-28 20:58 UTC, harshavardhana submitted a review, later dismissed

2021-12-29 05:35 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Common/FormComponents/QueryMultiSelector/QueryMultiSelector.tsx
> +      currentKeys.length == 1 &&
i believe this is used for testing this PR and can be be reverted.

2022-01-03 06:59 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/FormComponents/QueryMultiSelector/QueryMultiSelector.tsx
> +      currentKeys.length == 1 &&
yes! trying to get this to fail the PR :P

2022-01-07 06:49 UTC, harshavardhana requested changes

2022-01-07 06:49 UTC, harshavardhana commented on .github/workflows/react-no-warnings.yml
> +          if yarn build | grep "Compiled with warnings"; then echo "There are warnings in the code" && exit 1 ; fi
You can use `./check-warnings.sh`

2022-01-07 06:50 UTC, harshavardhana requested changes

2022-01-07 06:50 UTC, harshavardhana commented on .github/workflows/react-no-warnings.yml
> +          if yarn build | grep "Compiled with warnings"; then echo "There are warnings in the code" && exit 1 ; fi
```suggestion
          chmod +x check-warnings.sh  && ./check-warnings.sh 
```

2022-01-07 06:50 UTC, harshavardhana commented on portal-ui/check-warnings.sh
> +fi
```suggestion
fi

```

2022-01-07 06:51 UTC, harshavardhana requested changes

2022-01-07 06:51 UTC, harshavardhana commented on portal-ui/Makefile
> +	./check-warnings.sh
```suggestion
	./check-warnings.sh

```

2022-01-07 06:56 UTC, harshavardhana approved these changes

2022-01-07 12:35 UTC, prakashsvmx approved these changes
LGTM.

2022-01-07 17:14 UTC, Alevsk approved these changes
:+1:

2022-01-07 18:29 UTC, merged