Download Chinese filenames bug fix
minio/console pull request #1366
Opened 2022-01-05 21:40 UTC by adfost

Fixes a bug where Chinese filenames would be messed up when being downloaded.

2022-01-05 21:42 UTC, harshavardhana requested changes

2022-01-05 21:42 UTC, harshavardhana commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +
do we need these logs?

2022-01-05 21:42 UTC, harshavardhana commented on restapi/user_objects.go
> +		escapedName := url.QueryEscape(filename)
```suggestion
		escapedName := url.PathEscape(filename)
```

2022-01-05 22:26 UTC, jinapurapu commented
"+" being appended to end of filenames on download
![Screenshot from 2022-01-05 14-25-07](https://user-images.githubusercontent.com/65002498/148298315-6f91bc93-4d48-4c03-bdf1-d0a1a1586b3f.png)

2022-01-05 22:50 UTC, jinapurapu commented
Filenames being garbled if they contain "+", regardless of Chinese characters
![Screenshot from 2022-01-05 14-49-36](https://user-images.githubusercontent.com/65002498/148300893-eb8d65c2-a7c9-49ae-846d-1ff6d46075ce.png)

2022-01-06 09:29 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
> +import { decodeFileName } from "../../../../../common/utils";
Please remove this unused import.

2022-01-06 09:47 UTC, prakashsvmx submitted a review, later dismissed
Minor comment.

otherwise
Tested. Changes look good to me. :+1:

2022-01-06 17:25 UTC, prakashsvmx approved these changes

2022-01-06 18:19 UTC, harshavardhana approved these changes

2022-01-06 18:20 UTC, harshavardhana commented
Strange unrelated test failure

```
=== RUN   TestGetLicenseInfoFromJWT
2022/01/06 18:19:22 failed to verify license: exp not satisfied
=== RUN   TestGetLicenseInfoFromJWT/error_because_missing_license
=== RUN   TestGetLicenseInfoFromJWT/error_because_invalid_license
2022/01/06 18:19:22 Failed to parse public key: key must be a PEM encoded PKCS1 or PKCS8 key
=== RUN   TestGetLicenseInfoFromJWT/license_successfully_verified
2022/01/06 18:19:22 failed to verify license: exp not satisfied
    config_test.go:80: GetLicenseInfoFromJWT() error = invalid license key, wantErr false
--- FAIL: TestGetLicenseInfoFromJWT (0.09s)
    --- PASS: TestGetLicenseInfoFromJWT/error_because_missing_license (0.00s)
    --- PASS: TestGetLicenseInfoFromJWT/error_because_invalid_license (0.00s)
    --- FAIL: TestGetLicenseInfoFromJWT/license_successfully_verified (0.04s)
```

2022-01-06 18:41 UTC, dvaldivia commented
@harshavardhana that test started failing today, also on other PRs that didn't had go changes

2022-01-06 19:33 UTC, jinapurapu commented
Filenames with "?" are being modified on download
![Screenshot from 2022-01-06 11-32-06](https://user-images.githubusercontent.com/65002498/148440515-9148af6e-f897-4939-be0d-4e4ed1ef4ce1.png)

2022-01-06 20:15 UTC, harshavardhana commented
> TestGetLicenseInfoFromJWT

Well the stored license in the test has expired

```
{
  "alg": "ES384",
  "typ": "JWT"
}.{
  "sub": "kanagaraj+c1@minio.io",
  "cap": 50,
  "org": "Gringotts Inc.",
  "exp": 1641446169.001199,
  "plan": "STANDARD",
  "iss": "subnet@min.io",
  "aid": 1,
  "iat": 1609910169.001199
}.[Signature]
```

Expired @dvaldivia 

```
> Wed Jan 05 2022 21:16:09 GMT-0800 (Pacific Standard Time)
```

2022-01-06 20:16 UTC, harshavardhana commented
NOTE we don't have JWT based license anymore and this test is meaningless..

2022-01-06 20:19 UTC, harshavardhana commented
First step lets remove the test as it's not meaningful and then also remove the JWT parsing code - this is not valid anymore.

2022-01-07 05:04 UTC, prakashsvmx commented
> Filenames with "?" are being modified on download ![Screenshot from 2022-01-06 11-32-06](https://user-images.githubusercontent.com/65002498/148440515-9148af6e-f897-4939-be0d-4e4ed1ef4ce1.png)

@jinapurapu 
This is a browser limitation/bug. it would replace `<` `>` `*` `:` and few more characters if we are downloading. 

An Example:
Line 1: Original File name
Line 2 Downloaded file name

![image](https://user-images.githubusercontent.com/23444145/148494477-4ae44cf7-167e-4a61-85c5-ce0aa6ec71ad.png)

2022-01-07 05:23 UTC, harshavardhana commented
Please rebase @adfost your PR.

2022-01-07 08:15 UTC, prakashsvmx submitted a review, later dismissed
:+1:

2022-01-07 17:11 UTC, Alevsk requested changes

2022-01-07 17:11 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
> +        let rspHeaderDecoded = decodeURIComponent(rspHeader);
```suggestion
        let rspHeaderDecoded = decodeFileName(rspHeader);
```

Please use the `decodeFileName` function located at `portal-ui/src/common/utils.ts`, that function will handle the error when a string cannot be decoded

2022-01-07 19:04 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/utils.ts
> +        let rspHeaderDecoded = decodeURIComponent(rspHeader);
Tried that that doesn't work

2022-01-11 20:05 UTC, bexsoft approved these changes
LGTM

2022-01-11 20:09 UTC, dvaldivia approved these changes

2022-01-11 20:10 UTC, harshavardhana approved these changes

2022-01-11 22:26 UTC, Alevsk approved these changes

2022-01-11 23:11 UTC, merged