Delete all versions
minio/console pull request #1376
Opened 2022-01-11 19:03 UTC by adfost

Add a setting to delete all versions of a file.

2022-01-19 01:13 UTC, dvaldivia requested changes

2022-01-19 01:13 UTC, dvaldivia commented on restapi/user_objects.go
> +		minClient, err := newMinioClient(session)
since the `MinIO client` doesn't have the same problem as the `mc client`, we don't need to instanciate it inside the loop

2022-01-19 01:13 UTC, dvaldivia commented on restapi/user_objects_test.go
> +			err := deleteObjects(ctx, client, client2, tt.args.bucket, tt.args.path, tt.args.versionID, tt.args.recursive, false)
rename the clients to reflect what they are mocking

2022-01-20 13:46 UTC, prakashsvmx approved these changes
Tested 
- Versioned Bucket
- Un versioned  Bucket.

Changes look good to me.  :+1:

2022-01-20 22:28 UTC, jinapurapu approved these changes

2022-01-20 22:36 UTC, cniackz approved these changes

2022-01-21 01:08 UTC, dvaldivia approved these changes

2022-01-21 01:28 UTC, merged