Added Prometheus monitoring CPU and memory selector.
minio/console pull request #1387
Opened 2022-01-13 00:07 UTC by jinapurapu

Added CPU and memory resource request fields for Prometheus monitoring

![Screenshot from 2022-01-12 16-03-03](https://user-images.githubusercontent.com/65002498/149242253-7533acb0-e743-4d20-937e-08dbaae5976b.png)
![Screenshot from 2022-01-12 16-05-20](https://user-images.githubusercontent.com/65002498/149242378-742e025c-05b6-416c-8a1c-2145310ef2fa.png)

2022-01-13 00:38 UTC, dvaldivia requested changes
memory needs a unit, if we request `2` the value should be `2Gi` in the CRD, also if the storage class is empty don't attach it

```
  prometheus:
    diskCapacityGB: 5
    resources:
      requests:
        cpu: "2"
        memory: "2"
    storageClassName: ""
```

2022-01-14 18:13 UTC, dvaldivia approved these changes
LGTM. Tested.

2022-01-14 18:47 UTC, cniackz commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +      pattern: /^[0-9]?(10)?$/,
Why the limit is 10?, where do I can see this limation coming from?

2022-01-14 18:47 UTC, cniackz approved these changes
Looks good to me, just have a question, why the limit of requested CPUs is 10? Can it be 11?

2022-01-14 19:00 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringModal.tsx
> +      pattern: /^[0-9]?(10)?$/,
This limit was from a validation I reused, no actual reason. Please let me know if I should change it.

2022-01-14 19:10 UTC, dvaldivia commented
@cniackz that is a nice catch, why are we limiting to upper 10 @jinapurapu ? it's not hat critical, but it's good to know

2022-01-14 19:15 UTC, merged