Fix for issue #1390 caused by secure component having multiple childs
minio/console pull request #1394
Opened 2022-01-13 19:39 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-01-13 19:58 UTC, bexsoft requested changes

2022-01-13 19:58 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  <>
Please use `<Fragment>` for consistency

2022-01-13 19:59 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  <>
I see most examples on react using this shorthand, we should start adopting it

2022-01-13 20:03 UTC, bexsoft requested changes

2022-01-13 20:03 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  <>
Then we would need to change across all the code. I think Fragment is better because is more clear what this is referring to.

2022-01-13 20:16 UTC, bexsoft approved these changes

2022-01-13 20:16 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  <Fragment>
Thank you! =D

2022-01-14 18:17 UTC, jinapurapu approved these changes

2022-01-14 18:19 UTC, cniackz approved these changes
Learning from it:
A fragment lets us group multiple JSX elements without adding an extra wrapper node.

2022-01-14 18:22 UTC, merged

2022-01-14 18:32 UTC, adfost approved these changes