Logging resources selector
minio/console pull request #1402
Opened 2022-01-15 02:01 UTC by jinapurapu

Adds CPU and memory selector fields to EditLogModal for both Logging and Logging DB, and displays the current value of these resource requests on the TenantLogging screen.

![Screenshot from 2022-01-14 17-53-58](https://user-images.githubusercontent.com/65002498/149604568-f3cbe30a-8abc-4a85-970b-38c661c4430d.png)
![Screenshot from 2022-01-14 17-53-11](https://user-images.githubusercontent.com/65002498/149604569-65f150fc-e304-4480-a6e7-ca85933322ca.png)

2022-01-20 17:50 UTC, jinapurapu commented
![Screenshot from 2022-01-20 09-49-06](https://user-images.githubusercontent.com/65002498/150393875-ef0ce95a-220c-4b6f-9570-947ceab0a9fe.png)
Logging modal layout made consistent with Monitoring modal.

2022-01-21 19:19 UTC, dvaldivia requested changes
While trying to set a cpu 2 and memory 2 I get the following error
```
E: 2022/01/21 11:18:42 original error -> (operator_tenants.go:190: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$')
```
<img width="1392" alt="Screen Shot 2022-01-21 at 11 18 52 AM" src="https://user-images.githubusercontent.com/18384552/150587356-d01bee5d-18b3-4d42-be26-84cd6ee2a061.png">

2022-01-27 00:10 UTC, cniackz commented
While testing this branch today, I found the same problem Daniel found before:

<img width="1552" alt="Screen Shot 2022-01-26 at 7 10 12 PM" src="https://user-images.githubusercontent.com/6667358/151267819-5881d0de-2826-4666-a34b-99043fd446de.png">

The error I got is the same I think:
`detailedMessage: "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
`

2022-01-27 00:14 UTC, cniackz requested changes
While testing this branch today, I found the same problem Daniel found before:

<img width="1552" alt="Screen Shot 2022-01-26 at 7 10 12 PM" src="https://user-images.githubusercontent.com/6667358/151267819-5881d0de-2826-4666-a34b-99043fd446de.png">

The error I got is the same I think:
`detailedMessage: "quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
`
And I am testing on the latest commit for this pull request:
```
commit 74fcc55c59676bb555327cefefe43b35c61749fe (HEAD -> logging-resources-selector)
Merge: e8c3329c 41b34645
Author: Prakash Senthil Vel <23444145+prakashsvmx@users.noreply.github.com>
Date:   Mon Jan 24 05:52:49 2022 +0000

    Merge branch 'master' into logging-resources-selector
```

2022-01-27 16:56 UTC, cniackz submitted a review, later dismissed

2022-01-27 17:04 UTC, cniackz commented on operatorapi/operator_tenants.go
> +	/*if minTenant.Spec.Log.Image == "" {
Wonder if it is better to remove comments as this code is no longer used.

2022-01-27 18:36 UTC, jinapurapu commented on operatorapi/operator_tenants.go
> +	/*if minTenant.Spec.Log.Image == "" {
I removed the commented lines.

2022-01-27 20:01 UTC, cniackz approved these changes

2022-02-01 04:55 UTC, dvaldivia approved these changes

2022-02-01 05:17 UTC, merged