Added new features tu bucket replication rules panel
minio/console pull request #1412
Opened 2022-01-19 03:45 UTC by bexsoft

## What does this do?

- Added Edit option for replication
- Sorted by priority in replication list
- Fixed an issue where storage class was not saved for replication rule

**NOTE:** Please test add & edit rules roughly as both modules were changed

## How does it look?
<img width="1207" alt="Screen Shot 2022-01-18 at 21 42 59" src="https://user-images.githubusercontent.com/33497058/150060034-4cc43ee2-adb5-437a-a958-de89659ad01c.png">
<img width="1395" alt="Screen Shot 2022-01-18 at 21 42 49" src="https://user-images.githubusercontent.com/33497058/150060038-85d40b39-7f8e-41ff-aa35-28da3ec50375.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-01-19 03:55 UTC, dvaldivia approved these changes
LGTM.

2022-01-19 05:54 UTC, dvaldivia approved these changes

2022-01-19 06:06 UTC, poornas requested changes

2022-01-19 06:06 UTC, poornas commented on models/multi_bucket_replication_edit.go
> +
@bexsoft , model should also have a flag for replicating existing objects

2022-01-20 01:19 UTC, bexsoft commented on models/multi_bucket_replication_edit.go
> +
Fixed, added support to replicate existing objets & added selectors to form

2022-01-20 03:48 UTC, dvaldivia commented
@poornas PTAL

2022-01-20 05:26 UTC, bexsoft commented
Added selector for metadata replication. Regarding removing the validation for not deleting the last rule, minio-go sdk still contains this restriction. Will keep this behavior for now
<img width="776" alt="Screen Shot 2022-01-19 at 23 25 44" src="https://user-images.githubusercontent.com/33497058/150278876-dcf2d3f7-ddd2-4585-ad01-6ced490aa8a9.png">
<img width="789" alt="Screen Shot 2022-01-19 at 23 25 37" src="https://user-images.githubusercontent.com/33497058/150278881-abfa0eee-699d-4b4d-b225-23f7bb515c97.png">
<img width="758" alt="Screen Shot 2022-01-19 at 23 25 28" src="https://user-images.githubusercontent.com/33497058/150278885-d319b3d3-c50c-4564-8f1f-d28f6af49455.png">
<img width="974" alt="Screen Shot 2022-01-19 at 23 20 57" src="https://user-images.githubusercontent.com/33497058/150278888-d371edb3-ff49-4902-9f46-72b1e3d27ef9.png">
<img width="668" alt="Screen Shot 2022-01-19 at 23 19 05" src="https://user-images.githubusercontent.com/33497058/150278889-234d4741-7c55-4e7a-9814-36773e0b67f5.png">

2022-01-20 07:18 UTC, poornas approved these changes

2022-01-20 07:29 UTC, dvaldivia approved these changes

2022-01-20 07:29 UTC, merged