add header linter to avoid license header mistakes
minio/console pull request #1414
Opened 2022-01-19 08:56 UTC by harshavardhana

2022-01-21 20:08 UTC, dvaldivia requested changes

2022-01-21 20:08 UTC, dvaldivia commented on operatorapi/auth/operator_test.go
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-01-21 20:08 UTC, dvaldivia commented on operatorapi/error.go
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-01-21 20:08 UTC, dvaldivia commented on pkg/apis/networking.gke.io/v1beta1/doc.go
> -/*
some code will break without this

2022-01-21 21:16 UTC, harshavardhana commented on pkg/apis/networking.gke.io/v1beta1/doc.go
> -/*
there is no code that depends on this AFAICS

2022-01-21 21:16 UTC, harshavardhana commented on operatorapi/error.go
> +// Copyright (c) 2021 MinIO, Inc.
is this a new file? since its old file kept the appropriate year.

2022-01-21 21:16 UTC, harshavardhana commented on operatorapi/auth/operator_test.go
> +// Copyright (c) 2021 MinIO, Inc.
is this a new file? since its old file kept the appropriate year.

2022-01-21 22:42 UTC, dvaldivia commented on operatorapi/error.go
> +// Copyright (c) 2021 MinIO, Inc.
aah, I thought we should be updating any file we touched

2022-01-25 00:36 UTC, harshavardhana commented
PTAL @dvaldivia @bexsoft

2022-01-25 18:35 UTC, harshavardhana commented
Is this supposed to fail?

```
 2/77 failed (3m 25s)
child_process.js:660
    throw err;
    ^

Error: Command failed: xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe "chrome:headless" portal-ui/tests/permissions/ --skip-js-errors
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/home/runner/work/_actions/DevExpress/testcafe-action/latest/index.js:64:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 2676,
  stdout: null,
  stderr: null
}```

2022-01-25 18:37 UTC, dvaldivia commented
@harshavardhana we have a couple of UI tests that are failing, we can fix those

2022-01-25 18:38 UTC, dvaldivia approved these changes

2022-01-25 18:40 UTC, Alevsk approved these changes

2022-01-25 18:45 UTC, jinapurapu approved these changes

2022-01-25 18:48 UTC, merged