Fix the Admin UI Tests
minio/console pull request #1423
Opened 2022-01-20 20:17 UTC by dvaldivia

This fixes the admin.ts tests for the new menu
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-01-20 20:56 UTC, bexsoft requested changes

2022-01-20 20:56 UTC, bexsoft commented on Makefile
> +	test-apply-permissions
This target is being detected as a command during execution, I think you'll need to create one more target that includes both `test-apply-permissions` & `initialize-permissions`

2022-01-20 20:56 UTC, bexsoft commented on portal-ui/src/screens/Console/Menu/Menu.tsx
> +        // },
Please remove this as well as their imports:
```
src/screens/Console/Menu/Menu.tsx
  Line 61:3:  'InspectMenuIcon' is defined but never used   @typescript-eslint/no-unused-vars
  Line 62:3:  'ProfileMenuIcon' is defined but never used   @typescript-eslint/no-unused-vars
  Line 75:8:  'CallHomeMenuIcon' is defined but never used  @typescript-eslint/no-unused-vars
```

2022-01-20 23:46 UTC, kaankabalak commented
Hi @dvaldivia, I have fixed the 4 tests that were returning errors locally on the commit below, please feel free to cherry-pick it into your branch:
https://github.com/kaankabalak/console/commit/554d843122ca7e8a1adf2bce7389eb9b875a8e7f

2022-01-21 00:50 UTC, cniackz approved these changes

2022-01-21 00:50 UTC, Alevsk approved these changes

2022-01-21 00:50 UTC, merged

2022-01-21 00:56 UTC, bexsoft reviewed
LGTM