Pods Summary UI improvements
minio/console pull request #1449
Opened 2022-01-25 01:38 UTC by adfost

A few improvements to pods UI:
1. There is now a search bar, making the Pods Summary like Volumes Summary.
2. Pod name field has been widened, in order to show the full pod names.
3. An unnecessary newline was removed from Volumes Summary.

2022-01-25 03:52 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodsSummary.tsx
> +        <TextField
please use the existing `SearchBox` component.
```jsx
<SearchBox
            placeholder={"Search Users"}
            onChange={setFilter}
            overrideClass={classes.searchField} // use this to define custom width if required.
          />
```

2022-01-25 03:57 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodsSummary.tsx
> +          id="search-resource"
please avoid using id attribute. if it is intended for testing purposes,we could use data-test-id

as one of the [best practices](https://testcafe.io/documentation/402836/guides/basic-guides/best-practices#selector-strategy) recommended by TestCafe.

>Use custom attributes (like data-testid) whose sole purpose is to identify items with TestCafe. These attributes are unlikely to change during development, so you don’t need to rewrite your Selectors as frequently.

2022-01-25 03:59 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodsSummary.tsx
> +    elementItem.name.includes(filter)
we could make it case insensitive filter if the values have mixed case.

2022-01-27 06:34 UTC, prakashsvmx commented
@adfost Please resolve the conflicts.

2022-02-01 10:00 UTC, prakashsvmx submitted a review, later dismissed
LGTM :+1:

2022-02-02 19:32 UTC, bexsoft requested changes

2022-02-02 19:32 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +        <SearchBox
Please include the value prop as it is a new requirement for SearchBox
```suggestion
        <SearchBox
            value={filter}
```

2022-02-02 19:32 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/VolumesSummary.tsx
> +        <SearchBox
Same case:
```suggestion
        <SearchBox
            value={filter}
```

2022-02-09 20:04 UTC, cniackz requested changes
Let's investigate why tests are failing prior the merge.
If they are failing due to this PR, then let's fix it.
Thanks!

2022-02-17 00:51 UTC, dvaldivia commented
react code has warnings

2022-02-22 21:08 UTC, bexsoft approved these changes
LGTM

2022-02-22 21:11 UTC, dvaldivia approved these changes
tested. lgtm.

2022-02-22 21:25 UTC, jinapurapu commented
![Screenshot from 2022-02-22 13-23-52](https://user-images.githubusercontent.com/65002498/155221934-0fec112d-abd1-4e14-8972-7ca3a37caf72.png)
should this text be updated to "No matching pools found"?

2022-02-22 22:15 UTC, bexsoft approved these changes

2022-02-22 22:19 UTC, jinapurapu approved these changes

2022-02-23 07:14 UTC, prakashsvmx approved these changes
Tested. LGTM

2022-02-23 17:35 UTC, cniackz approved these changes

2022-02-23 17:37 UTC, merged