Service account policy UI 2
minio/console pull request #1519
Opened 2022-02-04 19:04 UTC by adfost

UI for getting service account policies
<img width="797" alt="Screen Shot 2022-02-04 at 11 04 33 AM" src="https://user-images.githubusercontent.com/15642172/152587954-88f280fe-d043-422d-8b7f-232fabbd6681.png">
.

2022-02-04 23:40 UTC, dvaldivia requested changes

2022-02-04 23:40 UTC, dvaldivia commented on portal-ui/src/screens/Console/Account/ServiceAccountPolicy.tsx
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-02-05 01:13 UTC, harshavardhana commented
Do we validate if its an invalid JSON in the UI?

2022-02-05 01:14 UTC, harshavardhana commented
Like do we react to what they pasted? - the way we are highlighting it has JSON, are we able to validate/parse it as well?

2022-02-08 03:39 UTC, prakashsvmx commented
@adfost Please resolve the conflicts.

2022-02-08 15:22 UTC, prakashsvmx approved these changes
Changes look good to me. :+1: 

Few minor changes can be part of #1525

2022-02-08 17:10 UTC, Alevsk commented
> Like do we react to what they pasted? - the way we are highlighting it has JSON, are we able to validate/parse it as well?

I think that highlight happens automatically by the `CodeMirror` library, currently theres no validation in place to check if whatever the user input its a valid json, however if the json is wrong minio will return an error and we will display that on the UI

2022-02-08 17:25 UTC, Alevsk submitted a review, later dismissed

2022-02-08 18:38 UTC, dvaldivia requested changes
When I create a SA without policy, it shows me a weird policy, if the SA has no policy, we should show empty
<img width="1390" alt="Screen Shot 2022-02-08 at 10 37 18 AM" src="https://user-images.githubusercontent.com/18384552/153053709-fa70acd2-18c4-4e52-b6e6-b407068635d2.png">

2022-02-09 02:39 UTC, dvaldivia approved these changes
Tested. LGTM

2022-02-09 03:35 UTC, prakashsvmx approved these changes
LGTM.

2022-02-09 06:52 UTC, merged