Inspect API
minio/console pull request #1540
Opened 2022-02-10 11:02 UTC by prakashsvmx

Inspect API  ( `mc admin inspect [--encrypt] <alias> <path>` )

Steps to Test:
- With Encryption  flag
   - `.enc` file will be generated along with a decryption key 
   - use `inspect` tool and enter the decryption key to get the `.zip` file
   - use `xl-meta` tool  to verify the contents of `.zip` file
- Without Encryption flag
   - use `xl-meta` tool  to verify the contents of `.zip` file.

2022-02-10 17:23 UTC, bexsoft requested changes

2022-02-10 17:23 UTC, bexsoft commented on restapi/admin_inspect.go
> +	})
Is better to set this code as an independent method, Please follow the pattern from other endpoints Eg.

```
api.UserAPIUpdateBucketLifecycleHandler = user_api.UpdateBucketLifecycleHandlerFunc(func(params user_api.UpdateBucketLifecycleParams, session *models.Principal) middleware.Responder {
		err := getEditBucketLifecycleRule(session, params)
		if err != nil {
			user_api.NewUpdateBucketLifecycleDefault(int(err.Code)).WithPayload(err)
		}

		return user_api.NewUpdateBucketLifecycleOK()
	})
```

2022-02-10 21:06 UTC, dvaldivia commented
When I reach an invalid path (invalid bucket or objects) , I get status response `200` instead of `404`

2022-02-10 21:34 UTC, harshavardhana commented
> When I reach an invalid path (invalid bucket or objects) , I get status response `200` instead of `404`

The API is not designed to get 404 it's expected to see failures since it's a "debugging" API - Do not think of it like S3 API as it is allowed to download any path any file in its RAW form. 

Like you can download

- alias/.minio.sys/format.json
- alias/.minio.sys/** (recursively download all .minio.sys data from all nodes all drives)
- alias/bucket/path/** (recursively download all xl.meta, part.1 data from all nodes all drives)
- alias/bucket/path/object/* (just download files at the path - non-recursive but all files at this path)
- alias/bucket/path/object/<uuid>/part.1 (download just part.1 for a specific object data-dir at uuid)

The response is a Zip stream, so failures are allowed and normal.

2022-02-10 21:35 UTC, harshavardhana commented
The UI should be designed to support these requirements

2022-02-11 00:55 UTC, dvaldivia approved these changes

2022-02-11 04:24 UTC, prakashsvmx commented on restapi/admin_inspect.go
> +	})
@bexsoft  thank you for the suggestion. I will update it.

2022-02-11 05:37 UTC, prakashsvmx commented on restapi/admin_inspect.go
> +	})
I have updated and tested . PTAL

2022-02-15 21:39 UTC, bexsoft approved these changes
LGTM

2022-02-15 21:46 UTC, dvaldivia approved these changes

2022-02-16 00:14 UTC, merged