Added delete bucket lifecycle rule capability
minio/console pull request #1547
Opened 2022-02-10 21:32 UTC by bexsoft

## What does this do?

Adds bucket lifecycle delete rule capability

## How does it look?

<img width="1286" alt="Screen Shot 2022-02-10 at 15 29 05" src="https://user-images.githubusercontent.com/33497058/153499919-ea77e001-fa3c-4bce-aa47-efcf85874f16.png">
<img width="751" alt="Screen Shot 2022-02-10 at 15 29 01" src="https://user-images.githubusercontent.com/33497058/153499925-02475ab3-4755-415c-8fa9-aa9e07f994a3.png">
<img width="1185" alt="Screen Shot 2022-02-10 at 15 28 58" src="https://user-images.githubusercontent.com/33497058/153499929-f01db215-24cf-40c5-b700-711de7459c3f.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-02-10 22:46 UTC, Alevsk requested changes

2022-02-10 22:46 UTC, Alevsk commented on restapi/user_buckets_lifecycle.go
> +			lfcCfg.Rules[n] = rule
could `lfcCfg.Rules[n]` be undefined?

2022-02-10 22:50 UTC, bexsoft commented on restapi/user_buckets_lifecycle.go
> +			lfcCfg.Rules[n] = rule
In this case no, as we are iterating in the range of Rules list. So if the list is empty, that loop won't be executed

2022-02-10 22:59 UTC, jinapurapu approved these changes

2022-02-10 23:05 UTC, Alevsk submitted a review, later dismissed

2022-02-10 23:57 UTC, jinapurapu commented
I get these errors after deleting the last rule, is that correct
![Screenshot from 2022-02-10 15-57-04](https://user-images.githubusercontent.com/65002498/153516978-ff560353-0f98-4379-a3ee-b9275ad90df4.png)
![Screenshot from 2022-02-10 15-56-50](https://user-images.githubusercontent.com/65002498/153516982-e5467a6e-0222-47f7-8683-73a9fd37c67b.png)
?

2022-02-11 00:15 UTC, bexsoft commented
> I get these errors after deleting the last rule, is that correct ![Screenshot from 2022-02-10 15-57-04](https://user-images.githubusercontent.com/65002498/153516978-ff560353-0f98-4379-a3ee-b9275ad90df4.png) ![Screenshot from 2022-02-10 15-56-50](https://user-images.githubusercontent.com/65002498/153516982-e5467a6e-0222-47f7-8683-73a9fd37c67b.png) ?

Yes, this error is expected as we are returning 404 when no rules are fetched. you can test this by opening this page in a clean bucket

2022-02-11 00:22 UTC, dvaldivia approved these changes

2022-02-11 00:25 UTC, merged