Release v0.14.5
minio/console pull request #1550
Opened 2022-02-10 21:59 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-02-10 22:05 UTC, harshavardhana requested changes

2022-02-10 22:05 UTC, harshavardhana commented on Makefile
> +	@git add k8s/operator-console/standalone/console-deployment.yaml
Rewrite this 

```suggestion
release: swagger-gen
	@echo "Generating Release: $(RELEASE)"
	@make assets
	@yq -i e '.spec.template.spec.containers[0].image |= "minio/console:$(RELEASE)"' k8s/operator-console/base/console-deployment.yaml
	@yq -i e 'select(.kind == "Deployment").spec.template.spec.containers[0].image |= "minio/console:$(RELEASE)"' k8s/operator-console/standalone/console-deployment.yaml
	@git add -u .
```

2022-02-10 22:06 UTC, cniackz approved these changes

2022-02-10 22:37 UTC, kaankabalak submitted a review, later dismissed

2022-02-10 22:42 UTC, harshavardhana requested changes

2022-02-10 22:42 UTC, harshavardhana commented on Makefile
> +	@git add -u .
```suggestion
	@git add -u .

```

2022-02-11 00:21 UTC, harshavardhana approved these changes

2022-02-11 01:05 UTC, bexsoft approved these changes

2022-02-11 01:06 UTC, harshavardhana approved these changes

2022-02-11 01:06 UTC, merged