Update tenant creation credentials JSON
minio/console pull request #1559
Opened 2022-02-11 20:45 UTC by jinapurapu

**What does this do:** Changes tenant creation credentials JSON output to the format :
     {	
	      "url" : "http://localhost:5000",
	      "accessKey" : "YJ0RI0F4R5HWY38MD873",
	      "secretKey" : "OHz5CT7xdMHiXnKZP0BmZ5P4G5UvWvVaxR8gljLG",
              "api": "s3v4",
	      "path": "auto",
}

Addresses https://github.com/miniohq/engineering/issues/270

2022-02-11 20:57 UTC, adfost reviewed
Fails permissions tests.

2022-02-11 21:29 UTC, harshavardhana requested changes

2022-02-11 21:29 UTC, harshavardhana commented on operatorapi/consts.go
> +	ConsoleMinIOServer     = "CONSOLE_MINIO_SERVER"
This may be not present in console operator @jinapurapu - you need to get this information from the "tenant" spec.

2022-02-12 00:45 UTC, harshavardhana requested changes
Are we not planning to change this for Service Accounts UI? @jinapurapu

2022-02-12 00:45 UTC, harshavardhana commented on operatorapi/consts.go
> +	ConsoleMinIOServer     = "CONSOLE_MINIO_SERVER"
You need to remove this though @jinapurapu - this is not used in operator

2022-02-16 19:49 UTC, dvaldivia approved these changes
Tested. LGMT.

2022-02-16 19:49 UTC, dvaldivia commented
@harshavardhana this works on both regular `console` and `operator ui`

2022-02-16 21:52 UTC, harshavardhana commented
> @harshavardhana this works on both regular `console` and `operator ui`

👍🏽

2022-02-16 21:52 UTC, harshavardhana approved these changes

2022-02-16 21:52 UTC, merged