Add test for Put Objects legalhold status end point in Console API
minio/console pull request #1577
Opened 2022-02-15 18:28 UTC by cniackz

Fixes https://github.com/miniohq/engineering/issues/385

Add test for `Put Object's legalhold status` end point in Console API

2022-02-16 12:07 UTC, prakashsvmx commented
@cniackz Please resolve conflicts.

2022-02-16 17:31 UTC, bexsoft approved these changes

2022-02-16 22:30 UTC, kaankabalak commented on integration/buckets_test.go
> +				assert.Fail("Error creating the bucket")
Should we change the error message here, as from what I have understood, we're not creating a bucket here?

2022-02-17 15:21 UTC, cniackz commented on integration/buckets_test.go
> +				assert.Fail("Error creating the bucket")
Good point, I will resolve conflict and change the error message too.
Thanks!

2022-02-17 20:31 UTC, adfost requested changes
Fix merge conflicts.

2022-02-22 17:23 UTC, dvaldivia approved these changes

2022-02-22 17:39 UTC, merged