Added delete all replication rules capability
minio/console pull request #1579
Opened 2022-02-15 20:00 UTC by bexsoft

## What does this do?
Added delete all replication rules capability

## How does it look?
![2022-02-15 13-28-29 2022-02-15 13_29_21](https://user-images.githubusercontent.com/33497058/154139568-c67ea821-a9d0-4e15-a32b-8767e4efb727.gif)
![2022-02-15 12-57-43 2022-02-15 12_58_56](https://user-images.githubusercontent.com/33497058/154139575-95ab874b-2672-4410-9e35-581eb9f678b4.gif)

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-02-15 20:02 UTC, harshavardhana commented
We should perhaps ask for more confirmation @bexsoft - asking them to type "yes" or "delete"

2022-02-15 20:17 UTC, bexsoft commented
> We should perhaps ask for more confirmation @bexsoft - asking them to type "yes" or "delete"

Fixed @harshavardhana 
<img width="658" alt="Screen Shot 2022-02-15 at 14 14 56" src="https://user-images.githubusercontent.com/33497058/154142079-3af884b3-c6a0-49a1-af22-b368f11e9831.png">
<img width="744" alt="Screen Shot 2022-02-15 at 14 14 48" src="https://user-images.githubusercontent.com/33497058/154142080-fe756b2a-7e69-4d44-a9ff-5c620e3cd61f.png">

2022-02-15 21:45 UTC, dvaldivia requested changes

2022-02-15 21:45 UTC, dvaldivia commented on swagger-console.yml
> +        - name: delete_all
I think it's better to have a dedicated `delete_all` call

2022-02-16 00:11 UTC, bexsoft commented on swagger-console.yml
> +        - name: delete_all
Resolved

2022-02-16 00:18 UTC, dvaldivia approved these changes

2022-02-16 01:13 UTC, adfost approved these changes

2022-02-16 01:14 UTC, merged