UI for Inspect
minio/console pull request #1583
Opened 2022-02-16 11:15 UTC by prakashsvmx

UI for Inspect
Closes https://github.com/miniohq/engineering/issues/480

2022-02-16 18:10 UTC, dvaldivia requested changes
do we need `js-cookie` and `file-saver` ?

2022-02-16 18:10 UTC, dvaldivia submitted a review, later dismissed

2022-02-16 18:11 UTC, cniackz commented
Is it possible to add one `testcafe` for the UI addition?

2022-02-16 18:12 UTC, cniackz reviewed
Is it possible to add a `testcafe` test for this added UI?

2022-02-16 18:17 UTC, dvaldivia commented
that's a great idea @cniackz

2022-02-17 18:13 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tools/Inspect.tsx
> +                        drives in a zip file.
```suggestion
                        drives in a zip file:
```

2022-02-17 18:13 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tools/Inspect.tsx
> +                        and optionally encrypt the downloaded zip.
```suggestion
                        and optionally encrypt the downloaded zip:
```

2022-02-17 18:13 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tools/Inspect.tsx
> +                        This can be an expensive operation use it with caution.
```suggestion
                        To Download recursively all objects at a prefix:
                        NOTE: This can be an expensive operation use it with caution.
```

2022-02-17 19:12 UTC, bexsoft reviewed
LGTM, Please handle @jinapurapu comments, Thank you!

2022-02-18 17:58 UTC, cniackz submitted a review, later dismissed
This change looks good to me. Later on we can add the test if is not added here!...

2022-02-19 04:48 UTC, prakashsvmx commented
Marking this as WIP as I will remove the packages and add some test in this PR itself.

2022-02-19 12:56 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tools/Inspect.tsx
> +                        drives in a zip file.
Thank you @jinapurapu . I have updated.

2022-02-19 13:08 UTC, prakashsvmx commented
@dvaldivia @bexsoft @cniackz @jinapurapu Thank you for the review and feedback. I have updated accordingly.  PTAL

2022-02-22 17:22 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-02-22 17:29 UTC, bexsoft approved these changes
LGTM

2022-02-22 18:05 UTC, merged