Adding IDs for Operator tests
minio/console pull request #1599
Opened 2022-02-17 20:24 UTC by cniackz

2022-02-17 21:25 UTC, dvaldivia approved these changes

2022-02-17 22:38 UTC, kaankabalak approved these changes

2022-02-17 23:13 UTC, bexsoft requested changes

2022-02-17 23:13 UTC, bexsoft commented on portal-ui/src/icons/DocumentationIcon.tsx
> +    id={"documentation-icon"}
Not sure if we should ass ids directly to the icons as you can have more than one icon of the same type on a single page. (Eg. buckets). I recommend to add ids only to buttons and clickable elements

2022-02-18 01:41 UTC, dvaldivia commented on portal-ui/src/icons/DocumentationIcon.tsx
> +    id={"documentation-icon"}
that's true, perhaps we should add them at button level? @cniackz

2022-02-18 17:01 UTC, cniackz commented on portal-ui/src/icons/DocumentationIcon.tsx
> +    id={"documentation-icon"}
Yeah, make sense, we can do that and look for other `CSS` selector when needed.
Actually, I just found `xpath` is also supported, so at the end we can become creative in terms of selectors.
Let me update this PR to do so.
Thank you guys for the review!

2022-02-18 18:31 UTC, cniackz commented on portal-ui/src/screens/Console/Common/GenericWizard/WizardPage.tsx
> +                id={"wizard-button"+btn.label}
That's a fair point, I did not noticed that I did that, it is good enough with this line below:
`id={"wizard-button"+btn.label}`

2022-02-18 18:48 UTC, kaankabalak approved these changes

2022-02-18 20:20 UTC, adfost approved these changes

2022-02-18 20:39 UTC, jinapurapu approved these changes

2022-02-19 04:08 UTC, bexsoft approved these changes
LGTM

2022-02-19 04:08 UTC, merged