UX error alert banner
minio/console pull request #1620
Opened 2022-02-24 07:04 UTC by prakashsvmx

UX error alert banner to be consistent with SUBNET

Impacted Screens:
- Login Page
- All screens with Error banner
- Modal with server side error

Closes https://github.com/miniohq/engineering/issues/519

2022-02-24 16:51 UTC, oscarocastellanos submitted a review, later dismissed
LGTM

2022-02-24 17:26 UTC, dvaldivia approved these changes

2022-02-24 17:26 UTC, dvaldivia commented on portal-ui/src/icons/AlertCloseIcon.tsx
> +      stroke="#FFF"
we should remove the hardcoded colors so this icon can be styled from external CSS. Also add it to `IconsScreen.tsx` and visit to `/icons` to see if it can be styled like the rest of the icons

2022-02-24 17:26 UTC, dvaldivia commented on portal-ui/src/icons/AlertCloseIcon.tsx
> +      stroke="#FFF"
Can we also get the icon with a viewport="0 0  256 256" @oscarocastellanos ? I dont' mind if we update this icon on a separate PR

2022-02-24 17:29 UTC, prakashsvmx commented on portal-ui/src/icons/AlertCloseIcon.tsx
> +      stroke="#FFF"
I used the icon from SUBNET. I will update it. Thank you for the suggestion.

2022-02-24 17:46 UTC, bexsoft requested changes
In some cases we may have two errors coming from backend (A generic error response and an advanced error). I think it would be better to add some logic to show only one of another, because I think error may get confusing. What do you think @oscarocastellanos ?

<img width="1270" alt="Screen Shot 2022-02-24 at 11 41 44" src="https://user-images.githubusercontent.com/33497058/155578971-7e9d1731-3685-49f5-a786-660706c19134.png">

2022-02-24 17:50 UTC, bexsoft requested changes

2022-02-24 17:50 UTC, bexsoft commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +      <CssBaseline />
Are we using this component?

2022-02-24 18:23 UTC, oscarocastellanos commented on portal-ui/src/icons/AlertCloseIcon.tsx
> +      stroke="#FFF"
> In some cases we may have two errors coming from backend (A generic error response and an advanced error). I think it would be better to add some logic to show only one of another, because I think error may get confusing. What do you think @oscarocastellanos ?
> 
> <img alt="Screen Shot 2022-02-24 at 11 41 44" width="1270" src="https://user-images.githubusercontent.com/33497058/155578971-7e9d1731-3685-49f5-a786-660706c19134.png">



> In some cases we may have two errors coming from backend (A generic error response and an advanced error). I think it would be better to add some logic to show only one of another, because I think error may get confusing. What do you think @oscarocastellanos ?
> 
> <img alt="Screen Shot 2022-02-24 at 11 41 44" width="1270" src="https://user-images.githubusercontent.com/33497058/155578971-7e9d1731-3685-49f5-a786-660706c19134.png">

I do agree @bexsoft. I would suggest that the more advanced error overrides the generic error.

2022-02-24 18:49 UTC, oscarocastellanos commented on portal-ui/src/icons/AlertCloseIcon.tsx
> +      stroke="#FFF"
> Can we also get the icon with a viewport="0 0 256 256" @oscarocastellanos ? I dont' mind if we update this icon on a separate PR

PR is opened here: https://github.com/miniohq/engineering/issues/548

2022-02-25 04:05 UTC, prakashsvmx commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +      <CssBaseline />
Yes this is required for the css reset of the entire page . post login it is used in Console.tsx as well.

2022-02-28 16:37 UTC, cniackz commented
Two things:
1. Is error below related to these changes?
` ✖ Start New Diagnostic button exists after Diagnostic is completed` <-- Will re-run the workflow to see if it can be reproduced again.
2. Let's resolve the conflict to proceed.

2022-03-02 01:07 UTC, bexsoft approved these changes
LGTM

2022-03-02 01:09 UTC, dvaldivia approved these changes

2022-03-02 03:36 UTC, merged