UX License page with registered state
minio/console pull request #1650
Opened 2022-03-02 12:14 UTC by prakashsvmx

UX License page with registered state
![MinIO-Console_Registered](https://user-images.githubusercontent.com/23444145/156359547-7e0f71b9-275a-41a4-9c46-1555c33846d1.png)

2022-03-02 15:41 UTC, oscarocastellanos approved these changes
LGTM

2022-03-02 19:13 UTC, Alevsk approved these changes

2022-03-02 19:23 UTC, jinapurapu requested changes
![Screenshot from 2022-03-02 10-42-48](https://user-images.githubusercontent.com/65002498/156433706-0e35dd77-5781-4824-a72e-b862f64448d4.png)
Text and lines overhang at some window sizes

2022-03-03 04:27 UTC, prakashsvmx commented
@jinapurapu Thank you for the feedback. :+1: 
 I have updated it to have a scrollbar when required.  PTAL

2022-03-03 21:42 UTC, dvaldivia approved these changes

2022-03-03 21:58 UTC, merged