Adding access_key to audit logs
minio/console pull request #1652
Opened 2022-03-02 18:36 UTC by adfost

Adds access_key to audit logs

2022-03-02 22:37 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-03-02 22:39 UTC, dvaldivia requested changes
![2022-03-02 14-38-26 2022-03-02 14_39_05](https://user-images.githubusercontent.com/18384552/156461847-d6310709-5b5e-4281-894c-92c57d433660.gif)

filtering by access key doesn't work

2022-03-07 21:37 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-03-07 21:38 UTC, bexsoft approved these changes
LGTM

2022-03-07 21:54 UTC, merged