Region list select in Add Tier screen
minio/console pull request #1657
Opened 2022-03-03 15:57 UTC by prakashsvmx

Region list select in Add Tier screen

Closes https://github.com/miniohq/engineering/issues/561

Data Source:
Azure: Got through the following command:
`az account list-locations --query "sort_by([].{label:displayName, value:name}, &label)" --output json`

S3: List Extarcted from
https://docs.aws.amazon.com/general/latest/gr/s3.html

GCS: List Extracted from 
https://cloud.google.com/storage/docs/locations#location-r

If value not found , it can still be added as an arbitary value in the dropdown.

2022-03-03 16:36 UTC, dvaldivia requested changes
It's working great, just one comment, can we match the font size as other fields?
<img width="471" alt="Screen Shot 2022-03-03 at 8 34 44 AM" src="https://user-images.githubusercontent.com/18384552/156609054-b28c7efd-fa24-4a78-b1d9-9ed775f8d586.png">

2022-03-03 16:53 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-03-03 18:18 UTC, jinapurapu requested changes

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/RegionSelect.tsx
> +import React from "react";
```suggestion
// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import React from "react";
```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/RegionSelectWrapper.tsx
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/azure-regions.json
> +[
```suggestion

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

[
```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/gcs-regions.json
> +[
```suggestion
// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

[
```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/gcs-regions.json
> +]
```suggestion
]

```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/s3-regions.json
> +[
```suggestion
// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

[
```

2022-03-03 18:18 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/s3-regions.json
> +]
```suggestion
]

```

2022-03-04 04:06 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/s3-regions.json
> +[
@jinapurapu Thank you for the review and feedback. 
JSON spec does not allow comments. So i have converted this to a ts file and added comments.

2022-03-07 17:39 UTC, dvaldivia approved these changes

2022-03-07 21:43 UTC, jinapurapu commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/gcs-regions.ts
> +import { RegionEntry } from "./types";
Add header

2022-03-07 22:33 UTC, jinapurapu approved these changes

2022-03-08 02:00 UTC, bexsoft approved these changes

2022-03-08 02:35 UTC, merged