New Login Design
minio/console pull request #1675
Opened 2022-03-07 21:04 UTC by dvaldivia

<img width="1392" alt="Screen Shot 2022-03-04 at 3 13 44 PM" src="https://user-images.githubusercontent.com/18384552/157117494-d154330f-b4c4-4b92-9c13-453525249cdb.png">
<img width="612" alt="Screen Shot 2022-03-07 at 1 02 37 PM" src="https://user-images.githubusercontent.com/18384552/157117450-8bfecaff-1a2f-4cdc-bf69-bd8784f20a03.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-03-07 21:05 UTC, oscarocastellanos submitted a review, later dismissed
LGTM

2022-03-07 22:00 UTC, jinapurapu requested changes

2022-03-07 22:00 UTC, jinapurapu commented on swagger-operator.yml
> +        type: string
```suggestion
        type: string
        
```

2022-03-07 22:00 UTC, jinapurapu commented on swagger-console.yml
> +        type: string
```suggestion
        type: string
        
```

2022-03-07 22:37 UTC, jinapurapu approved these changes

2022-03-08 00:00 UTC, bexsoft requested changes
Do we need to modify all these files (879)?

2022-03-08 01:30 UTC, adfost submitted a review, later dismissed

2022-03-08 01:46 UTC, Alevsk approved these changes
tested, works fine

2022-03-08 01:53 UTC, adfost approved these changes
Tested, LGTM. However, I was just wondering, should this be further split into 2 PRs? You seem to have changed a lot of utils from cluster.* to utils.*, in addition to changing the login.

2022-03-08 01:56 UTC, bexsoft approved these changes
Need to review the "Welcome to" tag as I think that was meant to be removed from the login pages. Beside of that LGTM

2022-03-08 01:56 UTC, merged