Removed underscore from tenant creation credentials
minio/console pull request #1683
Opened 2022-03-08 17:31 UTC by jinapurapu

**What does this do:**

Changes tenant creation credentials to remove underscores, now in the format

    "accessKey": "15JVL8xGfQa8AZqh",
      "secretKey": "Flk1QUrqZItYRRlDQWE8B4TOoprjnSDo",

2022-03-08 17:33 UTC, harshavardhana submitted a review, later dismissed

2022-03-08 17:33 UTC, harshavardhana commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
>                          },
this doesn't work @jinapurapu - this returns the values in this format

```
{
    console: [
    ]
}
```

this is not parsable by `mc`

2022-03-08 20:06 UTC, bexsoft requested changes

2022-03-08 20:06 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                          secretkey: consoleCreds.secretKey,
I think this should be in camelCase

```suggestion
                          accessKey: consoleCreds.accessKey,
                          secretKey: consoleCreds.secretKey,
```

2022-03-08 20:06 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                        secretkey: itemMap.secretKey,
Same Case:

```suggestion
                        accessKey: itemMap.accessKey,
                        secretKey: itemMap.secretKey,
```

2022-03-10 14:27 UTC, prakashsvmx commented
Observation:
When we cutomize the accesskey and secretKey and download,
It could not be imported. as the url is not present in the json  @jinapurapu 

- Create  New Service Account -> Customize Credentials ->   `test-svc-acct` and `test-svc-acct`  -> Create -> Download.

`mc alias import sa-creds ./sa_credentials.json`
```
mc: <ERROR> Invalid URL. URL `undefined` for MinIO Client should be of the form scheme://host[:port]/ without resource component.
```


`cat sa_credentials.json `

```json
{"url":"undefined","accessKey":"test-svc-acct","secretKey":"test-svc-acct","api":"s3v4","path":"auto"}
```

-  Similarly Customize + Restrict with Policy and download and observe that the url is undefined.

- [x] the default Credentials are successfully imported.

2022-03-10 23:12 UTC, dvaldivia approved these changes

2022-03-11 01:35 UTC, bexsoft requested changes

2022-03-11 01:35 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                    consoleExtras = cCreds[0];
Map can return more than one element in some cases (Eg. tenant creation with multiple users)

2022-03-11 03:13 UTC, harshavardhana commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                    consoleExtras = cCreds[0];
Generating multiple credentials files is actually useless @bexsoft it's not easily readable and also copy-paste friendly.

Anyone making an S3 API call only ever uses a single credential we should provide an option to download the first credential - as well as have a mechanism to download individual credentials separately. 

They should not be piled together in a single JSON file since those are quite meaningless. 

This JSON file should be treated like a `gcs-credentials.json` file that can be directly used with gcloud. In our case its `mc`. 

So currently without changing much of the UI - potentially choosing to show that you are downloading a single credential is enough since that itself is broken today. 

However potential for a UI change is also now visible because we do create multiple credentials during tenant provisioning but have no way to download them individually.

2022-03-11 07:50 UTC, prakashsvmx commented
@jinapurapu 
is the operator tenant creation credential download also updated to be `mc` import compatible ?   
otherwise changes look good to me :+1: 

I tried created a new tenant and downloaded the credentials. and it looks like the following

```
{"console":[{"url":"http://minio.new-tenant.svc.cluster.local:80","access_key":"t8yNwEmjW6iv7ZIS","secret_key":"VlyZRi2MIB1nwyP5bpJoprNmxoJLYWrf","api":"s3v4","path":"auto"}]}
```

2022-03-11 08:04 UTC, prakashsvmx approved these changes
Tested. changes look good to me. :+1: 

- Service Accounts,
- User Service accounts
- Operator Tenant Credentials.

2022-03-11 17:05 UTC, jinapurapu commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                    consoleExtras = cCreds[0];
I will work on a UI to download the entire credentials list in another PR

2022-03-11 17:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +                    consoleExtras = cCreds[0];
@harshavardhana I mention this because this component is used in multiple modules to handle different scenarios. 

@jinapurapu Ok, I think it would be better to make independent components to show credentials. This can be handled in another PR as you mention. Will approve this PR

2022-03-11 17:36 UTC, bexsoft approved these changes
A new component will be created to handle the multiple credentials scenario and replace it in create tenant screen.

2022-03-16 04:01 UTC, merged