Release v0.15.2
minio/console pull request #1696
Opened 2022-03-10 23:19 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-03-10 23:44 UTC, harshavardhana approved these changes

2022-03-10 23:59 UTC, bexsoft approved these changes

2022-03-11 00:25 UTC, Alevsk requested changes
Lets include this one on the release https://github.com/minio/console/pull/1698

2022-03-11 08:24 UTC, harshavardhana approved these changes

2022-03-11 09:08 UTC, harshavardhana commented
```
✖ Start New Diagnostic button exists after Diagnostic is completed

   1) AssertionError: expected false to be truthy

      Browser: Chrome 98.0.4758.102 / Linux 0.0

         80 |    .useRole(roles.diagnostics)
         81 |    .navigateTo("http://localhost:9090/support/diagnostics")
         82 |    .click(elements.startDiagnosticButton)
         83 |    .wait(2000)
         84 |    .expect(elements.startNewDiagnosticButton.exists)
       > 85 |    .ok();
         86 |});
         87 |
         88 |test("Start New Diagnostic button is clickable after
      Diagnostic is completed", async (t) => {
         89 |  await t
         90 |    .useRole(roles.diagnostics)

         at <anonymous>

   (/home/runner/work/console/console/portal-ui/tests/permissions/diagnostics.ts:85:6)
         at <anonymous>

   (/home/runner/work/console/console/portal-ui/tests/permissions/diagnostics.ts:23:71)
         at __awaiter

   (/home/runner/work/console/console/portal-ui/tests/permissions/diagnostics.ts:19:12)
         at <anonymous>
      (/home/runner/work/console/console/portal-ui/tests/permissions/diagnostics.ts:[78](https://github.com/minio/console/runs/5508307978?check_suite_focus=true#step:11:78):[86](https://github.com/minio/console/runs/5508307978?check_suite_focus=true#step:11:86))```
is this a known failure @prakashsvmx ?

2022-03-11 10:15 UTC, prakashsvmx commented
@harshavardhana 

>is this a known failure

Looks like a random failure . I re-ran the job and it completed.

2022-03-11 10:15 UTC, prakashsvmx approved these changes

2022-03-11 10:35 UTC, merged