Adding delete versions test
minio/console pull request #1701
Opened 2022-03-11 01:35 UTC by adfost

Adding test case for delete all versions.

2022-03-11 01:42 UTC, cniackz requested changes
Good that CSS selector is working, but remember we need to make this shorter by adding `id` or `class` or as @bexsoft  mentioned, if we can't add `class` then at least we should provide shorter selector and use nth property to click over the desired file, try something like below for first file:
```js
div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(1)
```
Or if it is the second then:
```js
div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(2)
```
and so on and so forth

2022-03-11 01:42 UTC, cniackz commented on portal-ui/tests/permissions/bucketDeleteAllVersions.ts
> +      .click("#object-list-wrapper > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.css-15j76c0 > div > div:nth-child(1) > div > div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div
Good that CSS selector is working, but remember we need to make this shorter by adding `id` or `class` or as @bexsoft  mentioned, if we can't add `class` then at least we should provide shorter selector and use nth property to click over the desired file, try something like below for first file:
```js
div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(1)
```
Or if it is the second then:
```js
div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(2)
```
and so on and so forth

2022-03-11 01:43 UTC, cniackz commented on portal-ui/tests/permissions/bucketDeleteAllVersions.ts
> +      .click("#object-list-wrapper > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-12.css-15j76c0 > div > div:nth-child(1) > div > div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div
Maybe it can get even smaller if we can add dynamic id over last div... need to investigate the best option 👍

2022-03-11 19:17 UTC, dvaldivia requested changes

2022-03-11 19:17 UTC, dvaldivia commented on portal-ui/tests/constants/timestamp.txt
> +1646960285
remove this file

2022-03-11 20:40 UTC, kaankabalak commented on portal-ui/tests/permissions/bucketDeleteAllVersions.ts
> +fixture("For user with Bucket Delete permissions").page("http://localhost:9090");
Hi @adfost, let's change this text as we're running the test for a user that has Read and Write permissions (i.e., we're using the `bucketReadWrite` role):

```suggestion
fixture("For user with Bucket Read & Write permissions").page("http://localhost:9090");
```

2022-03-11 20:55 UTC, kaankabalak commented
The test run on GitHub Actions seems to be failing as it can't locate the deleteButton specified on line 42. However, I have verified that the test works locally. Could you force push your changes again so that we can rerun the tests @adfost?

```
For user with Bucket Delete permissions
 ✖ All versions of an object can be deleted from a bucket

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('button:enabled')
         |   .withExactText('Delete')

      Browser: Chrome 98.0.4758.102 / Linux 0.0

         [37](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:37) |      .click(testBucketBrowseButton)
         [38](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:38) |      // Upload object to bucket
         [39](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:39) |      .setFilesToUpload(elements.uploadInput,
      "../uploads/test.txt")
         [40](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:40) |      .wait(5000)
         [41](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:41) |
      .click("div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid >
      div > div:nth-child(1)")
       > [42](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:42) |      .click(elements.deleteButton)
         [43](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:43) |      .click(elements.switchInput)
         [44](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:44) |
      .click(Selector("button:enabled").withExactText("Delete").nth(1))
         [45](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:45) |  }).after(async (t) => {
         [46](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:46) |    // Cleanup created bucket and corresponding uploads
         [47](https://github.com/minio/console/runs/5516154101?check_suite_focus=true#step:11:47) |    await functions.cleanUpBucketAndUploads(t,
      "bucketdelete3");

         at <anonymous>

   (/home/runner/work/console/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:42:8)
         at <anonymous>

   (/home/runner/work/console/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:23:71)
         at __awaiter

   (/home/runner/work/console/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:19:12)
         at <anonymous>
      (/home/runner/work/console/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:32:76)
```

2022-03-11 21:43 UTC, kaankabalak approved these changes
Approving as test runs successfully locally. The failure seems to be related to GitHub Actions and we can take a look at what's causing this on a subsequent PR.

2022-03-11 21:46 UTC, dvaldivia requested changes

2022-03-11 21:46 UTC, dvaldivia commented on portal-ui/tests/permissions/bucketDeleteAllVersions.ts
> +      .wait(5000)
I think waiting 5 seconds is too much for a text file, perhaps `1000` is better, even if it's just to wait for the table to render, its stoo much

2022-03-11 22:28 UTC, dvaldivia commented
@kaankabalak the test pass locally if it's not run as headless, but if it's run headless it fails, perhaps due to react virtualized? cc @bexsoft

2022-03-11 22:28 UTC, dvaldivia requested changes

2022-03-11 22:28 UTC, dvaldivia commented on portal-ui/tests/permissions/bucketDeleteAllVersions.ts
> +      .click(Selector("button:enabled").withExactText("Delete").nth(1))
this test is not expecting anything from the result after clicking, add something to validate the file is gone

2022-03-11 22:38 UTC, kaankabalak commented
> @kaankabalak the test pass locally if it's not run as headless, but if it's run headless it fails, perhaps due to react virtualized? cc @bexsoft

Not sure, the test also passed locally for me when I ran it in headless mode in Chrome:

```
kaan@Kaans-MacBook-Pro-2 console % testcafe chrome:headless portal-ui/tests/permissions/bucketDeleteAllVersions.ts --skip-js-errors 
 Running tests in:
 - Chrome 99.0.4844.51 / macOS 10.15.7

 For user with Bucket Delete permissions
 ✓ All versions of an object can be deleted from a bucket


 1 passed (11s)

```

2022-03-11 22:49 UTC, dvaldivia commented
seems like the test will fail headless on node `17` but not on `16`, and it's only finding that delete button @kaankabalak @adfost @bexsoft 
```
➜ nvm use 17
Now using node v17.3.0 (npm v8.3.0)
(base)  portal-ui git:(delete-versions-test) ✗ 
➜ yarn run testcafe chrome:headless ./tests/permissions/bucketDeleteAllVersions.ts --skip-js-errors
yarn run v1.22.17
$ /Users/dvaldivia/go/src/github.com/minio/console/portal-ui/node_modules/.bin/testcafe chrome:headless ./tests/permissions/bucketDeleteAllVersions.ts --skip-js-errors
 Running tests in:
 - Chrome 99.0.4844.51 / macOS 10.15.7

 For user with Bucket Read & Write permissions
 ✖ All versions of an object can be deleted from a bucket

   1) The specified selector does not match any element in the DOM tree.
      
       > | Selector('button:enabled')
         |   .withExactText('Delete')

      Browser: Chrome 99.0.4844.51 / macOS 10.15.7

         41 |      .setFilesToUpload(elements.uploadInput, "../uploads/test.txt")
         42 |      .wait(5000)
         43 |      .click(
         44 |        "div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(1)"
         45 |      )
       > 46 |      .click(elements.deleteButton)
         47 |      .click(elements.switchInput)
         48 |      .click(Selector("button:enabled").withExactText("Delete").nth(1));
         49 |  })
         50 |  .after(async (t) => {
         51 |    // Cleanup created bucket and corresponding uploads

         at <anonymous>

   (/Users/dvaldivia/go/src/github.com/minio/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:46:8)
         at <anonymous>

   (/Users/dvaldivia/go/src/github.com/minio/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:23:71)
         at __awaiter

   (/Users/dvaldivia/go/src/github.com/minio/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:19:12)
         at <anonymous>
      (/Users/dvaldivia/go/src/github.com/minio/console/portal-ui/tests/permissions/bucketDeleteAllVersions.ts:34:76)



 1/1 failed (30s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(base)  portal-ui git:(delete-versions-test) ✗ 
➜ nvm use 16                                                                                       
Now using node v16.13.2 (npm v8.1.2)
(base)  portal-ui git:(delete-versions-test) ✗ 
➜ yarn run testcafe chrome:headless ./tests/permissions/bucketDeleteAllVersions.ts --skip-js-errors
yarn run v1.22.17
$ /Users/dvaldivia/go/src/github.com/minio/console/portal-ui/node_modules/.bin/testcafe chrome:headless ./tests/permissions/bucketDeleteAllVersions.ts --skip-js-errors
 Running tests in:
 - Chrome 99.0.4844.51 / macOS 10.15.7

 For user with Bucket Read & Write permissions
 ✓ All versions of an object can be deleted from a bucket


 1 passed (9s)
✨  Done in 18.49s.
```

2022-03-11 23:02 UTC, kaankabalak commented
> seems like the test will fail headless on node `17` but not on `16`, and it's only finding that delete button @kaankabalak @adfost @bexsoft

Yeah, seems like this might be the issue that's causing the failure on GitHub Actions 👍

2022-03-14 23:15 UTC, cniackz approved these changes
I think @adfost already addressed the Selector and now is shorter:
`div.ReactVirtualized__Grid.ReactVirtualized__Table__Grid > div > div:nth-child(1)`
If in the future we need to make them better, we can open new PR for it.
For now approving this one!.
Thanks Adam for the fixes.

2022-03-15 21:40 UTC, merged