Download all credentials
minio/console pull request #1704
Opened 2022-03-11 19:24 UTC by jinapurapu

**REQUIRES PO 1683**

**What does it do:** If more than one set of accesskey/secretkey pairs is generated, provide a button to allow download of all accesskey/secretkey pairs. Adds tooltips on hover to explain difference between download formats. Also removes "Done" button to minimize accidental user closure of credential window.

**What does it look like:**
![Screenshot from 2022-03-11 11-09-02](https://user-images.githubusercontent.com/65002498/157935686-de5109c0-dbdf-4a71-931d-e2e088e730c4.png)
![Screenshot from 2022-03-11 11-08-33](https://user-images.githubusercontent.com/65002498/157935691-3b624d03-b43f-472b-a550-5fa7da4fed68.png)

2022-03-16 03:36 UTC, dvaldivia approved these changes

2022-03-16 04:04 UTC, bexsoft approved these changes

2022-03-16 04:18 UTC, dvaldivia requested changes
the UI tests on operator are failing due to the `Done` button being removed, perhaps the test should be updated to close the modal using the top right

2022-03-17 18:29 UTC, dvaldivia approved these changes

2022-03-17 19:27 UTC, bexsoft approved these changes
LGTM

2022-03-17 19:30 UTC, merged