WIP Added node and type selector UI to Error Logs screen
minio/console pull request #1715
Opened 2022-03-14 23:54 UTC by jinapurapu

**What it does:** Adds UI to allow node and log type selection for Error logs. 

**What it looks like:**
![Screenshot from 2022-03-14 16-43-03](https://user-images.githubusercontent.com/65002498/158278619-6f46aa97-ca40-4d9a-bf59-661fdeba76ee.png)
 
Addresses https://github.com/miniohq/engineering/issues/508

2022-03-24 03:39 UTC, kaankabalak commented on restapi/configure_console.go
> +	registersNodesHandler(api)
Very minor issue here, should we change the function name to `registerNodesHandler` to keep it consistent with the other functions?

```suggestion
	registerNodesHandler(api)
```

2022-03-24 03:40 UTC, kaankabalak commented on restapi/admin_nodes.go
> +func registersNodesHandler(api *operations.ConsoleAPI) {
Similar to my previous comment, should we change the name of the function here to `registerNodesHandler` to keep things consistent?

```suggestion
func registerNodesHandler(api *operations.ConsoleAPI) {
```

2022-03-25 04:15 UTC, kaankabalak commented on portal-ui/src/screens/Console/Logs/ErrorLogs/ErrorLogs.tsx
> +                value={"Minio"}
Another minor issue, should we change the `label` and `value` here from `Minio` to `MinIO`?

```suggestion
                label={"MinIO"}
                onChange={(item) => {
                  setAllTypes(false);
                  item.target.checked ? setLogType("minio") : setLogType("");
                }}
                value={"MinIO"}
```

2022-03-29 12:38 UTC, prakashsvmx commented
@jinapurapu  could you please resolve the conflicts ?

2022-03-31 18:26 UTC, dvaldivia submitted a review, later dismissed

2022-03-31 18:43 UTC, bexsoft requested changes
No Information is retrieved with default settings after clicking on the Start Logs button. I think it would be better to change the Log type default value to "All".
<img width="1207" alt="Screen Shot 2022-03-31 at 12 42 50" src="https://user-images.githubusercontent.com/33497058/161127064-273fbdd8-a5ad-4b6a-94b3-87335d7b91cb.png">
<img width="1297" alt="Screen Shot 2022-03-31 at 12 42 43" src="https://user-images.githubusercontent.com/33497058/161127075-5a57b895-b994-4ad7-8c9a-1a6ba3979c80.png">



Also it would be nice to have the selectors in full width alignment and put the Filter input bellow those fields as the action of that field has to work with the results

<img width="1233" alt="Screen Shot 2022-03-31 at 12 41 20" src="https://user-images.githubusercontent.com/33497058/161127112-46be45ca-692c-4539-83f0-676bbd657dd4.png">
<img width="1234" alt="Screen Shot 2022-03-31 at 12 41 25" src="https://user-images.githubusercontent.com/33497058/161127115-ac60e066-463e-4106-b5e1-e791d58501e3.png">


Beside of that, Works good!

2022-03-31 18:53 UTC, Alevsk commented on restapi/admin_console.go
> +	logKind := logRequest.logType
Please validate the provided value is one of those 3 options: minio, application or all, default to all if an invalid value is provided

2022-03-31 18:54 UTC, Alevsk requested changes

2022-03-31 18:54 UTC, Alevsk commented on restapi/admin_console.go
> +	logKind := logRequest.logType
Please validate the provided value is one of those 3 options: `minio`, `application` or `all`, default to `all` if an invalid value is provided

2022-03-31 19:27 UTC, Alevsk commented
![image](https://user-images.githubusercontent.com/1795553/161133853-1fc35c56-5079-4cd3-9a4c-930168e3d699.png)

This is more like a visual bug but theres a css class making the first letter of every word uppercase on the list of nodes, @bexsoft this is the default behavior for that component?

2022-03-31 19:32 UTC, Alevsk requested changes

2022-04-01 00:11 UTC, bexsoft commented
With latest changes I'm not able to retrieve any information, are there any special steps to follow?

2022-04-04 18:46 UTC, dvaldivia approved these changes

2022-04-04 18:50 UTC, bexsoft approved these changes
LGTM

2022-04-04 18:54 UTC, merged