Log text color styles and empty state
minio/console pull request #1733
Opened 2022-03-17 13:27 UTC by prakashsvmx

Log text color styles  border, height  and empty state

Closes https://github.com/miniohq/engineering/issues/596

@oscarocastellanos  Please confirm if we still want to add a new font in console for the log text. as of now it is using the existing font.

How does it look?

![image](https://user-images.githubusercontent.com/23444145/158817920-6cbb4410-a939-4756-9f23-fbc52ffaf85b.png)

![image](https://user-images.githubusercontent.com/23444145/158818347-63ffbd63-4b9e-4633-bb7c-28a7656a9033.png)

![image](https://user-images.githubusercontent.com/23444145/158818417-e0a42e1d-e7d9-4cd2-b62b-4f74dd3de768.png)

2022-03-17 17:11 UTC, oscarocastellanos submitted a review, later dismissed
LGTM. Thank you  @prakashsvmx

2022-03-17 18:29 UTC, dvaldivia submitted a review, later dismissed

2022-03-17 18:54 UTC, bexsoft requested changes

2022-03-17 18:54 UTC, bexsoft commented on portal-ui/src/screens/Console/Logs/ErrorLogs/LogLine.tsx
> +    fontFamily: "'monospace'",
Please remove single quotes, this leads to fallback font

```suggestion
    fontFamily: "monospace",
```
<img width="1159" alt="Screen Shot 2022-03-17 at 12 52 50" src="https://user-images.githubusercontent.com/33497058/158875552-c1243053-ccb0-4d8f-8738-b0b6e188a2d3.png">

2022-03-17 18:55 UTC, bexsoft requested changes

2022-03-17 18:55 UTC, bexsoft commented on portal-ui/src/screens/Console/Logs/ErrorLogs/LogLine.tsx
> +    fontFamily: "'monospace'",
Same case here

2022-03-18 01:35 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Logs/ErrorLogs/LogLine.tsx
> +    fontFamily: "'monospace'",
Thank you @bexsoft for pointing this out. :+1:

2022-03-18 04:20 UTC, bexsoft approved these changes
LGTM

2022-03-18 05:19 UTC, dvaldivia approved these changes

2022-03-18 05:19 UTC, merged