[WIP] - SSO Integration Test
minio/console pull request #1742
Opened 2022-03-21 20:00 UTC by cniackz

The intention of this test is to make sure we can log in using SSO via `Keycloak`
But as of now, I have containers running just locally, I am going to start by creating the commit just for the Go script.
Later today, I will add the environment to run with Keycloak and MinIO containers in GitHub Action, work in progress!

2022-03-23 19:53 UTC, dvaldivia requested changes

2022-03-23 19:53 UTC, dvaldivia commented on Makefile
> +    -e MINIO_ROOT_PASSWORD=minio123 "quay.io/minio/minio:latest" server /data{1...4} --address :9000 --console-address :9001)
the downside here is that this uses `minio:latest` instead of the code in the current PR, but we have a container image for the current PR so we could use that image instead, or the built minio binary

2022-03-24 22:24 UTC, dvaldivia approved these changes

2022-03-24 23:23 UTC, bexsoft approved these changes

2022-03-24 23:31 UTC, adfost approved these changes

2022-03-25 03:11 UTC, merged