Delete PVCs upon tenant deletion checkbox.
minio/console pull request #1752
Opened 2022-03-23 18:52 UTC by adfost

Apparently API was already implemented, just added a checkbox to delete PVCs upon tenant deletion
<img width="420" alt="Screen Shot 2022-03-23 at 11 52 04 AM" src="https://user-images.githubusercontent.com/15642172/159774436-ffc4cbaa-3250-4f52-ad1b-4c1904f1d8dd.png">

2022-03-23 18:54 UTC, dvaldivia requested changes

2022-03-23 18:54 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +                label={"Delete PVCs"}
Make it more clear what's gonna happen, use the description field as well, something like 
```
Delete Volumes: These will permanently delete the data.
```
Also display a warning once the checkbox is selected
<img width="669" alt="Screen Shot 2022-03-23 at 11 51 55 AM" src="https://user-images.githubusercontent.com/18384552/159774705-c816b356-2e96-4887-aa12-b95c3bd9571a.png">

2022-03-23 21:32 UTC, bexsoft requested changes

2022-03-23 21:32 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +            <CheckboxWrapper
Can we please change this component to be a `FormSwitchWrapper` for consistency?

2022-03-23 23:50 UTC, adfost commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +                label={"Delete PVCs"}
This was added but there is a persistent color problem of the text.

2022-03-24 04:05 UTC, dvaldivia commented
<img width="656" alt="Screen Shot 2022-03-23 at 9 04 37 PM" src="https://user-images.githubusercontent.com/18384552/159840084-fff7546c-f109-4660-848b-2c91f5240a6c.png">

please fix the translucent text

2022-03-24 04:10 UTC, dvaldivia requested changes

2022-03-24 04:10 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +          <Grid item xs={12}>
only show when `deletePVCs` is selected

2022-03-24 04:10 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +                label={"Delete PVCs"}
```suggestion
                label={"Delete Volumes"}
```

2022-03-24 04:12 UTC, dvaldivia requested changes

2022-03-24 04:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      top: 300,
remove this, it's invalid

2022-03-24 04:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      left: 666,
remove this, it's invalid

2022-03-24 04:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      width: 488,
remove this, it's not needed so that the warning is as wide as it's container

2022-03-24 04:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      height: 102,
remove this, it's not needed so that the warning is as high as it's content

2022-03-24 16:45 UTC, bexsoft requested changes

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      backgroundBlendMode: "normal",
This is not needed

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      opacity: 1,
Default opacity is 1, please remove this

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      backgroundBlendMode: "normal",
This is not needed

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      opacity: 1,
Same case for opacity

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +      display: "block",
I think that we don't need to float the whole element as it needs to be on the top and full width always. Also flex is preferred than float

2022-03-24 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/DeleteTenant.tsx
> +              label={"Delete Volumes: This will permanently delete the data."}
```suggestion
              label={"Delete Volumes: Data will be permanently deleted. Please proceed with caution"}
```

2022-03-24 17:36 UTC, dvaldivia requested changes

2022-03-24 17:36 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/WarningMessage/WarningMessage.tsx
> +    <Grid container className={classes.headerContainer}>
replace the `<Grid container` for a plain `<div` since there's no usage of grid in this component

2022-03-24 17:59 UTC, dvaldivia approved these changes

2022-03-24 19:12 UTC, dvaldivia approved these changes

2022-03-24 19:16 UTC, bexsoft approved these changes
LGTM

2022-03-24 19:17 UTC, merged