UX Trace Screen
minio/console pull request #1781
Opened 2022-03-30 11:55 UTC by prakashsvmx

UX Trace Screen

Fixes #https://github.com/miniohq/engineering/issues/676

Note: 
- Table Design is Common so not modified yet
- Filter Icon will be updated. @oscarocastellanos  

How does it look?:
![Screenshot from 2022-03-30 17-11-23](https://user-images.githubusercontent.com/23444145/160827867-a5d801fb-2feb-4468-9213-d2344b93466f.png)

2022-03-30 17:59 UTC, jinapurapu requested changes
The trace records disappear as soon as the trace is stopped, that might be unexpected for users.

2022-03-30 17:59 UTC, jinapurapu commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                <CheckboxWrapper
Should there be a visual indication that the checkboxes are locked while trace is running?

2022-03-30 18:50 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                <CheckboxWrapper
I have added a gray labels. for this. 

Also the records will be displayed untill next click on start

2022-03-30 19:00 UTC, jinapurapu requested changes

2022-03-30 19:00 UTC, jinapurapu commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                    text={"Start"}
```suggestion
                    text={"Start New Trace"}
```

2022-03-30 19:00 UTC, jinapurapu commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                    text={"Stop"}
```suggestion
                    text={"Stop Trace"}
```

2022-03-30 19:04 UTC, dvaldivia commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                    text={"Start"}
I think `Start` is enough since the whole screen is about trace, adding `new trace` would be redundant wouldn't it?

2022-03-30 19:07 UTC, jinapurapu commented on portal-ui/src/screens/Console/Trace/Trace.tsx
> +                    text={"Start"}
I thought adding New makes it more clear that the existing trace will be cleared.

2022-03-31 18:52 UTC, bexsoft approved these changes
LGTM

2022-03-31 18:53 UTC, dvaldivia approved these changes

2022-03-31 19:05 UTC, merged