Moving add and edit replication to pages
minio/console pull request #1788
Opened 2022-04-01 00:20 UTC by adfost

Moving add and edit replication to pages.
<img width="1162" alt="Screen Shot 2022-03-31 at 5 19 16 PM" src="https://user-images.githubusercontent.com/15642172/161170757-a6eeda38-d955-41bf-8d9c-2931e0a539f6.png">
<img width="1169" alt="Screen Shot 2022-03-31 at 5 19 28 PM" src="https://user-images.githubusercontent.com/15642172/161170779-7490548f-51c4-4881-a3c4-bfa425a265e1.png">

2022-04-04 04:22 UTC, prakashsvmx commented
1. Please make the back button consistent with other pages
![image](https://user-images.githubusercontent.com/23444145/161472781-f694b831-7d55-4bf0-81d4-8b884d5b680a.png)

2. Please make the vertical spacing between fields consistent with other pages
![image](https://user-images.githubusercontent.com/23444145/161472900-688fbd88-6e2f-4d44-8d9b-0fb48799b058.png)

3. Secret key field can be a password toggle filed.
![image](https://user-images.githubusercontent.com/23444145/161473189-c5255e3d-045d-4bbc-95fe-f0fb9000028f.png)


4. Please make the button spacing and alignment
![image](https://user-images.githubusercontent.com/23444145/161472979-f1ea5c6a-e79a-4c21-950a-107a5474ea12.png)

5. Please apply Similar spacing and alignment for Edit screen 
![image](https://user-images.githubusercontent.com/23444145/161473275-c0838ad1-64bd-4a3e-a619-fa6f1e10398b.png)

2022-04-04 04:23 UTC, prakashsvmx requested changes
Please address the UI feedback.

2022-04-04 18:59 UTC, bexsoft requested changes

2022-04-04 18:59 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +import React, {Fragment, useEffect, useState} from "react";
Please lint this file

2022-04-04 18:59 UTC, dvaldivia requested changes

2022-04-04 18:59 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +          <Grid container>
add `spacing={1}`

2022-04-05 05:38 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +                <Grid item xs={12} className={classes.modalButtonBar}>
```suggestion
                <Grid item xs={12} className={classes.buttonContainer}>
```

2022-04-05 05:40 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +      ...containerForHeader(theme.spacing(4)),
```suggestion

    fieldGroup: {
      ...createTenantCommon.fieldGroup,
    },
      ...containerForHeader(theme.spacing(4)),
```

2022-04-05 05:43 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +                  <Grid item xs={12} container className={classes.title}>
```suggestion
                  <Grid
                item
                xs={12}
                container
                className={classes.title}
                alignItems={"center"}
              >
```

2022-04-05 05:47 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +        ...containerForHeader(theme.spacing(4)),
```suggestion
 fieldGroup: {
      ...createTenantCommon.fieldGroup,
    },
    
        ...containerForHeader(theme.spacing(4)),
```

2022-04-05 05:47 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +            <Grid item xs={12} container className={classes.title}>
```suggestion
            <Grid
              item
              xs={12}
              container
              className={classes.title}
              alignItems={"center"}
            >
```

2022-04-05 05:48 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
>            <Grid item xs={12} className={classes.modalButtonBar}>
```suggestion
          <Grid item xs={12} className={classes.buttonContainer}>
```

2022-04-06 16:11 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +        ...containerForHeader(theme.spacing(4)),
I don't see why this is necessary.

2022-04-06 16:12 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +import React, {Fragment, useEffect, useState} from "react";
I think this as done automatically.

2022-04-06 16:17 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditReplication.tsx
> +        ...containerForHeader(theme.spacing(4)),
fieldGroup css (border) needs to be consistent. so i have added this suggestion

2022-04-06 23:02 UTC, dvaldivia requested changes
If I try to add a new replication rule, and it fails, I get redirected back to the list and shown the error, but I should be forced to stay on the page until I successfully add a rule

2022-04-18 16:13 UTC, dvaldivia requested changes
<img width="1392" alt="Screen Shot 2022-04-18 at 9 13 08 AM" src="https://user-images.githubusercontent.com/18384552/163837861-ae70eb0a-622c-4358-86b9-c89897ec6fe6.png">

2022-04-18 16:14 UTC, dvaldivia commented
After I successfully save a replication rule, I don't get redirected back to the list of replication rules

2022-04-18 18:58 UTC, bexsoft requested changes

2022-04-18 18:58 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +          setSnackBarMessage("Successfully added replication rule");
Please review routing in Buckets.tsx & BucketDetails.tsx. 

Redirect issue seems related on how components are declared inside the router and missing declarations. Please review routing flow to see how it works

2022-04-23 03:37 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +          setSnackBarMessage("Successfully added replication rule");
If this were history.push(`/buckets/${bucketName}/admin/replication`), which I copied verbatim from the code for the cancel button, and leads to the correct place, instead of the setSnackBarMessage command, it would mysteriously redirect to the bucket listing instead of going to the replication rules page.

2022-04-25 19:58 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +          setSnackBarMessage("Successfully added replication rule");
In bucket details, we have the following paths defined: const manageBucketRoutes: Record<string, any> = {
    events: "/admin/events",
    replication: "/admin/replication",
    lifecycle: "/admin/lifecycle",
    access: "/admin/access",
    prefix: "/admin/prefix",
  };

2022-04-28 14:08 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddReplication.tsx
> +          setSnackBarMessage("Successfully added replication rule");
@adfost 

I tried to hunt this down:

in `Console.tsx` the following seems to be causing the issue. (Lines: 700-702)

```js

{allowedRoutes.length > 0 ? (
                  <Redirect to={allowedRoutes[0].path} />
                ) : null}
```

When i commented the above, it worked.  Any background on this would help @dvaldivia @bexsoft 

side effect of this change is: 
- Post login , it does not redirect 
    -   if i try to fix this then after logout the previous url is not restored.

2022-06-15 11:03 UTC, prakashsvmx commented
@adfost  Please resolve the conflicts

2023-01-03 18:17 UTC, closed without merging