Adding usage objects and versions to tiers
minio/console pull request #1796
Opened 2022-04-05 00:01 UTC by adfost

Adding usage objects and versions to tiers. 
<img width="1152" alt="Screen Shot 2022-04-04 at 5 01 07 PM" src="https://user-images.githubusercontent.com/15642172/161652836-788627ca-2d99-4c8d-a2e6-63253f4334b9.png">

2022-04-05 16:21 UTC, dvaldivia requested changes
Upon visiting the tiers page, I get a 500 error for `/api/v1/admin/tiers`
<img width="1327" alt="Screen Shot 2022-04-05 at 9 19 51 AM" src="https://user-images.githubusercontent.com/18384552/161800121-4ea105a8-759a-404c-b3dc-e580b106c486.png">

2022-04-05 16:24 UTC, dvaldivia commented
as a side note, I have a single tier previously added via the UI

<img width="986" alt="Screen Shot 2022-04-05 at 9 23 51 AM" src="https://user-images.githubusercontent.com/18384552/161800841-8936ef05-2051-45f1-b7d2-ed8ae104165f.png">

2022-04-05 18:47 UTC, bexsoft approved these changes

2022-04-05 18:47 UTC, bexsoft approved these changes
LGTM, Works on my side

2022-04-06 05:30 UTC, dvaldivia approved these changes

2022-04-06 05:31 UTC, merged