Fixing SSO Operator mode showing CONSOLE
minio/console pull request #1808
Opened 2022-04-07 17:25 UTC by adfost

Fixes https://github.com/miniohq/engineering/issues/688.

2022-04-07 22:36 UTC, dvaldivia requested changes
<img width="586" alt="Screen Shot 2022-04-07 at 10 35 13 AM" src="https://user-images.githubusercontent.com/18384552/162330684-94c27af5-6ee8-489f-8a17-ff37afc96341.png">

please make sure to be using the right `prettier` version, seems like some of these changes are not needed

2022-04-08 19:09 UTC, cniackz commented
Ok, documented and tested this code: https://github.com/minio/operator/wiki/How-to-test-Operator-Login

2022-04-08 19:11 UTC, cniackz approved these changes
LGTM just address the changes from Daniel

2022-04-12 02:11 UTC, Alevsk requested changes

2022-04-12 02:11 UTC, Alevsk commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +    }
```suggestion
    case loginStrategyType.redirect, loginStrategyType.redirectServiceAccount: {
      loginComponent = (
        <React.Fragment>
          <Button
            component={"a"}
            href={loginStrategy.redirect}
            type="submit"
            variant="contained"
            color="primary"
            id="sso-login"
            className={classes.submit}
          >
            Login with SSO
          </Button>
        </React.Fragment>
      );
      break;
    }
```

2022-04-12 02:11 UTC, Alevsk commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +    }
You can modify the existing `case loginStrategyType.redirect:` and add the extra value that you want to match: `case loginStrategyType.redirect, loginStrategyType.redirectServiceAccount:` that way you dont have the same javascript code in two places

2022-04-18 16:17 UTC, dvaldivia approved these changes
lgtm

2022-04-18 22:40 UTC, Alevsk approved these changes
Tested, works fine, approved :+1:

2022-04-18 22:47 UTC, merged