Fix: compress health diagnostics file when download
minio/console pull request #1821
Opened 2022-04-11 06:25 UTC by Alevsk

- subnet expects the generated health diagnostics file to be gz compressed to work

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-04-11 06:28 UTC, Alevsk commented on restapi/admin_health_info.go
> +func tarGZ(healthInfo interface{}, version string) ([]byte, error) {
@klauspost can you check if this is the right way to implement the compression functionality from your library?

2022-04-11 07:28 UTC, dvaldivia approved these changes

2022-04-11 17:08 UTC, bexsoft requested changes
I'm getting errors trying to uncompress the file, is this expected?
<img width="400" alt="Screen Shot 2022-04-11 at 12 07 54" src="https://user-images.githubusercontent.com/33497058/162793302-7ea24ea0-9143-4276-ae57-fe36d4510077.png">
<img width="1095" alt="Screen Shot 2022-04-11 at 12 07 47" src="https://user-images.githubusercontent.com/33497058/162793307-6b84ecf2-f0e8-4882-9f33-63c54e315c3a.png">

2022-04-11 17:59 UTC, bexsoft commented
> > I'm getting errors trying to uncompress the file, is this expected?
> > <img alt="Screen Shot 2022-04-11 at 12 07 54" width="400" src="https://user-images.githubusercontent.com/33497058/162793302-7ea24ea0-9143-4276-ae57-fe36d4510077.png">
> > <img alt="Screen Shot 2022-04-11 at 12 07 47" width="1095" src="https://user-images.githubusercontent.com/33497058/162793307-6b84ecf2-f0e8-4882-9f33-63c54e315c3a.png">
> 
> Can you please try it on incognito window or chrome browser to see if this is safari related , I cannot replicate it

I'm using Chrome, Also tried with Firefox & Safari both on 5005 (with WS enabled) & 9090, same results are seen

2022-04-12 06:27 UTC, dvaldivia commented
same problem on `safari` file sizes mismatch if I download from firefox

2022-04-12 19:04 UTC, Alevsk commented
@dvaldivia @bexsoft this may be M1 related, I was able to generate, download and decompress the file on Mac OSX intel using safari

2022-04-12 19:05 UTC, Alevsk commented
We should merge this, right now this feature is not working so users cannot generate the right file, If M1 users complain we can ask them to use Chrome/Firefox to download the file

2022-04-12 23:15 UTC, dvaldivia approved these changes
Tested.LGTM.

2022-04-13 01:29 UTC, bexsoft approved these changes
Approved as it seems like the issue is only with generated files on M1 CPU.

2022-04-13 01:29 UTC, merged