Replace username variable in session policies
minio/console pull request #1828
Opened 2022-04-11 23:23 UTC by dvaldivia

Fixes https://github.com/minio/console/issues/1803 
Fixes https://github.com/minio/console/issues/1287

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-04-11 23:27 UTC, harshavardhana requested changes

2022-04-11 23:27 UTC, harshavardhana commented on restapi/user_login.go
> +	rawPolicy := bytes.ReplaceAll(accountInfo.Policy, []byte("${aws:username}"), []byte(accountInfo.AccountName))
this is the wrong way to do this, you should extract the SessionToken - claims have all the keys needed to replace the values here.

2022-04-11 23:28 UTC, dvaldivia commented on restapi/user_login.go
> +	rawPolicy := bytes.ReplaceAll(accountInfo.Policy, []byte("${aws:username}"), []byte(accountInfo.AccountName))
that will come next, right now I went after a single variable, all the JWT related variables do need the STS extracted

2022-04-12 00:27 UTC, harshavardhana commented on restapi/user_login.go
> +	rawPolicy := bytes.ReplaceAll(accountInfo.Policy, []byte("${aws:username}"), []byte(accountInfo.AccountName))
it should come in this PR alone, its a generic fix @dvaldivia you can't just do `aws:username` as one off, there is also `aws:userid` 

You need support to replace

```
aws:
jwt:
ldap:
```

And this is a generic fix.

2022-04-12 01:55 UTC, dvaldivia commented on restapi/user_login.go
> +	rawPolicy := bytes.ReplaceAll(accountInfo.Policy, []byte("${aws:username}"), []byte(accountInfo.AccountName))
We don't have a `userid` equivalent, should that be access key instead?

I added `jwt:` and `ldap:` to this PR @harshavardhana

2022-04-12 02:36 UTC, Alevsk approved these changes

2022-04-12 03:01 UTC, bexsoft approved these changes

2022-04-12 03:01 UTC, merged