Site replicaiton status
minio/console pull request #1834
Opened 2022-04-12 15:23 UTC by prakashsvmx

2022-04-13 23:34 UTC, dvaldivia submitted a review, later dismissed

2022-04-13 23:51 UTC, bexsoft requested changes

2022-04-13 23:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/SiteReplication/LookupStatus/BucketEntityStatus.tsx
> +  });
This can be a single function in utils file as this section is used across the three components. Also please remove the `// ts-ignore`

2022-04-14 03:42 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Configurations/SiteReplication/LookupStatus/BucketEntityStatus.tsx
> +  });
Thank  you. I have refactored into a method. however the ts-ignore could not be avoided as the result type is unknown as it will vary by stat

2022-04-14 04:14 UTC, bexsoft submitted a review, later dismissed

2022-04-14 04:51 UTC, dvaldivia approved these changes

2022-04-14 07:17 UTC, dvaldivia approved these changes

2022-04-14 07:19 UTC, Alevsk approved these changes

2022-04-14 07:21 UTC, merged