Go Mod Tidy dependencies
minio/console pull request #1853
Opened 2022-04-15 00:02 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-04-15 21:00 UTC, kaankabalak approved these changes

2022-04-16 02:49 UTC, harshavardhana commented
you may want to update deps once again especially for `minio/operator`

2022-04-18 19:15 UTC, bexsoft requested changes

2022-04-18 19:15 UTC, bexsoft commented on go.mod
> +	github.com/minio/operator v0.0.0-20220414212219-ba4c097324b2
Please update to 20220417

```suggestion
	github.com/minio/operator v0.0.0-20220417174843-5b012b004653
```

2022-04-23 03:23 UTC, bexsoft approved these changes
LGTM

2022-04-23 04:26 UTC, kannappanr approved these changes

2022-04-23 15:45 UTC, merged