[WIP] Error and Audit logger webhooks
minio/console pull request #1855
Opened 2022-04-16 06:41 UTC by Alevsk

Similar to MinIO now it's possible to configure webhooks to log all
triggered errors and incomming requests via env variables:

```
CONSOLE_LOGGER_WEBHOOK_ENABLE_<ID>
CONSOLE_LOGGER_WEBHOOK_ENDPOINT_<ID>
CONSOLE_LOGGER_WEBHOOK_AUTH_TOKEN_<ID>
CONSOLE_LOGGER_WEBHOOK_CLIENT_CERT_<ID>
CONSOLE_LOGGER_WEBHOOK_CLIENT_KEY_<ID>
CONSOLE_LOGGER_WEBHOOK_QUEUE_SIZE_<ID>

CONSOLE_AUDIT_WEBHOOK_ENABLE_<ID>
CONSOLE_AUDIT_WEBHOOK_ENDPOINT_<ID>
CONSOLE_AUDIT_WEBHOOK_AUTH_TOKEN_<ID>
CONSOLE_AUDIT_WEBHOOK_CLIENT_CERT_<ID>
CONSOLE_AUDIT_WEBHOOK_QUEUE_SIZE_<ID>
```

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-04-16 06:44 UTC, dvaldivia requested changes

2022-04-16 06:44 UTC, dvaldivia commented on cmd/console/logger.go
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-04-16 06:44 UTC, dvaldivia commented on pkg/errors/errors.go
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-04-16 06:44 UTC, dvaldivia commented on pkg/http/headers.go
> +// Copyright (c) 2015-2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

and so many more hahaha

2022-04-27 16:55 UTC, dvaldivia requested changes
There's a misprint somewhere 
```
%!(EXTRA madmin.ErrorResponse=Access Denied., *errors.errorString=invalid session)
```

2022-04-27 21:11 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-04-27 22:43 UTC, dvaldivia submitted a review, later dismissed

2022-04-27 23:03 UTC, bexsoft requested changes
All terminal messages are now in the form of 

```
{"level":"INFO","errKind":"","time":"2022-04-27T22:55:33.073901Z","message":"Serving console at http://[::]:9090"}
^C{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.637599Z","message":"Shutting down... "}
{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.642138Z","message":"Stopped serving console at http://[::]:9090"}
```

Is this correct? I think people that are not using webhooks to log information will complain about using too much space
<img width="890" alt="Screen Shot 2022-04-27 at 18 00 54" src="https://user-images.githubusercontent.com/33497058/165645289-9f573601-9248-48e3-a92d-c8d9f65df31a.png">

2022-04-27 23:27 UTC, Alevsk commented
> ink people tha



> All terminal messages are now in the form of
> 
> ```
> {"level":"INFO","errKind":"","time":"2022-04-27T22:55:33.073901Z","message":"Serving console at http://[::]:9090"}
> ^C{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.637599Z","message":"Shutting down... "}
> {"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.642138Z","message":"Stopped serving console at http://[::]:9090"}
> ```
> 
> Is this correct? I think people that are not using webhooks to log information will complain about using too much space <img alt="Screen Shot 2022-04-27 at 18 00 54" width="890" src="https://user-images.githubusercontent.com/33497058/165645289-9f573601-9248-48e3-a92d-c8d9f65df31a.png">

This is correct @bexsoft we are displaying more information on errors now, such as errorkind, error trace, requestID, etc

2022-04-27 23:30 UTC, bexsoft commented
> > ink people tha
> 
> > All terminal messages are now in the form of
> > ```
> > {"level":"INFO","errKind":"","time":"2022-04-27T22:55:33.073901Z","message":"Serving console at http://[::]:9090"}
> > ^C{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.637599Z","message":"Shutting down... "}
> > {"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.642138Z","message":"Stopped serving console at http://[::]:9090"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this correct? I think people that are not using webhooks to log information will complain about using too much space <img alt="Screen Shot 2022-04-27 at 18 00 54" width="890" src="https://user-images.githubusercontent.com/33497058/165645289-9f573601-9248-48e3-a92d-c8d9f65df31a.png">
> 
> This is correct @bexsoft we are displaying more information on errors now, such as errorkind, error trace, requestID, etc

But this is happening even if I don't set any of the env vars

2022-04-28 00:01 UTC, Alevsk commented
> > > ink people tha
> > 
> > 
> > > All terminal messages are now in the form of
> > > ```
> > > {"level":"INFO","errKind":"","time":"2022-04-27T22:55:33.073901Z","message":"Serving console at http://[::]:9090"}
> > > ^C{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.637599Z","message":"Shutting down... "}
> > > {"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.642138Z","message":"Stopped serving console at http://[::]:9090"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is this correct? I think people that are not using webhooks to log information will complain about using too much space <img alt="Screen Shot 2022-04-27 at 18 00 54" width="890" src="https://user-images.githubusercontent.com/33497058/165645289-9f573601-9248-48e3-a92d-c8d9f65df31a.png">
> > 
> > 
> > This is correct @bexsoft we are displaying more information on errors now, such as errorkind, error trace, requestID, etc
> 
> But this is happening even if I don't set any of the env vars

Yes, this is the default format for console logs now, if we print logs in json format we can even start printing logs for the embedded console  too, those logs can be parsed by any tool now

2022-04-28 06:08 UTC, Alevsk commented
> > > ink people tha
> > 
> > 
> > > All terminal messages are now in the form of
> > > ```
> > > {"level":"INFO","errKind":"","time":"2022-04-27T22:55:33.073901Z","message":"Serving console at http://[::]:9090"}
> > > ^C{"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.637599Z","message":"Shutting down... "}
> > > {"level":"INFO","errKind":"","time":"2022-04-27T22:56:14.642138Z","message":"Stopped serving console at http://[::]:9090"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is this correct? I think people that are not using webhooks to log information will complain about using too much space <img alt="Screen Shot 2022-04-27 at 18 00 54" width="890" src="https://user-images.githubusercontent.com/33497058/165645289-9f573601-9248-48e3-a92d-c8d9f65df31a.png">
> > 
> > 
> > This is correct @bexsoft we are displaying more information on errors now, such as errorkind, error trace, requestID, etc
> 
> But this is happening even if I don't set any of the env vars

I set now that the default is the stdout logs without any format and users can enable json/anonymous/quiet mode via environment variables :D

2022-04-28 15:09 UTC, dvaldivia approved these changes

2022-04-28 17:11 UTC, bexsoft commented
Please review lint issues

2022-04-28 18:25 UTC, bexsoft submitted a review, later dismissed

2022-04-28 19:42 UTC, bexsoft approved these changes

2022-04-28 19:43 UTC, dvaldivia approved these changes

2022-04-28 19:55 UTC, merged