Disable Bucket replication tab when site replication is enabled in Bucket Summary page
minio/console pull request #1858
Opened 2022-04-18 10:48 UTC by prakashsvmx

Disable Bucket replication tab when site replication is enabled in Bucket Summary page

2022-04-18 20:08 UTC, dvaldivia requested changes

2022-04-18 20:08 UTC, dvaldivia commented on portal-ui/src/reducer.ts
> +  debugger;
I think this can be removed

2022-04-19 03:51 UTC, prakashsvmx commented on portal-ui/src/reducer.ts
> +  debugger;
Thank you :+1:  . I have updated.

2022-04-19 17:37 UTC, dvaldivia approved these changes

2022-04-19 22:50 UTC, bexsoft approved these changes

2022-04-19 22:50 UTC, merged