Pod details api
minio/console pull request #1861
Opened 2022-04-18 16:38 UTC by adfost

Describe Pod API

2022-04-23 03:33 UTC, bexsoft requested changes

2022-04-23 03:33 UTC, bexsoft commented on operatorapi/tenants.go
> +		retval.Containers[i].EnvironmentVariables = make([]*models.EnvironmentVariable, len(pod.Spec.Containers[0].Env))
I think this would be cleaner if you create a new instance of *models.Container and insert the values there instead of setting prop by prop

2022-04-23 03:33 UTC, bexsoft commented on operatorapi/tenants.go
> +			retval.Volumes[i].Pvc.ClaimName = pod.Spec.Volumes[i].PersistentVolumeClaim.ClaimName
Same case here

2022-04-23 03:42 UTC, bexsoft requested changes
Please add tests for this new API

2022-04-27 19:59 UTC, cniackz approved these changes
LGTM

2022-04-27 20:00 UTC, cniackz requested changes
Please sqush to one commit.

2022-04-27 20:04 UTC, cniackz submitted a review, later dismissed
LGTM

2022-05-03 00:07 UTC, cniackz approved these changes
LGTM

2022-05-03 01:35 UTC, dvaldivia approved these changes

2022-05-03 01:35 UTC, merged