Added console & minio domains selector to add tenant wizard
minio/console pull request #1863
Opened 2022-04-18 23:52 UTC by bexsoft

## What does this do?

Added console & minio domains selector to add tenant wizard

## How does it look?

<img width="1311" alt="Screen Shot 2022-04-18 at 18 50 41" src="https://user-images.githubusercontent.com/33497058/163894393-d73977b3-cec9-443b-a9f9-5386658557cd.png">
<img width="1465" alt="Screen Shot 2022-04-18 at 18 50 16" src="https://user-images.githubusercontent.com/33497058/163894397-890d5644-ef0d-4775-96e1-bc6cb1c28a7e.png">
<img width="1503" alt="Screen Shot 2022-04-18 at 18 50 10" src="https://user-images.githubusercontent.com/33497058/163894400-42ec6a63-d5ff-4d60-9a0a-675d3ae13791.png">
<img width="543" alt="Screen Shot 2022-04-18 at 18 49 57" src="https://user-images.githubusercontent.com/33497058/163894402-374d9693-30fb-48f8-9ea5-9d5180142dfc.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-04-19 00:20 UTC, dvaldivia requested changes
There's no need for schema in the URLs, in fact the validation should tell them not to enter the schema since these domains go into the `MINIO_DOMAIN` env var. but it does raise the question about the public domain.

Also minio domains are not getting populated 
![2022-04-18 17-17-30 2022-04-18 17_20_19](https://user-images.githubusercontent.com/18384552/163896662-7e3f8e3f-efc0-4c17-99b6-9d1c39974970.gif)

2022-04-19 04:45 UTC, bexsoft commented
As per conversation, I will add validation to include protocol & ports.

Also MinIO domain should not allow subpaths

2022-04-19 20:47 UTC, bexsoft commented
> There's no need for schema in the URLs, in fact the validation should tell them not to enter the schema since these domains go into the `MINIO_DOMAIN` env var. but it does raise the question about the public domain.
> 
> Also minio domains are not getting populated ![2022-04-18 17-17-30 2022-04-18 17_20_19](https://user-images.githubusercontent.com/18384552/163896662-7e3f8e3f-efc0-4c17-99b6-9d1c39974970.gif)

Added validation to input boxes & fixed issue with one minio domain @dvaldivia

2022-04-20 00:08 UTC, dvaldivia approved these changes

2022-04-20 00:34 UTC, Alevsk approved these changes

2022-04-20 00:34 UTC, Alevsk commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Configure.tsx
> +        background: "#EAEAEA",
EAEAEAEAE XD

2022-04-20 17:29 UTC, merged