Moved AddUser from modal to screen
minio/console pull request #1869
Opened 2022-04-19 20:20 UTC by jinapurapu

**How it looks:**
![Screenshot from 2022-04-19 13-17-00](https://user-images.githubusercontent.com/65002498/164088485-989bb274-526b-4353-a582-6a8f2573acda.png)

Closes https://github.com/miniohq/engineering/issues/726

2022-04-19 20:27 UTC, oscarocastellanos requested changes
The assign groups search box should have more space on top so it doesn't clash with the previous box. 

Icons in the help bar should be smaller and just one color. Please let me know if you need me to adjust the icons.

Is it possible to use the side by side help box format as @prakashsvmx has been doing in other recent screens?

2022-04-19 22:06 UTC, dvaldivia commented
I think it's just some extra alignment 

![image](https://user-images.githubusercontent.com/23444145/163396648-a19dc336-d480-478b-89d6-212b8d1ddb0c.png)

2022-04-19 22:09 UTC, dvaldivia requested changes
There's a couple of issues, on error we are still redirecting, so avoid redirecting on error, also when we successfully ad we don't refresh the list of users, that might be a bug on user list screen


<img width="1818" alt="Screen Shot 2022-04-19 at 3 08 32 PM" src="https://user-images.githubusercontent.com/18384552/164109875-d592f9fd-28ac-44ec-ada3-45c412032015.png">
<img width="1818" alt="Screen Shot 2022-04-19 at 3 08 14 PM" src="https://user-images.githubusercontent.com/18384552/164109880-6d41a9fa-4c42-4441-838e-e034f35e6507.png">

2022-04-19 23:09 UTC, dvaldivia commented
Can you align like this @jinapurapu ?
<img width="919" alt="Screen Shot 2022-04-19 at 4 09 14 PM" src="https://user-images.githubusercontent.com/18384552/164115835-357168e4-3923-423d-9516-1526a9b8d622.png">

2022-04-20 02:00 UTC, bexsoft requested changes

2022-04-20 02:00 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/AddUserScreen.tsx
> +        </Box>
Please run prettier on this file to fix indentation

2022-04-21 04:12 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> -                                setAddScreenOpen(true);
`closeAddModalAndRefresh`   - function
`addScreenOpen`  - state
`AddUser` Component and Usage

please remove/cleanup these as they are no longer used in `ListUsers` component.

2022-04-22 04:56 UTC, prakashsvmx submitted a review, later dismissed
LGTM :+1:

2022-04-23 03:38 UTC, dvaldivia commented on portal-ui/src/common/SecureComponent/permissions.ts
> +    IAM_SCOPES.ADMIN_CREATE_USER, // displays create user button
```suggestion
    IAM_SCOPES.ADMIN_CREATE_USER,], // displays create user button
```

2022-04-23 03:39 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-04-23 03:42 UTC, oscarocastellanos submitted a review, later dismissed
Icon should  be correctly aligned and also the upper most field to the help box

2022-04-23 03:55 UTC, bexsoft approved these changes
LGTM

2022-04-23 04:40 UTC, merged