More Policy Tests, Set, List, Delete
minio/console pull request #1879
Opened 2022-04-20 19:19 UTC by adfost

2022-04-20 21:40 UTC, cniackz commented on integration/policy_test.go
> +	AddUser("testuser1", "testtest", []string{}, []string{"readwrite"})
Hello Adam,

These failures are expected. I helped with the first one: `service_account_test.go:74`
The reason is that in `integration/policy_test.go` a user is added `AddUser("testuser1", "testtest", []string{}, []string{"readwrite"})`
Hence by the time `TestAddServiceAccount` is executed, the user already exist so we are getting an expected 500:
```
{code: 500, detailedMessage: "Specified service account is used by another user",…}
code: 500
detailedMessage: "Specified service account is used by another user"
message: "an error occurred, please try again"
```
If the user is deleted then we can successfully post to `api/v1/service-account-credentials` to get other than 500.
Or you can use a different user to avoid the collision.
It is up to you how to handle this case, but make sure that any addition in any file is not breaking existing working scenarios :+1:

Best regards
-Cesar

2022-04-20 21:40 UTC, cniackz commented on integration/policy_test.go
> +	AddUser("testuser1", "testtest", []string{}, []string{"readwrite"})
Hello Adam,

These failures are expected. I helped with the first one: `service_account_test.go:74`
The reason is that in `integration/policy_test.go` a user is added `AddUser("testuser1", "testtest", []string{}, []string{"readwrite"})`
Hence by the time `TestAddServiceAccount` is executed, the user already exist so we are getting an expected 500:
```
{code: 500, detailedMessage: "Specified service account is used by another user",…}
code: 500
detailedMessage: "Specified service account is used by another user"
message: "an error occurred, please try again"
```
If the user is deleted then we can successfully post to `api/v1/service-account-credentials` to get other than 500.
Or you can use a different user to avoid the collision.
It is up to you how to handle this case, but make sure that any addition in any file is not breaking existing working scenarios :+1:

Best regards
-Cesar

2022-04-20 21:44 UTC, cniackz requested changes
Please avoid breaking existing scenarios. I helped to root cause the first failure observed in `service_account_test.go:74`.

Please start by fixing it and address the rest by debugging what is breaking the existing scenarios. Whatever is added in `policy_test.go` it may affect other tests as they are using the same running containers.

2022-04-20 22:23 UTC, cniackz submitted a review, later dismissed
LGTM

2022-04-21 04:41 UTC, dvaldivia requested changes

2022-04-21 04:41 UTC, dvaldivia commented on integration/policy_test.go
> +				api:        "/set-policy",
since these test a different endpoint, please put them on their own test method

2022-04-21 04:41 UTC, dvaldivia commented on integration/policy_test.go
> +		entityType string
don't overload arguments, this test is meant to only test POST to `/policies`, use a new method for other endpoints that have their own handlers.

2022-04-21 04:41 UTC, dvaldivia commented on integration/policy_test.go
> +				api:    "/policy?name=test",
each api handler should end up with it's own test method

2022-04-21 23:07 UTC, cniackz requested changes
Please squash the commits to one only

2022-04-21 23:08 UTC, cniackz requested changes
Squash commits

2022-04-21 23:33 UTC, cniackz submitted a review, later dismissed
LGTM

2022-04-23 00:16 UTC, dvaldivia requested changes

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be POST

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method     string
method is redundant, all tests will be PUT

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be PUT

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +				method: "GET",
method is redundant, all tests will be GET

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be GET, other arguments such as the policy name should be arguments themselves, also this tests depends on the other previous tests setting up policies `test3` and `test` which means if we run both tests in parallel, one could fail due to the race condition, setup policies unique to this test before the test

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +func Test_ConfigAPI(t *testing.T) {
This is a test for `config` on a file called `policy_test.go`, it should have it's own file `config_test.go`

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be GET

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be GET

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +			// Add policy
This comments is incorrect

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method string
method is redundant, all tests will be GET

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		},
this tests doesn't cover invalid get

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +				api:    "/policies/test/groups",
group name can be parametrized

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +			// Add policy
This comments is inaccurate

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +		method     string
method is redundant, all tests will be DELETE

2022-04-23 00:16 UTC, dvaldivia commented on integration/policy_test.go
> +			// Add policy
This comments is inaccurate

2022-04-23 02:20 UTC, adfost commented on integration/policy_test.go
> +		method     string
There needs to be some cleanup before delete.

2022-04-23 04:47 UTC, dvaldivia requested changes

2022-04-23 04:47 UTC, dvaldivia commented on integration/policy_test.go
> +				api: "/policy?name=test",
this test relies on a policy created by another test which will cause a race condition, create a policy with a name unique for this test

2022-04-28 05:12 UTC, dvaldivia approved these changes

2022-04-28 05:17 UTC, prakashsvmx commented on integration/policy_test.go
> +		This is an atomic function to add user and can be reused across
Comments could be updated to reflect "Policy Tests".

2022-04-28 05:29 UTC, prakashsvmx approved these changes
LGTM :+1:

2022-04-28 16:15 UTC, bexsoft approved these changes

2022-04-28 16:52 UTC, merged