Create service account screen
minio/console pull request #1886
Opened 2022-04-21 20:07 UTC by jinapurapu

**How it looks:**

![Screenshot from 2022-04-21 12-55-15](https://user-images.githubusercontent.com/65002498/164542569-d5aeac49-bec8-4617-8827-ca5da45bfe5d.png)

![Screenshot from 2022-04-21 12-55-38](https://user-images.githubusercontent.com/65002498/164542566-99f9b618-f724-4f14-ad08-9388ed4bfb02.png)

![Screenshot from 2022-04-21 12-56-54](https://user-images.githubusercontent.com/65002498/164542563-a753ef55-af82-4212-a771-ad5b3c418bf4.png)

Closes https://github.com/miniohq/engineering/issues/727

2022-04-21 23:10 UTC, cniackz requested changes
Please squash the commits to only one

2022-04-21 23:14 UTC, cniackz submitted a review, later dismissed
LGTM

2022-04-21 23:38 UTC, adfost submitted a review, later dismissed

2022-04-22 04:13 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Account/AddServiceAccountScreen.tsx
> + console.log("Displaying prompt - NewServiceAccount:", newServiceAccount)
Please remove the console logs (3) in the component

2022-04-22 04:17 UTC, bexsoft requested changes

2022-04-22 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/AddServiceAccountScreen.tsx
> +            console.log("From API2newSA:", res);
Please remove console.log

2022-04-22 04:20 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Account/AddServiceAccountScreen.tsx
> +                          <div className={classes.stackedInputs} >
Please make the spacing below this input consistent with other forms.

2022-04-22 22:20 UTC, dvaldivia submitted a review, later dismissed

2022-04-22 22:39 UTC, dvaldivia submitted a review, later dismissed

2022-04-23 00:18 UTC, dvaldivia approved these changes

2022-04-23 00:49 UTC, bexsoft approved these changes

2022-04-23 00:49 UTC, merged