More groups tests
minio/console pull request #1923
Opened 2022-04-28 21:40 UTC by adfost

2022-04-28 22:19 UTC, dvaldivia requested changes

2022-04-28 22:19 UTC, dvaldivia commented on integration/groups_test.go
> +				api: "/group?name=getgroup1",
all these tests are meant for the same endpoint `/group` so I don't think that should be an argument, on the other hand `name` is a valid argument

2022-04-28 22:20 UTC, dvaldivia requested changes

2022-04-28 22:20 UTC, dvaldivia commented on integration/groups_test.go
> +			// Add policy
invalid comment

2022-04-28 22:20 UTC, dvaldivia commented on integration/groups_test.go
> +			// Add policy
invalid comment

2022-04-28 22:20 UTC, dvaldivia commented on integration/groups_test.go
> +			// Add policy
invalid comment

2022-04-29 21:50 UTC, dvaldivia requested changes

2022-04-29 21:50 UTC, dvaldivia commented on integration/groups_test.go
> +				tt.verb, "http://localhost:9090/api/v1/group?name=grouptests1", requestDataBody)
please make the `name` an argument so you can also test attempting to delete an invalid group

2022-04-29 22:37 UTC, dvaldivia requested changes

2022-04-29 22:37 UTC, dvaldivia commented on integration/groups_test.go
> +			expectedStatus: 500,
Attempting to deleting a non-existing resource should return 404, I see the API returns 
```
{"code":500,"detailedMessage":"The specified group does not exist. (Specified group does not exist)","message":"an error occurred, please try again"}
```

Can you update the API tor return 404 for this specific error?

2022-04-30 01:24 UTC, dvaldivia requested changes

2022-04-30 01:24 UTC, dvaldivia commented on restapi/admin_groups.go
> +		err2 := ErrorWithContext(ctx, err)
Parse the error from MinIO via `ToErrorResponse` and check the code alone
```
minioError := madmin.ToErrorResponse(err)
		if minioError.Code == "XMinioAdminNoSuchGroup" {
			
		}
```

2022-04-30 03:57 UTC, dvaldivia approved these changes

2022-04-30 04:19 UTC, bexsoft approved these changes

2022-05-02 16:25 UTC, merged