Remove all un-used CSS classes
minio/console pull request #1924
Opened 2022-04-28 22:15 UTC by dvaldivia

Spring cleaning of CSS classes
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-04-28 22:26 UTC, adfost approved these changes

2022-04-28 22:28 UTC, Alevsk approved these changes

2022-04-28 22:30 UTC, bexsoft requested changes
I'd like to review this in more detail

2022-04-29 00:33 UTC, bexsoft approved these changes
LGTM

2022-04-29 00:33 UTC, merged