Test add remote bucket
minio/console pull request #1941
Opened 2022-05-03 00:06 UTC by adfost

Test for adding remote bucket

2022-05-03 01:31 UTC, dvaldivia requested changes

2022-05-03 01:31 UTC, dvaldivia commented on integration/remote_buckets_test.go
> +				api:          "/remote-buckets",
all these tests are testing the same API, please remove this argument

2022-05-03 18:24 UTC, dvaldivia requested changes

2022-05-03 18:24 UTC, dvaldivia commented on integration/remote_buckets_test.go
> +	AddBucketWithPort("remotebucketdest", false, true, map[string]interface{}{}, map[string]interface{}{}, "9001")
no need to duplicate the code, just add some options to the `AddBucket` helper method to pass the port

2022-05-10 16:12 UTC, dvaldivia requested changes

2022-05-10 16:12 UTC, dvaldivia commented on integration/user_api_bucket_test.go
> +func AddBucketWithPort(name string, locking bool, versioning bool, quota map[string]interface{}, retention map[string]interface{}, port string) (*http.Response, error) {
this is duplicate code, just update the existing AddBucket to accept a optional options which can specify the port, this was also my previous comment

2022-05-12 21:00 UTC, cniackz requested changes
Get the token if you are going to use a different port other than `9090` otherwise `401` is observed while testing:

<img width="1840" alt="Screen Shot 2022-05-12 at 4 00 14 PM" src="https://user-images.githubusercontent.com/6667358/168167241-3968fc1a-151a-4e28-a03b-ae6b6b48818e.png">

2022-06-02 16:05 UTC, cniackz commented
Hello Adam, good morning. Sorry I did not answer yesterday. I was busy with IBM Cloud Catalog.
Yes, I can see both buckets are being created and I see same error when testing with mc:
$ mc admin bucket remote add myminio/source http://minio:minio123@localhost/target --service "replication" --insecure
mc: <ERROR> Unable to configure remote target. Remote service connection error - please check remote service credentials and target bucket (Remote service endpoint or target bucket not available: target 
	Access Denied.).
Couple of comments:
If you plan on having two servers, I recommend separating them for they to work in parallel, because both in same function only one will work:
	// start console server
	go func() {
		fmt.Println("start server 9090")
		srv, err := initConsoleServer("9090")
		if err != nil {
			log.Println(err)
			log.Println("init fail")
			return
		}
		srv.Serve()
	}()
	go func() {
		fmt.Println("start server 9091")
		srv2, err := initConsoleServer("9091")
		if err != nil {
			log.Println(err)
			log.Println("init fail")
			return
		}
		srv2.Serve()

	}()
2. Second comment is, we only have one container for these tests:
@(docker run -v /data1 -v /data2 -v /data3 -v /data4 --net=mynet123 -d --name minio --rm -p 9000:9000 -p 9001:9001 -e MINIO_KMS_SECRET_KEY=my-minio-key:OSMM+vkKUTCvQs9YL/CVMIMt43HFhkUpqJxTmGl6rYw= $(MINIO_VERSION) server /data{1...4} --console-address ':9001' && sleep 5)
So don't use 9001 as it is collision with the container, try different port, also, I don't think this can be consider as remote because we are using the same container, we should be using two containers for the remote test. Nevertheless, I think we can safely use https://play.min.io for that matter as shown in:
https://github.com/cniackz/minio/wiki/remote-bucket
That way you don't need to create more containers, etc, etc... All you need is two create two buckets with versioning in both sides, in our current container, you can even reuse one if created and in play side with versioning, a simple mc command prior running the test can do the trick for us. This could simplify our testing a lot. But it is up to you as long as it works :slightly_smiling_face: and don't break other tests.

2022-06-09 16:06 UTC, closed without merging