[WIP] - Simplify SSO Integration test with Dex
minio/console pull request #1954
Opened 2022-05-04 22:35 UTC by cniackz

This is work in progress for now, got all working locally, now need to put all in GitHub action.

2022-05-05 00:35 UTC, harshavardhana requested changes
@cniackz you know that you can use our published containers here? 

```
	podman run \
    --name dex \
    --pod iam-testing \
    --detach \
    quay.io/minio/dex:latest
```

and server config is 

```
export MINIO_IDENTITY_OPENID_CONFIG_URL="http://localhost:5556/dex/.well-known/openid-configuration"
export MINIO_IDENTITY_OPENID_CLIENT_ID="minio-client-app"
export MINIO_IDENTITY_OPENID_CLIENT_SECRET="minio-client-app-secret"
# export MINIO_IDENTITY_OPENID_CLAIM_NAME="groups"
export MINIO_IDENTITY_OPENID_SCOPES="openid,groups"
export MINIO_IDENTITY_OPENID_REDIRECT_URI="http://127.0.0.1:10000/oauth_callback"
# role policy if desired:
export MINIO_IDENTITY_OPENID_ROLE_POLICY="consoleAdmin"

export MINIO_ROOT_USER=minio
export MINIO_ROOT_PASSWORD=minio123

# OR
mc admin config set myminio identity_openid \
    config_url="http://localhost:5556/dex/.well-known/openid-configuration" \
    client_id="minio-client-app" \
    client_secret="minio-client-app-secret" \
    scopes="openid,groups" \
    redirect_uri="http://127.0.0.1:10000/oauth_callback" \
    role_policy="consoleAdmin"

# OR
mc admin config set myminio identity_openid:dextest \
    config_url="http://localhost:5556/dex/.well-known/openid-configuration" \
    client_id="minio-client-app" \
    client_secret="minio-client-app-secret" \
    scopes="openid,groups" \
    redirect_uri="http://127.0.0.1:10000/oauth_callback" \
    role_policy="consoleAdmin"



./minio server --console-address ":10000" /tmp/disk
```

2022-05-05 00:40 UTC, cniackz commented
Thank @harshavardhana for the review, tomorrow or in a near future I will be addressing this requested change.

2022-05-05 13:29 UTC, cniackz commented
Hello @harshavardhana, I have used our Published images and configured server accordingly.
Please kindly review it again and thank you for your time 👍

2022-05-05 17:03 UTC, donatello approved these changes
Looks good, however is it running in the CI?

2022-05-05 17:03 UTC, donatello commented on sso-integration/Dockerfile
> +ADD config.docker.yaml /etc/dex/
Is this file needed anymore since you are using our published image?

2022-05-05 17:28 UTC, dvaldivia approved these changes

2022-05-05 17:29 UTC, dvaldivia commented on sso-integration/Dockerfile
> +ADD config.docker.yaml /etc/dex/
it runs on github actions :)

2022-05-05 17:29 UTC, merged

2022-05-06 04:09 UTC, cniackz commented
@donatello what do you mean by CI?, continuous integration?. The short answer is yes, the Python code can show that by getting the code and the state that later on we use in our Console API to get the token, if token is obtained, then we pass the test as in our other integration tests 👍