Users screen UI revision
minio/console pull request #1961
Opened 2022-05-06 19:53 UTC by jinapurapu

![Screenshot from 2022-05-06 11-51-35](https://user-images.githubusercontent.com/65002498/167200269-b04014db-34d7-486e-816c-945fdbbe6988.png)

![Screenshot from 2022-05-06 11-51-43](https://user-images.githubusercontent.com/65002498/167200200-48376faa-7f75-4333-92eb-f60cdc5602bd.png)

2022-05-06 20:52 UTC, ravindk89 commented on portal-ui/src/screens/Console/Users/DeleteUser.tsx
> +          Are you sure you want to delete the following {selectedUsers.length} user{selectedUsers.length >1 ? "s?": "?"}
General question - can we retrieve the list of serviceaccounts for the selected users?

It might be good to warn users of the full chain - of not only these users, but all connected service accounts - being deleted

2022-05-06 20:52 UTC, ravindk89 submitted a review, later dismissed
LGTM, left one optional nit

2022-05-06 21:55 UTC, dvaldivia commented on portal-ui/src/screens/Console/Users/DeleteUser.tsx
> +          Are you sure you want to delete the following {selectedUsers.length} user{selectedUsers.length >1 ? "s?": "?"}
we can certainly do that, but we would need to rework the delete prompt to display more information, for example if you are deleting 100 users and we need to display 1,000 service accounts

2022-05-09 06:53 UTC, prakashsvmx commented
some minor observations:

1. The icon size is not fully shown: ( firefox & chrome)
![image](https://user-images.githubusercontent.com/23444145/167355305-957f04a6-fa75-44ed-8f16-2301c01837d5.png)

2. `/identity/add-user` is accessible to user with admin actions denied. are we missing some policy permission?

Sample policy and . login as the user with this policy and directly enter the url in address bar. ( on save access denied is shown)
<details>

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "Action": [
                "admin:*"
            ]
        }
    ]
}
```

</details>

2022-05-10 05:41 UTC, prakashsvmx approved these changes
Tested. changes look good to me.

2022-05-10 19:01 UTC, jinapurapu commented on portal-ui/src/screens/Console/Users/DeleteUser.tsx
> +          Are you sure you want to delete the following {selectedUsers.length} user{selectedUsers.length >1 ? "s?": "?"}
I will work on this in another PR

2022-05-12 23:07 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-05-12 23:21 UTC, dvaldivia requested changes
Let's match the style of the users helpbox when there's no users to existing helpboxes like in groups

2022-05-13 04:49 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> -                <Grid item xs={12} marginTop={"25px"}>
this margin is required to add some space to differentiate the help box. or add `  marginBottom={"15px"}` at line number 272

2022-05-13 19:57 UTC, dvaldivia submitted a review, later dismissed

2022-05-13 20:25 UTC, kaankabalak approved these changes

2022-05-13 20:25 UTC, kaankabalak commented
@jinapurapu Looks good to me, however can we resolve the conflicts?

2022-05-16 02:50 UTC, prakashsvmx approved these changes
LGTM :+1:

2022-05-16 18:21 UTC, cniackz approved these changes
Tested locally with long user names and it looks good to me:

<img width="1840" alt="Screen Shot 2022-05-16 at 1 21 19 PM" src="https://user-images.githubusercontent.com/6667358/168657516-dffcc8c9-ad7b-4f56-9aad-3bb4b16f4ee5.png">

Good Job @jinapurapu

2022-05-16 18:27 UTC, adfost approved these changes

2022-05-16 18:27 UTC, bexsoft approved these changes
LGTM

2022-05-16 18:28 UTC, merged