Get config
minio/console pull request #1966
Opened 2022-05-09 23:22 UTC by adfost

Test for configs/{name} endpoint

2022-05-09 23:41 UTC, dvaldivia requested changes

2022-05-09 23:41 UTC, dvaldivia commented on integration/config_test.go
> +				api: "/configs/storage_class",
All test use the same API, just pass the parameter

2022-05-09 23:41 UTC, dvaldivia commented on restapi/admin_config.go
> +			return cfgApi.NewConfigInfoDefault(404).WithPayload(err)
This is invalid, some errors might be 400, please process them according to potential error codes coming from MinIO

2022-05-09 23:41 UTC, dvaldivia commented on integration/config_test.go
> +func Test_GetConfigAPI(t *testing.T) {
This is duplicate code from the above test

2022-05-09 23:41 UTC, dvaldivia commented on integration/config_test.go
>  			client := &http.Client{
You are instantiating a new client on each loop, this is inefficient, reuse the same client

2022-05-09 23:41 UTC, dvaldivia commented on integration/config_test.go
> -			requestDataJSON, _ := json.Marshal(requestDataPolicy)
Why ignore the response?

2022-05-10 00:00 UTC, adfost commented on integration/config_test.go
> +func Test_GetConfigAPI(t *testing.T) {
No this isn't, the above test lists configs with /configs, this test is /configs/{name}

2022-05-10 00:58 UTC, adfost commented on integration/config_test.go
> -			requestDataJSON, _ := json.Marshal(requestDataPolicy)
The code you are highlighting is unnecessary code that I removed, this was from an endpoint that had a body, and these endpoints don't have a body.

2022-05-10 03:45 UTC, dvaldivia commented on integration/config_test.go
> +func Test_GetConfigAPI(t *testing.T) {
ok

2022-05-10 03:48 UTC, dvaldivia requested changes

2022-05-10 03:48 UTC, dvaldivia commented on integration/config_test.go
>  		api string
this is no longer the `api` it's the `name` parameter, it should be called that and not include the slash

2022-05-10 03:48 UTC, dvaldivia commented on integration/config_test.go
> -			requestDataJSON, _ := json.Marshal(requestDataPolicy)
this endpoint does have a body, it returns a `configuration`
```yaml
  /configs/{name}:
    get:
      summary: Configuration info
      operationId: ConfigInfo
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        200:
          description: A successful response.
          schema:
            $ref: "#/definitions/configuration"
        default:
          description: Generic error response.
          schema:
            $ref: "#/definitions/error"
      tags:
        - Configuration
```

2022-05-10 16:41 UTC, adfost commented on integration/config_test.go
> -			requestDataJSON, _ := json.Marshal(requestDataPolicy)
It doesn't have a body in the request, only in the response. This code that I removed was to set up a json struct for request body.

2022-05-10 20:42 UTC, dvaldivia approved these changes

2022-05-10 20:42 UTC, dvaldivia commented on integration/config_test.go
> +				name: "/storage_class",
the `/` is not needed for the config name, that is part of the URL

2022-05-11 02:18 UTC, bexsoft requested changes

2022-05-11 02:18 UTC, bexsoft commented on integration/config_test.go
> +				"GET", fmt.Sprintf("http://localhost:9090/api/v1/configs%s", tt.args.name), nil)
Please change this to be 
```suggestion
				"GET", fmt.Sprintf("http://localhost:9090/api/v1/configs/%s", tt.args.name), nil)
```
and remove the slashes from `args.name`

2022-05-12 04:35 UTC, bexsoft approved these changes

2022-05-12 05:04 UTC, dvaldivia approved these changes

2022-05-12 05:06 UTC, merged