Fixed disabled Change Password button and added clarifying text
minio/console pull request #1973
Opened 2022-05-11 01:55 UTC by jinapurapu

![Screenshot from 2022-05-10 18-52-55](https://user-images.githubusercontent.com/65002498/167752982-6c336022-a467-465c-b024-1a5b6ca1b775.png)

2022-05-11 01:56 UTC, dvaldivia submitted a review, later dismissed

2022-05-11 02:14 UTC, bexsoft requested changes

2022-05-11 02:14 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/Account.tsx
> +                disabled={false}
If disabled will be always false, then we can remove this prop.

Also, Please review this behavior as I think that when user is logged with IDP this button should disappear

2022-05-11 22:14 UTC, bexsoft requested changes

2022-05-11 22:14 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/Account.tsx
>    useEffect(() => {
This information is stored in a reducer after session login. I think the key is `console.features`. You can omit this session request & check if the string `external-idp` is present in the reducer value

<img width="598" alt="Screen Shot 2022-05-11 at 17 12 32" src="https://user-images.githubusercontent.com/33497058/167956186-a52d627c-78c6-41b3-9cd2-bd001da4a50e.png">
<img width="326" alt="Screen Shot 2022-05-11 at 17 12 27" src="https://user-images.githubusercontent.com/33497058/167956188-893d05cb-b0f1-4747-b684-cb55827b9df4.png">

2022-05-13 04:24 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Account/ChangePasswordModal.tsx
> +        This will change your Console password. Please note your new password down, as it will be required to log into Console after this session.
We could update the text such that it is generic because , same credentials may be used in clients like  mc , or any application(SDK) .

2022-05-13 04:25 UTC, prakashsvmx approved these changes
:+1:  Changes look good to me.

2022-05-13 18:29 UTC, bexsoft approved these changes
LGTM

2022-05-13 19:09 UTC, dvaldivia approved these changes

2022-05-13 19:10 UTC, merged