Support for special characters and remove buggy functions
minio/console pull request #1977
Opened 2022-05-11 05:49 UTC by Alevsk

- remove the use of encodeURI and encodeURIComponent functions and
  instead use encodeFileName and decodeFileName functions
- support for users with special characters
- support for users with special characters
- support for users with special characters
- fixed incorrectly group list display for policies

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-05-11 19:00 UTC, harshavardhana requested changes

2022-05-11 20:12 UTC, bexsoft requested changes

2022-05-11 20:12 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/DeleteServiceAccount.tsx
> +      `/api/v1/service-accounts/${encodeFileName(selectedServiceAccount)}`
If we want to use this function for all the REST calls, then I think we must rename it as not everything are file names

2022-05-11 20:12 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +    // setPolicyName("");
Please remove this if useState was removed

2022-05-11 20:12 UTC, bexsoft commented on restapi/admin_groups.go
> +	// create a MinIO Admin Client interface implementation
```suggestion
	// Create a MinIO Admin Client interface implementation
```

2022-05-11 22:16 UTC, Alevsk commented on portal-ui/src/screens/Console/Groups/DeleteGroup.tsx
> +    closeDeleteModalAndRefresh(false);
This was a bug, we close the modal and redirect the user back to listing groups even if the delete operation failed

2022-05-11 22:17 UTC, Alevsk commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +    // setPolicyName("");
done

2022-05-12 04:14 UTC, bexsoft requested changes
Found a couple of issues:

- Add members to group returns 404 in group call
- Set policies to groups has the same issue too
- Add Groups to user
- Saving policies to user returns 404 and don't show the current policies
- Trying to create a service account for a user, redirect you back to buckets list


<img width="1425" alt="Screen Shot 2022-05-11 at 23 08 16" src="https://user-images.githubusercontent.com/33497058/167990750-c0989e92-27ea-4731-ba5b-1e35144a9608.png">
<img width="1464" alt="Screen Shot 2022-05-11 at 23 07 54" src="https://user-images.githubusercontent.com/33497058/167990757-a1c91041-c3f5-4bff-8ea2-54480f54d571.png">
<img width="1461" alt="Screen Shot 2022-05-11 at 23 07 16" src="https://user-images.githubusercontent.com/33497058/167990767-12954ae5-2b95-4223-b84a-25a5aee63565.png">
<img width="1414" alt="Screen Shot 2022-05-11 at 23 06 53" src="https://user-images.githubusercontent.com/33497058/167990769-bd5bb98c-f2eb-4579-9f46-aea764d7b6a5.png">

2022-05-12 21:20 UTC, Alevsk commented
> Found a couple of issues:
> 
> * Add members to group returns 404 in group call
> * Set policies to groups has the same issue too
> * Add Groups to user
> * Saving policies to user returns 404 and don't show the current policies
> * Trying to create a service account for a user, redirect you back to buckets list
> 
> <img alt="Screen Shot 2022-05-11 at 23 08 16" width="1425" src="https://user-images.githubusercontent.com/33497058/167990750-c0989e92-27ea-4731-ba5b-1e35144a9608.png">
> 
> <img alt="Screen Shot 2022-05-11 at 23 07 54" width="1464" src="https://user-images.githubusercontent.com/33497058/167990757-a1c91041-c3f5-4bff-8ea2-54480f54d571.png">
> 
> <img alt="Screen Shot 2022-05-11 at 23 07 16" width="1461" src="https://user-images.githubusercontent.com/33497058/167990767-12954ae5-2b95-4223-b84a-25a5aee63565.png">
> 
> <img alt="Screen Shot 2022-05-11 at 23 06 53" width="1414" src="https://user-images.githubusercontent.com/33497058/167990769-bd5bb98c-f2eb-4579-9f46-aea764d7b6a5.png">

This issues should be fixed now

2022-05-12 22:38 UTC, cniackz approved these changes
LGTM, it would be nice to increment the coverage threshold accordingly.
But can be done in a separate PR.

2022-05-13 16:21 UTC, dvaldivia submitted a review, later dismissed

2022-05-13 17:12 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/DeleteUserModal.tsx
> +      id: encodeURLString(userName),
Do we need to send user name twice?

2022-05-13 18:03 UTC, Alevsk commented on portal-ui/src/screens/Console/Users/DeleteUserModal.tsx
> +      id: encodeURLString(userName),
this was not need it indeed, its removed now

2022-05-13 18:18 UTC, bexsoft submitted a review, later dismissed
LGTM

2022-05-13 19:30 UTC, dvaldivia submitted a review, later dismissed

2022-05-13 20:07 UTC, bexsoft approved these changes

2022-05-13 20:13 UTC, dvaldivia approved these changes

2022-05-13 20:13 UTC, merged