[WIP] - To support multiple CSRs per tenant
minio/console pull request #1997
Opened 2022-05-13 18:23 UTC by cniackz

To support multiple CSRs per tenant, example:

```
storage-kms-encrypted  -client  -tenant-kms-encrypted-csr
storage-kms-encrypted  -kes     -tenant-kms-encrypted-csr
storage-kms-encrypted           -tenant-kms-encrypted-csr     
```

Where the nomenclature is like this:

`<tenant-name>-<*>-<namespace>-csr`

> * means anything, either something or nothing, so anything

I will apply TDD, test driven development making sure we can retrieve all the tenants from one particular tenant.

2022-05-16 21:33 UTC, Alevsk submitted a review, later dismissed

2022-05-17 04:37 UTC, bexsoft submitted a review, later dismissed

2022-05-24 18:20 UTC, dvaldivia approved these changes

2022-05-24 18:33 UTC, Alevsk requested changes

2022-05-24 18:33 UTC, Alevsk commented on operatorapi/volumes.go
> +	listResult, _ := clientset.CertificatesV1().CertificateSigningRequests().List(ctx, listByTenantLabel)
```suggestion
	listResult, err := clientset.CertificatesV1().CertificateSigningRequests().List(ctx, listByTenantLabel)
```
Please handle this errors here, a nil `listResult` may end on a `NPE` because of `listResult.Items`

2022-05-24 18:33 UTC, Alevsk commented on operatorapi/volumes.go
> +	listKESResult, _ := clientset.CertificatesV1().CertificateSigningRequests().List(ctx, listByKESLabel)
handle error

2022-05-24 21:11 UTC, Alevsk submitted a review, later dismissed

2022-05-24 22:23 UTC, bexsoft submitted a review, later dismissed

2022-05-25 00:26 UTC, cniackz commented
Ok, I tested this locally and it worked, now Operator API Test is failing, I need to investigate this further and fix it.
Tomorrow I will create a new commit with the fix if this is still not working.

2022-05-25 18:34 UTC, Alevsk approved these changes

2022-05-25 20:07 UTC, merged