Set access rules test
minio/console pull request #1998
Opened 2022-05-13 19:12 UTC by adfost

2022-05-13 19:26 UTC, dvaldivia requested changes

2022-05-13 19:26 UTC, dvaldivia commented on integration/access_rules_test.go
> +			expectedStatus: 200,
invalid should not return `200`, it should return `404`

2022-05-13 19:28 UTC, adfost commented on integration/access_rules_test.go
> +			expectedStatus: 200,
ok we just showed the code is broken. I can fix it.

2022-05-16 17:57 UTC, cniackz requested changes
Also remember to squash the commits from many to one 👍

2022-05-24 23:49 UTC, cniackz approved these changes

2022-05-24 23:50 UTC, cniackz approved these changes
LGTM

2022-05-24 23:53 UTC, cniackz approved these changes
LGTM

2022-05-25 22:14 UTC, dvaldivia approved these changes

2022-05-25 22:46 UTC, bexsoft approved these changes

2022-05-25 23:04 UTC, merged