Add new tab and section for displaying describe PVC output
minio/console pull request #2008
Opened 2022-05-17 23:32 UTC by reivaj05

Closes: https://github.com/miniohq/engineering/issues/458
Tests will be implemented in: 830

2022-05-18 17:49 UTC, jinapurapu submitted a review, later dismissed

2022-05-18 18:59 UTC, bexsoft requested changes

2022-05-18 18:59 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/pvcs/PVCDescribe.tsx
> +    <React.Fragment>
Please replace this to use Fragment only

```suggestion
    <Fragment>
```

2022-05-18 18:59 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/pvcs/PVCDescribe.tsx
> +}
Please define this inside a types file

2022-05-18 18:59 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/pvcs/PVCDescribe.tsx
> +    <React.Fragment>
Same case for this
```suggestion
    <Fragment>
```

2022-05-23 05:30 UTC, prakashsvmx approved these changes
Tested. Changes look good to me. :+1:

2022-05-23 20:02 UTC, dvaldivia approved these changes
tested. LGTM

2022-05-24 02:43 UTC, bexsoft approved these changes
LGTM

2022-05-24 02:43 UTC, merged