Warn if deleting user with associated Service Account
minio/console pull request #2022
Opened 2022-05-20 19:51 UTC by jinapurapu

![Screenshot from 2022-05-20 12-44-59](https://user-images.githubusercontent.com/65002498/169601104-851289b7-8b60-4c8e-ab6a-dd74bae9e176.png)

2022-05-20 21:09 UTC, cniackz approved these changes
LGTM, tested locally:
![image](https://user-images.githubusercontent.com/6667358/169610829-a1ca8c61-6580-4cb0-b226-aa3210c02844.png)

2022-05-20 21:13 UTC, cniackz commented
After user is deleted, service account is gone, which is good:

<img width="1838" alt="Screen Shot 2022-05-20 at 4 13 43 PM" src="https://user-images.githubusercontent.com/6667358/169611322-28f4fd20-fa55-4c00-a674-c4a883f2fe98.png">

2022-05-20 22:53 UTC, reivaj05 approved these changes

2022-05-20 23:24 UTC, bexsoft requested changes

2022-05-20 23:24 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/DeleteUser.tsx
> +        <>
Please use explicit Fragment
```suggestion
        <Fragment>
```

2022-05-21 04:04 UTC, bexsoft approved these changes
LGTM

2022-05-21 09:35 UTC, prakashsvmx approved these changes

2022-05-23 05:14 UTC, merged