Removed unneeded encoding of credentials download
minio/console pull request #2032
Opened 2022-05-24 18:33 UTC by jinapurapu

Fixes https://github.com/minio/console/issues/2031

2022-05-24 19:30 UTC, bexsoft approved these changes
LGTM

2022-05-24 19:31 UTC, bexsoft requested changes

2022-05-24 19:31 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/CredentialsPrompt/CredentialsPrompt.tsx
> +    "data:text/plain;charset=utf-8," + text
Please remove import for this:

https://github.com/minio/console/pull/2032/files#diff-9989d3345835ccb52d5ca352ea42ce0c6d4491b0aaca18f522b348da477fb08aR30

2022-05-24 19:47 UTC, bexsoft approved these changes
LGTM

2022-05-24 19:57 UTC, dvaldivia approved these changes

2022-05-25 05:07 UTC, prakashsvmx approved these changes
:+1:

2022-05-25 19:48 UTC, merged