Logs, Watch Slices to replace old reducers
minio/console pull request #2035
Opened 2022-05-24 23:36 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-05-25 19:47 UTC, bexsoft requested changes
Labels under node selector are not working. Values doesn't change.
<img width="1143" alt="Screen Shot 2022-05-25 at 14 41 09" src="https://user-images.githubusercontent.com/33497058/170354191-ae95f20d-2082-417a-857b-aad9614cfc38.png">

Identity Provider > Built-in, cannot add additional users

Identity Provider > Active Directory, cannot add additional users under List of user DNs

2022-05-25 19:47 UTC, bexsoft commented on portal-ui/src/screens/Console/Logs/ErrorLogs/ErrorLogs.tsx
> +        dispatch(dispatch(setLogsStarted(false)));
Do we need a double dispatch here?

2022-05-25 19:47 UTC, bexsoft commented on restapi/ws_handle.go
> +	// // DELETE ME !!!
```suggestion
	// DELETE ME !!!
```

2022-05-25 23:59 UTC, Alevsk approved these changes

2022-05-26 00:03 UTC, bexsoft approved these changes
LGTM

2022-05-26 00:12 UTC, merged