Fixed formatting of Site Replication Helpbox text
minio/console pull request #2080
Opened 2022-06-02 21:15 UTC by jinapurapu

2022-06-02 22:43 UTC, dvaldivia submitted a review, later dismissed

2022-06-03 11:03 UTC, prakashsvmx requested changes
one comment. else changes look good to me

2022-06-03 11:03 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Configurations/SiteReplication/SiteReplication.tsx
> +  const hasSites = !sites?.length;
please  update the condition as `const hasSites = sites?.length;` as per the old code. Hope it was used to take the screenshots.

2022-06-03 18:49 UTC, kaankabalak approved these changes

2022-06-03 18:52 UTC, bexsoft approved these changes

2022-06-04 02:19 UTC, merged