API to receive an email address and set it
minio/console pull request #2095
Opened 2022-06-07 00:22 UTC by reivaj05

Closes: https://github.com/miniohq/engineering/issues/870

This PR adds an API to receive and set email addresses for marketplace operators

2022-06-07 19:41 UTC, bexsoft approved these changes

2022-06-08 15:59 UTC, dvaldivia requested changes

2022-06-08 15:59 UTC, dvaldivia commented on operatorapi/configure_operator.go
> +	// Namespaces handlers
this comment needs updating

2022-06-09 22:42 UTC, bexsoft approved these changes

2022-06-09 22:42 UTC, dvaldivia approved these changes

2022-06-09 23:13 UTC, merged