Added Initial Time support to Prometheus dashboard
minio/console pull request #2099
Opened 2022-06-07 19:36 UTC by bexsoft

## What does this do?

Added Initial Time support to Prometheus dashboard metrics, also incremented initial time for data usage growth chart

## How does it look?
<img width="1298" alt="Screen Shot 2022-06-07 at 14 34 55" src="https://user-images.githubusercontent.com/33497058/172467328-18c17ca2-4456-4473-8c6c-add0700be193.png">

2022-06-07 22:01 UTC, dvaldivia submitted a review, later dismissed

2022-06-07 23:25 UTC, cniackz commented
I got prometheus working locally in port 9000 with these instructions https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html?ref=con#minio-metrics-collect-using-prometheus
But how you test this on port 5005? 🤔

2022-06-07 23:43 UTC, bexsoft commented
> I got prometheus working locally in port 9000 with these instructions https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html?ref=con#minio-metrics-collect-using-prometheus But how you test this on port 5005? 🤔

You can start console server using this flag: `CONSOLE_PROMETHEUS_URL=http://localhost:9091/` changing the port according your prometheus settings (just be aware prometheus is using the same ports as MinIO & Console)

2022-06-08 01:19 UTC, cniackz approved these changes
It looks good to me even when no data is ignored from the graph.

2022-06-08 01:49 UTC, cniackz commented
Actually this is much more accurate even when it looks ugly is more accurate:

<img width="1840" alt="Screen Shot 2022-06-07 at 9 48 46 PM" src="https://user-images.githubusercontent.com/6667358/172513886-d6af9d9b-6795-480a-abf6-00f7a0248045.png">

### Code change:

```go
$ git diff restapi/admin_info.go
diff --git a/restapi/admin_info.go b/restapi/admin_info.go
index 31434a07..31a49efa 100644
--- a/restapi/admin_info.go
+++ b/restapi/admin_info.go
@@ -296,7 +296,7 @@ var widgets = []Metric{
                                Expr:         `sum(minio_bucket_usage_total_bytes{$__query}) by (instance)`,
                                LegendFormat: "Used Capacity",
                                InitialTime:  -180,
-                               Step:         900,
+                               Step:         10,
                        },
                },
        },
```

2022-06-08 02:03 UTC, cniackz requested changes
Can we discuss this tomorrow? For me to show you my scenario, then we can decide if we change the `Step` value.

2022-06-08 02:03 UTC, cniackz commented on restapi/admin_info.go
> +				Step:         900,
`900` will give a very small number of steps and graph will be confusing and not accurate enough:

![image](https://user-images.githubusercontent.com/6667358/172515251-1ce009ae-ca91-4963-8570-d2b71779e262.png)

for the same data with `Steps` equal `10` we can get a much better resolution of what I did during these hours:

![image](https://user-images.githubusercontent.com/6667358/172515313-cbada886-1458-47e6-843d-4d4bb13fff0d.png)

2022-06-08 02:06 UTC, cniackz commented
My question is, do we want to show just an approximation of the usage or real data?...
If we just want an approximation then this change might be ok, but for some customers I bet this will be confusing as graph may not contain desired points in time.

2022-06-09 00:15 UTC, bexsoft commented on restapi/admin_info.go
> +				Step:         900,
Agree on this, what happens if we set Step to 60? does it still show good information? 

The issue with setting to 10 is that the chart will slow down on old computers as we will be throwing too much information to plot each point in the chart this can lead to a hard hang in the application. I think a value between 60 and 300 could work, what do you think?

2022-06-09 19:33 UTC, cniackz commented on restapi/admin_info.go
> +				Step:         900,
Let me quickly test it, one sec

2022-06-09 19:42 UTC, cniackz commented on restapi/admin_info.go
> +				Step:         900,
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/6667358/172930905-0904f178-ad44-435c-89a8-fca208830876.png">

In a quick run we are going to still have some innacurate behaviour with `300` but it will be much better than `900` I believe. I guess this is more like a aestetic change to perform. So let's try to put this in 300 and adjust according to the end user input.

2022-06-09 22:41 UTC, bexsoft commented
Setting Step to 10, will see how it behaves, in case something goes strange, we can increment this value

2022-06-09 22:52 UTC, merged