Prompt email after login
minio/console pull request #2108
Opened 2022-06-09 18:35 UTC by reivaj05

Closes https://github.com/miniohq/engineering/issues/876

This PR adds a new component that will be used to register email when operator console is in Marketplace mode

2022-06-09 18:59 UTC, jinapurapu requested changes

2022-06-09 18:59 UTC, jinapurapu commented on portal-ui/src/screens/Console/Marketplace/SetEmailModal.tsx
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-06-14 21:53 UTC, Alevsk commented
We need to have a GDPR discussion about this feature @harshavardhana @aead @dvaldivia

2022-06-23 17:49 UTC, dvaldivia approved these changes

2022-06-23 19:22 UTC, merged