Policy selector fix
minio/console pull request #2123
Opened 2022-06-13 23:30 UTC by jinapurapu

Policy selector for users and groups was not working after Redux changes. Updated to use redux state in policy selectors. 

![Screenshot from 2022-06-13 16-27-10](https://user-images.githubusercontent.com/65002498/173463653-505bca74-86f6-40b8-a729-33ea15cde5ab.png)
![Screenshot from 2022-06-13 16-29-43](https://user-images.githubusercontent.com/65002498/173463881-b0ae8b33-8e54-4f04-9480-fcd8c94d5040.png)

2022-06-13 23:54 UTC, dvaldivia submitted a review, later dismissed
Tested. LGTM.

2022-06-14 00:21 UTC, kaankabalak commented on portal-ui/src/screens/Console/Users/AddUsersSlice.tsx
> +            console.log("You clicked the thing! You're in the reducer")
@jinapurapu Can we remove the `console.log` statement here please?

2022-06-14 00:28 UTC, bexsoft requested changes
LGTM, Please remove console log

2022-06-14 16:04 UTC, kaankabalak approved these changes

2022-06-14 16:05 UTC, reivaj05 approved these changes

2022-06-14 17:18 UTC, merged