Release v0.19.0
minio/console pull request #2125
Opened 2022-06-14 21:51 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-06-14 21:54 UTC, Alevsk approved these changes

2022-06-14 21:56 UTC, harshavardhana approved these changes

2022-06-15 19:15 UTC, harshavardhana commented
```
Building minio docker image 'minio/minio:8082d1fed6b5262cb34f74be14bafd462d088160'
sha256:aa9b64e1170e60a65dab1ea1a76c8aeb8274dcf70ed263cb8c908fc9499db4fc
Jumping back to console repository to run the integration test
We are going to use the built image on test-integration
minio/minio:8082d1fed6b5262cb34f74be14bafd462d088160
Create bucket for replication with versioning
Download mc for Ubuntu
Change the permissions to execute mc command
Create the folder to put the all.out file
TARGET_BUCKET: bce8a9d616389b2fbfb9
mc: <ERROR> Unable to make bucket `play/bce8a9d616389b2fbfb9/`. Server not initialized, please try again.
Error: Process completed with exit code 1.
```

In CI/CD you should really not depend on `play/`

2022-06-15 19:59 UTC, bexsoft requested changes
Need to update assets

2022-06-15 23:32 UTC, dvaldivia commented
done @bexsoft

2022-06-15 23:34 UTC, bexsoft approved these changes

2022-06-15 23:38 UTC, bexsoft submitted a review, later dismissed

2022-06-16 00:14 UTC, reivaj05 approved these changes

2022-06-16 01:11 UTC, harshavardhana approved these changes

2022-06-16 01:14 UTC, bexsoft approved these changes

2022-06-16 01:18 UTC, merged