UI AGPL license consent
minio/console pull request #2154
Opened 2022-06-29 11:16 UTC by prakashsvmx

How does it look?:

![image](https://user-images.githubusercontent.com/23444145/176422796-ca386925-772f-438d-ba47-0e3f2bb7514e.png)

The acknowledgement is stored in local storage key. if it is cleared, it would prompt again.

2022-06-29 17:23 UTC, oscarocastellanos approved these changes
LGTM

2022-06-30 03:35 UTC, bexsoft commented on portal-ui/src/screens/Console/License/LicenseConsentModal.tsx
> +    setLicenseConsent(); //to Local storage.
I think we should hide the red dot in the menu once the user acknowledge this

2022-06-30 03:36 UTC, bexsoft requested changes

2022-06-30 03:36 UTC, bexsoft commented on portal-ui/src/screens/Console/License/LicenseConsentModal.tsx
> +    setLicenseConsent(); //to Local storage.
I think we should hide the red dot in the menu once the user acknowledge this

2022-06-30 19:28 UTC, bexsoft approved these changes
LGTM

2022-07-05 16:12 UTC, reivaj05 approved these changes

2022-07-05 16:13 UTC, cniackz commented
<img width="1840" alt="Screen Shot 2022-07-05 at 12 13 08 PM" src="https://user-images.githubusercontent.com/6667358/177371596-09c0a156-a8a6-401b-952a-b9bf54b3a479.png">

Yeap, I can see the pop-up from here.

2022-07-05 16:14 UTC, cniackz approved these changes
Looks good to me, it appears once if acknowledged

2022-07-05 16:17 UTC, merged