Tenant Monitoring Screen TestCafe UI tests
minio/console pull request #2161
Opened 2022-07-02 01:41 UTC by jinapurapu

Tests that text can be entered into fields on Monitoring screen, saved, and confirmed to have been saved on the YAML.

2022-07-02 03:35 UTC, bexsoft requested changes

2022-07-02 03:35 UTC, bexsoft commented on portal-ui/tests/operator/utils.ts
> +  // .ok();
These lines can be removed

2022-07-05 12:35 UTC, jinapurapu commented on portal-ui/tests/operator/utils.ts
> +  // .ok();
This was passing locally, but failed on Github. I will look into this and fix it, until then I am flagging this as WIP.

2022-07-15 04:29 UTC, kaankabalak approved these changes

2022-07-15 19:06 UTC, bexsoft approved these changes
LGTM

2022-07-15 19:06 UTC, merged