Split register section in tabs
minio/console pull request #2176
Opened 2022-07-18 19:48 UTC by reivaj05

Splits Register section in tabs.

This was done by @bexsoft, i'm just creating a new PR with his changes since his other PR where this is implemented is blocked for the moment: https://github.com/minio/console/pull/2168

![Screen Shot 2022-07-18 at 14 45 42](https://user-images.githubusercontent.com/10521119/179605056-5bdcdc30-5f14-46b9-8f8c-834f1759bed2.png)
![Screen Shot 2022-07-18 at 14 45 55](https://user-images.githubusercontent.com/10521119/179605059-7c12084d-6fdb-4e3d-8749-6d8502b3cbcf.png)

2022-07-18 22:48 UTC, cniackz approved these changes
LGTM

2022-07-20 03:44 UTC, jinapurapu requested changes
The proxy input field is always disabled

2022-07-20 03:44 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/Register.tsx
> +        </Fragment>
This field is always disabled (at 912)
```suggestion
        {displaySubnetProxy && (
                  <InputBoxWrapper
                    disabled
                    id="subnetProxy"
                    name="subnetProxy"
                    placeholder=""
                    onChange={() => {}}
                    label=""
                    value={proxyConfigurationCommand}
                    overlayIcon={<CopyIcon />}
                    extraInputProps={{
                      readOnly: true,
                    }}
                    overlayAction={() =>
                      navigator.clipboard.writeText(proxyConfigurationCommand)
                    }
                  />
                )}
```

2022-07-20 18:56 UTC, reivaj05 commented on portal-ui/src/screens/Console/Support/Register.tsx
> +        </Fragment>
That's the expected behavior, we can only copy the text inside the input

2022-07-20 23:44 UTC, dvaldivia approved these changes

2022-07-21 01:26 UTC, merged