Implement Websockets for Profile download
minio/console pull request #2190
Opened 2022-07-22 00:43 UTC by kaankabalak

2022-07-22 11:56 UTC, kaankabalak commented
Seems like the integration tests are failing, will take a look at it. Marking the PR as WIP for now.

```
=== CONT  TestStartProfiling
    profiling_test.go:79: 
        	Error Trace:	profiling_test.go:79
        	Error:      	Not equal: 
        	            	expected: 201
        	            	actual  : 501
        	Test:       	TestStartProfiling
failed to write error response: applicationZip producer has not yet been implemented
    profiling_test.go:97: 
        	Error Trace:	profiling_test.go:97
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 501
        	Test:       	TestStartProfiling
    profiling_test.go:103: 
        	Error Trace:	profiling_test.go:103
        	Error:      	Not equal: 
        	            	expected: "application/zip"
        	            	actual  : "text/plain; charset=utf-8"
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-application/zip
        	            	+text/plain; charset=utf-8
        	Test:       	TestStartProfiling
    profiling_test.go:107: 
        	Error Trace:	profiling_test.go:107
        	Error:      	Expected nil, but got: &errors.errorString{s:"zip: not a valid zip file"}
        	Test:       	TestStartProfiling
        	Messages:   	start/stop profiling returned an error: zip: not a valid zip file
--- FAIL: TestStartProfiling (5.01s)
```

2022-07-22 12:52 UTC, kaankabalak commented
> Seems like the integration tests are failing, will take a look at it. Marking the PR as WIP for now.

Fixed the integration test failures, reopening the PR for reviews

2022-07-22 18:08 UTC, dvaldivia requested changes

2022-07-22 18:08 UTC, dvaldivia commented on .github/workflows/jobs.yaml
> +          threshold=53.30
We shouldn't decrease the coverage threshold, if enough code was introduced to cause this to fail, additional tests need to be written to cover the new code.

In this case`ws_handle.go` code added has no test for it it seems
<img width="925" alt="Screen Shot 2022-07-22 at 11 08 02 AM" src="https://user-images.githubusercontent.com/18384552/180498481-6e53dc17-202f-4e2e-bb05-fe7b370b6b97.png">
<img width="1087" alt="Screen Shot 2022-07-22 at 11 07 58 AM" src="https://user-images.githubusercontent.com/18384552/180498487-50f9b2ad-ab63-4137-b8d9-9a67b1f740bf.png">

2022-07-22 18:53 UTC, kaankabalak commented on .github/workflows/jobs.yaml
> +          threshold=53.30
Thanks for letting me know @dvaldivia, will add tests for this part of the code 👍

2022-07-26 04:20 UTC, kaankabalak commented on .github/workflows/jobs.yaml
> +          threshold=53.30
Fixed

2022-07-26 04:21 UTC, kaankabalak commented
@dvaldivia, I have addressed your feedback, would appreciate if you could take another look. Thanks in advance 👍

2022-07-26 22:07 UTC, dvaldivia approved these changes
Tested. LGTM.

2022-07-26 23:23 UTC, bexsoft approved these changes
LGTM, Do we still need the Stop Profiling button?

2022-07-26 23:36 UTC, kaankabalak commented
@bexsoft I thought we might want to keep it just in case the profiling takes too long. If required, I can send in another PR to make this change 👍

2022-07-27 01:40 UTC, merged