Auto register API Key once it's retrieved from Subnet and minor refactor
minio/console pull request #2195
Opened 2022-07-22 22:22 UTC by reivaj05

2022-07-26 23:31 UTC, bexsoft requested changes

2022-07-26 23:31 UTC, bexsoft commented on portal-ui/src/screens/Console/Support/Register.tsx
> +          <ApiKeyRegister classes={classes} afterRegister={fetchLicenseInfo} />
Classes shouldn't be passed this way. Please implement HOC in ApiKeyRegister or load them using `useStyles` hook.

2022-07-27 23:29 UTC, cniackz commented
All good, except we can't decrease our coverage:

<img width="484" alt="Screen Shot 2022-07-27 at 7 29 16 PM" src="https://user-images.githubusercontent.com/6667358/181389653-d55a2ec8-60a1-4260-9f50-1efe0659f836.png">

2022-07-27 23:29 UTC, cniackz reviewed
All good, except we can't decrease our coverage.

2022-07-27 23:49 UTC, cniackz commented
As this is FE change only, please adjust Threshold accordingly.
Not sure why this is affected. But we can figure that later on.

2022-08-01 23:16 UTC, bexsoft submitted a review, later dismissed
Could you please squash all the commits in a single one?  Thank you!

2022-08-01 23:42 UTC, reivaj05 commented
new PR https://github.com/minio/console/pull/2217

2022-08-01 23:42 UTC, closed without merging