Reimplemented DirectPV API in operator console
minio/console pull request #2207
Opened 2022-07-28 22:54 UTC by bexsoft

## What does this do?
- Reimplemented DirectPV API in operator console
- Updated API to use latest directpv library

**NOTE:** This requires https://github.com/minio/directpv/pull/615 to get merged in order to remove replace in go.mod

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-07-29 05:02 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +			if driveItem.Status.DriveStatus == directcsi.DriveStatusUnavailable {
we should also deny format requests for "Released" drive state

you can refer https://github.com/minio/directpv/blob/master/cmd/kubectl-directpv/drives_format.go#L104 for such conditions

2022-07-29 23:16 UTC, reivaj05 requested changes

2022-07-29 23:16 UTC, reivaj05 commented on operatorapi/directpv.go
> +// This file is part of MinIO Console Server
Please add tests for the code that was added

2022-08-04 22:11 UTC, bexsoft commented on operatorapi/directpv.go
> +// This file is part of MinIO Console Server
Added some test cases, extra cases can be added in an upcoming PR

2022-08-05 19:22 UTC, reivaj05 approved these changes

2022-08-09 10:40 UTC, Praveenrajmani commented on go.mod
> +replace github.com/minio/directpv => github.com/Praveenrajmani/direct-csi v0.2.2-0.20220727063700-b3c6a60de191
the PR got merged, we can use the master branch's commid id

```
require (
    github.com/minio/directpv 948ca473165172621e805ef44e43c123eca70904
)
```

2022-08-09 10:40 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +		volumes := len(d.Finalizers)
drive's finalizers have one reserved finalizer - `/purge-protection` - we need to skip that

```go
if len(d.Finalizers) > 1 {
	volumes = len(d.Finalizers)-1
}
```

2022-08-09 10:40 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +			for _, c := range d.Status.Conditions {
We can do something like this

```go
msg := ""
for _, c := range d.Status.Conditions {
	switch c.Type {
		case string(directcsi.DirectCSIDriveConditionInitialized), string(directcsi.DirectCSIDriveConditionOwned), string(directcsi.DirectCSIDriveConditionReady):
			if c.Status != metav1.ConditionTrue {
				msg = c.Message
				if msg != "" {
					status = d.Status.DriveStatus + "*"
					msg = strings.ReplaceAll(msg, d.Name, "")
					msg = strings.ReplaceAll(msg, getDirectCSIPath(d.Status.FilesystemUUID), drive)
					msg = strings.ReplaceAll(msg, directCSIPartitionInfix, "")
					msg = strings.Split(msg, "\n")[0]
				}
			}
	}
}
```

reference: https://github.com/minio/directpv/blob/master/cmd/kubectl-directpv/drives_list.go#L216

2022-08-09 10:40 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +			}
```go
if drive.Status.DriveStatus == directcsi.DriveStatusInUse {
	...
        ...
}

if drive.Status.DriveStatus == directcsi.DriveStatusReady {
	...
        ...
}

if drive.Status.Filesystem != "" && !force {
	...
        ...
}

if drive.Status.DriveStatus == directcsi.DriveStatusReleased {
	...
        ...
}
```

ref: https://github.com/minio/directpv/blob/master/cmd/kubectl-directpv/drives_format.go#L107

2022-08-09 22:23 UTC, bexsoft commented on operatorapi/directpv.go
> +		volumes := len(d.Finalizers)
Changed

2022-08-10 16:43 UTC, Praveenrajmani commented on cluster/cluster.go
> +func DirectPVDriveInterface(token string) (*directpvclient.DirectCSIDriveInterface, error) {
Just a small suggestion if it can be achievable - Can we initialize the directpv clients (both the drive and volume clients) only once and use it in a global scope?

Like, keeping drive and volume clients as global vars and use it throughout the scope. 

The function `DirectCSIDriveInterfaceForConfig` would read the config and calls few k8s discovery APIs underneath. So, by storing them as global vars, we can skip this instead of loading them on each API hits.

2022-08-10 16:43 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +	drivesList, err := driveInterface.List(ctx, metav1.ListOptions{})
we don't need to list directpv drives to know the path. The volume labels have the path of the drive. 

for reference: https://github.com/minio/directpv/blob/master/cmd/kubectl-directpv/volumes_list.go#L155

2022-08-10 16:43 UTC, Praveenrajmani commented on operatorapi/directpv.go
> +				base.Error = "Drive is in 'released state'. Please unrelease before formatting"
The `unrelease` command is deprecated in directpv. Releasing a drive would umount it and make it "Available" automatically. 

So, we can just say `Drive is in 'released state'. Please wait until it becomes available`

2022-08-12 04:10 UTC, bexsoft commented on cluster/cluster.go
> +func DirectPVDriveInterface(token string) (*directpvclient.DirectCSIDriveInterface, error) {
In this case this is the pattern we are following in other apis for console, also it helps to test individual functions

2022-08-12 04:27 UTC, bexsoft commented on operatorapi/directpv.go
> +	drivesList, err := driveInterface.List(ctx, metav1.ListOptions{})
Fixed

2022-08-12 04:27 UTC, bexsoft commented on operatorapi/directpv.go
> +				base.Error = "Drive is in 'released state'. Please unrelease before formatting"
Fixed

2022-08-16 21:03 UTC, reivaj05 approved these changes

2022-08-17 17:20 UTC, Praveenrajmani approved these changes
LGTM

2022-08-17 18:05 UTC, merged