UI to delete configured notification targets
minio/console pull request #2213
Opened 2022-08-01 09:48 UTC by prakashsvmx

UI to delete configured notification targets

2022-08-03 19:01 UTC, reivaj05 approved these changes

2022-08-08 19:20 UTC, bexsoft requested changes

2022-08-08 19:20 UTC, bexsoft commented on portal-ui/src/screens/Console/NotificationEndpoints/ListNotificationEndpoints.tsx
> +          />
Can we make this an independent component, please?

2022-08-09 04:53 UTC, prakashsvmx commented on portal-ui/src/screens/Console/NotificationEndpoints/ListNotificationEndpoints.tsx
> +          />
Thank you :+1: . refactored into a component.

2022-08-17 18:24 UTC, reivaj05 approved these changes

2022-08-17 20:40 UTC, bexsoft approved these changes
LGTM

2022-08-17 20:40 UTC, merged