Image field fix
minio/console pull request #2231
Opened 2022-08-05 21:54 UTC by jinapurapu

Allows underscore in image fields for Audit Log and Prometheus Monitoring config screens. Also fixes missing DBInitImage update in setTenantLogs
![Screenshot from 2022-08-05 14-50-52](https://user-images.githubusercontent.com/65002498/183215944-ba7c9808-94c0-4424-942a-6fb712ffb855.png)
![Screenshot from 2022-08-05 14-51-20](https://user-images.githubusercontent.com/65002498/183215947-12ad3f22-086a-48b8-adba-0022eb7a970c.png)
.

2022-08-08 02:58 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Tenants/TenantDetails/EditTenantMonitoringScreen.tsx
> +              pattern={"^[a-zA-Z0-9-_./:]{1,253}$"}
`"^[a-zA-Z0-9-_./:]{1,253}$"` this could be extracted into a Constant and imported wherever it is used.

2022-08-08 20:00 UTC, bexsoft requested changes

2022-08-08 20:00 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/utils.ts
> +export const resourcePattern = "[0-9]*";
This should be calles numeric pattern  as we are using it in other parts of the application too
```suggestion
export const numericPattern = "[0-9]*";
```

2022-08-08 20:28 UTC, reivaj05 approved these changes

2022-08-08 20:33 UTC, bexsoft approved these changes

2022-08-09 06:43 UTC, prakashsvmx approved these changes
LGTM :+1:

2022-08-09 16:04 UTC, merged