Call Home Enabled in console
minio/console pull request #2248
Opened 2022-08-16 00:19 UTC by bexsoft

## What does this do?

Enabled Call Home functionality in Console

**NOTE: ** Tests for API will be handled in a new PR

## How does it look?

<img width="1093" alt="Screen Shot 2022-08-15 at 19 16 16" src="https://user-images.githubusercontent.com/33497058/184757627-ffc44828-e8b5-4579-837b-dbd2f4f90a8e.png">
<img width="1186" alt="Screen Shot 2022-08-15 at 19 16 08" src="https://user-images.githubusercontent.com/33497058/184757629-115c0bc5-3867-496c-9fe6-0f604bb5875c.png">
<img width="1684" alt="Screen Shot 2022-08-15 at 18 54 49" src="https://user-images.githubusercontent.com/33497058/184757632-87cc2507-8dff-463b-a155-1151de288cd2.png">
<img width="1721" alt="Screen Shot 2022-08-15 at 18 54 34" src="https://user-images.githubusercontent.com/33497058/184757635-81dd87eb-e457-4175-bb3a-11ad48391c1d.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-08-19 16:03 UTC, jinapurapu requested changes

2022-08-19 17:43 UTC, jinapurapu requested changes

2022-08-19 17:43 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHomeConfirmation.tsx
> +      title={currentStatus ? "Disable CallHome" : "Enable CallHome"}
```suggestion
      title={currentStatus ? "Disable Call Home" : "Enable Call Home"}
```

2022-08-19 17:56 UTC, jinapurapu commented
I don't have Subnet credentials to test the API, but UI LGTM

2022-10-07 18:50 UTC, cniackz commented
@bexsoft when you get a chance, please resolve the conflicts:

<img width="1033" alt="Screen Shot 2022-10-07 at 2 50 27 PM" src="https://user-images.githubusercontent.com/6667358/194630215-be6c0ef4-bc22-40bd-acaf-bf23c239de4c.png">

2022-10-07 18:52 UTC, cniackz commented
ok ignore my previous comment, maybe we need to have this on subnet first...

2023-02-08 00:35 UTC, bexsoft commented
> @bexsoft when you get a chance, please resolve the conflicts:
> 
> <img alt="Screen Shot 2022-10-07 at 2 50 27 PM" width="1033" src="https://user-images.githubusercontent.com/6667358/194630215-be6c0ef4-bc22-40bd-acaf-bf23c239de4c.png">

Fixed

2023-02-08 00:39 UTC, bexsoft commented
Original PR: https://github.com/minio/console/pull/1664

2023-02-08 04:12 UTC, allanrogerr commented
@bexsoft How do I enable these new options on the console - again I pulled the branch, checked out, ran `make k8sdev` and reloaded the console pod. I cannot see Call Home.

2023-02-08 05:27 UTC, dvaldivia approved these changes

2023-02-08 11:46 UTC, prakashsvmx commented
@bexsoft @dvaldivia 

the call home can be enabled selectively as well
e.g
 `mc support callhome enable <alias>   --logs ` 
 `mc support callhome enable <alias>   --diag `

So we would have to add these options in the UI as well. 
Could you please check this ?

2023-02-08 17:00 UTC, bexsoft commented
> @bexsoft @dvaldivia
> 
> the call home can be enabled selectively as well e.g `mc support callhome enable <alias> --logs ` `mc support callhome enable <alias> --diag `
> 
> So we would have to add these options in the UI as well. Could you please check this ?

Hi @prakashsvmx !

Yes, Let me add them, this is an old PR so these features were not available at the time of development.

2023-02-09 00:04 UTC, allanrogerr approved these changes
Tested

2023-02-09 00:07 UTC, allanrogerr requested changes
After attempting to use the API, the changes are not visible in the UI after refreshing the page

➜  portal-ui git:(call-home-api) ✗ sudo mc support callhome disable myminio --logs --insecure
Logs is now disabled

but,

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/16472240/217680306-636f23d7-9185-4213-9a13-2f80b9ab2c38.png">

2023-02-10 02:19 UTC, bexsoft commented
> After attempting to use the API, the changes are not visible in the UI after refreshing the page
> 
> ➜ portal-ui git:(call-home-api) ✗ sudo mc support callhome disable myminio --logs --insecure Logs is now disabled
> 
> but,
> 
> <img alt="image" width="1049" src="https://user-images.githubusercontent.com/16472240/217680306-636f23d7-9185-4213-9a13-2f80b9ab2c38.png">

Yes, this was related to a functionality that was not implemented at the time this PR was originally made, implemented new functionality and redesigned screens

2023-02-10 02:37 UTC, dvaldivia submitted a review, later dismissed

2023-02-10 05:13 UTC, pjuarezd commented
Tested, build console and minio and loaded it into k8s kind using docker image, now the UI shows the callhome section

But keep receiving error code 500 in endpoint `https://localhost:9444/api/v1/support/callhome`.

```json
{"code":500,"detailedMessage":"there is no target `subnet` for subsystem `logger_webhook`","message":"an error occurred, please try again"}
```

Could I be missing something?

![Screenshot 2023-02-09 at 8 26 07 PM](https://user-images.githubusercontent.com/1334362/218002438-cc264ea2-d6ed-4313-b8a7-a56e9e585e19.png)

So, I though it could be that I am missing to login  in subnet, or register the cluster, so I went to subnet and reguistered it (using airgap method)

![Screenshot 2023-02-09 at 8 36 40 PM](https://user-images.githubusercontent.com/1334362/218003058-47a646c9-42ee-4b36-b028-438a586f087d.png)

```sh
 ~ mc license update callhome ./cluster-license-.key --insecure
License updated successfully for callhome
```

And I still see the "Register your cluster" button, additionally to the redbanner error


<img width="1508" alt="Screenshot 2023-02-09 at 8 17 19 PM" src="https://user-images.githubusercontent.com/1334362/218005044-ac3195dc-4f2e-44bb-9b6b-80d0990076fa.png">

![Screenshot 2023-02-09 at 8 45 38 PM](https://user-images.githubusercontent.com/1334362/218003194-f570eeb9-62c2-47a1-b190-bd78ca0e4175.png)

So, noticed that a restart of the minio services is required to show the cluster as registered, so perhaps is worth show the "The instance needs to be restarted for configuration changes to take effec" banner?

![Screenshot 2023-02-09 at 8 55 39 PM](https://user-images.githubusercontent.com/1334362/218004568-2ce9bee2-fd70-46fe-91fa-0e3c01b9b204.png)

Anyways, I restarted the cluster like this

```~ mc admin service restart callhome --insecure
Restart command successfully sent to `callhome`. Type Ctrl-C to quit or wait to follow the status of the restart process.
...!!
Restarted `callhome` successfully in 3 seconds
```

But I keep receiving that red banner error message, but at least I can enable callhome now

![Screenshot 2023-02-09 at 9 03 43 PM](https://user-images.githubusercontent.com/1334362/218005278-6d05c11e-55ae-40d8-8c8c-b01d25a605e6.png)


A console hard refresh and now the red banner is gone, looks like console (or minio, not sure) is looking for that webhook  even before callhome is activated, because once calhome is activated it shows the logging webhook  and the red banner dissapeared.
![Screenshot 2023-02-09 at 9 08 56 PM](https://user-images.githubusercontent.com/1334362/218005964-bc8e17a1-9b8f-4be1-b2cb-57fb254cad16.png)

2023-02-10 18:13 UTC, bexsoft commented
Fixing red banner

2023-02-10 18:54 UTC, jinapurapu requested changes

2023-02-10 18:54 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHome.tsx
> +    /*clusterRegistered &&*/ diagEnabled !== oDiagEnabled ||
Please remove comment

2023-02-10 18:54 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHome.tsx
> +                      "                  subnet account. Get real-time insights and troubleshoot issues quickly"
```suggestion
                      "                  subnet account. Get real-time insights and troubleshoot issues quickly."
```

2023-02-10 18:54 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHome.tsx
> +                      "                  seamless performance and identify potential issues before they escalate"
```suggestion
                      "                  seamless performance and identify potential issues before they escalate."
```

2023-02-10 18:54 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHomeConfirmation.tsx
> +          Please Acknowledge that doing this action, we will not receive updated
```suggestion
          Please Acknowledge that after doing this action, we will no longer receive updated
```

2023-02-10 18:54 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHomeConfirmation.tsx
> +          cluster information automatically anymore, losing the potential
```suggestion
          cluster information automatically, losing the potential
```

2023-02-10 19:26 UTC, bexsoft commented on portal-ui/src/screens/Console/Support/CallHome.tsx
> +    /*clusterRegistered &&*/ diagEnabled !== oDiagEnabled ||
Fixed

2023-02-10 19:35 UTC, jinapurapu requested changes

2023-02-10 19:35 UTC, jinapurapu commented on portal-ui/src/screens/Console/Support/CallHome.tsx
> +                      "                  subnet account. Get real-time insights and troubleshoot issues quickly."
```suggestion
                      "                  SUBNET account. Get real-time insights and troubleshoot issues quickly."
```

2023-02-10 20:04 UTC, jinapurapu approved these changes

2023-02-10 20:46 UTC, allanrogerr approved these changes

2023-02-10 21:39 UTC, pjuarezd approved these changes
no red banner, all good!

2023-02-13 23:04 UTC, merged