Fixes and improvements for Tenant Security page
minio/console pull request #2252
Opened 2022-08-17 23:58 UTC by Alevsk

- tenant securityContext was only being applied to first pool
- fixed style issues on tenant security page to be more consistent
- added missing FsGroupChangePolicy in the SecurityContextSelector
  component

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-08-18 02:55 UTC, bexsoft requested changes

2022-08-18 02:55 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/securityContextSelector.tsx
> +            <br />
Please use marginBottom for this

2022-08-18 02:55 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/types.ts
> +  fsGroupChangePolicy: string;
Please don't change this as it only accept those two values

2022-08-18 02:55 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/types.ts
> +  fsGroupChangePolicy: string;
```suggestion
  fsGroupChangePolicy: "Always" | "OnRootMismatch";
```

2022-08-29 17:30 UTC, harshavardhana approved these changes

2022-08-29 20:35 UTC, bexsoft approved these changes
LGTM

2022-08-29 20:35 UTC, merged