[WIP] Add support for Multiple IDPs on Login screen
minio/console pull request #2258
Opened 2022-08-23 04:12 UTC by kaankabalak

Fixes miniohq/engineering#955

2022-08-29 04:21 UTC, harshavardhana commented
Is there a screenshot or an animation to look at how this will work? @kaankabalak

2022-08-29 10:11 UTC, kaankabalak commented
> Is there a screenshot or an animation to look at how this will work? @kaankabalak

Based on the identity providers added, the login screen will look as follows:

<img width="433" alt="Screen Shot 2022-08-29 at 12 39 26 PM" src="https://user-images.githubusercontent.com/27314853/187178316-2e6b181a-b7de-4ddc-8f82-d3a8f1f3160a.png">

2022-08-29 10:42 UTC, kaankabalak commented
Here are the instructions to test this PR:

* Install Podman here: https://podman.io/getting-started/installation
* Create and start your Podman machine:
```
podman machine init
podman machine start
```
* Run `make podman-run` from https://github.com/minio/minio-iam-testing to start testing IDP services.
* Copy the models, portal-ui and restate directories from the `console` repository to `vendor/github.com/minio/console` located in the `minio` repository (I used this as a workaround because I only could get the SSO configuration to be seen from the Console embedded to the MinIO Server — would appreciate if anyone can point me in the right direction)
* Build the MinIO server binary and start your MinIO Server. Make sure that the server is started with alias `myminio` and Console on port 10000.
* Then, add identity providers as follows using `mc`:
```
mc admin idp set myminio openid dex1 config_url="http://localhost:5556/dex/.well-known/openid-configuration"     client_id="minio-client-app"     client_secret="minio-client-app-secret"     scopes="openid,groups"     redirect_uri="http://127.0.0.1:10000/oauth_callback"     display_name="Login via dex1"     role_policy="consoleAdmin"
```
```
mc admin idp set myminio openid dex2 config_url="http://localhost:5557/dex/.well-known/openid-configuration"     client_id="minio-client-app-2"     client_secret="minio-client-app-secret-2"     scopes="openid,groups"     redirect_uri="http://127.0.0.1:10000/oauth_callback"     display_name="Login via dex2"     role_policy="readwrite"
```
* Restart your server using `mc admin service restart myminio`
* Now, verify that you see multiple SSO login options when the Console is accessed on port 10000
* Additionally, make sure that the login screen is displayed properly for the cases where we don’t have any IDPs or if we have a single IDP

2022-08-29 12:07 UTC, harshavardhana commented
> > Is there a screenshot or an animation to look at how this will work? @kaankabalak
> 
> Based on the identity providers added, the login screen will look as follows:
> 
> <img alt="Screen Shot 2022-08-29 at 12 39 26 PM" width="433" src="https://user-images.githubusercontent.com/27314853/187178316-2e6b181a-b7de-4ddc-8f82-d3a8f1f3160a.png">

Shouldn't this be a drop down selector? What if we have a  dozen IDPs to login from ?

This design seems to be not catering for such eventualities.

2022-08-29 15:20 UTC, oscarocastellanos commented
> > > Is there a screenshot or an animation to look at how this will work? @kaankabalak
> > 
> > 
> > Based on the identity providers added, the login screen will look as follows:
> > <img alt="Screen Shot 2022-08-29 at 12 39 26 PM" width="433" src="https://user-images.githubusercontent.com/27314853/187178316-2e6b181a-b7de-4ddc-8f82-d3a8f1f3160a.png">
> 
> Shouldn't this be a drop down selector? What if we have a dozen IDPs to login from ?
> 
> This design seems to be not catering for such eventualities.

@kaankabalak On one of the early explorations when we adapted the SSO login I had something like this. Maybe this could work:
![Captura de Pantalla 2022-08-29 a la(s) 10 20 36](https://user-images.githubusercontent.com/89046849/187235904-cf036a4d-09ab-4217-9abb-c8a985b2851a.png)

Let me know what you think!

2022-08-29 17:02 UTC, kaankabalak commented
> @kaankabalak On one of the early explorations when we adapted the SSO login I had something like this. Maybe this could work: ![Captura de Pantalla 2022-08-29 a la(s) 10 20 36](https://user-images.githubusercontent.com/89046849/187235904-cf036a4d-09ab-4217-9abb-c8a985b2851a.png)
> 
> Let me know what you think!

@harshavardhana If this looks good, I can start working on this 👍

2022-08-29 22:49 UTC, harshavardhana commented
> @harshavardhana If this looks good, I can start working on it +1

Yes it does look good to me 👍🏽

2022-08-30 22:09 UTC, kaankabalak commented
@harshavardhana @oscarocastellanos, I have updated the design and the login screen for multiple IDPs now look as follows. Please let me know if any further changes are required. Thanks in advance!

<img width="467" alt="Screen Shot 2022-08-31 at 1 06 04 AM" src="https://user-images.githubusercontent.com/27314853/187552516-89980796-9734-4c73-a6f2-64a95e57be91.png">

2022-08-31 14:10 UTC, oscarocastellanos commented
> @harshavardhana @oscarocastellanos, I have updated the design and the login screen for multiple IDPs now look as follows. Please let me know if any further changes are required. Thanks in advance!
> 
> <img alt="Screen Shot 2022-08-31 at 1 06 04 AM" width="467" src="https://user-images.githubusercontent.com/27314853/187552516-89980796-9734-4c73-a6f2-64a95e57be91.png">

Looks good Kaan 👍

2022-08-31 16:21 UTC, kaankabalak commented
I have implemented the design feedback, I would appreciate it if you could take a look whenever you're available. Thanks in advance 👍 

@Alevsk @cniackz @bexsoft @jinapurapu @dvaldivia @reivaj05 @bexsoft

2022-08-31 22:10 UTC, bexsoft commented
Review in progress

2022-09-01 04:30 UTC, bexsoft commented
LGTM, just need to test the full redirect flow

2022-09-01 20:13 UTC, bexsoft requested changes
Cannot complete login flow using IDP with provided test steps / Auth0. After redirection I get the following error:

<img width="1862" alt="Screen Shot 2022-09-01 at 12 22 50" src="https://user-images.githubusercontent.com/33497058/188003248-0b1185ad-79da-4482-b40a-7539fbd21690.png">

Trying with Auth0 / new steps provided in idp-test repo, I get an error similar to this:

<img width="1555" alt="Screen Shot 2022-09-01 at 14 52 29" src="https://user-images.githubusercontent.com/33497058/188003666-c7947f8e-c6a4-4fcc-b15f-ffebb05543f4.png">

2022-09-01 21:12 UTC, oscarocastellanos commented
Agree with @dvaldivia. In case of the single IDP, the text in the drop down (now button) could be the IDP name and not the action.

2022-09-02 00:13 UTC, bexsoft commented
> Cannot complete login flow using IDP with provided test steps / Auth0. After redirection I get the following error:
> 
> <img alt="Screen Shot 2022-09-01 at 12 22 50" width="1862" src="https://user-images.githubusercontent.com/33497058/188003248-0b1185ad-79da-4482-b40a-7539fbd21690.png">
> 
> Trying with Auth0 / new steps provided in idp-test repo, I get an error similar to this:
> 
> <img alt="Screen Shot 2022-09-01 at 14 52 29" width="1555" src="https://user-images.githubusercontent.com/33497058/188003666-c7947f8e-c6a4-4fcc-b15f-ffebb05543f4.png">

Issue was related to my local environment. I can now login using this component.

2022-09-02 00:13 UTC, bexsoft approved these changes
LGTM

2022-09-02 07:56 UTC, kaankabalak commented
> I think when there's a single IDP, we don't need the dropdown, just a button would suffice, it would also solve the redundancy of double `login with sso`

@dvaldivia @oscarocastellanos Done 👍

2022-09-02 17:50 UTC, bexsoft approved these changes
LGTM

2022-09-02 18:07 UTC, dvaldivia approved these changes

2022-09-03 16:02 UTC, merged

2023-09-26 06:47 UTC, bpedersen2 commented on restapi/user_login.go
> +			if err != nil {
Should probaly not return, but skip to next provider in list.

2023-12-23 19:49 UTC, harshavardhana commented on restapi/user_login.go
> +			if err != nil {
In-fact this code is terribly written the openIDProviders is a slice that implements NewOauth2ProviderClient however we are looping over it as well. 

I have no idea why it is written this way.

2023-12-23 20:52 UTC, harshavardhana commented on restapi/user_login.go
> +			if err != nil {
https://github.com/minio/console/pull/3168 tries to clean this up and fix the problem as well.