read license from envt variable
minio/console pull request #2259
Opened 2022-08-23 04:43 UTC by sinhaashish

Earlier the license were read from config , and only admin had the privilige to read those the config , so any normal user with read write permission were seeing AGPL license even when they had the license .

With this PR the license is being read from envt variable which is set in MinIO and initialization.

There is one more change in reading the `subnetBaseURL` . If the envt variable `CONSOLE_SUBNET_URL` is set then 
it takes the local public key for parsing the license ( basically to test against local subnet) . If its not set then the prod url is taken to get the public key.

2022-08-23 14:32 UTC, bexsoft requested changes
Please run `make prettify` in `portal_ui` folder

2022-08-24 23:09 UTC, kannappanr submitted a review, later dismissed

2022-08-25 00:32 UTC, bexsoft requested changes

2022-08-25 00:32 UTC, bexsoft commented on restapi/admin_subnet.go
> +	licenseInfo, err := subnet.ParseLicense(client, os.Getenv("CONSOLE_SUBNET_LICENSE"))
We are now returning an error when license is not present. Not sure if we want to return this error as it will be throwing unwanted error messages in register pages:
<img width="2433" alt="Screen Shot 2022-08-24 at 19 29 31" src="https://user-images.githubusercontent.com/33497058/186547669-07f9b285-9912-4090-8242-a97e7234d987.png">

2022-08-25 09:13 UTC, sinhaashish commented on restapi/admin_subnet.go
> +	licenseInfo, err := subnet.ParseLicense(client, os.Getenv("CONSOLE_SUBNET_LICENSE"))
Thanks @bexsoft  .

2022-08-25 14:03 UTC, prakashsvmx approved these changes
LGTM :+1:

2022-08-26 18:17 UTC, bexsoft approved these changes
LGTM

2022-08-26 23:09 UTC, merged