Adds a logout view which enables minio to logout when using OIDC
minio/console pull request #2281
Opened 2022-08-29 15:00 UTC by benmarte

- Added logout view
- Added Logout Route
- Refactored logout button in ConsoleMenuList component
- Refactored Menu component

When setting up minio in an OIDC client you can now add the logout route `http://localhost:9001/logout` as a Front Channel Logout in order for it to terminate the session.

2022-09-06 16:24 UTC, dvaldivia requested changes
A couple of comments

2022-09-06 16:24 UTC, dvaldivia commented on portal-ui/src/screens/LogoutPage/LogoutPage.tsx
> +LogoutPage.propTypes = {};
I think this is not needed, since we don't do it on other components, to keep it consistent it can be removed

2022-09-06 16:24 UTC, dvaldivia commented on portal-ui/src/screens/LogoutPage/LogoutPage.tsx
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-09-06 16:28 UTC, benmarte commented on portal-ui/src/screens/LogoutPage/LogoutPage.tsx
> +LogoutPage.propTypes = {};
Updated PR and removed propTypes

2022-09-06 16:29 UTC, benmarte commented on portal-ui/src/screens/LogoutPage/LogoutPage.tsx
> +// Copyright (c) 2021 MinIO, Inc.
Updated PR with correct date

2022-09-15 16:33 UTC, dvaldivia approved these changes

2022-09-16 18:26 UTC, bexsoft approved these changes

2022-09-16 21:21 UTC, merged

2022-09-16 21:22 UTC, dvaldivia commented
Thanks for your contribution!

2024-03-25 09:10 UTC, balaKarur commented
@dvaldivia  @cguermi @benmarte  @djwfyi @wangyanzhao
Hello all, despite the comments above indicating that the issue has been resolved, but it still persists in the latest version.
**Issue** : On Logout minio ,its called api **http://localhost:9001/api/v1/logout** and got 200 response , but its not logout from keycloak.
@benmarte
Where  to add the **logout route** http://localhost:9001/logout as a Front Channel Logout in order for it to terminate the session in keycloak.
Latest minio version : quay.io/minio/minio:**RELEASE.2024-03-21T23-13-43Z**
Latest keycloak : quay.io/keycloak/**keycloak:24.0.2**

Please look into this issue. Your assistance will be greatly appreciated. 
Thank you all

2024-03-26 14:16 UTC, balaKarur commented
> we'll take a look @balaKarur. cc @adriangitvitz
@cesnietor Thanks for your support .
@adriangitvitz ,Please let me know ,if any info needed from my end , i will share .
Your assistance will be greatly appreciated.
Thank you all

2024-04-08 07:36 UTC, balaKarur commented
Hello @cesnietor,@adriangitvitz 
could you get time to check the above reported issue .

2024-04-08 07:41 UTC, prakashsvmx commented
@balaKarur , please do not comment on merged PRs. 
Please consider a subscription via min.io/pricing for SLA backed support/ issue troubleshooting.

Also feel free to contribute with Fixes/Changes via a new PR

2024-04-08 08:20 UTC, balaKarur commented
@prakashsvmx 
Currently, we are exploring MinIO for our project. Once we confirm that MinIO solves our use case, we will proceed with a subscription. Once I am comfortable with MinIO, I am happy to contribute.

This PR relates to Keycloak logout from MinIO. I am facing the same issue, so I reported my issue here. Now I am clear,  from the PR that we should not raise our issue. Thank you for informing me.