Alternative to test SSO in UI
minio/console pull request #2287
Opened 2022-08-31 15:37 UTC by cniackz

### Objective:

Allow environmental variables set SSO for testing as this support was removed in previous PR: https://github.com/minio/console/pull/2167

### How to test:

1. Prepare MinIO for SSO

```sh
export MINIO_ROOT_USER=minio
export MINIO_ROOT_PASSWORD=minio123
export MINIO_IDENTITY_OPENID_CONFIG_URL=<url>
export MINIO_IDENTITY_OPENID_CLIENT_ID=<client-id>
export MINIO_IDENTITY_OPENID_CLIENT_SECRET=<secret>
export MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
export MINIO_IDENTITY_OPENID_CLAIM_NAME="https://min.io/policy"
export MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
export MINIO_SERVER_URL=http://localhost:9000
minio server ~/Data --console-address ":9001"
```

2. Set your Console Variables, compile and execute:

```sh
cd ~/console
export CONSOLE_IDP_URL=<url>
export CONSOLE_IDP_CLIENT_ID=<client-id>
export CONSOLE_IDP_SECRET=<secret>
export CONSOLE_IDP_CALLBACK=<url>
make install-sso
~/go/bin/console server
```

3. Prepare UI for testing:

```sh
cd ~/console/portal-ui
yarn install
yarn build
yarn run start
```

4. You can test SSO Login in UI port 5005:

<img width="1362" alt="Screenshot 2023-01-05 at 6 30 16 PM" src="https://user-images.githubusercontent.com/6667358/210905600-1e257401-7573-4d7d-a54f-757a4aade3a0.png">

### Related PRs:

* https://github.com/minio/console/pull/2167
* https://github.com/minio/console/pull/2201

### Important Part:

To modify a variable in Go Binary during build

```
-ldflags="-s -w -X 'main.ssoTesting=readFromVars'"
```

### Other unrelated failures:

Operator API test is failing but unrelated to this PR:

* https://github.com/minio/console/pull/2289

2023-01-05 23:25 UTC, dvaldivia submitted a review, later dismissed

2023-01-06 19:03 UTC, allanrogerr approved these changes
Reviewed and works as expected

2023-01-09 22:36 UTC, dvaldivia approved these changes

2023-01-09 22:56 UTC, reivaj05 requested changes

2023-01-09 22:56 UTC, reivaj05 commented on cmd/console/server.go
> +	if ssoTesting == "readFromVars" {
We shouldn't add testing logic in production logic, it's not a good practice, testing should live in a different place separated from production code

Maybe we can discuss a different approach

2023-03-06 20:28 UTC, closed without merging