Add dummy endpoints for kms integration
minio/console pull request #2301
Opened 2022-09-07 23:36 UTC by reivaj05

Add dummy endpoints for kms integration

Implementation will come in another PR

2022-09-08 00:46 UTC, Alevsk submitted a review, later dismissed

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +  /kms/key/create:
Why don't have just a `/kms/key` endpoint? to perform `create`, `delete` and `get` operations via `POST`, `GET` and `DELETE` ?

To list all the keys we can have `GET /kms/keys`
To import a key we can have `POST /kms/import/key`

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +  /kms/key/status:
```suggestion
  /kms/key/{id}:
```
Passing the key id should return information about the key including the status

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +          type: string
```suggestion
        - name: id
          description: KMS key id
          in: path
          required: true
          type: string
```

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +  /kms/key/import:
```suggestion
  /kms/import/key:
```
we can reverse this if we want to support the `/kms/key/{id}` endpoint

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +  /kms/key/list:
```suggestion
  /kms/keys:
```
we can rename this if we want to support the `/kms/key/{id}` endpoint

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +  /kms/key/delete:
```suggestion
  /kms/key/{id}:
```

We can merge this endpoint with the one above and use the `DELETE` method

2022-09-08 00:46 UTC, Alevsk commented on swagger-console.yml
> +          type: string
```suggestion
        - name: id
          description: KMS key id
          in: path
          required: true
          type: string
```

2022-09-08 01:04 UTC, reivaj05 commented on swagger-console.yml
> +  /kms/key/create:
Not sure, i just followed the same convention   as endpoints are in kes, that way all repos have the same endpoints. Is It ok they aré diferente? 🧐

2022-09-09 18:50 UTC, jinapurapu requested changes

2022-09-09 18:50 UTC, jinapurapu commented on restapi/admin_kms.go
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-09-09 20:31 UTC, bexsoft approved these changes

2022-09-16 17:27 UTC, jinapurapu submitted a review, later dismissed

2022-09-19 20:17 UTC, bexsoft approved these changes
LGTM

2022-09-20 23:09 UTC, dvaldivia approved these changes

2022-09-20 23:09 UTC, merged