Add Minio tier type
minio/console pull request #2302
Opened 2022-09-08 22:49 UTC by jinapurapu

<img width="746" alt="Screen Shot 2022-09-08 at 3 06 03 PM" src="https://user-images.githubusercontent.com/65002498/189235338-f9d4d91c-cb11-4471-97b9-67ad9a0b89f4.png">

NOTE: This PR requires madmin-go PR ## 

closes https://github.com/miniohq/engineering/issues/843

2022-09-08 22:54 UTC, reivaj05 requested changes

2022-09-08 22:54 UTC, reivaj05 commented on go.mod
> +
You should only replace for testing, production should use github repos

2022-09-08 22:54 UTC, reivaj05 commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/AddTierConfiguration.tsx
> +      //}
Should this be comment?

2022-09-15 16:45 UTC, dvaldivia approved these changes

2022-09-15 17:25 UTC, reivaj05 approved these changes

2022-09-15 19:00 UTC, merged