Toggle Bucket Naming Rules display by clicking text
minio/console pull request #2311
Opened 2022-09-13 20:24 UTC by jinapurapu

Adds show/hide rules toggle to text adjacent to button.
<img width="564" alt="Screen Shot 2022-09-13 at 1 19 43 PM" src="https://user-images.githubusercontent.com/65002498/190001323-91a79e9b-2104-4b2a-b021-42817b49e597.png">

2022-09-14 03:54 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
> +          <span
Please extract to a  function  
```
const toggleNamingRules = () => {
              setShowNamingRules(!showNamingRules);
            }
 ```

and 

```
          <span
            onClick={toggleNamingRules}
            style={{ color: "#0288D1", textDecoration: "underline" }}
          >
          
 ```

2022-09-14 20:38 UTC, reivaj05 submitted a review, later dismissed

2022-09-15 03:40 UTC, bexsoft requested changes

2022-09-15 03:40 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
> +            style={{ color: "#0288D1", textDecoration: "underline" }}
Please add pointer cursor & check font size

```suggestion
            style={{ color: "#0288D1", textDecoration: "underline", cursor: "pointer", fontSize: "14px" }}
```

2022-09-15 03:40 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
> +            toggleNamingRules();
Please change this button to use mds buttons. Perhaps label could be inserted in it to avoid the big spacing between label & caret.

mds button can be styled using style prop so you can make it narrow

2022-09-15 12:27 UTC, kaankabalak commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
>              Hide Bucket Naming Rules{" "}
@jinapurapu Not directly related to this PR, however I think we can get rid of the spaces here:

```suggestion
            Hide Bucket Naming Rules
```

2022-09-15 12:35 UTC, kaankabalak commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
> +            style={{ color: "#0288D1", textDecoration: "underline" }}
@bexsoft @jinapurapu, as an additional note, it seems like the font sizes for the rules are also large. It might be better to reduce them to 14px too:

<img width="430" alt="Screen Shot 2022-09-15 at 3 34 04 PM" src="https://user-images.githubusercontent.com/27314853/190404849-063525ba-3982-4b9d-a25d-0174b660b12a.png">

2022-09-15 19:54 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/BucketNamingRules.tsx
> +        }}
Add type button
```suggestion
        }}
        type="button"
```

2022-09-15 19:55 UTC, bexsoft approved these changes
LGTM

2022-09-15 20:04 UTC, bexsoft approved these changes
LGTM

2022-09-16 00:37 UTC, dilverse approved these changes

2022-09-16 18:12 UTC, merged