Skip TLS verif for local address
minio/console pull request #2323
Opened 2022-09-20 13:46 UTC by vadmeste

If Console is talking locally to MinIO, skip the TLS verification if any.

This will allow users to avoid defining the correct MINIO_SERVER_URL domain
address, when TLS is enabled, useful in a bare-metal setup.

2022-09-20 17:31 UTC, harshavardhana requested changes

2022-09-20 17:31 UTC, harshavardhana commented on restapi/client-admin.go
> +
Please simply to always use 127.0.0.1 instead

2022-09-20 17:36 UTC, Alevsk requested changes

2022-09-20 17:36 UTC, Alevsk commented on restapi/client-admin.go
> +	client = PrepareConsoleHTTPClient(isLocalAddress)
Based on the internal conversation we cannot trust on any dns/nslookup resolution and instead implement this logic only if the provided address is the 127.0.0.1  string, we may thing about the corner case of the ipv6 local address as well

2022-09-21 08:32 UTC, vadmeste commented on restapi/client-admin.go
> +	client = PrepareConsoleHTTPClient(isLocalAddress)
> Based on the internal conversation we cannot trust on any dns/nslookup resolution and instead implement this logic only if the provided address is the 127.0.0.1 string, we may thing about the corner case of the ipv6 local address as well

Yes, we cannot trust DNS resolution but I think we can trust ip.IsLoopback(), I like loopback because it also supports ipv6 localhost (and I hate parsing ipv6)

2022-09-21 08:33 UTC, vadmeste commented on restapi/client-admin.go
> +
> Please simply to always use 127.0.0.1 instead

127.0.0.1 won't always work I guess, this looks a better way to support both ipv4 and ipv6 localhost

2022-09-21 10:07 UTC, harshavardhana commented on restapi/client-admin.go
> +
127.0.0.1 will always work @vadmeste it will work even with IPv6 is enabled.

2022-09-23 15:53 UTC, harshavardhana commented on restapi/client.go
> +	if u, err := url.ParseRequestURI(endpoint); err == nil && u.Host != "" {
This is still url.Parse()

2022-09-23 15:54 UTC, harshavardhana commented on restapi/client.go
> +	if u, err := url.ParseRequestURI(endpoint); err == nil && u.Host != "" {
This should be converted into a function where it says `isLocalURL(endpoint)` and used everywhere.

2022-09-23 17:17 UTC, harshavardhana approved these changes

2022-09-30 20:55 UTC, harshavardhana commented
PTAL at the failed tests @vadmeste

2022-10-03 08:54 UTC, harshavardhana requested changes

2022-10-03 08:54 UTC, harshavardhana commented on restapi/client-admin.go
> +	if u, err := url.Parse(address); err == nil && u.Host != "" {
use `u.Hostname()`  so that you can remove the port and then 

```
ip := net.ParseIP(u.Hostname())
return ip.IsLoopback()
```

2022-10-03 10:45 UTC, vadmeste commented on restapi/client-admin.go
> +	if u, err := url.Parse(address); err == nil && u.Host != "" {
yes, I like loopback better as well, done

2022-10-03 15:50 UTC, harshavardhana requested changes

2022-10-03 15:50 UTC, harshavardhana commented on restapi/client-admin.go
> +	return ip.IsLoopback()
Check for ip to be non-nil other wise this function can crash.

2022-10-09 19:15 UTC, harshavardhana commented on restapi/client-admin.go
> +	return ip.IsLoopback()
@vadmeste ^^

2022-10-10 09:33 UTC, vadmeste commented on restapi/client-admin.go
> +	return ip.IsLoopback()
> Check for ip to be non-nil other wise this function can crash.

Fixed, good catch

2022-10-15 04:30 UTC, harshavardhana approved these changes

2022-10-17 19:13 UTC, Alevsk approved these changes
Tested, works fine, this verification will only apply if the provided IP is `127.0.0.1`

2022-10-17 19:33 UTC, harshavardhana commented
> Tested, works fine, this verification will only apply if the provided IP is `127.0.0.1`

Yes this must be done via server setting as well. MinIO must set this to local IP always for embedded console. 

// cc @vadmeste can you make this server change as well?

2022-10-17 19:34 UTC, merged