Updating documentation links to new URLs
minio/console pull request #2325
Opened 2022-09-20 22:45 UTC by djwfyi

The new doc site has launched, and all docs have new URLs.
This PR updates the documentation URLs in the Console to point to the new locations.

2022-09-20 23:50 UTC, bexsoft requested changes
Please run `make prettify` in portal-ui folder

2022-09-21 14:51 UTC, ravindk89 submitted a review, later dismissed
These look good, but I do have some questions for engineering on whether we can go a little farther.

2022-09-21 15:32 UTC, djwfyi commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +    : "https://min.io/docs/minio/kubernetes/upstream/administration/minio-console.html?ref=con";
Updating line 489 to point to Linux.

2022-09-21 16:29 UTC, bexsoft commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +    : "https://min.io/docs/minio/kubernetes/upstream/administration/minio-console.html?ref=con";
Yes @ravindk89, we have the isOperator flag available to render the correct menu & logos for the application. this can be used to render the correct links for documentation in case a component is shared between  Console & Operator Console

2022-09-22 02:56 UTC, bexsoft commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +                href="https://min.io/docs/minio/kubernetes/upstream/index.html?ref=con"
I think this should lead to  linux page instead of k8s one
```suggestion
                href="https://min.io/docs/minio/linux/index.html"
```

2022-09-22 19:16 UTC, djwfyi commented on portal-ui/src/screens/LoginPage/LoginPage.tsx
> +    : "https://min.io/docs/minio/kubernetes/upstream/administration/minio-console.html?ref=con";
@bexsoft We should use this going forward, then. Operator points to kubernetes/upstream and Console points to linux.

2022-09-22 23:07 UTC, bexsoft approved these changes
LGTM

2022-09-23 05:37 UTC, harshavardhana approved these changes

2022-09-23 05:37 UTC, merged