Add support for edit/add/remove environment variables to MinIO tenant
minio/console pull request #2331
Opened 2022-09-21 17:47 UTC by Alevsk

![image](https://user-images.githubusercontent.com/1795553/191574784-69d55ca6-0a8c-41f3-b7f5-8526854cc8d2.png)

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2022-09-21 17:55 UTC, Alevsk commented
@harshavardhana @aead @dvaldivia guys I need to get your opinion on:

- Should we allow people to edit secrets/passwords/auth token environment variables from this UI or those more sensitive values should be have to be manually edited via `kubectl`
- Right now we are returning all the content of the tenant configuration file to the user, including sensitive data such as `MINIO_ROOT_PASSWORD`, etc, technically any user that logs to operator with a valid `k8s token` have access to this data already, would it be worth it to return `REDACTED` values instead or something like that just to prevent this credentials in plain text to reach the client? again the user already have access to all of this via the k8s token

2022-09-21 18:50 UTC, jinapurapu requested changes

2022-09-21 18:50 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantConfiguration.tsx
> +// Copyright (c) 2021 MinIO, Inc.
```suggestion
// Copyright (c) 2022 MinIO, Inc.
```

2022-09-23 16:40 UTC, reivaj05 commented on operatorapi/tenants.go
> +func getTenantConfigurationResponse(session *models.Principal, params operator_api.TenantConfigurationParams) (*models.TenantConfigurationResponse, *models.Error) {
It needs tests for the new code

2022-09-27 01:32 UTC, Alevsk commented on operatorapi/tenants.go
> +func getTenantConfigurationResponse(session *models.Principal, params operator_api.TenantConfigurationParams) (*models.TenantConfigurationResponse, *models.Error) {
added tests

2022-09-27 15:57 UTC, reivaj05 approved these changes

2022-09-27 18:02 UTC, jinapurapu requested changes
After confirming save and restart, Save button is disabled but you can add/delete fields using the +/- buttons, this may be confusing to users.
![Screen Shot 2022-09-27 at 10 59 53 AM](https://user-images.githubusercontent.com/65002498/192602307-698a8f56-3af2-4e18-8c28-5cd7ef821aa9.png)
![Screen Shot 2022-09-27 at 11 00 52 AM](https://user-images.githubusercontent.com/65002498/192602303-cf7a9426-a40c-4ad3-bc4f-f32d6cb30b6c.png)

2022-09-28 03:50 UTC, Alevsk commented
> After confirming save and restart, Save button is disabled but you can add/delete fields using the +/- buttons, this may be confusing to users. ![Screen Shot 2022-09-27 at 10 59 53 AM](https://user-images.githubusercontent.com/65002498/192602307-698a8f56-3af2-4e18-8c28-5cd7ef821aa9.png) ![Screen Shot 2022-09-27 at 11 00 52 AM](https://user-images.githubusercontent.com/65002498/192602303-cf7a9426-a40c-4ad3-bc4f-f32d6cb30b6c.png)

fixed, thanks!!

2022-09-28 17:55 UTC, jinapurapu requested changes
It is possible to save an empty KV pair, or an individual key or value. 

![Screen Shot 2022-09-28 at 10 44 37 AM](https://user-images.githubusercontent.com/65002498/192854050-e4c2bd35-8e64-4e2c-86a0-e04653187044.png)

2022-09-28 18:09 UTC, Alevsk commented
> It is possible to save an empty KV pair, or an individual key or value.
> 
> ![Screen Shot 2022-09-28 at 10 44 37 AM](https://user-images.githubusercontent.com/65002498/192854050-e4c2bd35-8e64-4e2c-86a0-e04653187044.png)

You should be able to save keys with empty values (in case you want to reset something to the default value), on the other hand you should not be able to save empty keys and values, will check if this is happening because i have some logic around to prevent that

2022-09-28 22:58 UTC, jinapurapu requested changes
Operator API test is failing here locally as well
```
--- FAIL: Test_TenantInfoTenantAdminClient (0.00s)
--- FAIL: Test_TenantInfoTenantAdminClient/Return_Tenant_Admin,_no_errors (0.00s)

```

2022-09-29 19:44 UTC, reivaj05 submitted a review, later dismissed

2022-09-30 00:07 UTC, jinapurapu approved these changes

2022-09-30 03:28 UTC, bexsoft approved these changes

2022-09-30 03:50 UTC, merged