Size handling for CounterCard long value
minio/console pull request #2345
Opened 2022-09-29 19:30 UTC by jinapurapu

Avoids overlap of counterValue text and Browse button.
<img width="591" alt="Screen Shot 2022-09-29 at 12 21 44 PM" src="https://user-images.githubusercontent.com/65002498/193123577-d0fbb8b1-7fab-4bae-abba-f1e372fd8d92.png">

2022-09-29 19:40 UTC, reivaj05 submitted a review, later dismissed

2022-09-30 11:41 UTC, kaankabalak commented
We might want to bring the Browse button down a couple of pixels (using relative positioning or adjusting the margin values), so that the number field (marked in red) doesn't overlap with the Browse button (marked in blue):

<img width="890" alt="Screen Shot 2022-09-30 at 2 38 25 PM" src="https://user-images.githubusercontent.com/27314853/193262007-acedf853-7b10-48e1-b3ea-54b939641903.png">

The overlap is more apparent once the viewport width is decreased:

<img width="684" alt="Screen Shot 2022-09-30 at 2 36 02 PM" src="https://user-images.githubusercontent.com/27314853/193262070-bc36ccf9-b382-4f46-aa29-009d58b992f5.png">

2022-09-30 21:35 UTC, dvaldivia commented on portal-ui/src/common/SecureComponent/permissions.ts
> +  /* Access */
I removed this in my other PR since policies is no longer under access

2022-09-30 22:17 UTC, kaankabalak commented on portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx
> +                counterValue={usage ? 999999 : 0} // representationNumber(usage.buckets)
Hi @jinapurapu, I think this was left from testing out large numbers, we can revert this back to its previous version

2022-09-30 22:18 UTC, kaankabalak commented on portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx
> +                counterValue={usage ? 999999 : 0} // representationNumber(usage.buckets)
Hi @jinapurapu, I think this was left from testing out large numbers, we can revert this back to how it was previously

2022-09-30 22:18 UTC, kaankabalak requested changes
Please see comment

2022-09-30 22:21 UTC, kaankabalak commented on portal-ui/src/screens/Console/Dashboard/BasicDashboard/BasicDashboard.tsx
> +                counterValue={usage ? representationNumber(usage.buckets) : 0}
I think this will not pass the Prettier check until we remove the trailing space, we might want to run `make prettify`

2022-10-01 16:54 UTC, kaankabalak approved these changes

2022-10-04 11:58 UTC, prakashsvmx approved these changes
LGTM :+1:

2022-10-04 17:01 UTC, bexsoft approved these changes
LGTM

2022-10-04 22:09 UTC, Alevsk approved these changes

2022-10-04 22:10 UTC, Alevsk approved these changes

2022-10-04 22:10 UTC, merged