Release v0.20.5
minio/console pull request #2349
Opened 2022-09-29 22:56 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-09-29 22:57 UTC, reivaj05 approved these changes

2022-09-29 22:59 UTC, bexsoft approved these changes

2022-09-30 03:56 UTC, bexsoft requested changes
Let's wait until https://github.com/minio/console/pull/2338 gets merged, please regenerate assets

2022-09-30 07:18 UTC, harshavardhana commented
> Let's wait until #2338 gets merged, please regenerate assets

@bexsoft PTAL

2022-09-30 08:45 UTC, prakashsvmx approved these changes

2022-09-30 08:51 UTC, harshavardhana approved these changes

2022-09-30 08:51 UTC, merged