Changed Object browser logic to work with websockets
minio/console pull request #2361
Opened 2022-10-06 00:25 UTC by bexsoft

## What does this do?

This allows us to start streaming results to the objects list instead of waiting to retrieve all the objects before sending them to the client.

## How des it look?
![2022-10-05 19-19-39 2022-10-05 19_21_05](https://user-images.githubusercontent.com/33497058/194186970-30ff9d82-2e82-4258-a0a1-20fafd86f1b7.gif)

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-10-07 18:12 UTC, cniackz submitted a review, later dismissed
LGTM

2022-10-07 18:19 UTC, jinapurapu commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +          //c.close(1000);
Should this be commented out?

2022-10-07 18:40 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +          //c.close(1000);
Good catch, this needs to be removed

2022-10-07 18:40 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +          //c.close(1000);
Good catch.

This block is not necessary, I have removed it

2022-10-07 18:47 UTC, cniackz approved these changes
LGTM

2022-10-07 20:36 UTC, jinapurapu submitted a review, later dismissed

2022-10-07 20:53 UTC, dvaldivia requested changes
There's a few problems:

After uploading a file, it shows up twice

<img width="1008" alt="Screen Shot 2022-10-07 at 1 50 29 PM" src="https://user-images.githubusercontent.com/18384552/194650613-5e3c4e74-2dd5-4a21-9f84-c308a0befbc2.png">

If the object is shown duplicate, even refreshing the list will show it twice.
![2022-10-07 13-50-53 2022-10-07 13_51_08](https://user-images.githubusercontent.com/18384552/194650662-a42bb3f1-1175-4412-9948-3d47f443c7a1.gif)

Attempting to delete selected objects does nothing
![2022-10-07 13-51-13 2022-10-07 13_51_48](https://user-images.githubusercontent.com/18384552/194650708-18ac6705-21e5-434e-9966-f9d38b3cf179.gif)

2022-10-07 22:21 UTC, bexsoft commented
> There's a few problems:
> 
> After uploading a file, it shows up twice
> 
> <img alt="Screen Shot 2022-10-07 at 1 50 29 PM" width="1008" src="https://user-images.githubusercontent.com/18384552/194650613-5e3c4e74-2dd5-4a21-9f84-c308a0befbc2.png">
> 
> If the object is shown duplicate, even refreshing the list will show it twice. ![2022-10-07 13-50-53 2022-10-07 13_51_08](https://user-images.githubusercontent.com/18384552/194650662-a42bb3f1-1175-4412-9948-3d47f443c7a1.gif) [ ![2022-10-07 13-50-53 2022-10-07 13_51_08](https://user-images.githubusercontent.com/18384552/194650662-a42bb3f1-1175-4412-9948-3d47f443c7a1.gif) ](https://user-images.githubusercontent.com/18384552/194650662-a42bb3f1-1175-4412-9948-3d47f443c7a1.gif) [ ](https://user-images.githubusercontent.com/18384552/194650662-a42bb3f1-1175-4412-9948-3d47f443c7a1.gif)
> 
> Attempting to delete selected objects does nothing ![2022-10-07 13-51-13 2022-10-07 13_51_48](https://user-images.githubusercontent.com/18384552/194650708-18ac6705-21e5-434e-9966-f9d38b3cf179.gif) [ ![2022-10-07 13-51-13 2022-10-07 13_51_48](https://user-images.githubusercontent.com/18384552/194650708-18ac6705-21e5-434e-9966-f9d38b3cf179.gif) ](https://user-images.githubusercontent.com/18384552/194650708-18ac6705-21e5-434e-9966-f9d38b3cf179.gif) [ ](https://user-images.githubusercontent.com/18384552/194650708-18ac6705-21e5-434e-9966-f9d38b3cf179.gif)

Cannot reproduce, Can you please provide some steps for this issue? Thank you!

https://user-images.githubusercontent.com/33497058/194670496-5c6e4dad-bb8c-4dd1-a1db-8ba1fcf7a38c.mp4

2022-10-08 00:22 UTC, Alevsk requested changes
[Screencast from 10-07-2022 05:20:49 PM.webm](https://user-images.githubusercontent.com/1795553/194678064-3f58bb28-3133-41d8-9fd3-dd31ce1d7c12.webm)

Testing this PR im not able to list objects inside a bucket, im using minio root credentials, if i use master branch then everything works fine

2022-10-08 01:06 UTC, bexsoft commented
> [Screencast from 10-07-2022 05:20:49 PM.webm](https://user-images.githubusercontent.com/1795553/194678064-3f58bb28-3133-41d8-9fd3-dd31ce1d7c12.webm)
> 
> 
> 
> Testing this PR im not able to list objects inside a bucket, im using minio root credentials, if i use master branch then everything works fine

Please use 9090 or enable websockets support on 5005

2022-10-10 19:04 UTC, Alevsk approved these changes
Tested, works fine

2022-10-17 08:27 UTC, prakashsvmx approved these changes
Tested. Changes look good to me :+1:

2022-10-21 18:57 UTC, closed without merging