Adding bucket events test
minio/console pull request #2365
Opened 2022-10-06 03:56 UTC by adfost

Test case for adding bucket events

2022-10-06 22:59 UTC, bexsoft requested changes

2022-10-06 22:59 UTC, bexsoft commented on integration/buckets_events_test.go
> +		fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
Please remove this line

2022-10-06 22:59 UTC, bexsoft commented on integration/buckets_events_test.go
> +			log.Printf(string(body))
Do we need to only print the body value?

2022-10-06 23:04 UTC, bexsoft commented
Please squash commits

2022-10-07 20:57 UTC, dvaldivia commented on integration/buckets_events_test.go
> +	go http.ListenAndServe(":8081", nil)
server should be stopped at the end of the test, else we are going to have a goroutine leak

2022-10-10 18:51 UTC, bexsoft commented on integration/buckets_events_test.go
> +			log.Printf(string(body))
On this line you are not using `body` anywhere else, Not sure if this block is really needed

2022-10-18 21:08 UTC, reivaj05 commented on integration/buckets_events_test.go
> +			requestDataEvents["conf"].(map[string]interface{})["configuration"].(map[string]interface{})["suffix"] = tt.args.conf.configuration.suffix
It would be better to define a new struct for this config and then marshal it.This way is really difficult to read

2022-10-18 21:12 UTC, reivaj05 commented on integration/buckets_events_test.go
> +				return
`err != nil` should make the test fail? this way the test will pass

2022-10-18 21:12 UTC, reivaj05 commented on integration/buckets_events_test.go
> +			}
same as in line 114

2023-01-28 06:28 UTC, closed without merging