Add inspection v2 (always encrypted) option.
minio/console pull request #2386
Opened 2022-10-14 12:58 UTC by klauspost

Keep v1 if non-encrypted.

2022-10-26 14:01 UTC, klauspost commented
Still pending [mc 4185](https://github.com/minio/mc/pull/4185), but short of `go.mod` updates it is ready for review.

2022-10-29 18:34 UTC, harshavardhana commented
@klauspost PTAL at the tests

```
=== RUN   TestInspect
=== RUN   TestInspect/Test_Invalid_Path
=== RUN   TestInspect/Test_Invalid_characters_in_Path
=== RUN   TestInspect/Test_valid_bucket
=== CONT  TestInspect
    inspect_test.go:99: 
        	Error Trace:	/home/runner/work/console/console/integration/inspect_test.go:99
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestInspect
=== RUN   TestInspect/Test_Empty_Path
--- FAIL: TestInspect (0.03s)
    --- PASS: TestInspect/Test_Invalid_Path (0.01s)
    --- PASS: TestInspect/Test_Invalid_characters_in_Path (0.01s)
    --- PASS: TestInspect/Test_valid_bucket (0.01s)
    --- PASS: TestInspect/Test_Empty_Path (0.01s)
=== RUN   TestLoginStrategy
```

2022-10-29 18:56 UTC, klauspost commented
@harshavardhana It is a cyclic dependency. Minio depends on this and this depends on minio

2022-10-29 21:00 UTC, harshavardhana commented
> @harshavardhana It is a cyclic dependency. Minio depends on this and this depends on minio

Then can we skip it? @klauspost as a non-failure?

2022-10-31 21:53 UTC, harshavardhana submitted a review, later dismissed

2022-11-01 03:38 UTC, bexsoft requested changes

2022-11-01 03:38 UTC, bexsoft commented on go.mod
> +replace github.com/minio/mc => github.com/klauspost/mc v0.0.0-20221014120903-10af4c8890f4
Please remove this replace

2022-11-01 03:38 UTC, bexsoft commented on restapi/admin_inspect.go
> +		cfg.PublicKey, _ = base64.StdEncoding.DecodeString("MIIBCgKCAQEAs/128UFS9A8YSJY1XqYKt06dLVQQCGDee69T+0Tip/1jGAB4z0/3QMpH0MiS8Wjs4BRWV51qvkfAHzwwdU7y6jxU05ctb/H/WzRj3FYdhhHKdzear9TLJftlTs+xwj2XaADjb
Do we need this Public Key here?

2022-11-01 10:29 UTC, klauspost commented on restapi/admin_inspect.go
> +		cfg.PublicKey, _ = base64.StdEncoding.DecodeString("MIIBCgKCAQEAs/128UFS9A8YSJY1XqYKt06dLVQQCGDee69T+0Tip/1jGAB4z0/3QMpH0MiS8Wjs4BRWV51qvkfAHzwwdU7y6jxU05ctb/H/WzRj3FYdhhHKdzear9TLJftlTs+xwj2XaADjb
Yes, we must always encrypt.

2022-11-01 10:31 UTC, klauspost commented on restapi/admin_inspect.go
> +		cfg.PublicKey, _ = base64.StdEncoding.DecodeString("MIIBCgKCAQEAs/128UFS9A8YSJY1XqYKt06dLVQQCGDee69T+0Tip/1jGAB4z0/3QMpH0MiS8Wjs4BRWV51qvkfAHzwwdU7y6jxU05ctb/H/WzRj3FYdhhHKdzear9TLJftlTs+xwj2XaADjb
As noted, the UI could be made to ask for a public key.

The un-encrypted option should be removed from the UI, but that is beyond my capabilities.

2022-11-02 16:12 UTC, harshavardhana approved these changes

2022-11-02 16:35 UTC, bexsoft approved these changes
Cannot generate inspect files with encryption set as true:
<img width="1726" alt="Screenshot 2022-11-02 at 10 31 57" src="https://user-images.githubusercontent.com/33497058/199547352-138b9fb8-23ba-469c-9237-2ccab0420dcf.png">

This seems related to the missing dependency from minio, will approve this to unblock the rest of required PRs

2022-11-02 16:56 UTC, klauspost commented
@bexsoft Yes, the encryption option requires the minio PR to be running to work (and the PR above requires this console version).

2022-11-02 17:35 UTC, merged