[WIP] - Fixing Permission test 4
minio/console pull request #2393
Opened 2022-10-18 18:02 UTC by cniackz

### Objective:

To fix failing tests.

2022-10-18 19:25 UTC, Alevsk approved these changes
Are we adding the vulncheck job in a different PR ?

2022-10-18 19:26 UTC, pjuarezd submitted a review, later dismissed

2022-10-18 19:27 UTC, harshavardhana commented
Workflow is not running 

> The workflow is not valid. .github/workflows/jobs.yaml (Line: 26, Col: 9): Job 'replication' depends on unknown job 'vulnerable-dependencies-checks'. .github/workflows/jobs.yaml (Line: 94, Col: 9): Job 'sso-integration' depends on unknown job 'vulnerable-dependencies-checks'.

@cniackz

2022-10-18 20:08 UTC, cniackz commented
no, i am adding it vulncheck here @Alevsk & this time the workflow should work, thx @harshavardhana

2022-10-18 20:10 UTC, reivaj05 approved these changes

2022-10-18 20:11 UTC, Alevsk approved these changes

2022-10-18 20:12 UTC, dvaldivia approved these changes

2022-10-18 22:11 UTC, harshavardhana requested changes

2022-10-18 22:11 UTC, harshavardhana commented on .github/workflows/jobs.yaml
> +        go-version: [ 1.19 ]
```suggestion
        go-version: [ 1.19.x ]
```

2022-10-18 22:15 UTC, pjuarezd commented on .github/workflows/jobs.yaml
> +        go-version: [ 1.19 ]
Last time I’ve tried that made no effect, the GitHub action was still using the latest cached version of go. 

The `check-latest: true` did the trick of get the latest revision.

anyways, having it doesn’t hurt

2022-10-19 07:07 UTC, harshavardhana approved these changes

2022-10-19 07:07 UTC, merged