Add tier status checking to non-Minio type tiers
minio/console pull request #2420
Opened 2022-10-31 20:19 UTC by jinapurapu

2022-10-31 20:30 UTC, reivaj05 approved these changes

2022-11-01 03:24 UTC, bexsoft requested changes

2022-11-01 03:24 UTC, bexsoft commented on restapi/admin_tiers.go
> +				Status: checkTierStatus(tierData.GCS.Endpoint, "minioadmin", "minioadmin", tierData.GCS.Bucket),
Are this credentials correct?

2022-11-01 19:47 UTC, jinapurapu commented on restapi/admin_tiers.go
> +				Status: checkTierStatus(tierData.GCS.Endpoint, "minioadmin", "minioadmin", tierData.GCS.Bucket),
No, none of these are actually getting the real credentials, as they are redacted by the server. Right now this is just checking that a MinIO server exists at the endpoint, so I could use fixed dummy credentials for all of them. 

I am working on something that will actually check the credentials and bucket using checkWarmBackend on the MinIO server, so I do not have to expose the tier credentials - or is it ok to pass them to the Console server because it is local to the MinIO server?

2022-12-01 04:46 UTC, bexsoft submitted a review, later dismissed

2022-12-02 05:31 UTC, prakashsvmx commented
@jinapurapu Could you please resolve conflicts ?

2022-12-05 17:27 UTC, krisis approved these changes
LGTM

2022-12-06 19:34 UTC, bexsoft approved these changes

2022-12-06 19:34 UTC, dvaldivia approved these changes

2022-12-06 20:13 UTC, merged