Add internationalization support to MinIO
minio/console pull request #2443
Opened 2022-11-09 06:35 UTC by lvyueyang

Automatically added internationalization to MinIO using a script, this time about 90% of the time, the rest needs to be added manually. The part of template string splicing is not processed, because the context between different languages is different, it needs to be processed manually according to the rules of i18next.

>使用脚本自动的为 MinIO 添加了国际化处理，这次大概处理了 90%，剩下需要进行手动添加。并没有对模板字符串拼接的部分进行处理，因为不同语言之间的语境不同，需要根据 i18next 的规则进行手动处理。

2022-11-09 09:58 UTC, harshavardhana requested changes
why do we need to commit the en.json files?

2022-11-09 10:14 UTC, lvyueyang commented
Because other languages need to be translated according to this document.

If you don't submit it, it needs to be generated by the translator himself, emm... 🤔 This seems to be not bad.

2022-11-09 10:33 UTC, lvyueyang commented
@harshavardhana 
I can resubmit a PR, delete en.json, and ignore it, and let the translator generate this file and translate it.

2022-11-09 11:07 UTC, harshavardhana commented
> I can resubmit a PR, delete en.json, and ignore it, and let the translator generate this file and translate it.

That would be preferred @lvyueyang

2022-11-09 12:13 UTC, lvyueyang commented
> > I can resubmit a PR, delete en.json, and ignore it, and let the translator generate this file and translate it.
> 
> That would be preferred @lvyueyang

It's now fixed and bugs in checke have been fixed.

2022-11-10 08:26 UTC, harshavardhana requested changes

2022-11-10 08:26 UTC, harshavardhana commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/VersionsNavigator.tsx
> +
why are these space characters added, this is clobbering up the entire PR here can these be removed? - I see this in all files. 

The PR should limit itself to a simpler change instead of making additional changes are not part or of concern with the PR's gist.

2022-11-11 04:43 UTC, lvyueyang commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/VersionsNavigator.tsx
> +
I have solved the problem of this extra line break through scripting. Because I need to roll back the previously submitted commit content, I used a forced commit this time.

2022-11-11 04:47 UTC, harshavardhana commented
Now the PR is more clean thanks @lvyueyang

2022-11-11 04:49 UTC, lvyueyang commented
> Now the PR is more clean thanks @lvyueyang

You're welcome, I also benefited a lot from this question. @harshavardhana

2022-11-15 02:12 UTC, lvyueyang commented
@harshavardhana 
Do you need to make any adjustments? Is it possible to merge?

2022-11-15 03:16 UTC, harshavardhana commented
> @harshavardhana Do you need to make any adjustments? Is it possible to merge?

We are discussing internally the implications of this change and how we must maintain going forward.

2022-11-15 03:22 UTC, lvyueyang commented
> > @harshavardhana Do you need to make any adjustments? Is it possible to merge?
> 
> We are discussing internally the implications of this change and how we must maintain going forward.

Okay, this change does involve a lot of places, and it should be reviewed more strictly and carefully.
For subsequent use, I can provide another i18n check script to help developers check whether there is any copy that has not been added to i18n when submitting.

2022-12-05 03:42 UTC, harshavardhana reviewed
We will merge this PR soon, we have decided to include this change.

2022-12-05 05:15 UTC, lvyueyang commented
Well, this is really happy news.

2023-01-06 09:08 UTC, lvyueyang commented
Are you still pushing forward with the merge of this PR?

2023-05-08 09:15 UTC, cyril-cheng commented
这是放弃了吗？

2023-05-08 16:37 UTC, cesnietor commented
Hello, our team has decided not to move forward with this since we won't be able to keep with all the languages since we can't guarantee the quality of the translations yet.

2023-05-08 16:37 UTC, closed without merging

2023-05-09 04:08 UTC, ty114514 commented
Are you considering introducing translation platforms such as Crowdin, where the community provides localized translations?

2023-07-07 10:23 UTC, 6ang996 commented
> Hello, our team has decided not to move forward with this since we won't be able to keep with all the languages since we can't guarantee the quality of the translations yet.

I think the core of the problem is not the translation quality, people want the i18n framework, not just the Chinese translation.
The developer develops in English, and the translator follows up. I haven't seen any open source project stop i18n attempts because of the slow translation problem

Thanks

2024-04-30 09:22 UTC, dudiao commented
So how is internationalization progressing now?

2024-08-25 14:56 UTC, CNsurly commented
Refer to the website https://play.minio.org.cn/login

2024-08-25 14:57 UTC, CNsurly commented
Refer to the website https://play.minio.org.cn/login
username：minioadmin
password：minioadmin