Added formatting to required permssions in permissionTooltipHelper
minio/console pull request #2447
Opened 2022-11-09 23:29 UTC by jinapurapu

Adds spacing and comma between required permissions listed in tooltips

<img width="962" alt="Screen Shot 2022-11-09 at 3 26 03 PM" src="https://user-images.githubusercontent.com/65002498/200963899-b4b69fd5-8254-40bc-9f15-2e17aa383c29.png">

2022-11-10 08:01 UTC, dilverse approved these changes

2022-11-10 09:52 UTC, prakashsvmx requested changes

2022-11-10 09:52 UTC, prakashsvmx commented on portal-ui/src/common/SecureComponent/permissions.ts
> +  var niceScopes = "";
```suggestion
`let niceScopes = scopes.join(", ").toString() `
```
please use the `join` method in array 
which can be used to avoid `var` and the `forEach`

2022-11-11 10:19 UTC, prakashsvmx approved these changes
Thank you @jinapurapu . LGTM. :+1:

2022-11-13 18:49 UTC, dilverse approved these changes

2022-11-14 07:42 UTC, kaankabalak approved these changes

2022-11-14 15:47 UTC, bexsoft approved these changes
LGTM

2022-11-14 15:48 UTC, merged