WIP - Tenant health monitoring
minio/console pull request #2466
Opened 2022-11-17 23:34 UTC by jinapurapu

Not yet working - unable to connect to tenant

<img width="1134" alt="Screen Shot 2022-11-17 at 3 05 18 PM" src="https://user-images.githubusercontent.com/65002498/202579583-1341c1e5-34ce-4a78-8625-6690620a8e0c.png">

2022-12-08 01:02 UTC, reivaj05 requested changes

2022-12-08 01:02 UTC, reivaj05 commented on .github/workflows/jobs.yaml
> +          threshold=53.30
Please add more tests to cover the new code that was added, we should be increasing coverage not reducing the threshold

2022-12-08 01:14 UTC, jinapurapu commented on .github/workflows/jobs.yaml
> +          threshold=53.30
I added a test for the /health endpoint I made, which brought the coverage up from 53.0%, thought it was a rounding issue. What is included is the coverage check, is it just the API tests or others too?

2022-12-08 18:24 UTC, reivaj05 commented on operatorapi/tenants.go
> +
subnet package already has functionality to make http requests, can that functionality be used here instead of adding new methods?

2022-12-08 18:24 UTC, reivaj05 commented on operatorapi/tenants.go
> +		token, thisThing, e := restapi.SubnetLogin(subnetHTTPClient, "jill@min.io", "testPassword1!")
Why these credentials are hardcoded?

2022-12-08 18:26 UTC, reivaj05 commented on .github/workflows/jobs.yaml
> +          threshold=53.30
You can view [here](https://play.min.io:9443/buckets/builds/browse/bWluaW8vY29uc29sZS8yNDY2LzM2NDQxNzM3Mzkv) the coverage of your build, most of the handlers you added and the code in tenants.go file is not tested

2022-12-08 18:30 UTC, reivaj05 commented on operatorapi/tenants.go
> +func getTenantHealthReport(session *models.Principal, params operator_api.TenantHealthReportParams) (*models.HealthReport, *models.Error) {
It might be better to split this long function into smaller pieces

2022-12-08 19:42 UTC, jinapurapu commented on .github/workflows/jobs.yaml
> +          threshold=53.30
Thank you, I will clear out the redundant Subnet functions and add testing for the remaining new ones.

2022-12-12 20:41 UTC, dvaldivia requested changes

2022-12-12 20:41 UTC, dvaldivia commented on portal-ui/build/index.html
> +
No need to send this file

2023-01-26 22:44 UTC, closed without merging