Fixing ip bug
minio/console pull request #2469
Opened 2022-11-18 07:05 UTC by adfost

Fixes https://github.com/minio/console/issues/2453.

2022-11-18 08:31 UTC, harshavardhana requested changes

2022-11-18 08:31 UTC, harshavardhana commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/AddBucket.tsx
> +    `^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)(\\.(?!$)|$)){4}$`
The correct regex for bucket name validation is this

```
^[a-z0-9][a-z0-9\.\-]{1,61}[a-z0-9]$
```

And correct regex for IP validation is 

```
^(\d+\.){3}\d+$
```

2022-11-18 08:31 UTC, harshavardhana commented on portal-ui/src/screens/Console/Buckets/ListBuckets/AddBucket/AddBucket.tsx
> +    `^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)(\\.(?!$)|$)){4}$`
Look at the implementation for strict interpretation https://github.com/minio/minio-go/blob/master/pkg/s3utils/utils.go#L367

2022-11-18 08:32 UTC, harshavardhana commented
I know that this PR was not scoped to be a larger change however we have an opportunity here to fix things, lets get it fixed comprehensively.

2022-11-18 22:46 UTC, harshavardhana approved these changes

2022-11-21 20:12 UTC, dvaldivia approved these changes

2022-11-21 21:30 UTC, merged