Added tooltip on hover to Notification type selector buttons
minio/console pull request #2502
Opened 2022-12-12 21:18 UTC by jinapurapu

https://user-images.githubusercontent.com/65002498/207156382-21f2923b-712c-4c6d-b9a6-2b2f0195bdc0.mov

Closes https://github.com/miniohq/engineering/issues/715

2022-12-12 21:47 UTC, kaankabalak approved these changes

2022-12-12 22:43 UTC, dvaldivia commented
I think we also need a hover of color so the user can feel the mouse is over the whole box

2022-12-12 23:25 UTC, reivaj05 submitted a review, later dismissed

2022-12-14 04:26 UTC, bexsoft requested changes

2022-12-14 04:26 UTC, bexsoft commented on portal-ui/src/screens/Console/NotificationEndpoints/NotificationTypeSelector.tsx
> +                    }}
This can be avoided and use only `::hover` selector from css inside `lambdaNotif` class

```
"&::hover": {
                      backgroundColor: "#ebebeb",
                    }
```

2022-12-14 18:23 UTC, bexsoft approved these changes
LGTM

It would be nice to apply this same change to the `Add Tier` page elements in an upcoming PR

<img width="1394" alt="Screenshot 2022-12-14 at 12 21 53" src="https://user-images.githubusercontent.com/33497058/207676870-4effe154-625d-40ed-8b9f-0f74fa9866d2.png">

2022-12-14 18:25 UTC, kaankabalak approved these changes

2022-12-14 20:38 UTC, merged