Add hover effect to Tier Type buttons
minio/console pull request #2509
Opened 2022-12-14 22:29 UTC by jinapurapu

https://user-images.githubusercontent.com/65002498/207727237-610146be-4af9-4398-aa32-641c03a29ab9.mov

2022-12-14 23:16 UTC, bexsoft requested changes

2022-12-14 23:16 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/TierTypeCard.tsx
> +import { Button } from "@mui/material";
We are not using material-ui buttons anymore

2022-12-14 23:16 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/TierTypeCard.tsx
> +        "&:hover": {
In this case what you can do is to create a new class element with all the values contained in style and then assign it to each button

2022-12-15 05:27 UTC, prakashsvmx approved these changes
Tested. LGTM :+1:

2022-12-15 17:03 UTC, oscarocastellanos approved these changes
LGTM

2022-12-15 19:25 UTC, bexsoft requested changes
I'm seeing this issue on wide screens:

<img width="1686" alt="Screenshot 2022-12-15 at 11 41 14" src="https://user-images.githubusercontent.com/33497058/207949112-31434e8d-f3b8-49d7-897d-f6e9600101e4.png">

2022-12-16 19:10 UTC, bexsoft approved these changes
Issue can be fixed in an upcoming PR

2022-12-16 19:41 UTC, merged