Tweaks to Menu and Bucket Details
minio/console pull request #2512
Opened 2022-12-15 18:39 UTC by dvaldivia

<img width="447" alt="Screenshot 2022-12-15 at 10 39 04 AM" src="https://user-images.githubusercontent.com/18384552/207941143-033d2cdb-b5ad-448c-acc6-36fa3abb4a5a.png">
<img width="344" alt="Screenshot 2022-12-15 at 10 38 59 AM" src="https://user-images.githubusercontent.com/18384552/207941151-1dcd55a9-d147-445d-950e-56739335c6e5.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2022-12-15 18:44 UTC, dilverse submitted a review, later dismissed

2022-12-15 18:54 UTC, reivaj05 submitted a review, later dismissed

2022-12-15 19:25 UTC, bexsoft approved these changes

2022-12-15 19:26 UTC, bexsoft requested changes
Please review tests

2022-12-16 00:40 UTC, reivaj05 approved these changes

2022-12-16 00:43 UTC, bexsoft approved these changes

2022-12-16 00:45 UTC, merged