UI changes to IDP screen and remove old sections from settings screen
minio/console pull request #2513
Opened 2022-12-15 19:03 UTC by reivaj05

2022-12-15 19:18 UTC, dvaldivia approved these changes

2022-12-16 17:43 UTC, jinapurapu requested changes

2022-12-16 17:43 UTC, jinapurapu commented on portal-ui/src/screens/Console/IDP/IDPConfigurationDetails.tsx
> +                {/* <FormSwitchWrapper
Should this be removed?

2022-12-16 17:59 UTC, jinapurapu submitted a review, later dismissed

2022-12-16 19:44 UTC, dvaldivia approved these changes

2022-12-16 19:45 UTC, jinapurapu approved these changes

2022-12-16 19:46 UTC, merged