Ignoring message from MinIO
minio/console pull request #2515
Opened 2022-12-15 23:03 UTC by cniackz

2022-12-16 02:28 UTC, cniackz commented on restapi/admin_remote_buckets.go
> +		_ = deleteBucketReplicationRulesResponse(session, params)
That is correct, 404 is still valid, I will correct that, thank you Javier 👍

2022-12-16 15:42 UTC, cniackz commented
Thank you @dvaldivia I have correted the error that Javier pointed out. My next step in this PR is to use latest version of Swagger to reduce the number of changed files.

2022-12-16 15:53 UTC, cniackz commented
Ok, I am done with the changes, new Swagger version reduced the files changed and improved the way we handle the errors as per Javier feedback... Once all tests are passing, I will ping you guys in the channel for another round of review.

2022-12-16 16:55 UTC, reivaj05 commented on restapi/admin_remote_buckets.go
> +			if err.Code == 500 && *err.DetailedMessage == "The remote target does not exist" {
Is minio returning a 500 when the target does not longer exists?

2022-12-16 17:18 UTC, dvaldivia requested changes

2022-12-16 17:18 UTC, dvaldivia commented on go.mod
> +	github.com/cilium/ebpf v0.9.3 // indirect
I think all the go.mod changes are unnecessary, let's remove them from this PR

2022-12-16 19:21 UTC, bexsoft approved these changes

2022-12-16 19:45 UTC, dvaldivia approved these changes

2022-12-16 20:16 UTC, merged

2022-12-17 00:35 UTC, reivaj05 commented on restapi/admin_remote_buckets.go
> +			if err.Code == 500 && *err.DetailedMessage == "The remote target does not exist" {
@cniackz This is already merged but we shouldn't return a 204 if the remote target doesn't exist

2022-12-21 17:10 UTC, cniackz commented on restapi/admin_remote_buckets.go
> +			if err.Code == 500 && *err.DetailedMessage == "The remote target does not exist" {
Hello @reivaj05 the remote target does exist and the rules are getting deleted but MinIO is doing more that just this is our trace log; so after showing this trace to Harsha and Poorna they told me to ignore this one as the rules are being deleted anyway; what I was thinking is something more complex, to change the logic or the way we actually delete these rules, to have an API that only does this deletion and no 500 is returned, but that will require more work and a deeper understanding on how we interact with MinIO and how we can get MinIO to just delete the rules. Maybe in a new PR we can improve this.