First Phase of Luxon migration
minio/console pull request #2521
Opened 2022-12-19 22:38 UTC by bexsoft

## What does this do?

- Started the migration of moment js to Luxon
- Fixed Time Zone & Modified Times in Object Browser

## How does it look?

<img width="1559" alt="Screenshot 2022-12-19 at 15 57 14" src="https://user-images.githubusercontent.com/33497058/208540273-dbeb9c78-f9a9-4a13-9169-316ac9ed2c1c.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2022-12-20 00:01 UTC, reivaj05 submitted a review, later dismissed

2022-12-21 08:46 UTC, prakashsvmx requested changes

2022-12-21 08:46 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjectsHelpers.tsx
> +    currTime.day === objectTime.day &&
Could this be simplified with builtin method for comparision
```
const isToday =  currTime.hasSame(objectTime, "day") && currTime.hasSame(objectTime, "month") && currTime.hasSame(objectTime, "year");
```

2022-12-21 17:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjectsHelpers.tsx
> +    currTime.day === objectTime.day &&
Applied suggestion! Thank you @prakashsvmx =D

2022-12-21 17:18 UTC, dvaldivia approved these changes

2022-12-21 17:19 UTC, pjuarezd approved these changes

2022-12-21 17:24 UTC, prakashsvmx approved these changes

2022-12-21 17:56 UTC, merged