License FAQ
minio/console pull request #2581
Opened 2023-01-20 18:33 UTC by dvaldivia

<img width="1392" alt="Screenshot 2023-01-20 at 10 30 21 AM" src="https://user-images.githubusercontent.com/18384552/213778537-e1afc94a-97e5-41c7-8d57-c062c3f4e0cd.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2023-01-20 18:45 UTC, pjuarezd submitted a review, later dismissed

2023-01-20 18:46 UTC, jinapurapu requested changes

2023-01-20 18:46 UTC, jinapurapu commented on portal-ui/src/screens/Console/License/FAQModal.tsx
> +// Copyright (c) 2022 MinIO, Inc.
```suggestion
// Copyright (c) 2023 MinIO, Inc.
```

2023-01-20 18:46 UTC, jinapurapu commented on portal-ui/src/screens/Console/License/licenseSlice.ts
> +// Copyright (c) 2022 MinIO, Inc.
```suggestion
// Copyright (c) 2023 MinIO, Inc.
```

2023-01-20 18:54 UTC, reivaj05 submitted a review, later dismissed

2023-01-20 19:21 UTC, allanrogerr commented on portal-ui/src/screens/Console/License/licenseSlice.ts
> +// Copyright (c) 2022 MinIO, Inc.
Great catch - can this be automated?

2023-01-20 19:21 UTC, allanrogerr approved these changes

2023-01-20 19:27 UTC, dvaldivia commented on portal-ui/src/screens/Console/License/licenseSlice.ts
> +// Copyright (c) 2022 MinIO, Inc.
We would need to write an action to check the year for new files.

Fixed @jinapurapu

2023-01-20 19:29 UTC, reivaj05 approved these changes

2023-01-20 19:29 UTC, jinapurapu approved these changes

2023-01-20 20:43 UTC, kaankabalak commented on portal-ui/src/screens/Console/License/licenseSlice.ts
> +  name: "addPool",
@dvaldivia Wouldn't we need to change the name of the slice here?

2023-01-20 20:43 UTC, kaankabalak commented on portal-ui/src/screens/Console/License/utils.tsx
> +                console.log("ohla");
Could we also remove the `console.log` here?

2023-01-20 20:51 UTC, kaankabalak commented on portal-ui/src/screens/Console/License/LicenseFAQ.tsx
> +        https://www.gnu.org/licenses/agpl-3.0.en.html.
Would it make sense to turn this into a hyperlink as follows?

```diff
diff --git a/portal-ui/src/screens/Console/License/LicenseFAQ.tsx b/portal-ui/src/screens/Console/License/LicenseFAQ.tsx
index 3322d9f4..df9f9e65 100644
--- a/portal-ui/src/screens/Console/License/LicenseFAQ.tsx
+++ b/portal-ui/src/screens/Console/License/LicenseFAQ.tsx
@@ -24,8 +24,19 @@ const LicenseFAQ = () => {
         The GNU AGPL v3 is short for the "GNU Affero General Public License v3."
         It is a common open source license certified by the Free Software
         Foundation and the Open Source Initiative. You can get a copy of the GNU
-        AGPL v3 license with MinIO source code or at
-        https://www.gnu.org/licenses/agpl-3.0.en.html.
+        AGPL v3 license with MinIO source code or at{" "}
+        <a
+          href="https://www.gnu.org/licenses/agpl-3.0.en.html"
+          className={"link-text"}
+          target="_blank"
+          rel="noopener noreferrer"
+          style={{
+            color: "#2781B0",
+          }}
+        >
+          https://www.gnu.org/licenses/agpl-3.0.en.html
+        </a>
+        .
       </p>
       <h2>What does it mean for me to comply with the GNU AGPL v3?</h2>
       <p>

```

2023-01-20 22:25 UTC, dvaldivia commented on portal-ui/src/screens/Console/License/LicenseFAQ.tsx
> +        https://www.gnu.org/licenses/agpl-3.0.en.html.
it does!

2023-01-20 22:25 UTC, dvaldivia commented on portal-ui/src/screens/Console/License/utils.tsx
> +                console.log("ohla");
solved

2023-01-20 22:25 UTC, dvaldivia commented on portal-ui/src/screens/Console/License/licenseSlice.ts
> +  name: "addPool",
solved

2023-01-20 22:33 UTC, kaankabalak commented
Hi @dvaldivia, just a quick comment, seems like we need a space here between the word `at` and the link:

<img width="710" alt="Screen Shot 2023-01-20 at 2 32 14 PM" src="https://user-images.githubusercontent.com/27314853/213817156-0d5ccde6-b850-4da8-bb82-ce75a9199860.png">

2023-01-20 22:36 UTC, kaankabalak submitted a review, later dismissed

2023-01-20 23:04 UTC, allanrogerr reviewed
I would suggest these small grammar changes. @kaankabalak @dvaldivia

2023-01-20 23:04 UTC, allanrogerr commented on portal-ui/src/screens/Console/License/LicenseFAQ.tsx
> +        The method of combining does not matter. When MinIO is linked to a
The method of combining does not matter. When MinIO is linked to a
        larger software stack in any form, including statically, dynamically,
        pipes, containerized or invoked remotely, the AGPL v3 applies to
        your use. What triggers the AGPL v3 obligations is the exchanging of data
        between the larger stack and MinIO.

2023-01-20 23:12 UTC, allanrogerr commented on portal-ui/src/screens/Console/License/LicenseFAQ.tsx
> +        your use. What triggers the AGPL v3 obligations is the exchanging data
```suggestion
        pipes, containerized or invoked remotely, the AGPL v3 applies to
        your use. What triggers the AGPL v3 obligations is the exchanging of data
```

2023-01-23 09:10 UTC, prakashsvmx approved these changes
LGTM :+1: 
the website has been updated to redirect to GNU AGPL v3 as well.

2023-01-23 17:09 UTC, bexsoft requested changes

2023-01-23 18:08 UTC, bexsoft approved these changes

2023-01-23 18:19 UTC, pjuarezd approved these changes

2023-01-23 18:33 UTC, merged