Tenant health info upload
minio/console pull request #2606
Opened 2023-01-26 22:44 UTC by jinapurapu

### What it does:
For registered clusters, after generating the Health Info report, Health Info is uploaded to Subnet, and latest metrics are visible in Subnet. If airgap mode is enabled, the report is not uploaded to Subnet. 

### What it looks like:

<img width="936" alt="Screen Shot 2023-01-26 at 2 03 38 PM" src="https://user-images.githubusercontent.com/65002498/214961621-c39c1b59-2032-46d2-a30d-a02d1c63b163.png">
<img width="936" alt="Screen Shot 2023-01-26 at 2 04 02 PM" src="https://user-images.githubusercontent.com/65002498/214961625-384b04bb-96d1-4fb5-9ca5-802294dd9c76.png">
<img width="936" alt="Screen Shot 2023-01-26 at 2 06 06 PM" src="https://user-images.githubusercontent.com/65002498/214961630-b76d1d41-03cb-4920-8ce6-5f0ee0d7dd2e.png">

2023-01-26 23:36 UTC, kaankabalak commented on restapi/admin_health_info.go
> +	filename := fmt.Sprintf("%s-health_%s.json", "testing", time.Now().Unix())
Would it make sense to remove `testing` from the filename here?

2023-01-27 00:54 UTC, reivaj05 commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> -  const registeredCluster = plan === "STANDARD" || plan === "ENTERPRISE";
Why is this removed? is it a bug and licenseInfo is not stored in the slice?

2023-01-27 01:11 UTC, jinapurapu commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> -  const registeredCluster = plan === "STANDARD" || plan === "ENTERPRISE";
It stopped working from the slice suddenly, so I put in the workaround. I will try to debug getting licenseInfo from the slice again.

2023-01-27 20:24 UTC, dvaldivia commented
Coverage is failing, you should add some tests for the new code @jinapurapu

2023-02-02 23:10 UTC, dvaldivia requested changes

2023-02-02 23:10 UTC, dvaldivia commented on restapi/admin_health_info.go
> +		sendHealthInfoToSubnet(ctx, healthInfo, client)
please handle this error

2023-02-02 23:12 UTC, dvaldivia requested changes

2023-02-02 23:12 UTC, dvaldivia commented on restapi/admin_health_info.go
> +	saveHealthInfo(healthInfo, filename)
please handle this error

2023-02-02 23:12 UTC, dvaldivia commented on restapi/admin_health_info.go
> +	subnet.UploadFileToSubnet(subnetHTTPClient, filename, subnetUploadURL, headers)
please handle this error

2023-02-02 23:12 UTC, dvaldivia commented on restapi/admin_health_info.go
> +	os.Remove(filename)
please handle this error

2023-02-02 23:20 UTC, dvaldivia requested changes
Please also show the generated URL page for the report

2023-02-22 10:26 UTC, prakashsvmx commented
@jinapurapu  could you please resolve the conflicts ?

2023-02-23 23:01 UTC, reivaj05 commented on restapi/admin_health_info.go
> +		report.SubnetResponse = "ERROR"
maybe fmt.Sprintf("Error: %s", err.Error()) ?

2023-03-14 00:41 UTC, allanrogerr commented
@jinapurapu Also, when I hit "Sign Out", I face this blank screen. I effectively can't sign out.
![image](https://user-images.githubusercontent.com/16472240/224863118-aa3fcd1c-bb07-4aae-a360-62b5cb5c5899.png)

2023-03-14 00:53 UTC, allanrogerr commented
> @jinapurapu Thanks for your offline help! After registering my cluster I am facing this request to register my cluster still. How do I get past this? Let me know if you have any idea. I can't test unfortunately.

Resolved after pulling latest changes

2023-03-14 00:54 UTC, allanrogerr commented
@jinapurapu New issue. As soon as I click "Start New Diagnostic", I face "An error occurred while getting the Diagnostic file."
![image](https://user-images.githubusercontent.com/16472240/224864680-bd0ef79f-4f47-4915-bacf-bb0cd2a96f41.png)

2023-03-16 19:51 UTC, allanrogerr approved these changes
Works as expected

2023-03-16 19:53 UTC, allanrogerr commented
> @jinapurapu Looks good. I ran diagnostics - observed the output - ran again and noticed that the value I changed did change. Except a bug unrelated to your change perhaps. I used to have 5 objects in my bucket. Then I deleted 2. However the UI is still reporting 5 objects (Access: PRIVATE102.6 MiB - 5 Objects)
> 
> See ![image](https://user-images.githubusercontent.com/16472240/225628161-e099b548-1e66-40c7-9168-73531cf96922.png)
> 
> vs
> 
> ![image](https://user-images.githubusercontent.com/16472240/225628181-4e768fde-6646-48b8-bacf-ef1764d5c0eb.png)

Unrelated but valid issue

2023-03-16 20:07 UTC, jinapurapu commented
> > Please also show the generated URL page for the report
> 
> @jinapurapu Was this addressed?

The link to the Subnet Health screen for the report is here - do we want to include the same display in Console Health as well?
<img width="1249" alt="Screen Shot 2023-03-16 at 12 55 16 PM" src="https://user-images.githubusercontent.com/65002498/225740280-218caea7-a54a-4942-894f-35cf868bdd0f.png">

2023-03-17 16:42 UTC, merged