Redesigned Logger Webhooks & Audit Webhooks pages
minio/console pull request #2620
Opened 2023-02-01 02:05 UTC by bexsoft

## What does this do?

- Added the capability to set custom names to logger & audit webhooks
- Added the capability to edit webhooks
- Added the capability to delete wehooks
- Display webhook status

*NOTE:* Add certificates is pending as we need to define how we can store this information

## How does it look?

<img width="1670" alt="Screenshot 2023-01-31 at 20 01 05" src="https://user-images.githubusercontent.com/33497058/215927248-00bcf121-ae77-421e-9c01-a32d55cca0a6.png">
<img width="1678" alt="Screenshot 2023-01-31 at 20 01 00" src="https://user-images.githubusercontent.com/33497058/215927261-6737208f-dc1e-4251-b0f4-ff4090ac34ff.png">
<img width="1420" alt="Screenshot 2023-01-31 at 19 59 28" src="https://user-images.githubusercontent.com/33497058/215927264-f7f4f6cf-9c59-47bb-87e0-3f60d0ddde8b.png">
<img width="1386" alt="Screenshot 2023-01-31 at 19 59 23" src="https://user-images.githubusercontent.com/33497058/215927269-73cd3886-ef8f-4571-ac6f-3c20e88cb7bf.png">
<img width="1098" alt="Screenshot 2023-01-31 at 19 59 17" src="https://user-images.githubusercontent.com/33497058/215927270-b701c0ef-f7cb-48ad-b8eb-466cdf5568df.png">
<img width="1082" alt="Screenshot 2023-01-31 at 19 59 08" src="https://user-images.githubusercontent.com/33497058/215927272-beeae370-64dc-4084-bdec-64b47505376b.png">
<img width="1673" alt="Screenshot 2023-01-31 at 19 58 59" src="https://user-images.githubusercontent.com/33497058/215927274-f16a92dc-4eb2-4f24-9adf-9c314cfde14c.png">

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2023-02-01 12:31 UTC, prakashsvmx commented
@bexsoft  some observations: 
1. Is Auth Token field mandatory ? . i think it should be optional.
2. While adding new webhook, the field widths are not equal
<details>

![image](https://user-images.githubusercontent.com/23444145/216043120-8c4551e1-6543-4a61-82dd-457cbbfb504f.png)

</details>
3. Unable to reset/disbale the default audit_webhook

<details>

https://user-images.githubusercontent.com/23444145/216042671-3d9d37fb-4ee5-4245-98b0-873e86e825be.mp4

</details>

2023-02-01 19:51 UTC, bexsoft commented
> 

Fixed:

<img width="1324" alt="Screenshot 2023-02-01 at 13 49 11" src="https://user-images.githubusercontent.com/33497058/216148046-0436fcf0-6c8c-4772-a23e-fde8c3f0bd11.png">
<img width="1423" alt="Screenshot 2023-02-01 at 13 48 56" src="https://user-images.githubusercontent.com/33497058/216148051-a9c4fca2-5a05-4f49-b660-25f0c759ec50.png">
<img width="1687" alt="Screenshot 2023-02-01 at 13 48 49" src="https://user-images.githubusercontent.com/33497058/216148056-5b3cecc4-de01-481f-8aad-146420f2de81.png">

2023-02-01 21:50 UTC, dvaldivia approved these changes
Tested. LGTM.

2023-02-02 04:28 UTC, prakashsvmx commented
@bexsoft  could you please resolve the conflicts ?

2023-02-02 05:00 UTC, dvaldivia submitted a review, later dismissed

2023-02-02 07:08 UTC, prakashsvmx requested changes
Tested Changes look good to me :+1:  

Suggestion : The Edit option could  have explicit button

2023-02-02 07:08 UTC, prakashsvmx commented on portal-ui/src/screens/Console/NotificationEndpoints/WebhookSettings/EditWebhookEndpoint.tsx
> +    if (endpoint.trim() === "") {
Click on Default Endpoint, 
toggle Enabled On 
Do not enter value of Endpoint
Click Save. this throws JS error.  ( validation error is not shown for mandatory field)

```
react-dom.development.js:4312 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
```

2023-02-02 18:43 UTC, bexsoft commented on portal-ui/src/screens/Console/NotificationEndpoints/WebhookSettings/EditWebhookEndpoint.tsx
> +    if (endpoint.trim() === "") {
Fixed this issue, For the edit option will send it in another PR as there is a small bug inDataTable from mds that needs to be fixed first

2023-02-02 18:53 UTC, reivaj05 approved these changes

2023-02-02 19:29 UTC, jinapurapu approved these changes

2023-02-02 22:02 UTC, allanrogerr approved these changes

2023-02-03 05:00 UTC, prakashsvmx approved these changes
Thank you.  LGTM :+1:

2023-02-03 05:01 UTC, dvaldivia approved these changes

2023-02-03 05:22 UTC, merged