Updated copyright tags to 2023
minio/console pull request #2631
Opened 2023-02-03 03:07 UTC by bexsoft

## What does this do?

Updated all Copyright tags to 2023

Signed-off-by: Benjamin Perez <benjamin@bexsoft.net>

2023-02-03 03:47 UTC, dilverse submitted a review, later dismissed

2023-02-03 04:41 UTC, dvaldivia requested changes
We should only do this for `NOTICE` and autogenerated files, but not for any file we have not changed since it was created

2023-02-03 17:56 UTC, reivaj05 approved these changes

2023-02-03 18:10 UTC, jinapurapu approved these changes

2023-02-03 21:11 UTC, allanrogerr approved these changes
These look like swagger auto generated files and a NOTICE

2023-02-07 04:32 UTC, dvaldivia approved these changes

2023-02-07 04:32 UTC, merged