Menu Tweaks and Rename Notifications to Events
minio/console pull request #2639
Opened 2023-02-06 19:00 UTC by dvaldivia

- Rename notifications to events.
- Add categories to event destinations
- Menu changes

<img width="1276" alt="Screenshot 2023-02-06 at 10 48 16 AM" src="https://user-images.githubusercontent.com/18384552/217060936-6faef983-e21e-4a8c-88bf-5d18bd146ae6.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2023-02-06 19:02 UTC, pjuarezd submitted a review, later dismissed

2023-02-06 19:03 UTC, dilverse submitted a review, later dismissed

2023-02-06 19:09 UTC, jinapurapu requested changes

2023-02-06 19:09 UTC, jinapurapu commented on portal-ui/src/screens/Console/NotificationEndpoints/ListNotificationEndpoints.tsx
> +                          Add a Event Destination
```suggestion
                          Add an Event Destination
```

2023-02-06 19:37 UTC, pjuarezd approved these changes

2023-02-06 20:51 UTC, kaankabalak commented on portal-ui/src/screens/Console/Console.tsx
> +  () => import("./EventDestinations/EventTypeSelector")
Would it make sense to rename these constants as well as the constants `IAM_PAGES.NOTIFICATIONS_ENDPOINTS_ADD_SERVICE`, `IAM_PAGES.NOTIFICATIONS_ENDPOINTS_ADD` and `IAM_PAGES.NOTIFICATIONS_ENDPOINTS`?

2023-02-06 22:56 UTC, dvaldivia commented on portal-ui/src/screens/Console/Console.tsx
> +  () => import("./EventDestinations/EventTypeSelector")
yes, we should also rename those

2023-02-06 22:59 UTC, dvaldivia commented on portal-ui/src/screens/Console/Console.tsx
> +  () => import("./EventDestinations/EventTypeSelector")
done @kaankabalak

2023-02-07 13:20 UTC, allanrogerr approved these changes

2023-02-07 17:39 UTC, kaankabalak approved these changes

2023-02-07 18:41 UTC, jinapurapu commented
The Add Event Destination screens still describe them as "Notification Endpoints"
![Screen Shot 2023-02-07 at 10 39 30 AM](https://user-images.githubusercontent.com/65002498/217336397-f8c9a114-1537-4acd-9257-46214aa89fe3.png)

2023-02-08 05:19 UTC, merged

2023-02-08 05:19 UTC, dvaldivia commented
@jinapurapu let me address that in a separate PR