Upgrade Go Dependencies
minio/console pull request #2676
Opened 2023-02-21 17:44 UTC by dvaldivia

2023-02-21 18:05 UTC, kaankabalak approved these changes

2023-02-21 18:31 UTC, bexsoft approved these changes

2023-02-21 18:32 UTC, bexsoft requested changes
Issue with new dependencies
<img width="1445" alt="Screenshot 2023-02-21 at 12 31 44" src="https://user-images.githubusercontent.com/33497058/220429731-12b84cb8-a1fe-402b-9634-1b6d879bc399.png">

2023-02-23 15:48 UTC, bexsoft approved these changes

2023-02-23 15:54 UTC, dilverse approved these changes

2023-02-23 15:55 UTC, merged