Fixed When the MINIO_BROWSER_REDIRECT_URL parameter contains path, the console cannot be accessed normally.
minio/console pull request #2725
Opened 2023-03-20 14:09 UTC by polaris-phecda

## What does this do?

When the MINIO_BROWSER_REDIRECT_URL parameter contains path, like _http://0.0.0.0:9001/minio-console_, the homepage cannot be accessed.

## How does it look?

![after](C:\Users\h00642346\Pictures\after.png)

2023-04-03 08:10 UTC, polaris-phecda commented
@dvaldivia @bexsoft hello brother, I have been running the code associated with the PR locally and promoted it within our team for a while. Please review whether the code can be merged into your branch.

2023-04-25 08:52 UTC, mskyttner commented
Reverse proxying the console to a subpath of the same domain where the minio server is running is much needed, +1 for this.

2023-05-02 17:49 UTC, cesnietor reviewed
Thanks for sending this change, I've added some comments to it.

2023-05-02 17:49 UTC, cesnietor commented on restapi/embedded_spec.go
> +	"github.com/minio/pkg/env"
This file shouldn't be edited manually since it's autogenerated and overwritten whenever we add a new api or the schema changes. We use [go-swagger](https://goswagger.io/tutorial/custom-server.html) for this and we specify the basePath in [here](https://github.com/minio/console/blob/master/swagger.yml#L12)

2023-05-02 17:49 UTC, cesnietor commented on restapi/embedded_spec.go
> +			println(`Invalid MINIO_BROWSER_REDIRECT_URL bas been configured. Ignore it.`)
we can use fmt.Println(` since we use fmt as our standard logging library. See [this](https://stackoverflow.com/questions/14680255/difference-between-fmt-println-and-println-in-go) for differences between both.

2023-05-02 19:50 UTC, cesnietor commented
Issue https://github.com/minio/console/issues/2774 has been assigned  and will be addressed there.

2023-05-06 02:52 UTC, polaris-phecda commented on restapi/embedded_spec.go
> +	"github.com/minio/pkg/env"
I realize I'm not handling the place properly. I've read baseurl from the environment variable when swagger is loaded in server.go.

2023-05-06 02:52 UTC, polaris-phecda commented on restapi/embedded_spec.go
> +			println(`Invalid MINIO_BROWSER_REDIRECT_URL bas been configured. Ignore it.`)
This part of the code shouldn't be here anymore. I've deleted it.

2023-05-06 03:00 UTC, polaris-phecda commented on restapi/embedded_spec.go
> +	"github.com/minio/pkg/env"
and this modification also needs to be added to the _initConsoleServer_ function of the _minio_ code. After the pr is reviewed, I will submit this content synchronously.

2023-05-08 16:38 UTC, dvaldivia requested changes

2023-05-08 16:38 UTC, dvaldivia commented on portal-ui/src/api/consoleApi.ts
> +  public baseUrl: string = `${new URL(document.baseURI).pathname}api/v1`;
this is an auto-generated file, so we need to inject this value at runtime or from the start of the application

2023-05-13 02:50 UTC, polaris-phecda commented on portal-ui/src/api/consoleApi.ts
> +  public baseUrl: string = `${new URL(document.baseURI).pathname}api/v1`;
I've fixed that. I found that all calls to consoleapi use api/index.ts proxy. I've now modified to inject baseurl into api/index.ts.

2023-05-16 17:28 UTC, dvaldivia requested changes

2023-05-16 17:28 UTC, dvaldivia commented on restapi/operations/console_api.go
> +const (
this file is auto-generated as mentioned on top of the file, might be better to move this to a different location, perhaps back to `restapi`

2023-05-16 17:31 UTC, dvaldivia commented
the way we regenerate the auto-generated files from the swagger specification is via the `make swagger-gen` command, which if you run, it removes all the code you added on `restapi/operations/console_api.go` and `restapi/operations/console_api_test.go`

2023-05-17 17:23 UTC, dvaldivia commented
I'm not able to test this PR successfully, do you mind sharing your `nginx.conf` ?

mine is simply
```
events { worker_connections 1024; }

http {

server {
    listen 8000;

    location /console/subpath/ {
        rewrite   ^/console/subpath/(.*) /$1 break;
        proxy_pass http://localhost:9091;
    }
}

}
```

but I don't see the assets successfully getting served

2023-05-19 02:45 UTC, polaris-phecda commented
> 

Did you forget that `Connection "upgrade" `needs to be added to the websocket API? This is my config file.
`
...
    location /minio-console {
        proxy_set_header Host $host;
        proxy_set_header Remote-Addr $remote_addr;
        proxy_pass http://127.0.0.1:9001;
        client_max_body_size 0;
    }

    location /minio-console/ws {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout   3600s;
        proxy_set_header Remote-Addr $remote_addr;
        proxy_pass http://127.0.0.1:9001;
    }

...

`

it works fine.

2023-05-22 02:17 UTC, polaris-phecda commented on restapi/operations/console_api.go
> +const (
I've resolved that.  i move it back to restapi.

2023-05-22 08:32 UTC, polaris-phecda commented
> I'm not able to test this PR successfully, do you mind sharing your `nginx.conf` ?
> 
> mine is simply
> 
> ```
> events { worker_connections 1024; }
> 
> http {
> 
> server {
>     listen 8000;
> 
>     location /console/subpath/ {
>         rewrite   ^/console/subpath/(.*) /$1 break;
>         proxy_pass http://localhost:9091;
>     }
> }
> 
> }
> ```
> 
> but I don't see the assets successfully getting served

If you start the console through minio server instead of directly starting the console, you also need to inject basepath into minio server according to this submission.
[](https://github.com/minio/minio/pull/17259)

2023-06-06 17:10 UTC, cesnietor commented
This should have been solved here https://github.com/minio/console/pull/2818, please reopen if this is not the case. Thanks.

2023-06-06 17:10 UTC, closed without merging