Fixed snackMessage to display if error returned creating policy
minio/console pull request #2726
Opened 2023-03-20 22:54 UTC by jinapurapu

Errors returned when creating a policy were not being displayed, now display along with guiding text for user. 
<img width="1018" alt="Screen Shot 2023-03-20 at 3 49 15 PM" src="https://user-images.githubusercontent.com/65002498/226482903-e5a48141-2ae8-4b05-9275-3fdcac356297.png">
fixes https://github.com/miniohq/engineering/issues/1183

2023-03-20 22:57 UTC, kaankabalak commented on portal-ui/src/screens/Console/Policies/AddPolicyScreen.tsx
> +              " Please check Policy syntax.",
Very minor comment, should we add a dot before the `Please check Policy syntax.` so that the two sentences are separated?

```suggestion
              ". Please check Policy syntax.",
```

2023-03-20 22:59 UTC, kaankabalak commented on portal-ui/src/screens/Console/Policies/AddPolicyScreen.tsx
> +      .catch((err: any) => {
Was there any specific reason why we changed the type of the error here?

2023-03-20 23:22 UTC, kaankabalak approved these changes

2023-03-21 00:16 UTC, dvaldivia commented
there's some lint problems @jinapurapu

2023-03-21 16:09 UTC, bexsoft requested changes
Please review Lint issues, beside of that LGTM

2023-03-22 21:08 UTC, reivaj05 approved these changes

2023-03-22 21:09 UTC, bexsoft approved these changes
LGTM, Lint issues are not related to this change.

2023-03-22 21:39 UTC, merged