Fix tenants screens
minio/console pull request #277
Opened 2020-09-16 02:36 UTC by Alevsk

<img width="1276" alt="Screen Shot 2020-09-15 at 7 35 29 PM" src="https://user-images.githubusercontent.com/1795553/93285882-c459fa00-f78a-11ea-9455-17858a7d95f3.png">

<img width="1297" alt="Screen Shot 2020-09-15 at 7 35 35 PM" src="https://user-images.githubusercontent.com/1795553/93285890-c6bc5400-f78a-11ea-91d9-99cc588ff933.png">

2020-09-16 02:38 UTC, dvaldivia submitted a review, later dismissed

2020-09-16 22:21 UTC, bexsoft requested changes

2020-09-16 22:21 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +                  console.log(element);
I think we can remove this console.log. Also, if edit zone is not going to be implemented we can remove this view action as it is not needed

2020-09-16 23:24 UTC, dvaldivia approved these changes

2020-09-17 04:40 UTC, dvaldivia approved these changes

2020-09-17 04:41 UTC, bexsoft approved these changes
LGTM

2020-09-17 05:45 UTC, dvaldivia approved these changes

2020-09-17 05:59 UTC, bexsoft approved these changes

2020-09-17 06:01 UTC, merged