Parity API
minio/console pull request #280
Opened 2020-09-17 05:01 UTC by dvaldivia

Brings the API to calculate parity for a given number of nodes and disks

2020-09-17 06:25 UTC, bexsoft approved these changes

2020-09-17 21:59 UTC, bexsoft approved these changes

2020-09-17 22:35 UTC, cesnietor approved these changes

2020-09-17 22:35 UTC, cesnietor requested changes

2020-09-17 22:35 UTC, cesnietor commented on pkg/utils/parity_test.go
> +
please change copyright

2020-09-18 18:11 UTC, Alevsk requested changes

2020-09-18 18:11 UTC, Alevsk commented on restapi/admin_parity.go
> +	parityVals, err := utils.PossibleParityValues(fmt.Sprintf(`http://minio{1...%d}/export/set{1...%d}`, nodes, disksPerNode))
its ok to assume http will be used always?, I think instead the function should receive either `http` or `https`

2020-09-18 18:25 UTC, dvaldivia commented on restapi/admin_parity.go
> +	parityVals, err := utils.PossibleParityValues(fmt.Sprintf(`http://minio{1...%d}/export/set{1...%d}`, nodes, disksPerNode))
there's no connectivity happening here so it's alright

2020-09-19 08:14 UTC, Alevsk approved these changes

2020-09-22 17:50 UTC, cesnietor approved these changes

2020-09-22 18:15 UTC, merged