if end return
minio/console pull request #2805
Opened 2023-05-07 17:05 UTC by jiuker

It cause leak of goroutine.
We login minio,refresh alway.
goroutine's num add + 1 alway.

2023-05-10 00:39 UTC, bexsoft requested changes
Hi!

Thank you for your contribution, I have tested this change but loader stays forever if you try to navigate to a second or third bucket.

Please refer to the following gif for this issue:
![2023-05-09 18-35-17 2023-05-09 18_36_51](https://github.com/minio/console/assets/33497058/16b9f1eb-86b7-4af2-af84-fee8a80ff587)

2023-05-10 01:46 UTC, jiuker commented
Reproduction steps.
1. Add the following code to minio's startup code
```go
// Copyright (c) 2015-2021 MinIO, Inc.
//
// This file is part of MinIO Object Storage stack
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main // import "github.com/minio/minio"

import (
	"fmt"
	"os"
	"runtime"
	"time"

	// MUST be first import.
	_ "github.com/minio/minio/internal/init"

	minio "github.com/minio/minio/cmd"
)

func main() {
	go func() {
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()
		for _ = range ticker.C {
			runtime.GC()
			fmt.Println("go nums:", runtime.NumGoroutine())

		}
	}()
	minio.Main(os.Args)
}
```
3. Use server /somedir to start
The output will be 
```
go nums: 358
go nums: 358
go nums: 358
go nums: 358
go nums: 358
go nums: 358
go nums: 358
```
4. Login to the console, then wait a few seconds, the output will be stable all the time
5. Add a bucket, upload the file to this bucket, and wait in /browser/{bucket}.
Then use F5 to refresh the page and wait for the output to stabilize
Then you will find the number of output +1
```shell
go nums: 362
go nums: 362
go nums: 362
go nums: 362
go nums: 362
go nums: 362
go nums: 362
```
The number of times added is the number of refreshes
```go
go nums: 363
go nums: 363
go nums: 363
go nums: 363
go nums: 363
go nums: 363
```
Then use pprofile, you will find that this is the place where the go did not exit.

@bexsoft

2023-05-10 01:58 UTC, jiuker commented
This may not be a good solution, but there is really no good exit mechanism here.
@bexsoft

2023-05-16 12:47 UTC, klauspost approved these changes
Great find!

2023-06-12 21:30 UTC, dvaldivia requested changes

2023-06-12 21:30 UTC, dvaldivia commented on restapi/ws_objects.go
> +			if writeM.RequestEnd {
I don't think we should exit this goroutine, as we still re-use the socket for other subsequent listing requests over the socket, this goroutine should exit when `<-done` in line 250 is reached, if we have a leak perhaps, the socket closing is not properly killing the parent goroutine, so we should instead close the `done` channel when the socket gets closed

2023-07-05 03:08 UTC, harshavardhana requested changes

2023-07-05 03:08 UTC, harshavardhana commented on restapi/ws_objects.go
> +					LogInfo("Error while parsing the response", err)
This comment is wrong we are not parsing here we are marshalling.

2023-07-05 18:39 UTC, harshavardhana approved these changes

2023-07-05 19:13 UTC, cesnietor commented
@jiuker  do you mind adding in the description what the change does and how it fixes the leak so that it is documented for posterity?

2023-07-05 19:15 UTC, cesnietor approved these changes
Tested adding objects, loading objects and everything looks good.

2023-07-05 19:17 UTC, merged