Use operator port variables
minio/console pull request #282
Opened 2020-09-21 21:40 UTC by cesnietor

Updates function getTenantSchemeNPort to return port depending on scheme.
Uses lates operator v3.0.21

-Tests updated

2020-09-21 21:43 UTC, harshavardhana requested changes

2020-09-21 21:43 UTC, harshavardhana commented on restapi/admin_tenants.go
> +func getTenantSchemeNPort(mi *operator.Tenant) (scheme string, port int) {
why not just return a proper URL? instead of scheme and port?

2020-09-21 21:43 UTC, harshavardhana commented on restapi/admin_tenants.go
> +	tenantScheme, port := getTenantSchemeNPort(minTenant)
```suggestion
	svcURL := getTenantSchemeNPort(minTenant, svcName)
```

2020-09-21 21:43 UTC, harshavardhana commented on restapi/admin_tenants.go
> +		port,
```suggestion
		svcURL,
```

2020-09-21 22:18 UTC, Alevsk approved these changes

2020-09-21 22:35 UTC, cesnietor commented on restapi/admin_tenants.go
> +func getTenantSchemeNPort(mi *operator.Tenant) (scheme string, port int) {
done

2020-09-22 01:19 UTC, cesnietor commented
@harshavardhana  done

2020-09-22 02:07 UTC, harshavardhana approved these changes
Neat!

2020-09-22 04:31 UTC, merged