Fixed subnet file upload to allow upload of different report types
minio/console pull request #2823
Opened 2023-05-19 22:02 UTC by jinapurapu

Functions to process Health reports for Subnet upload were incorrectly included in the subnetUploadReq, preventing generalization for other reports. This PR breaks the processing steps out to allow the other reports to be uploaded.

2023-05-22 17:34 UTC, bexsoft requested changes

2023-05-22 17:34 UTC, bexsoft commented on pkg/subnet/utils.go
> +		}
I think we can comment / remove these lines as for now no function is set

2023-05-27 02:03 UTC, bexsoft reviewed
Code looks good so far, Just found a small issue trying to generate a health report after registering my cluster:
<img width="1439" alt="Screenshot 2023-05-26 at 19 57 38" src="https://github.com/minio/console/assets/33497058/4f6fe3f4-fc75-4199-ac12-c313626ec7ae">

In the terminal:

`E: 2023/05/27 01:58:09 ErrorWithContext:error on ReadMessage: read tcp [::1]:10000->[::1]:63855: use of closed network connection`

Not sure if issue is related to the change

2023-06-06 17:18 UTC, cesnietor commented on pkg/subnet/utils.go
> +		return nil, "", errors.New("Invalid Subnet upload type")
could we make the error start with lowercase? Sharing some references: https://github.com/golang/go/wiki/Errors

2023-06-06 17:18 UTC, cesnietor commented on pkg/subnet/utils.go
> +		infoBody, formDataType, e = processHealthReport(info)
could we please rename the error variable to `err`? (also in other places in this doc) please see reference: https://github.com/golang/go/wiki/Errors#naming.

No need to define the variable at the top, we can do this by just defining them like `infoBody, formDataType, e :=...`

2023-06-06 22:54 UTC, jinapurapu commented
> Code looks good so far, Just found a small issue trying to generate a health report after registering my cluster: <img alt="Screenshot 2023-05-26 at 19 57 38" width="1439" src="https://user-images.githubusercontent.com/33497058/241348668-4f6fe3f4-fc75-4199-ac12-c313626ec7ae.png">
> 
> In the terminal:
> 
> `E: 2023/05/27 01:58:09 ErrorWithContext:error on ReadMessage: read tcp [::1]:10000->[::1]:63855: use of closed network connection`
> 
> Not sure if issue is related to the change

Replicated on baremetal, looking into it now

2023-07-03 18:44 UTC, reivaj05 commented on pkg/subnet/utils.go
> +		return infoBody, formDataType, nil
It could just be `return processHealthReport(info)`

2023-07-03 18:45 UTC, reivaj05 approved these changes

2023-07-03 23:51 UTC, bexsoft commented
Hi!, Is Upload issue resolved?

2023-07-07 18:13 UTC, closed without merging