Changed Share Object logic to use Access Keys
minio/console pull request #2827
Opened 2023-05-23 00:22 UTC by bexsoft

## What does this do?

Changed Share Object Logic to use access keys instead of console login key. This is first step for this new change, as second phase we will auto generate auto expiring service accounts

## How does it look?

<img width="813" alt="Screenshot 2023-05-22 at 18 19 59" src="https://github.com/minio/console/assets/33497058/e7636653-fe79-4d97-a10e-cf8ebd730369">
<img width="890" alt="Screenshot 2023-05-22 at 18 19 47" src="https://github.com/minio/console/assets/33497058/c1ee7cde-a8a4-45fd-b3eb-9fee664a31b9">
<img width="947" alt="Screenshot 2023-05-22 at 18 19 43" src="https://github.com/minio/console/assets/33497058/ad0c8b80-8232-41de-baff-1855a64be372">
<img width="851" alt="Screenshot 2023-05-22 at 18 19 32" src="https://github.com/minio/console/assets/33497058/bfd8b250-ff0a-4186-bbca-7f65e78176c5">
<img width="926" alt="Screenshot 2023-05-22 at 18 19 24" src="https://github.com/minio/console/assets/33497058/9eb6c536-d936-4b74-9eb3-719821ac022b">

2023-05-23 16:43 UTC, cesnietor commented
Could we add something like `An Access Key with privileges for current user is required to sign this URL`  (adding the `for current user`) or something like that? Just to be clear that even being an admin won't list other service accounts (made me think that).

2023-05-23 16:45 UTC, cesnietor commented
I found that selecting 0 days, 0 hours, and 0 minutes hangs the UI.
![Screenshot 2023-05-23 at 9 40 29 AM](https://github.com/minio/console/assets/11819101/6db8265d-7024-4618-81b7-78191534c986)

2023-05-23 20:54 UTC, reivaj05 requested changes

2023-05-23 20:54 UTC, reivaj05 commented on swagger.yml
> +    post:
I believe we should keep the method as get since the handler is not modifying the current state of the system, maybe access_key and secret_key can be passed as headers in the request and the rest as query parameters

2023-05-23 21:40 UTC, bexsoft commented on swagger.yml
> +    post:
As discussed, we will keep it as POST as this is the pattern we are following in other endpoints with this behavior. Also discussed with Daniel and its better to keep it as POST

2023-05-23 22:38 UTC, cesnietor approved these changes
Tested, LTM.
It nows gives the option to list user's service accounts or use other one by just typing it.

![Screenshot 2023-05-23 at 3 37 21 PM](https://github.com/minio/console/assets/11819101/33d49f48-e124-4609-85ec-b622291cf3c3)

2023-05-24 17:51 UTC, dvaldivia approved these changes

2023-05-24 17:52 UTC, merged

2023-06-01 17:29 UTC, grubjack commented
trying to share a file under LDAP user with consoleAdmin permissions and get the error:

`{"Code":"AccessDenied","Message":"Access Denied.","Resource":"/minio/admin/v3/list-service-accounts","RequestId":"176498F6A04CC8B9","HostId":"dd90..."}`

under regular LDAP user get the error:

`{"Code":"AccessDenied","Message":"Access Denied.","Resource":"/minio/admin/v3/list-service-accounts","RequestId":"176498F6A04CC8B9","HostId":"dd90..."}`