apply policy resource restrictions for file extensions
minio/console pull request #2842
Opened 2023-05-30 08:31 UTC by prakashsvmx

Fixes https://github.com/minio/console/issues/2838

Sample policy to test:
( Allow and deny both actions are used)
```json

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionTagging",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/txt/*.txt",
                "arn:aws:s3:::mybucket/*.jpg",
                "arn:aws:s3:::mybucket/anything/*",
                "arn:aws:s3:::mybucket/jpg/*.jpg",
                "arn:aws:s3:::mybucket/l1/l2/*.txt",
                "arn:aws:s3:::mybucket/png/*.png",
                "arn:aws:s3:::mybucket/txt/*.doc"
            ]
        },
        {
            "Effect": "Deny",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/txt/*.doc",
                "arn:aws:s3:::mybucket/txt/*.txt"
            ]
        }
    ]
}
```

Testing:
- Allow/Deny file extensions on a root level,
- Allow/Deny at prefix level
- Drag and Drop individual files
- Drag and drop folders ( only allowed extensions are uploaded )

2023-05-30 08:37 UTC, harshavardhana commented on portal-ui/src/screens/Console/Buckets/ListBuckets/UploadPermissionUtils.ts
> +import { ISessionPermissions } from "../../types";
license header missing

2023-05-30 13:08 UTC, prakashsvmx commented on portal-ui/src/screens/Console/Buckets/ListBuckets/UploadPermissionUtils.ts
> +import { ISessionPermissions } from "../../types";
Thank you . I have updated.

2023-06-02 18:39 UTC, bexsoft requested changes
There is an issue if I try to upload a file using drag and drop:

![2023-06-02 12-36-01 2023-06-02 12_38_09](https://github.com/minio/console/assets/33497058/805d0ebb-eb24-4af1-b19d-fc412c8fd4f2)

2023-06-05 10:32 UTC, prakashsvmx commented
Thank you @bexsoft  :+1: . I have added logs and improved the dnd handling to accept one or more files.

2023-06-12 21:30 UTC, dvaldivia commented
there's a warning @prakashsvmx

2023-06-13 10:08 UTC, prakashsvmx commented
@dvaldivia thank you, i have updated the type reference.

2023-06-15 01:28 UTC, bexsoft requested changes
If I try to upload a file with the extension `.JPG` (Uppercase), an error is thrown

<img width="1548" alt="Screenshot 2023-06-14 at 19 17 59" src="https://github.com/minio/console/assets/33497058/55f11968-bc61-4d93-a8ce-0965d61490b1">

Trying to do drag and drop, I see the following issue in any case:

<img width="1550" alt="Screenshot 2023-06-14 at 19 18 47" src="https://github.com/minio/console/assets/33497058/63aed2ac-e63e-4dbd-ada2-95559101f7b5">

If I try to create a new subpath inside anything folder, button is not enabled
<img width="1298" alt="Screenshot 2023-06-14 at 19 26 28" src="https://github.com/minio/console/assets/33497058/3eb074ee-6157-49a2-bdc5-b614567f34d9">

2023-06-15 04:48 UTC, prakashsvmx commented
@bexsoft 
> 1. If I try to upload a file with the extension .JPG (Uppercase), an error is thrown

it is working as expected. test with mc

> 2. Trying to do drag and drop, I see the following issue in any case:
  
 Fixed
   
>3. If I try to create a new subpath inside anything folder, button is not enabled

it is working as per master/release.  ( in master/release as well it is disabled)


<details>

```
➜ mc cp 1.png fxt/mybucket/png                 
...-file-types/1.png: 4 B / 4 B ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 501 B/s 0s 

# Copy PNG ( uppercase extension)

 ➜ mc cp 2.PNG fxt/mybucket/png/       
mc: <ERROR> Failed to copy `/home/prakash/Downloads/test-all-file-types/2.PNG`. Insufficient permissions to access this path `http://localhost:22000/mybucket/png/2.PNG`

 ➜ mc ls fxt/mybucket/png/          
[2023-06-15 09:48:22 IST]     4B STANDARD 1.png
[2023-06-15 08:50:22 IST] 9.5KiB STANDARD image (4).png
```
</details>

2023-06-15 16:33 UTC, bexsoft approved these changes
LGTM

2023-06-15 16:41 UTC, dvaldivia approved these changes

2023-06-15 16:43 UTC, cesnietor requested changes
reviewing

2023-06-15 17:14 UTC, cesnietor commented
@prakashsvmx  I was also expecing a similar thing as @bexsoft.
And I think we should solve the following:
Since JPG (uppercase) is not allowed, it shouldn't allow you to select the file in the browser, similar to how others are not allowed, otherwise it's letting me know that it's allowed but then the app fails. This however can be an enhancement.

<img width="259" alt="Screenshot 2023-06-15 at 10 03 57 AM" src="https://github.com/minio/console/assets/11819101/2d8738e0-bd49-48c8-b632-8a2b4581d8eb">

2023-06-15 18:29 UTC, cesnietor approved these changes
LGTM

2023-06-15 18:33 UTC, merged

2023-06-16 10:40 UTC, prakashsvmx commented
Thank you @cesnietor  :+1: