Hide Lookup Bind Password from the Console UI
minio/console pull request #2846
Opened 2023-06-01 16:23 UTC by cniackz

2023-06-01 16:26 UTC, cesnietor commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +  return result;
no need to have a result variable, we can just do :
```
return field === enabledConfigLDAP.at(2)
```

2023-06-01 16:27 UTC, cesnietor commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +function isPassword(field: any) {
can we rename it as `isLDAPPassword` so that it documents itself.

2023-06-01 16:28 UTC, cesnietor commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +  return result;
notice the three equal operators for reference see [this](https://www.c-point.com/javascript_tutorial/jsgrpComparison.htm)

2023-06-01 16:35 UTC, cesnietor commented
Thinking about it, I think we should just not return it in the API. wdyt @cniackz ? otherwise this looks a bit hacky.

2023-06-01 16:40 UTC, cniackz commented
I think you are right @cesnietor we should instead modify the API to avoid retrieving this value.
But this will require more time for me to learn.
Moving this PR as a draft in the meantime.

2023-06-01 22:58 UTC, cniackz commented
I don't think `Workflow / Checking Lint (1.20.x, ubuntu-latest) (pull_request) ` is related to this change.

2023-06-01 23:01 UTC, cniackz commented
Yeah, confirmed, unrelated: https://github.com/minio/console/pull/2847

2023-06-02 01:11 UTC, reivaj05 commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +                        {Object.entries(formFieldsWithOutPassword).map(
No need to have an extra variable, if we don't show the password in the details the user might think that there is no password set, it's better if we just display it as "*****"

2023-06-02 01:20 UTC, reivaj05 commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +                              value={fields[key] ? fields[key] : ""}
cons getFieldValue = (key, value: string) => {
    if (key === "lookup_bind_password") {
      return value ? "********" : "";
    }
    return value;
  };

value={getFieldValue(fields[key] ? fields[key] : "")}

2023-06-02 01:22 UTC, reivaj05 commented on restapi/admin_config.go
> +			if kv.Key != "lookup_bind_password" {
I think we shouldn't modify this since this is mirroring the same behavior as `mc admin config get`, if we are not changing the behavior for mc right now then console should do the same

2023-06-02 01:23 UTC, reivaj05 requested changes
see comments

2023-06-02 18:44 UTC, cesnietor commented on restapi/admin_config.go
> +			if kv.Key != "lookup_bind_password" {
It's intended to do this in the future I believe. but I'll  defer this to @cniackz

2023-06-02 18:44 UTC, cesnietor commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +                        {Object.entries(formFieldsWithOutPassword).map(
I agree with @reivaj05 , **IF** we can have ldap enabled without password set, then the user should know, so we 
 should display `****` or `Set Password` so that the user knows that it's set or not. If we don't allow (in mc also) to enable ldap without password then no need to display the `Set Password`.

Also the use of the variable might not super convenient cause, everytime we add a key  to the response in the api, or coming from the admin client, we'd need to update that map vs just letting backend drive what should be shown.  Are there any other fields that we want to hide?

2023-06-02 18:59 UTC, reivaj05 commented on restapi/admin_config.go
> +			if kv.Key != "lookup_bind_password" {
It's ok, I only meant to actually make the change in console once the change is done in mc

2023-06-03 11:06 UTC, cniackz commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +                        {Object.entries(formFieldsWithOutPassword).map(
For now only `Lookup Bind Password` should not be shown in plain text.

2023-06-03 11:07 UTC, cniackz commented on portal-ui/src/screens/Console/IDP/LDAP/IDPLDAPConfigurationDetails.tsx
> +                              value={fields[key] ? fields[key] : ""}
with a slight modification but it work and I understood your point, thanks Javi!.

2023-06-03 11:09 UTC, cniackz commented on restapi/admin_config.go
> +			if kv.Key != "lookup_bind_password" {
I think `mc` change will take time if approved, I will ask @kannappanr but in the meantime, all we can do is to avoid displaying the password in plan text if provided since API will anyways provide the password, this does not depends on us but is more of a BE change.

2023-06-05 21:57 UTC, allanrogerr commented
Fixes 1199

2023-06-05 22:16 UTC, allanrogerr approved these changes

2023-06-05 22:16 UTC, allanrogerr approved these changes

2023-06-07 19:09 UTC, allanrogerr commented
Closing in place of a direct change to minio. PR number pending

2023-06-07 19:09 UTC, closed without merging