Pass Client IP address to MinIO on x-forwarded-for header
minio/console pull request #2864
Opened 2023-06-12 19:23 UTC by dvaldivia

This PR introduces a custom `RoundTripper` for the transport we use when communicating with MinIO via the SDKs.

The intention is to communicate the IP address of the actual user to MinIO.

While reviewing this PR:

If the request was available, that was used as an inline solution, like when the client is instantiated from the handler
`context.Context` was used whenever was possible as the middleware can introduce the IP address and have it be pass it around
websocket can't use the same `context.Context` have their own remoteAddress call

Fixes https://github.com/minio/console/issues/2290

2023-06-12 19:44 UTC, cesnietor commented on restapi/ws_handle.go
> +	remoteAddress() string
Can we add this one to `mockConn` so that it passes the lint errors.

2023-06-12 21:22 UTC, dvaldivia commented on restapi/ws_handle.go
> +	remoteAddress() string
added

2023-06-13 18:59 UTC, reivaj05 requested changes

2023-06-13 18:59 UTC, reivaj05 commented on cmd/console/app_commands.go
> +	transport := restapi.PrepareSTSClientTransport(false, "127.0.0.1")
Could you add "127.0.0.1" as constant in `const.go` file?

2023-06-13 21:15 UTC, dvaldivia commented on cmd/console/app_commands.go
> +	transport := restapi.PrepareSTSClientTransport(false, "127.0.0.1")
done

2023-06-14 02:41 UTC, bexsoft approved these changes

2023-06-14 10:25 UTC, vadmeste commented on restapi/tls.go
> +	req.Header.Add("X-Forwarded-For", t.ClientIP)
Do we really need to use X-Forwarded-For header? it is a known header that has its own purpose and Console is not a real proxy, I guess we should be able to use a different header name without issues.

2023-06-14 19:02 UTC, dvaldivia commented on restapi/tls.go
> +	req.Header.Add("X-Forwarded-For", t.ClientIP)
we are technically proxying requests for the users via the UI, and we need to communicate to MinIO the real IP address of the client behind the browser and MinIO is already reading this header by default so I don't think we should be using a custom header

2023-06-14 19:32 UTC, reivaj05 approved these changes

2023-06-14 19:36 UTC, merged