Added missing validations in add tenant modal
minio/console pull request #288
Opened 2020-09-24 20:09 UTC by bexsoft

## What does this do?

Added missing validations in add tenant modal

## How to test?

- Open add tenant modal
- Verify that required fields ar correctly validated

2020-09-24 20:18 UTC, dvaldivia requested changes

2020-09-24 20:18 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
> +        <CredentialsPrompt
I don't see changes on the `CredentialsPrompt` component, will it also display the console credentials if they are available?

2020-09-24 22:13 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
> +        <CredentialsPrompt
Yes, Credentials prompt will show them, also TenantCredentialsPrompt is missing on master, so this change is required.

2020-09-24 22:33 UTC, dvaldivia approved these changes

2020-09-24 22:35 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/ListTenants.tsx
> +        <CredentialsPrompt
Fixed

2020-09-24 22:35 UTC, dvaldivia approved these changes

2020-09-28 17:36 UTC, Alevsk submitted a review, later dismissed

2020-09-28 19:25 UTC, bexsoft commented
Changes merged in #289

2020-09-28 19:25 UTC, closed without merging