Fixed subnet Health report upload
minio/console pull request #2927
Opened 2023-07-06 23:52 UTC by jinapurapu

Adds functions to get API key from Subnet using license key, to correctly generate SUBNET upload headers, process Health report for upload, generic subnet upload. 
Also adds UI improvements on HealthInfo screen to display error if empty Health report is returned, prompt user to retry failed reports.
<img width="922" alt="Screenshot 2023-07-06 at 4 18 55 PM" src="https://github.com/minio/console/assets/65002498/dd9d71f4-ed56-4114-9a78-70956faa2191">

2023-07-07 08:20 UTC, anjalshireesh commented on restapi/admin_health_info.go
> +	apiKey, e := subnet.GetSubnetAPIKeyUsingLicense(subnetTokenConfig.License)
Maybe this should be done only if `subnetTokenConfig.APIKey` is empty?

2023-07-07 08:20 UTC, anjalshireesh commented on restapi/client-admin.go
> +		healthV1 := mcCmd.MapHealthInfoToV1(info, nil)
Since this will be embedded with latest `minio`, you'll never have to deal with older versions of the health info. The version will always be `madmin.HealthInfoVersion`

`mc` has this kind of code because it needs to support older versions of `minio`.

2023-07-14 18:26 UTC, jinapurapu commented on pkg/subnet/utils.go
> +	part, e := writer.CreateFormFile("file", "filename")
It's only a temporary "file" to make the correct header, I don't think the name is used anywhere else

2023-07-19 19:29 UTC, reivaj05 submitted a review, later dismissed

2023-07-20 17:48 UTC, bexsoft requested changes
Behavior is not consistent all the times, some random errors are seen when you click on the generate diagnostics button
![2023-07-20 11-34-00 2023-07-20 11_46_00](https://github.com/minio/console/assets/33497058/a41491fa-0e83-4c31-9811-5b20d1dbe6fb)

2023-07-27 20:50 UTC, cesnietor commented
@jinapurapu  how can I test this? seems I need to register my cluster but this is local. do you have some creds? please share privately.

2023-07-27 21:29 UTC, bexsoft approved these changes
LGTM

2023-07-27 21:30 UTC, cesnietor approved these changes
tested with @bexsoft lgtm

2023-07-27 22:29 UTC, merged