dashboard metrics
minio/console pull request #2952
Opened 2023-07-18 12:31 UTC by prakashsvmx

![image](https://github.com/minio/console/assets/23444145/674585a1-9927-4f17-a917-1cb9f9ec0d79)

Note: `Buckets`  i.e: Number of Buckets  requires  update to new endpoint may be, as  it is not available at cluster level `minio_cluster_usage_total_bytes` does not publish bucket name.

@harshavardhana

2023-07-18 20:59 UTC, harshavardhana commented
> Note: `Buckets` i.e: Number of Buckets requires update to new endpoint may be, as it is not available at cluster level `minio_cluster_usage_total_bytes` does not publish bucket name.

will add this as `minio_cluster_total_buckets` @prakashsvmx

2023-07-19 05:34 UTC, prakashsvmx commented
Thank you @harshavardhana . i have updated this PR to use the `minio_cluster_buckets_total` and the screenshot for reference.

2023-07-19 05:35 UTC, harshavardhana requested changes

2023-07-19 05:35 UTC, harshavardhana commented on restapi/admin_info.go
> +				Expr:         `sum(minio_cluster_usage_total_bytes{$__query}) by (instance)`,
This is not a sum anymore @prakashsvmx since it's already a sum()

2023-07-19 05:35 UTC, harshavardhana commented on restapi/admin_info.go
> +				Expr:         `topk(1, sum(minio_cluster_usage_object_total{$__query}) by (instance))`,
```suggestion
				Expr:         `topk(1, minio_cluster_usage_object_total{$__query} by (instance))`,
```

2023-07-19 05:49 UTC, prakashsvmx commented on restapi/admin_info.go
> +				Expr:         `sum(minio_cluster_usage_total_bytes{$__query}) by (instance)`,
Thank you, i have updated the query and verified.

2023-07-19 05:53 UTC, prakashsvmx commented on restapi/admin_info.go
> +				Expr:         `sum(minio_cluster_usage_total_bytes{$__query}) by (instance)`,
```
# TYPE minio_cluster_bucket_total gauge
minio_cluster_bucket_total{server="127.0.0.1:22000"} 3
minio_cluster_usage_object_total{server="127.0.0.1:22000"} 12
minio_cluster_usage_total_bytes{server="127.0.0.1:22000"} 1.09520916e+08

# TYPE minio_cluster_objects_size_distribution gauge
minio_cluster_objects_size_distribution{range="BETWEEN_1024_B_AND_1_MB",server="127.0.0.1:22000"} 1
minio_cluster_objects_size_distribution{range="BETWEEN_10_MB_AND_64_MB",server="127.0.0.1:22000"} 0
minio_cluster_objects_size_distribution{range="BETWEEN_128_MB_AND_512_MB",server="127.0.0.1:22000"} 0
minio_cluster_objects_size_distribution{range="BETWEEN_1_MB_AND_10_MB",server="127.0.0.1:22000"} 1
minio_cluster_objects_size_distribution{range="BETWEEN_64_MB_AND_128_MB",server="127.0.0.1:22000"} 1
minio_cluster_objects_size_distribution{range="GREATER_THAN_512_MB",server="127.0.0.1:22000"} 0
minio_cluster_objects_size_distribution{range="LESS_THAN_1024_B",server="127.0.0.1:22000"} 9

```

2023-07-19 06:45 UTC, harshavardhana requested changes
one more change `max by range` is not needed apparently.

2023-07-19 06:45 UTC, harshavardhana commented on restapi/admin_info.go
> +				Expr:         `max by (range) (minio_cluster_objects_size_distribution{$__query})`,
```suggestion
				Expr:         `minio_cluster_objects_size_distribution{$__query}`,
```

2023-07-19 06:45 UTC, harshavardhana commented
https://github.com/minio/minio/pull/17683 PTAL

2023-07-19 07:18 UTC, prakashsvmx commented on restapi/admin_info.go
> +				Expr:         `max by (range) (minio_cluster_objects_size_distribution{$__query})`,
Thank you again. i have updated the query. also updated the widget as per new response structure.

2023-07-19 07:25 UTC, harshavardhana approved these changes

2023-07-20 05:02 UTC, bexsoft approved these changes

2023-07-20 14:57 UTC, merged