Add bucket replication screen
minio/console pull request #3040
Opened 2023-09-07 23:05 UTC by jinapurapu

Also adds selector for replication of existing objects, as opposed to being enabled by default.

<img width="618" alt="Screenshot 2023-09-07 at 4 01 26 PM" src="https://github.com/minio/console/assets/65002498/809417e5-57d2-469a-9b2f-cffd718431eb">

2023-09-28 18:30 UTC, dvaldivia approved these changes

2023-10-31 16:26 UTC, bexsoft requested changes

2023-10-31 16:26 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddBucketReplication.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Please avoid removing the `exhaustive-deps` linter as much as possible

2023-10-31 16:26 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddBucketReplication.tsx
> +                disabled={addLoading || !validated}
This button remains disabled even if I fill all the fields

<img width="1345" alt="Screenshot 2023-10-31 at 10 26 10 a m" src="https://github.com/minio/console/assets/33497058/a538f657-9f33-4265-aa0b-c581e3ef5c7a">

2024-02-26 21:44 UTC, harshavardhana approved these changes

2024-02-26 21:44 UTC, merged