Load the available CA in logout API
minio/console pull request #3044
Opened 2023-09-12 06:07 UTC by pjuarezd

## What does this do?
Load the available CA in the  API when invoking the `openid-connect/logout` remote IDP endpoint.

Found that even though the CA certificates are properly provided to minio console, the invoke to the logout endpoint when using OIDP was not loading the CA certificates, causing several things:

1) API `/api/v1/logout` returned a 500 error.

2) API call returned `tls: failed to verify certificate: x509: certificate signed by unknown authority` error:

```json
{
    "detailedMessage": "Post \"https://kc-service.keycloak.svc.cluster.local/realms/oidc-iam/protocol/openid-connect/logout\": tls: failed to verify certificate: x509: certificate signed by unknown authority",
    "message": "an error occurred, please try again"
}
```

3) User session on IDP was not closed 

4) User session in Minio Console was not really closed, user is still logged in

![idp no logout](https://github.com/minio/console/assets/1334362/dfa85c17-d449-48e1-92d4-e754e796594b)

2023-09-12 22:04 UTC, dvaldivia approved these changes

2023-09-12 22:22 UTC, harshavardhana requested changes

2023-09-12 22:22 UTC, harshavardhana commented on restapi/user_logout.go
> +		_, err := client.PostForm(providerCfg.EndSessionEndpoint, params)
Actually, there is no point in throwing an error here since it's an idempotent behavior, that was the main reason.

Logout is one way action so it is simply safe to not even bother with the error in http.PostForm() you can simply invalidate the cookie anyways that would force a re-login

Some HTTP API calls are idempotent such as DELETE in S3 API which never returns an error, logout is similar.

2023-09-12 22:27 UTC, harshavardhana requested changes

2023-09-12 22:27 UTC, harshavardhana commented on restapi/user_logout.go
> +		_, err := client.PostForm(providerCfg.EndSessionEndpoint, params)
We do not really care if the user session from remote IDP is not closed or not, that is up to them to manage inactive sessions.

The main reason is even a simple network error will do that too, IMO if we say something to indicate that "IDP handshake failed, logging out locally to allow for re-login" would work if you want to let them know why.

IMO we do not have to throw any error, no one would notice.

2023-09-12 22:35 UTC, pjuarezd commented on restapi/user_logout.go
> +		_, err := client.PostForm(providerCfg.EndSessionEndpoint, params)
Shuld we out a log line to the console stdout error instead?

2023-09-12 23:14 UTC, pjuarezd commented on restapi/user_logout.go
> +			api.Logger("IDP logout failed: %v", err.APIError)
Sending the error to api logger instead of prevent the cookies clean here @harshavardhana

2023-09-13 17:43 UTC, harshavardhana approved these changes

2023-09-13 18:56 UTC, reivaj05 approved these changes

2023-09-13 20:50 UTC, harshavardhana approved these changes

2023-09-13 21:26 UTC, bexsoft approved these changes
LGTM

2023-09-13 21:26 UTC, merged