Fix: cache clientIP in GetConsoleHTTPClient
minio/console pull request #3056
Opened 2023-09-21 02:12 UTC by adriangitvitz

2023-09-21 02:57 UTC, harshavardhana requested changes

2023-09-21 02:57 UTC, harshavardhana commented on restapi/client-admin.go
> +        client.Transport.(*ConsoleTransport).ClientIP = clientIP
Why would do this kind of ract updates for in-memory copies, is there a better way to set this which is safer?

2023-09-21 02:58 UTC, harshavardhana commented on restapi/client-admin.go
> +        client.Transport.(*ConsoleTransport).ClientIP = clientIP
And what happens if it's not ConsoleTransport - how is a crash protected here ?

2023-09-21 16:27 UTC, cesnietor commented
Can you please add more details to the description of the PR, including which issue it fixes, changes/context and how to test it. 
Some examples: https://github.com/minio/console/pull/3047,  https://github.com/minio/console/pull/3038.

2023-09-21 19:18 UTC, dvaldivia commented on restapi/client-admin.go
> +        client.Transport.(*ConsoleTransport).ClientIP = clientIP
Since we are using that `httpClients` cache, we need to update the clientIP everytime we pull the cached client, not sure why we introduced the cache in the first place since we need this clientIP be different for each client to properly communicate who is making the request. cc @vadmeste

2023-09-21 19:54 UTC, harshavardhana commented on restapi/client-admin.go
> +        client.Transport.(*ConsoleTransport).ClientIP = clientIP
Yeah we cannot update ClientIP in this manner since its racy, its a pointer and its shared.

2023-09-21 21:26 UTC, dvaldivia commented
I tested the fix, it does addresses the problem, but let's remove the http client cache and make the casting of the transport more defensive

2023-09-26 05:14 UTC, harshavardhana requested changes

2023-09-26 05:14 UTC, harshavardhana commented on restapi/client-admin.go
> +		}
Remember this transport is a global object and pointer manipulation in this manner is racy.

We have to do it differently by adding this information as part of the request headers. Meaning this information must be sent differently than the way it's implemented.

2023-10-03 00:48 UTC, harshavardhana commented on restapi/client-admin.go
> +		}
👍🏼

2023-10-09 18:56 UTC, dvaldivia approved these changes
Tested. Works as expected.

2023-10-09 19:06 UTC, dvaldivia approved these changes
Tested.

2023-10-09 19:06 UTC, bexsoft approved these changes
LGTM, Tested along side with @dvaldivia & @adriangitvitz

2023-10-09 19:40 UTC, merged