Set Bucket Quota on Creation
minio/console pull request #308
Opened 2020-10-01 20:13 UTC by dvaldivia

Fixes #294 

Introduces the capability to set bucket quota on bucket creation and adds the API to set the bucket on it's own

<img width="1072" alt="Screen Shot 2020-10-01 at 1 11 23 PM" src="https://user-images.githubusercontent.com/18384552/94858365-cb6a4480-03e7-11eb-887c-b0c8a92d47ee.png">
<img width="1034" alt="Screen Shot 2020-10-01 at 1 11 25 PM" src="https://user-images.githubusercontent.com/18384552/94858355-c907ea80-03e7-11eb-9bf8-a21ba5013fc6.png">

2020-10-01 20:26 UTC, bexsoft requested changes
Please add some space between size & size measure fields

2020-10-01 23:49 UTC, dvaldivia commented
@bexsoft done, the input height should be fixed from how all the input wrappers work

2020-10-02 00:04 UTC, bexsoft approved these changes

2020-10-02 01:45 UTC, Alevsk approved these changes
Lgtm

2020-10-02 01:59 UTC, merged