Add UI to select number of non-current versions subject to ILM rule
minio/console pull request #3088
Opened 2023-10-12 23:25 UTC by jinapurapu

Adds unit selector to Add Lifecycle rule modal to enable selection to expire or transition non-current versions of objects after a number of non-current versions OR a number of days, and UI changes to display non-current version count based rules.

https://github.com/minio/console/assets/65002498/509fc585-91f9-4894-902e-db8d01712143

closes https://github.com/miniohq/engineering/issues/1282

2023-10-31 18:07 UTC, bexsoft approved these changes
LGTM

2023-10-31 20:27 UTC, cesnietor commented
@jinapurapu  please remove the console log:
```set to valid:  true  lifecycledays:  231906034276324167843127894132794372979234174138`

2023-10-31 20:29 UTC, cesnietor commented
if the number is too long:
`231906034276324167843127894132794372979234174138207324072341`
the request fails like:
```
"parsing body body from \"\" failed, because json: cannot unmarshal number 2.3190603427632416e+59 into Go struct field AddBucketLifecycle.noncurrentversion_expiration_days of type int32"
```
And there is no ui indication that something went wrong.
Could we add a max allowed field in the input.
And also show the error if it occurs?

2023-10-31 20:31 UTC, cesnietor commented
As UX this text doesn't have a way to let the user know that it's clickable:
<img width="99" alt="Screenshot 2023-10-31 at 1 29 51 PM" src="https://github.com/minio/console/assets/11819101/353e9506-2e73-483e-ac04-1c7231054b02">
So users may never found out about it.
We can fix this by simply adding something like an icon e.g. `^` next to the text?

2023-10-31 20:38 UTC, cesnietor commented
0 value should not be allowed:
```

{detailedMessage: "expiration days cannot be set to zero",…}
detailedMessage
: 
"expiration days cannot be set to zero"
message
: 
"an error occurred, please try again"
```

2023-10-31 20:45 UTC, bexsoft commented
> Since 0 days is not a valid value. We correctly disable the button but we don't say what the valid values are, or that `0` is not valid. not sure if this can be done via a simple helper text or something else @bexsoft . <img alt="Screenshot 2023-10-31 at 1 39 40 PM" width="542" src="https://user-images.githubusercontent.com/11819101/279509957-8402932e-2496-42dc-86c4-1f931c24f70c.png">

Yes, it can be done by setting the `error` prop for this specific field

2023-10-31 20:45 UTC, bexsoft requested changes

2023-10-31 20:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddLifecycleModal.tsx
> +    console.log("set to valid: ", valid, " lifecycledays: ", lifecycleDays);
Please remove this line

2023-11-07 21:46 UTC, cesnietor commented
Can we change the validation error to be something like: `value should be between 1-<the actual max>`. We can save them to google the value by actually telling them the max.

2023-11-10 00:02 UTC, cesnietor commented
Tested, it now shows the validation warnings as well as some docs on the days/versions.
![Screenshot 2023-11-09 at 4 01 43 PM](https://github.com/minio/console/assets/11819101/db894967-c239-4d51-8e31-4987142ec13c)
![Screenshot 2023-11-09 at 4 01 39 PM](https://github.com/minio/console/assets/11819101/781d1d0d-bc42-44a3-bd52-161bf12b2983)
![Screenshot 2023-11-09 at 4 01 32 PM](https://github.com/minio/console/assets/11819101/91f76172-0f54-4be5-9b11-e6673120e05f)

2023-11-10 00:02 UTC, cesnietor approved these changes

2023-11-10 00:07 UTC, cesnietor requested changes
Ah @jinapurapu the message should be either `less than or equal to 2147483647` or `less than 2147483648` cause it allows `2147483647`.
![Screenshot 2023-11-09 at 4 06 41 PM](https://github.com/minio/console/assets/11819101/99afdff7-9423-45a7-9e58-f12d32ba88d7)

2023-11-10 01:20 UTC, cesnietor approved these changes

2023-11-16 19:33 UTC, bexsoft approved these changes

2023-11-16 19:34 UTC, merged