simplify the provider config init, loading and allow reachable IDPs
minio/console pull request #3168
Opened 2023-12-23 20:47 UTC by harshavardhana

fixes https://github.com/minio/console/issues/3018

2023-12-24 05:24 UTC, tsuzu commented on restapi/user_login.go
> +	}
I'm sorry if my understanding is incorrect.
I think we should be able to sign in with credentials(ID/Password) even if all `openIDProviders` are unavailable.
but with this if statement, the error page will be shown when all `openIDProviders` are unavailable.
so it may be better that `getLoginDetailsResponse` never returns errors and instead returns `LoginDetails` with `LoginDetailsLoginStrategyForm`

2023-12-24 06:04 UTC, harshavardhana commented on restapi/user_login.go
> +	}
Oh yes that is fine. I kept it the way it is today however the idea was that we do not fail if one of the IDP is unreachable.

2023-12-24 08:24 UTC, tsuzu commented on restapi/user_login.go
> +	}
I get it. Thanks. However, the objective of #3018 is to ensure successful sign-in even when the sole oidc provider is unavailable. Therefore, I believe the issue shouldn't be marked as closed until this scenario is addressed.

2023-12-26 20:20 UTC, dvaldivia requested changes

2023-12-26 20:20 UTC, dvaldivia commented on .github/workflows/jobs.yaml
> +          threshold=50
not needed anymore :P

2023-12-26 20:32 UTC, dvaldivia approved these changes

2023-12-26 20:38 UTC, merged