Implement License page
minio/console pull request #324
Opened 2020-10-10 05:14 UTC by kaankabalak

Fixes #320

## Description of changes proposed

This commit implements the License page

## Screenshots

![Screen Shot 2020-10-09 at 10 01 38 PM](https://user-images.githubusercontent.com/27314853/95646367-8cd62900-0a7c-11eb-8706-bfcda629547f.png)

2020-10-10 05:23 UTC, dvaldivia approved these changes

2020-10-10 19:12 UTC, cesnietor requested changes
can you please do `make assets` to have your changes running on localhost:9090?

2020-10-12 16:17 UTC, kaankabalak commented
> can you please do `make assets` to have your changes running on localhost:9090?

Done, thanks for the feedback and would appreciate if you could review again @cesnietor

2020-10-12 16:55 UTC, dvaldivia submitted a review, later dismissed

2020-10-12 17:12 UTC, Alevsk approved these changes

2020-10-12 17:20 UTC, bexsoft approved these changes

2020-10-12 17:29 UTC, bexsoft requested changes
Please fix `make lint` issues

2020-10-12 17:49 UTC, cesnietor approved these changes

2020-10-12 18:52 UTC, dvaldivia approved these changes

2020-10-12 18:53 UTC, Alevsk approved these changes

2020-10-12 18:54 UTC, bexsoft approved these changes

2020-10-12 18:56 UTC, merged