Fix URL of inspect object API
minio/console pull request #3247
Opened 2024-02-26 22:37 UTC by bayasdev

This PR adds the missing `window.location.origin` to the URL generated for the inspect object API

2024-02-26 23:27 UTC, dvaldivia requested changes

2024-02-26 23:27 UTC, dvaldivia commented on web-app/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/InspectObject.tsx
> +    const urlOfInspectApi = `${window.location.origin}${basename}/api/v1/admin/inspect?volume=${volume}&file=${file}&encrypt=${isEncrypt}`;
hold on, we are explicitely removing `window.location.origin` on the previous line, what was the bug caused by this being missing?

2024-02-26 23:43 UTC, bayasdev commented on web-app/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/InspectObject.tsx
> +    const urlOfInspectApi = `${window.location.origin}${basename}/api/v1/admin/inspect?volume=${volume}&file=${file}&encrypt=${isEncrypt}`;
I was testing on my dev environment and it was trying to connect to http//api/v1.... when clicking on the inspect object button

2024-02-27 19:52 UTC, bexsoft commented on web-app/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/InspectObject.tsx
> +    const urlOfInspectApi = `${window.location.origin}${basename}/api/v1/admin/inspect?volume=${volume}&file=${file}&encrypt=${isEncrypt}`;
This is just a replacement to include the subdomains, it is a change that was implemented in other parts of the application such as Preview or Share.

2024-02-27 19:52 UTC, bexsoft approved these changes

2024-02-28 00:31 UTC, bexsoft approved these changes

2024-02-28 18:14 UTC, dvaldivia approved these changes

2024-02-29 02:51 UTC, merged