Reuse GetClusterRegInfo from mc
minio/console pull request #3270
Opened 2024-03-19 13:59 UTC by anjalshireesh

The logic related to calculating no of pools has changed in mc, but still old in console. Ensuring that the function from mc is reused here will avoid such issues in future.

2024-03-20 04:10 UTC, bexsoft requested changes

2024-03-20 04:10 UTC, bexsoft commented on go.mod
> +replace github.com/minio/mc => github.com/anjalshireesh/mc v0.0.0-20240319134657-0e1592c105d9
Please remove replace

2024-03-20 04:58 UTC, anjalshireesh commented on go.mod
> +replace github.com/minio/mc => github.com/anjalshireesh/mc v0.0.0-20240319134657-0e1592c105d9
@bexsoft will remove it after the corresponding PR https://github.com/minio/mc/pull/4881 is merged in `mc`.

2024-03-21 04:13 UTC, anjalshireesh commented on go.mod
> +replace github.com/minio/mc => github.com/anjalshireesh/mc v0.0.0-20240319134657-0e1592c105d9
@bexsoft done, PTAL.

2024-03-21 04:46 UTC, shtripat approved these changes
lgtm

2024-04-01 11:23 UTC, prakashsvmx approved these changes

2024-04-01 16:14 UTC, harshavardhana approved these changes

2024-04-01 16:14 UTC, merged