Use Console as proxy for share object logic
minio/console pull request #3284
Opened 2024-04-05 19:02 UTC by cesnietor

2024-04-09 02:09 UTC, bexsoft submitted a review, later dismissed
LGTM, Tested in local env as well as making a custom MinIO build with this fix.

2024-04-09 07:18 UTC, prakashsvmx commented
@cesnietor , Do we still need to limit  the number of hours as in the screenshot?

![image](https://github.com/minio/console/assets/23444145/94f162ae-e276-418e-aa36-f35c942cb977)

2024-04-09 07:54 UTC, harshavardhana requested changes

2024-04-09 07:54 UTC, harshavardhana commented on api/public_objects.go
> +			fmt.Printf("error parsing url '%s': %s", *inputURLDecoded, err)
Frivolous log please remove.

2024-04-09 07:54 UTC, harshavardhana commented on api/public_objects.go
> +			fmt.Println("error copying response body:", err)
Another frivolous log

2024-04-09 07:54 UTC, harshavardhana commented on api/public_objects_test.go
> +package api
Missing copyright

2024-04-09 16:43 UTC, cesnietor commented on api/public_objects_test.go
> +package api
done

2024-04-09 16:43 UTC, cesnietor commented on api/public_objects.go
> +			fmt.Println("error copying response body:", err)
done

2024-04-10 04:23 UTC, prakashsvmx approved these changes
LGTM :+1:

2024-04-10 17:15 UTC, bexsoft approved these changes
LGTM

2024-04-10 17:16 UTC, merged