Add ILM rule tags generated by mc to getBucketLifecycle response
minio/console pull request #3369
Opened 2024-06-05 19:22 UTC by jinapurapu

Some ILM tags generated by mc are being presented differently from those in Console. This adds tags that are in this form to the tags to be displayed with the ILM rule in the editLifecycleConfiguration modal.

Closes https://github.com/minio/console/issues/3362

2024-06-05 20:22 UTC, ramondeklein requested changes

2024-06-05 20:22 UTC, ramondeklein commented on api/user_buckets_lifecycle.go
> +		if len(rule.RuleFilter.Tag.Key) > 0 {
I think this is more idiomatic Go:
```suggestion
		if rule.RuleFilter.Tag.Key != "" {
```

2024-06-05 21:32 UTC, ramondeklein approved these changes

2024-06-06 15:32 UTC, sen-io approved these changes

2024-06-06 22:22 UTC, merged