ws: Calculate the client IP from the WS request headers as well
minio/console pull request #3403
Opened 2024-07-09 16:15 UTC by vadmeste

Currently, the websocket code adds an IP to X-Forwarded-For where the IP is calculated
from the TCP connection established to Console, however the established TCP connection
can be coming from the load balancer as well, hence the necesssity to evaluate the client 
IP based on X-Forwarded-For or X-Real-IP headers

Look for client IPs in the websocket request connection.

2024-07-09 16:47 UTC, harshavardhana requested changes
no random logs please

2024-07-09 16:47 UTC, harshavardhana commented on api/ws_handle.go
> +		}
use conn.RemoteAddr().String() itself as is if the splitHostPort fails.

2024-07-09 17:50 UTC, vadmeste commented on api/ws_handle.go
> +		}
In fact, this would never happen in theory unless minio/websocket goes fairly crazy. It is better to keep logging this instead for easier debugging. I am using LogError() now.

2024-07-09 18:14 UTC, harshavardhana approved these changes

2024-07-10 14:31 UTC, ramondeklein approved these changes

2024-07-10 15:04 UTC, merged