Change KMSKeyInfo.CreatedAt to a time.Time
minio/console pull request #3421
Opened 2024-08-08 03:21 UTC by marktheunissen

2024-08-08 04:17 UTC, marktheunissen commented
Don't know why this JS build is failing in the CI...

2024-08-08 14:28 UTC, ramondeklein commented
We had the same failure in EOS console since yesterday, so looks like an external issue.

2024-08-08 16:34 UTC, cesnietor requested changes

2024-08-08 16:34 UTC, cesnietor commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
we can't send this change

2024-08-08 16:37 UTC, ramondeklein commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
I think there was a TODO before that this should be changed before merging. I guess it needs it for now, until https://github.com/minio/madmin-go/pull/296 is merged.

2024-08-08 16:49 UTC, cesnietor commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
yes, so blocking it so we don't merge it by mistake :D

2024-08-08 18:35 UTC, ramondeklein commented
This should fix the Javascript action: https://github.com/minio/console/pull/3423

2024-08-09 03:04 UTC, marktheunissen commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
It was intentional, just to run the tests in CI. Was planning on removing before merge, normally I leave a comment myself on the line as a reminder, will try do so in future always.

2024-08-16 00:16 UTC, cesnietor submitted a review, later dismissed

2024-08-16 00:16 UTC, marktheunissen commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
It has been replaced with the correct import version now

2024-08-16 00:20 UTC, cesnietor commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/marktheunissen/madmin-go/v3 v3.0.0-20240808031524-8a6ddcc05e14
thank you @marktheunissen

2024-08-16 00:29 UTC, marktheunissen commented
@cesnietor govet complained about `errorsApi.ServeError(w, req, errorsApi.New(http.StatusUnauthorized, err.Error()))` which was not something I touched in the PR.

I have just pushed a commit to change that to `errorsApi.ServeError(w, req, errorsApi.New(http.StatusUnauthorized, "%s", err.Error()))` which will probably fix the linting but ultimately doesn't do anything as the .New() call handled it fine before.

Another option is to change the linter configuration, let me know.

2024-08-16 09:25 UTC, ramondeklein commented
@marktheunissen We've seen this in more repositories. It looks like the most recent `golangci-lint` version is more strict. We have issued PRs for both [MinIO](https://github.com/minio/minio/pull/20263) and [mc](https://github.com/minio/mc/pull/5023) already. Note that this is in fact a proper warning that needs fixing.

2024-08-16 09:27 UTC, ramondeklein commented
> I have just pushed a commit to change that to `errorsApi.ServeError(w, req, errorsApi.New(http.StatusUnauthorized, "%s", err.Error()))` which will probably fix the linting, but ultimately doesn't do anything, as the .New() call handled it fine before.

I think it warns, because there could be some unexpected behavior when the error message contains formatting instructions, such as `%1000d` or some other extreme stuff. Not sure if it could cause a crash when `%s` is used without passing any arguments...

2024-08-16 11:09 UTC, harshavardhana commented
Please look at a more comprehensive update @marktheunissen at #3425

2024-08-20 00:48 UTC, marktheunissen commented
@ramondeklein I don't disagree.... :) generally speaking, the vetting is correct.

My comment was just about this specific case, where the function being called is `errorsApi.New()` which is:

```go
// New creates a new API error with a code and a message
func New(code int32, message string, args ...interface{}) Error {
	if len(args) > 0 {
		return &apiError{
			code:    code,
			message: fmt.Sprintf(message, args...),
		}
	}
	return &apiError{
		code:    code,
		message: message,
	}
}
```

My comment was " the .New() call handled it fine before.". What I meant is that passing 0 args bypasses the call to `fmt.Sprintf`, but the linter doesn't know that. Edge case I suppose

@harshavardhana has completed this work in the PR https://github.com/minio/console/pull/3425 so I'll close this, thanks!

2024-08-20 00:48 UTC, closed without merging