update deps to latest releases
minio/console pull request #3425
Opened 2024-08-16 11:01 UTC by harshavardhana

2024-08-16 11:11 UTC, harshavardhana commented on api/admin_kms.go
> +	printDate = "2006-01-02 15:04:05 MST"
keeping this here same as `mc ls` output - lets not use time.RFC3339 since is visibly verbose.

2024-08-16 11:53 UTC, ramondeklein requested changes

2024-08-16 11:53 UTC, ramondeklein commented on api/admin_kms.go
> +			CreatedAt: key.CreatedAt.Format(printDate),
Doesn't this conflict with https://github.com/minio/madmin-go/pull/296?

2024-08-16 22:59 UTC, harshavardhana commented on api/admin_kms.go
> +			CreatedAt: key.CreatedAt.Format(printDate),
conflict?

2024-08-17 16:37 UTC, ramondeklein approved these changes

2024-08-17 16:37 UTC, ramondeklein commented on api/admin_kms.go
> +			CreatedAt: key.CreatedAt.Format(printDate),
I guess I wasn't awake. We need to format it, because now it's a `time.Time` structure. Not sure what I was thinking...

2024-08-17 21:52 UTC, merged