Return network error when logging in and the network connection fails
minio/console pull request #3432
Opened 2024-09-03 02:57 UTC by marktheunissen

Displays "unable to login due to network error" to the user when a network error is encountered.

- Works with scenarios where the DNS does not resolve, or the port is closed or there is a timeout, etc. 
- We have InsecureSkipVerify set on the http.Client now, so certificate errors are no longer detected by our http client as errors.

@harshavardhana Up to you, I know MINIO_SERVER_URL is deprecated but it looks like people still use it and get into trouble with DNS. 

Fixes: https://github.com/minio/console/issues/3427

2024-09-03 06:37 UTC, harshavardhana commented
```
=== NAME  Test_PolicyListGroupsAPI
    policy_test.go:740: 
        	Error Trace:	/home/runner/work/console/console/integration/policy_test.go:740
        	Error:      	Not equal: 
        	            	expected: "[\"testgroup12345\"]\n"
        	            	actual  : "[\"testgroup12345\",\"testgroup12345\"]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-["testgroup12345"]
        	            	+["testgroup12345","testgroup12345"]
        	            	 
        	Test:       	Test_PolicyListGroupsAPI
=== RUN   Test_PolicyListGroupsAPI/List_Users_for_Policy_-_Invalid
--- FAIL: Test_PolicyListGroupsAPI (0.05s)
```

This looks like some duplicate groups are being listed @marktheunissen - needs a fix on the minio upstream side.

2024-09-05 06:47 UTC, marktheunissen commented
@harshavardhana I've tracked this error down to a specific location, this integration test is adding groups and then when getting them back, the duplicates are being introduced.

The group name `testgroup12345` is appended here: https://github.com/minio/minio/blob/master/cmd/iam-store.go#L995

And then the same group name `testgroup12345` is appended again here: https://github.com/minio/minio/blob/master/cmd/iam-store.go#L1005

The function was modified and no longer does `if store.getUsersSysType() == LDAPUsersSysType {` so I wonder if that would be the issue?

I can keep working on it but I thought you might be able to find the issue faster than me since it's the first time I've looked at this.

2024-09-06 01:46 UTC, marktheunissen commented
Made a simpler test that is easy to work with and reached out to a few people here: https://github.com/minio/minio/pull/20388/files

2024-09-09 01:33 UTC, marktheunissen commented on .github/workflows/vulncheck.yaml
> +          go-version: 1.22
Changing this to 1.22 instead of 1.22.7, as I think the rest of the build pipelines all use the latest go patch version... correct me if I'm wrong.

2024-09-16 09:43 UTC, ramondeklein commented on api/errors.go
> +				errorCode = 401
Shouldn't we report `503 Service Unavailable` instead?

2024-09-16 23:44 UTC, marktheunissen commented on api/errors.go
> +				errorCode = 401
Yep will change it

2024-09-17 08:57 UTC, ramondeklein submitted a review, later dismissed

2024-09-20 15:48 UTC, bexsoft commented on .github/workflows/vulncheck.yaml
> +          go-version: 1.22
Had to hardcode the version as github workflows sometimes keep old go versions and denies to upgrade by itself

2024-09-20 15:49 UTC, bexsoft requested changes
Pleasew review my comment

2024-09-20 15:55 UTC, merged