error handling in bucket creation ui
minio/console pull request #3455
Opened 2024-10-22 10:22 UTC by prakashsvmx

error handling in bucket creation ui

Fixes 2459 

Test cases
- Policy permissions
- MinIO not reachable

![image](https://github.com/user-attachments/assets/824aad27-280f-4311-a581-3ef338744d88)

e.g: Create a bucket with a pattern which does not allow the user to to create ( using iam policy)

2024-10-22 11:48 UTC, bayasdev requested changes

2024-10-22 11:48 UTC, bayasdev commented on web-app/src/screens/Console/Buckets/ListBuckets/AddBucket/addBucketsSlice.ts
> +  error: any;
@prakashsvmx does this have to be of type any?

2024-10-22 12:32 UTC, prakashsvmx commented on web-app/src/screens/Console/Buckets/ListBuckets/AddBucket/addBucketsSlice.ts
> +  error: any;
I think it is the same type in the other component and expects it that way.  i tried to use `ApiError` . 
let me double check .

2024-10-22 17:07 UTC, reivaj05 submitted a review, later dismissed

2024-10-23 04:12 UTC, prakashsvmx commented on web-app/src/screens/Console/Buckets/ListBuckets/AddBucket/addBucketsSlice.ts
> +  error: any;
i have updated the type. thank you for pointing this out.

2024-10-23 04:16 UTC, bayasdev approved these changes

2024-10-23 04:16 UTC, bayasdev commented on web-app/src/screens/Console/Buckets/ListBuckets/AddBucket/addBucketsSlice.ts
> +  error: any;
Thanks @prakashsvmx

2024-10-23 22:31 UTC, cesnietor approved these changes

2024-10-23 22:32 UTC, cesnietor commented
@prakashsvmx  could you please take a look at the failing tests, seem unrelated but all permission ones are failing

2024-10-24 07:31 UTC, prakashsvmx commented
@cesnietor  something broken in testcafe/chrome versions in CI. there is not release/update from testcafe. we need to wait for stable release. 

i tried with `rc` release  Ref: https://github.com/minio/console/pull/3457

I will investigate when there is a new release of testcafe.

2024-10-28 17:53 UTC, bexsoft approved these changes

2024-10-28 18:02 UTC, reivaj05 approved these changes

2024-10-28 18:16 UTC, merged