To enable spaces in policy names
minio/console pull request #3482
Opened 2024-12-02 22:06 UTC by cniackz

Since `mc` allows them:

```shell
mc admin policy create play "1Password IT" mypolicy.json
```

2024-12-02 22:14 UTC, cesnietor reviewed
@cniackz PTAL at the `validSave` cause the validation you changed checks while typing but during save we run a different logic and the same validation is there.
```
 const validSave =
    policyName.trim() !== "" &&
    policyName.indexOf(" ") === -1 &&
    policyDefinition.trim() !== "";
```

2024-12-03 09:45 UTC, ramondeklein commented
Shouldn't we change MinIO/STS instead, because policy names have the following limitation in AWS IAM ([source](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-names)):

> Names of users, groups, roles, policies, instance profiles, server certificates, and paths must be alphanumeric, including the following common characters: plus (+), equals (=), comma (,), period (.), at (@), underscore (_), and hyphen (-).

2024-12-03 14:42 UTC, cniackz commented
@cesnietor, you were right—additional changes were needed for this to work completely. I have made all the necessary adjustments and tested them.

<img width="1840" alt="Screenshot 2024-12-03 at 9 41 29 AM" src="https://github.com/user-attachments/assets/06959921-71a4-45fe-91be-951e75fa975b">

2024-12-03 14:43 UTC, cniackz commented
@ramondeklein, that’s a good question. Since this is already supported by mc, I’m unsure how to proceed. I’ve added @ramondeklein and @harshavardhana to help determine the best course of action.

2024-12-03 14:51 UTC, ramondeklein commented
It's hard to change now, because people may already use these names, so disallowing now is hard. We are S3 compatible, not IAM compatible, so deviating from AWS IAM isn't a real issue. Let's be practical and make sure we're compatible with our implementation.

2024-12-03 14:57 UTC, cniackz commented
Understood, @ramondeklein. I’ll leave this change up to you. Please approve and merge if you think it’s fine to proceed, or add any additional comments if you believe we shouldn’t or have a different perspective. Thanks!

2024-12-03 15:35 UTC, ramondeklein requested changes
I think it's bad to perform validations in the AIStor back-end. These checks should be done by MinIO itself.

2024-12-03 18:53 UTC, cesnietor commented on web-app/src/screens/Console/Policies/AddPolicyScreen.tsx
> +    if (policyName.trim() === "") {
this logic is so that we show it on the UI before submitting. Prevent them from even trying something that we know would fail. This one is ok. Just a basic check of not empties.

2024-12-03 19:59 UTC, cesnietor commented
@cniackz  I can't create a new policy the Save button never gets enabled

How it looks:
<img width="644" alt="Screenshot 2024-12-03 at 11 58 42 AM" src="https://github.com/user-attachments/assets/23eab943-9c35-4184-b106-a37c85ff795e">

How it should look when passing validations:
<img width="239" alt="Screenshot 2024-12-03 at 11 59 21 AM" src="https://github.com/user-attachments/assets/e2744475-1c71-4b4f-a4a8-166e3515345b">

2024-12-03 20:00 UTC, cesnietor reviewed
Also I noticed that we allow spaces after and before the policy, those I think we should remove.
<img width="268" alt="Screenshot 2024-12-03 at 11 57 10 AM" src="https://github.com/user-attachments/assets/868da6cb-0bf5-439f-aa66-74ea06306c8c">


I couldn't test if those are saved like that or we actually trimmed  (due to the error above) them but worth considering. If we trim them after submitting then is fine.

2024-12-04 06:11 UTC, cniackz commented
Why it does not work for you?... I need time to figure this out as it worked for me, we can synch on this later 👍

2024-12-04 15:01 UTC, cniackz commented
@cesnietor, I’m still unsure why it’s not working for you. I retested everything from scratch and was able to create the policy with spaces in the name. Here’s the screenshot:

<img width="1840" alt="Screenshot 2024-12-04 at 10 00 14 AM" src="https://github.com/user-attachments/assets/2aa91c17-db08-4c5f-86f5-0a57eddba207">

Would you mind pairing up this afternoon to look into this together? The steps I used for testing are documented in this wiki: [How to test console UI](https://github.com/cniackz/public/wiki/How-to-test-console-UI).

2024-12-04 21:38 UTC, cesnietor submitted a review, later dismissed

2024-12-04 21:38 UTC, cesnietor commented
tested works as expected.

2024-12-05 00:15 UTC, bexsoft approved these changes
LGTM

2024-12-05 00:17 UTC, bexsoft submitted a review, later dismissed
Can you please help us to review 

```
policy_test.go:237: 
        	Error Trace:	/home/runner/work/console/console/integration/policy_test.go:237
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 201
        	Test:       	Test_AddPolicyAPI
        	Messages:   	Create Policy - Space in Name Failed
```

Seems like this test should be reworked, beside of that LGTM. Thank you very much

2024-12-05 01:04 UTC, cniackz commented
Sure Benjamin, let look into that test deeper

2024-12-05 13:14 UTC, cniackz commented
The issue at `policy_test.go:237` comes from the [Integration Tests with Latest Distributed MinIO (1.23.x)](https://github.com/minio/console/actions/runs/12162522384/job/33919803994?pr=3482#logs)

<img width="1840" alt="Screenshot 2024-12-05 at 8 13 07 AM" src="https://github.com/user-attachments/assets/6dfd0114-6b19-408d-b76f-9a64421c60bf">

I will re-run this test to ensure the failure is replicable. Simultaneously, I will create an empty PR to verify if the failure was introduced in this PR.

2024-12-05 13:15 UTC, cniackz commented
Haha, well, it’s obvious just by looking at the log:

```
=== NAME  Test_AddPolicyAPI
    policy_test.go:237: 
        	Error Trace:	/home/runner/work/console/console/integration/policy_test.go:237
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 201
        	Test:       	Test_AddPolicyAPI
        	Messages:   	Create Policy - Space in Name Failed
```

2024-12-05 13:23 UTC, cniackz commented on web-app/src/screens/Console/Policies/AddPolicyScreen.tsx
> +    if (policyName.trim() === "") {
Thank you, @ramondeklein! I implemented your request, and it works perfectly.

2024-12-05 13:24 UTC, cniackz commented
Now waiting for the tests to complete. If everything passes, I’ll request another round of reviews to finalize this.

2024-12-05 13:48 UTC, cniackz commented
Ok, @cesnietor and I have reviewed this test, and the failure is unrelated. Therefore, this PR is now ready for review:

<img width="1840" alt="Screenshot 2024-12-05 at 8 48 11 AM" src="https://github.com/user-attachments/assets/badfcbb9-dd0d-445e-8ea9-17ec8a1c52c6">

2024-12-05 15:26 UTC, ramondeklein approved these changes

2024-12-05 17:55 UTC, cesnietor approved these changes

2024-12-05 17:55 UTC, merged