Release v1.7.5
minio/console pull request #3484
Opened 2024-12-06 21:58 UTC by bexsoft

2024-12-06 21:59 UTC, bayasdev requested changes

2024-12-06 21:59 UTC, bayasdev commented on CHANGELOG.md
> +- Allow spaced in Policy names
```suggestion
- Allow spaces in Policy names
```

2024-12-06 23:47 UTC, cesnietor approved these changes

2024-12-06 23:47 UTC, cesnietor commented on CHANGELOG.md
> +- Allow spaced in Policy names
done @bayasdev

2024-12-06 23:48 UTC, bayasdev approved these changes

2024-12-06 23:49 UTC, cesnietor approved these changes

2024-12-07 00:22 UTC, bayasdev commented
@bexsoft could you PTAL at the failed test? Thank you!

2024-12-07 00:31 UTC, bexsoft commented
> @bexsoft could you PTAL at the failed test? Thank you!

This is not a real failure, if you test manually te test case passes, this is something related to testcafe & github workflows.

2024-12-07 00:41 UTC, cniackz approved these changes

2024-12-07 00:42 UTC, merged