SNI support for Console
minio/console pull request #352
Opened 2020-10-28 06:04 UTC by Alevsk

2020-10-28 12:46 UTC, aead commented on pkg/certs/certs.go
> +	GlobalContext = context.Background()
Why is `GlobalContext` a package variable if we (re)set it here to `context.Background()`

2020-10-28 18:34 UTC, harshavardhana commented on pkg/certs/certs.go
> +	GlobalContext = context.Background()
yeah we can't do it like this, this looks rather scary.

2020-10-28 18:37 UTC, harshavardhana requested changes

2020-10-28 18:37 UTC, harshavardhana commented on pkg/certs/certs.go
> +var GlobalContext context.Context
```suggestion
var GlobalContext context.Context
```

This should be initialized

```
// GlobalContext context that is canceled when the server is requested to shut down.
var GlobalContext context.Context

// cancelGlobalContext can be used to indicate server shutdown.
var cancelGlobalContext context.CancelFunc

// Initialize service mutex once.
func init() {
        initGlobalContext()
}

func initGlobalContext() {
        GlobalContext, cancelGlobalContext = context.WithCancel(context.Background())
        GlobalServiceDoneCh = GlobalContext.Done()
}
```

2020-10-28 18:49 UTC, Alevsk commented on pkg/certs/certs.go
> +	GlobalContext = context.Background()
right, talked with harsha, removed globalContext since console doesnt support that yet, im using just `context.Background()` instead

2020-10-28 18:49 UTC, Alevsk commented on pkg/certs/certs.go
> +var GlobalContext context.Context
removed globalContext since console doesnt support that yet, im using just context.Background() instead

2020-10-28 19:17 UTC, harshavardhana submitted a review, later dismissed

2020-10-28 19:17 UTC, harshavardhana commented on README.md
> +```$xslt
```suggestion
```bash
```

2020-10-28 19:17 UTC, harshavardhana commented on README.md
> +```$xslt
```suggestion
```
```

2020-10-28 19:17 UTC, harshavardhana commented on restapi/consts.go
> +	ConsoleVersion        = `0.1.0`
A breaking change so perhaps 

```suggestion
	ConsoleVersion        = `0.2.0`
```

2020-10-29 12:05 UTC, aead approved these changes

2020-10-29 17:38 UTC, dvaldivia approved these changes

2020-10-30 05:26 UTC, merged