Build assets inside the container
minio/console pull request #357
Opened 2020-10-28 23:15 UTC by dvaldivia

This makes it so the dockerfile builds the assets inside of it before compiling the final version of the container.

Also addresses #183

2020-10-29 02:21 UTC, Alevsk approved these changes

2020-10-30 04:57 UTC, bexsoft requested changes
Please review an issue related with. seems like a socket is failing, I tried to re-execute flow and it didn't work
```
2020/10/29 16:35:44 error unexpected CloseError on ReadMessage: websocket: close 1006 (abnormal closure)
2020/10/29 16:35:44 error on ReadMessage: error
2020/10/29 16:35:44 closed conn.ReadMessage: websocket: close 1001 (going away)
--- PASS: TestWSHandle (0.00s)
FAIL
FAIL	github.com/minio/console/restapi	12.961s
?   	github.com/minio/console/restapi/operations	[no test files]
?   	github.com/minio/console/restapi/operations/admin_api	[no test files]
?   	github.com/minio/console/restapi/operations/user_api	[no test files]
FAIL
Makefile:53: recipe for target 'test' failed
make: *** [test] Error 1
Error: Process completed with exit code 2.```

2020-10-30 05:27 UTC, dvaldivia commented
@bexsoft the strange thing is that I didn't change code D: only updated the Go version

2020-10-30 17:27 UTC, Alevsk submitted a review, later dismissed

2020-10-30 17:38 UTC, bexsoft submitted a review, later dismissed

2020-10-31 07:45 UTC, Alevsk submitted a review, later dismissed

2020-10-31 07:49 UTC, harshavardhana approved these changes

2020-10-31 07:50 UTC, harshavardhana requested changes

2020-10-31 07:50 UTC, harshavardhana commented on .goreleaser.yml
> +    dockerfile: d
is this correct? @dvaldivia

2020-11-01 03:40 UTC, dvaldivia commented on .goreleaser.yml
> +    dockerfile: d
nein, that looks like an ugly mistake

2020-11-01 03:41 UTC, dvaldivia commented on .goreleaser.yml
> +    dockerfile: d
fixed

2020-11-01 04:49 UTC, Alevsk approved these changes

2020-11-01 15:33 UTC, harshavardhana approved these changes

2020-11-01 15:34 UTC, merged