Add support for multiple form switch indicator labels & adjust styling
minio/console pull request #381
Opened 2020-11-10 21:35 UTC by kaankabalak

Previously, only a single label was being displayed regardless of the
checked status of a switch.

This commit also adjusts form switch styling based on mockups, such as
greying out the switch track color when switch is not checked

<img width="794" alt="Screen Shot 2020-11-10 at 1 34 22 PM" src="https://user-images.githubusercontent.com/27314853/98736328-84159300-2359-11eb-9cf8-a67909be7cfd.png">

2020-11-11 01:51 UTC, dvaldivia submitted a review, later dismissed

2020-11-11 02:26 UTC, bexsoft requested changes

2020-11-11 02:26 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
I think colors must be inverse as in design:

<img width="688" alt="Screen Shot 2020-11-10 at 8 22 37 PM" src="https://user-images.githubusercontent.com/33497058/98757660-a4ae0f00-2392-11eb-804e-51124f49e2b0.png">
<img width="561" alt="Screen Shot 2020-11-10 at 8 22 30 PM" src="https://user-images.githubusercontent.com/33497058/98757663-a5df3c00-2392-11eb-82b8-c9c2769bdeb7.png">

2020-11-11 05:01 UTC, kaankabalak commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
Will do @bexsoft 👍

2020-11-12 23:28 UTC, Alevsk approved these changes

2020-11-19 19:55 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
![image](https://user-images.githubusercontent.com/18384552/99717277-1276cc80-2a5e-11eb-975f-5226a9b995a1.png)

2020-11-19 19:56 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
<img width="114" alt="Screen Shot 2020-11-19 at 11 55 53 AM" src="https://user-images.githubusercontent.com/18384552/99717379-2de1d780-2a5e-11eb-9fa0-ffb64775eae5.png">
I think how we have them right now makes sense, only the highlight color is off

2020-11-19 19:58 UTC, dvaldivia commented
The changes are already merged

2020-11-19 19:58 UTC, closed without merging

2020-11-19 21:59 UTC, kaankabalak commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
@dvaldivia, I have just rebased the branch, however, could you elaborate on what the highlight color should be please?

2020-11-19 22:02 UTC, dvaldivia commented on portal-ui/src/screens/Console/Common/FormComponents/FormSwitchWrapper/FormSwitchWrapper.tsx
> +    backgroundColor: "#9C9C9C",
I think you have the right color in general, what we have in the design looks slightly counter intuitive to what we see in the design, after rebasing the branch, this PR shows there's 0 changes, so I assume the changes are already merged via other branches