Add set policy to multiple user/groups
minio/console pull request #382
Opened 2020-11-10 23:42 UTC by cesnietor

Added api that allow setting policy to multiple users and/or groups.
PUT api on `/api/v1/set-policy-multi/<policy_name>`

Request payload response e.g.:
```
{
    "users": ["user1"],
    "groups": ["newgroup1"]
}
```

users and groups can be empty.

- [X] Tests included

2020-11-11 01:57 UTC, dvaldivia requested changes

2020-11-11 01:57 UTC, dvaldivia commented on restapi/admin_policies.go
> +		if err := client.setPolicy(ctx, policyName, user, false); err != nil {
if there's an error because a single user is wrong we'll go into a bad state wouldn't we, we some users were applied the policy and the rest was not due to one incorrect user in the middle of the list, why dont we add a validation for users and groups before we apply the policies?

2020-11-11 02:59 UTC, cesnietor commented on restapi/admin_policies.go
> +		if err := client.setPolicy(ctx, policyName, user, false); err != nil {
yes, there's currently no way to make this 100% atomic.

2020-11-12 18:29 UTC, dvaldivia commented on restapi/admin_policies.go
> +		if err := client.setPolicy(ctx, policyName, user, false); err != nil {
it's ok if it's not atomic, but we should at least make sure all the users and groups are valid before we start applying the policy

2020-11-19 18:45 UTC, dvaldivia commented on restapi/admin_policies.go
> +		if err := client.setPolicy(ctx, policyName, user, false); err != nil {
@cesnietor

2020-11-20 18:58 UTC, cesnietor commented on restapi/admin_policies.go
> +		if err := client.setPolicy(ctx, policyName, user, false); err != nil {
I've updated to validate on request the user/group string based on a regex defined on aws restrictions.
```
User names can be a combination of up to 64 letters, digits, and these characters: plus (+), equal (=), comma (,), period (.), at sign (@), underscore (_), and hyphen (-). 
```

2020-11-20 19:08 UTC, Alevsk approved these changes

2020-11-30 20:33 UTC, bexsoft approved these changes

2020-11-30 23:23 UTC, merged