Connected Object details page to navigation
minio/console pull request #394
Opened 2020-11-15 05:05 UTC by bexsoft

## What does this do?

Connected Object details page to navigation schema. Also connected file details view with backend

**NOTE:** There is a known issue on clicking back button / hot reload where information is not loaded on screen. Will adress this in the next PR

2020-11-16 19:31 UTC, dvaldivia commented on pkg/acl/endpoints_test.go
> +			want: 20,
```suggestion
			want: 18,
```

2020-11-16 19:31 UTC, dvaldivia commented on pkg/acl/endpoints_test.go
> +			want: 17,
```suggestion
			want: 15,
```

2020-11-16 19:37 UTC, dvaldivia reviewed
This will fix testrs

2020-11-16 20:02 UTC, dvaldivia approved these changes

2020-11-16 20:42 UTC, Alevsk requested changes

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    // ];
please delete this commented code

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
> +  }, [match]);
is this need it?

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
> +      console.log("asdf");
please delete this

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetRetention.tsx
> +    console.log("on submit");
please delete this

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
> +            ))} */}
please delete this

2020-11-16 20:42 UTC, Alevsk commented on portal-ui/src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
> +            ))} */}
please delete this

2020-11-17 18:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
> +            ))} */}
This is going to be needed for next step of date selector

2020-11-17 18:53 UTC, bexsoft commented on portal-ui/src/screens/Console/Common/FormComponents/DateSelector/DateSelector.tsx
> +            ))} */}
This is going to be needed for next step of date selector

2020-11-17 18:53 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
> +  }, [match]);
No, we don't need it anymore

2020-11-17 18:53 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +    // ];
done

2020-11-17 18:54 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ObjectRouting.tsx
> +      console.log("asdf");
done

2020-11-17 19:00 UTC, Alevsk approved these changes

2020-11-17 19:59 UTC, kaankabalak approved these changes

2020-11-17 20:03 UTC, cesnietor commented
tested LGTM

2020-11-17 21:03 UTC, merged