Connected object tags API
minio/console pull request #421
Opened 2020-11-19 19:21 UTC by bexsoft

## What does this do?

Connects object tags API to object details screen.

**NOTE:** There is a small delay between tag changes after saving any modification, will fix this after adding loaders to object details page.

## How does it look?

<img width="1801" alt="Screen Shot 2020-11-19 at 13 16 26" src="https://user-images.githubusercontent.com/33497058/99713499-03961700-2a6a-11eb-939c-7708b9175100.png">
<img width="1795" alt="Screen Shot 2020-11-19 at 13 16 15" src="https://user-images.githubusercontent.com/33497058/99713508-06910780-2a6a-11eb-8296-571c36b12fab.png">
<img width="1797" alt="Screen Shot 2020-11-19 at 13 16 07" src="https://user-images.githubusercontent.com/33497058/99713513-07c23480-2a6a-11eb-99e8-7b53184328e5.png">
<img width="1796" alt="Screen Shot 2020-11-19 at 13 15 58" src="https://user-images.githubusercontent.com/33497058/99713515-08f36180-2a6a-11eb-9c20-a83d28d068d9.png">

2020-11-19 19:21 UTC, dvaldivia submitted a review, later dismissed

2020-11-19 21:22 UTC, cesnietor requested changes
I saw that we set the same value on `key` and `value` but minio allows them to be different, so if the object has tags already set by mc we would show only one value:
```
mc tag list s3/testbucket/testobject
Name                :    testobject
editable            :    only-by-owner-and-authenticated
confidentiality     :    open-to-authenticated-only
```
we might need to change to show/set both key and values.

2020-11-19 21:59 UTC, dvaldivia commented
@cesnietor would showing that need some changes to the UI?

2020-11-19 22:50 UTC, cesnietor commented
> @cesnietor would showing that need some changes to the UI?

yes probably a redesign or do a `key:value` on tag itself.

2020-11-19 23:14 UTC, bexsoft commented
But in this case what would be the purpose of showing the key too?, wouldn't it be better to make the labels as string arrays? I think people would be used to look for complete phrases rather than key values

2020-11-19 23:18 UTC, cesnietor commented
> But in this case what would be the purpose of showing the key too?, wouldn't it be better to make the labels as string arrays? I think people would be used to look for complete phrases rather than key values

yes, I agree, but since we mirror mc's behavior we need to do an equivalent thing.  Also it is an AWS thing https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html

2020-11-20 01:01 UTC, bexsoft commented
> I saw that we set the same value on `key` and `value` but minio allows them to be different, so if the object has tags already set by mc we would show only one value:
> 
> ```
> mc tag list s3/testbucket/testobject
> Name                :    testobject
> editable            :    only-by-owner-and-authenticated
> confidentiality     :    open-to-authenticated-only
> ```
> 
> we might need to change to show/set both key and values.

Added changed to be S3 Compliant:

<img width="1087" alt="Screen Shot 2020-11-19 at 19 00 11" src="https://user-images.githubusercontent.com/33497058/99742658-94381b80-2a99-11eb-88e6-5c54a55a4d5e.png">
<img width="1303" alt="Screen Shot 2020-11-19 at 19 00 03" src="https://user-images.githubusercontent.com/33497058/99742661-9601df00-2a99-11eb-87f1-a20ca3f91ba4.png">
<img width="1167" alt="Screen Shot 2020-11-19 at 18 59 56" src="https://user-images.githubusercontent.com/33497058/99742662-969a7580-2a99-11eb-8af7-a20bb2d5d34b.png">
<img width="1437" alt="Screen Shot 2020-11-19 at 18 59 43" src="https://user-images.githubusercontent.com/33497058/99742664-97330c00-2a99-11eb-97ce-24f76dde4600.png">

2020-11-20 02:54 UTC, cesnietor approved these changes
tested LGTM

2020-11-20 04:36 UTC, kaankabalak approved these changes

2020-11-20 05:30 UTC, merged