Add Dockerfile based on Red Hat UBI
minio/console pull request #453
Opened 2020-11-27 14:20 UTC by nitisht

2020-11-30 17:32 UTC, harshavardhana approved these changes

2020-11-30 17:33 UTC, harshavardhana requested changes

2020-11-30 17:33 UTC, harshavardhana commented on Dockerfile.release.ubi
> +
We don't need this @nitisht `microdnf install ca-certificates` is enough at single layer

2020-12-01 10:20 UTC, nitisht commented on Dockerfile.release.ubi
> +
done

2020-12-02 23:50 UTC, cesnietor approved these changes

2020-12-03 02:17 UTC, bexsoft approved these changes

2020-12-03 07:34 UTC, nitisht commented
Can we merge this pls?

2020-12-03 08:54 UTC, harshavardhana approved these changes

2020-12-03 08:54 UTC, merged