Password endpoint
minio/console pull request #457
Opened 2020-12-01 18:47 UTC by Alevsk

2020-12-03 02:26 UTC, bexsoft requested changes
Please run `gofmt -w restapi/user_account.go`

2020-12-03 02:28 UTC, bexsoft requested changes

2020-12-03 02:28 UTC, bexsoft commented on portal-ui/src/screens/Console/ServiceAccounts/ServiceAccounts.tsx
>    containerForHeader,
Please rename this file as Accounts as it will no longer be only for ServiceAccounts

2020-12-03 07:56 UTC, Alevsk commented on portal-ui/src/screens/Console/ServiceAccounts/ServiceAccounts.tsx
>    containerForHeader,
done

2020-12-04 01:10 UTC, cesnietor requested changes

2020-12-04 01:10 UTC, cesnietor commented on restapi/user_account.go
> +func getChangePasswordResponse(session *models.Principal, params user_api.AccountChangePasswordParams) (*models.LoginResponse, *models.Error) {
could you please make getChangePasswordResponse just a dummy function that creates the client and calls the main function? And then add tests on that function?

2020-12-04 21:59 UTC, Alevsk commented on restapi/user_account.go
> +func getChangePasswordResponse(session *models.Principal, params user_api.AccountChangePasswordParams) (*models.LoginResponse, *models.Error) {
`changePassword` is the main function, ill add test to that and also to `getConsoleCredentials`

2020-12-07 17:47 UTC, dvaldivia commented
I think that because there's no easy way to recover a mis-typed password, you should add a field to `type new password again` which makes sure both passwords are valid.

2020-12-07 19:13 UTC, Alevsk commented
> I think that because there's no easy way to recover a mis-typed password, you should add a field to `type new password again` which makes sure both passwords are valid.

Good idea, i knew the password form look weird, ill add the new field

2020-12-07 19:22 UTC, Alevsk commented
> I think that because there's no easy way to recover a mis-typed password, you should add a field to `type new password again` which makes sure both passwords are valid.

done

2020-12-07 19:27 UTC, cesnietor requested changes

2020-12-07 19:27 UTC, cesnietor commented on portal-ui/src/screens/Console/Account/ChangePasswordModal.tsx
> +      setError("New Passwords doesn't match");
```suggestion
      setError("New passwords don't match");
```

2020-12-07 19:29 UTC, dvaldivia submitted a review, later dismissed

2020-12-07 20:08 UTC, cesnietor approved these changes
tested LGTM

2020-12-07 21:13 UTC, cesnietor approved these changes

2020-12-07 21:37 UTC, bexsoft approved these changes

2020-12-07 21:59 UTC, dvaldivia approved these changes

2020-12-07 23:11 UTC, merged