Update console to use latest operator
minio/console pull request #476
Opened 2020-12-05 00:59 UTC by cesnietor

Main changes Rename everything from Zone->Pool

Test Notes:
Please test a tenant is deployed correctly with Pools defined
Also add zone
Delete tenant

and make sure everything was renamed correctly (no typos)

2020-12-05 01:42 UTC, harshavardhana approved these changes

2020-12-06 21:29 UTC, harshavardhana submitted a review, later dismissed

2020-12-07 02:12 UTC, bexsoft commented on pkg/utils/parity.go
> +// multiple poolss, ensuring that parities returned are common
Please fix typo

2020-12-07 02:35 UTC, bexsoft requested changes
I couldn't be able to create a new tenant, the following error was thrown in log:

<img width="1010" alt="Screen Shot 2020-12-06 at 20 26 07" src="https://user-images.githubusercontent.com/33497058/101302825-41cd5d80-3802-11eb-93d2-ae825e4220d0.png">

I'm using operator@3.0.29, Do we need an special version of operator?

2020-12-07 02:37 UTC, harshavardhana commented
> I couldn't be able to create a new tenant, the following error was thrown in log:
> 
> <img alt="Screen Shot 2020-12-06 at 20 26 07" width="1010" src="https://user-images.githubusercontent.com/33497058/101302825-41cd5d80-3802-11eb-93d2-ae825e4220d0.png">
> 
> I'm using operator@3.0.29, Do we need an special version of operator?

You need to use latest operator from master @bexsoft

2020-12-07 02:42 UTC, cesnietor commented on pkg/utils/parity.go
> +// multiple poolss, ensuring that parities returned are common
done

2020-12-07 03:16 UTC, harshavardhana approved these changes

2020-12-07 15:06 UTC, Alevsk approved these changes
LGTM

2020-12-07 15:40 UTC, bexsoft approved these changes
LGTM

2020-12-07 15:49 UTC, merged