First set of changes for settings pages new design
minio/console pull request #493
Opened 2020-12-09 02:06 UTC by bexsoft

## What does this do?

Implements the first page for new settings page design.

## How does it look?

<img width="1678" alt="Screen Shot 2020-12-08 at 19 58 24" src="https://user-images.githubusercontent.com/33497058/101564430-cb129a80-3990-11eb-9138-165e24dd6d3e.png">
<img width="1664" alt="Screen Shot 2020-12-08 at 19 58 08" src="https://user-images.githubusercontent.com/33497058/101564437-ccdc5e00-3990-11eb-8715-aaa7dbe480bd.png">
<img width="1682" alt="Screen Shot 2020-12-08 at 19 58 00" src="https://user-images.githubusercontent.com/33497058/101564438-ce0d8b00-3990-11eb-940b-fa9b6faa8d40.png">

2020-12-09 17:57 UTC, Alevsk requested changes

2020-12-09 17:57 UTC, Alevsk commented on portal-ui/src/screens/Console/Configurations/ConfigurationPanels/ConfigurationsList.tsx
> +          //setEditScreenOpen(true);
can this be deleted?

2020-12-09 18:04 UTC, cesnietor commented
Works fine I just saw that it is alligned a little bit lower than other pages.
<img width="643" alt="Screen Shot 2020-12-09 at 12 02 00 PM" src="https://user-images.githubusercontent.com/11819101/101668762-92b59f80-3a16-11eb-9ad5-2a5bcf215c91.png">
<img width="485" alt="Screen Shot 2020-12-09 at 12 02 08 PM" src="https://user-images.githubusercontent.com/11819101/101668756-90534580-3a16-11eb-8716-2176b2f2b7ac.png">

2020-12-09 19:30 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/ConfigurationPanels/ConfigurationsList.tsx
> +          //setEditScreenOpen(true);
done

2020-12-09 19:32 UTC, bexsoft commented
> Works fine I just saw that it is aligned a little bit lower than other pages.
> <img alt="Screen Shot 2020-12-09 at 12 02 00 PM" width="643" src="https://user-images.githubusercontent.com/11819101/101668762-92b59f80-3a16-11eb-9ad5-2a5bcf215c91.png">
> <img alt="Screen Shot 2020-12-09 at 12 02 08 PM" width="485" src="https://user-images.githubusercontent.com/11819101/101668756-90534580-3a16-11eb-8716-2176b2f2b7ac.png">

Let me check, what browser are you using? I see these titles aligned:

<img width="1639" alt="Screen Shot 2020-12-09 at 13 30 52" src="https://user-images.githubusercontent.com/33497058/101677991-eded8f00-3a22-11eb-9d61-e94c1d0640bc.png">
<img width="1642" alt="Screen Shot 2020-12-09 at 13 30 45" src="https://user-images.githubusercontent.com/33497058/101677995-f04fe900-3a22-11eb-849c-64921fff69db.png">

2020-12-09 19:40 UTC, cesnietor commented
@bexsoft  works fine, I had to make the assets

2020-12-09 19:40 UTC, cesnietor submitted a review, later dismissed

2020-12-09 22:24 UTC, Alevsk approved these changes
LGTM

2020-12-10 01:47 UTC, dvaldivia approved these changes

2020-12-10 03:15 UTC, Alevsk approved these changes

2020-12-10 04:06 UTC, merged