[WIP] Subnet integration
minio/console pull request #518
Opened 2020-12-15 17:00 UTC by Alevsk

2020-12-18 19:58 UTC, cesnietor reviewed
Some comments added. 
Other question: How do we allow the trial version?

2020-12-18 19:58 UTC, cesnietor commented on restapi/admin_subscription.go
> +	//defer cancel()
can you remove this.

2020-12-18 19:58 UTC, cesnietor commented on pkg/subnet/config.go
> +// Copyright (c) 2019 MinIO, Inc.
```suggestion
// Copyright (c) 2020 MinIO, Inc.
```

Please check in other files

2020-12-18 19:58 UTC, cesnietor commented on portal-ui/src/screens/Console/License/ActivationModal.tsx
> +              Subscription Network
In here I would suggest mentioning this are Subnet's credentials either with a tooltip or instead of Subscription Network something like `Subscription Network (SUBNET)`

2020-12-18 22:05 UTC, cesnietor commented
If the errors are informative we should return them as well :
for instance `original error: license is not present` shows:
<img width="547" alt="Screen Shot 2020-12-18 at 4 04 04 PM" src="https://user-images.githubusercontent.com/11819101/102665638-cac18e80-414a-11eb-948f-ce06e0a7f768.png">

2020-12-22 06:17 UTC, Alevsk commented
> If the errors are informative we should return them as well :
> for instance `original error: license is not present` shows:
> <img alt="Screen Shot 2020-12-18 at 4 04 04 PM" width="547" src="https://user-images.githubusercontent.com/11819101/102665638-cac18e80-414a-11eb-948f-ce06e0a7f768.png">

<img width="791" alt="Screen Shot 2020-12-22 at 00 16 54" src="https://user-images.githubusercontent.com/1795553/102855866-0da19180-43eb-11eb-97f3-8822e4f98fce.png">
<img width="783" alt="Screen Shot 2020-12-22 at 00 16 42" src="https://user-images.githubusercontent.com/1795553/102855871-1003eb80-43eb-11eb-8ba4-d11622f86757.png">

Added validation so the buttons are disabled if the input fields are empty

2020-12-23 05:01 UTC, bexsoft requested changes

2021-01-04 16:24 UTC, bexsoft approved these changes
LGTM

2021-01-04 22:32 UTC, dvaldivia requested changes

2021-01-04 22:32 UTC, dvaldivia commented on pkg/subnet/config_test.go
> +	license := "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZW5pbitjMUBtaW5pby5pbyIsInRlYW1OYW1lIjoiY29uc29sZS1jdXN0b21lciIsImV4cCI6MS42Mzk5NTI2MTE2MDkxNDQ3MzJlOSwiaXNzIjoic3VibmV0QG1pbmlvLmlvIiwiY
🙈

2021-01-04 22:32 UTC, dvaldivia commented on portal-ui/src/screens/Console/Groups/DeleteGroup.tsx
> +// Copyright (c) 2020 MinIO, Inc.
if you are mass replacing files with this, perhaps let's go to `2021` xD

2021-01-05 17:55 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/DeleteGroup.tsx
> +// Copyright (c) 2020 MinIO, Inc.
I think this change must be done after we merge log search & prometheus functionality to avoid multiple merge conflicts

2021-01-11 17:10 UTC, Alevsk commented on pkg/subnet/config_test.go
> +	license := "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZW5pbitjMUBtaW5pby5pbyIsInRlYW1OYW1lIjoiY29uc29sZS1jdXN0b21lciIsImV4cCI6MS42Mzk5NTI2MTE2MDkxNDQ3MzJlOSwiaXNzIjoic3VibmV0QG1pbmlvLmlvIiwiY
this is a license verification token from testing environment, will not work on production environment

2021-01-11 17:11 UTC, Alevsk commented on portal-ui/src/screens/Console/Groups/DeleteGroup.tsx
> +// Copyright (c) 2020 MinIO, Inc.
2021 all the things!

2021-01-11 19:00 UTC, dvaldivia approved these changes

2021-01-11 19:54 UTC, dvaldivia approved these changes

2021-01-11 22:36 UTC, dvaldivia approved these changes

2021-01-12 05:39 UTC, bexsoft approved these changes
LGTM

2021-01-12 21:55 UTC, merged