Log Search API integration
minio/console pull request #525
Opened 2020-12-17 19:12 UTC by dvaldivia

introduces the API for log search

2020-12-17 19:29 UTC, cesnietor requested changes

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +			return user_api.NewSessionCheckDefault(int(err.Code)).WithPayload(err)
wrong function

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +func getLogSearchResponse(params user_api.LogSearchParams) (*models.LogSearchResponse, *models.Error) {
please split the function as we have it in all other files, Response functions only should create clients and call function to be tested.

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +	endpoint = fmt.Sprintf("%s&%s=ok", endpoint, *params.Order)
params.Order can be nil.

2020-12-17 19:29 UTC, cesnietor commented on swagger.yml
> +          enum: [ reqinfo,raw ]
you can do a definition so that it creates a struct, to avoid comparing against raw string "reqinfo".

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +	endpoint = fmt.Sprintf("%s&pageNo=%d", endpoint, *params.PageNo)
PageSize and PageNo can be nil

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +			}
no need to do this you can use prepareError(err), also it will be log automatically, no need to log.

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +			}
no need to log, use prepareError(err)

2020-12-17 19:29 UTC, cesnietor commented on restapi/user_log_search.go
> +	}
use prepareError(err)

2020-12-17 19:29 UTC, cesnietor commented on swagger.yml
> +            type: string
what is fp and q? please add Description

2020-12-17 20:09 UTC, Alevsk submitted a review, later dismissed

2020-12-18 01:39 UTC, bexsoft requested changes
Please verify lint issues:

```
level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1001: failed prerequisites: [(inspect@github.com/minio/console/restapi/operations/user_api, isgenerated@github.com/minio/console/restapi/operations/user_api): analysis skipped: errors in package: [/home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:45:18: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:55:51: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:61:50: LogSearchResponse not declared by package models]]"
level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:45:18: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:55:51: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:61:50: LogSearchResponse not declared by package models]"
Makefile:37: recipe for target 'lint' failed
level=error msg="Running error: buildir: analysis skipped: errors in package: [/home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:45:18: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:55:51: LogSearchResponse not declared by package models /home/runner/work/console/console/restapi/operations/user_api/log_search_responses.go:61:50: LogSearchResponse not declared by package models]"```

2020-12-28 18:35 UTC, harshavardhana approved these changes

2021-01-11 18:43 UTC, bexsoft commented on restapi/consts.go
> +	LogSearchQueryAuthToken                      = "LOGSEARCH_QUERY_AUTH_TOKEN"
Fixed

2021-01-11 20:43 UTC, bexsoft commented on restapi/user_log_search.go
> +	}
done

2021-01-11 20:43 UTC, bexsoft commented on restapi/user_log_search.go
> +			}
done

2021-01-11 20:44 UTC, bexsoft commented on restapi/user_log_search.go
> +			}
done

2021-01-11 20:45 UTC, bexsoft commented on restapi/user_log_search.go
> +	endpoint = fmt.Sprintf("%s&%s=ok", endpoint, *params.Order)
In this case we are sending default values in swagger, so order cannot be null. We require default values as we have lazy load pagination with multiple requests implemented

2021-01-11 20:45 UTC, bexsoft commented on restapi/user_log_search.go
> +	endpoint = fmt.Sprintf("%s&pageNo=%d", endpoint, *params.PageNo)
Same case as Order

2021-01-11 20:49 UTC, harshavardhana commented
When is the plan to merge this? @dvaldivia

2021-01-11 21:16 UTC, bexsoft commented on restapi/user_log_search.go
> +			return user_api.NewSessionCheckDefault(int(err.Code)).WithPayload(err)
fixed

2021-01-12 04:23 UTC, bexsoft commented on restapi/user_log_search.go
> +func getLogSearchResponse(params user_api.LogSearchParams) (*models.LogSearchResponse, *models.Error) {
done

2021-01-12 22:22 UTC, dvaldivia commented
@harshavardhana as soon as possible xD

2021-01-12 22:57 UTC, cesnietor commented
please make it a single commit

2021-01-13 00:43 UTC, cesnietor commented
plase remove this logs:
```
 2021-01-13 00:42:33.365961 I | 2021/01/13 00:42:33 admin_info.go:489: lxl disk                 │                                                                                                 │
│ 2021-01-13 00:42:33.366051 I | 2021/01/13 00:42:33 admin_info.go:489: lxl instance             │                                                                                                 │
│ 2021-01-13 00:42:36.087540 I | 2021/01/13 00:42:36 admin_info.go:487: ll instance              │                                                                                                 │
│ 2021-01-13 00:42:36.087701 I | 2021/01/13 00:42:36 admin_info.go:487: ll disk                  │                                                                                                 │
│ 2021-01-13 00:42:36.087781 I | 2021/01/13 00:42:36 admin_info.go:489: lxl disk                 │                                                                                                 │
│ 2021-01-13 00:42:36.088122 I | 2021/01/13 00:42:36 admin_info.go:489: lxl instance             │                                                                                                 │
│ 2021-01-13 00:42:36.246063 I | 2021/01/13 00:42:36 admin_info.go:487: ll instance              │                                                                                                 │
│ 2021-01-13 00:42:36.246152 I | 2021/01/13 00:42:36 admin_info.go:487: ll disk                  │                                                                                                 │
│ 2021-01-13 00:42:36.246230 I | 2021/01/13 00:42:36 admin_info.go:489: lxl disk                 │                                                                                                 │
│ 2021-01-13 00:42:36.246477 I | 2021/01/13 00:42:36 admin_info.go:489: lxl instance 
```

2021-01-13 03:41 UTC, bexsoft commented
Created new squashed PR #549

2021-01-13 19:57 UTC, closed without merging