[WIP] Remove use of Privileged Credentials
minio/console pull request #535
Opened 2020-12-25 17:36 UTC by Alevsk

Leverage on MinIO Oauth integration instead of the current Console
implementation

2020-12-31 06:59 UTC, harshavardhana requested changes

2020-12-31 06:59 UTC, harshavardhana commented on README.md
>  #required to encrypt jwet payload
```suggestion
# Salt to encrypt JWT payload
```

2020-12-31 06:59 UTC, harshavardhana commented on README.md
> +#minio endpoint
```suggestion
# MinIO Endpoint
```

2021-01-04 17:50 UTC, harshavardhana approved these changes

2021-01-07 19:08 UTC, bexsoft approved these changes
LGTM

2021-01-07 19:49 UTC, merged