[WIP] Add get healthInfo api using websockets
minio/console pull request #543
Opened 2021-01-07 01:58 UTC by cesnietor

2021-01-09 05:02 UTC, bexsoft requested changes

2021-01-09 05:02 UTC, bexsoft commented on portal-ui/src/actions.ts
> +}
Please run prettier on files (version 2.1.1)

2021-01-11 18:21 UTC, Alevsk requested changes

2021-01-11 18:21 UTC, Alevsk commented on restapi/admin_health_info.go
> +				return errors.New(adminHealthInfo.Error)
Since this errors will be returned directly to the client via `sendWsCloseMessage(wsc.conn, err)` should we return a more generic error using the prepareError function? to avoid any kind of sensitive information exposure via an error stacktrace or something

2021-01-11 21:03 UTC, cesnietor commented on restapi/admin_health_info.go
> +				return errors.New(adminHealthInfo.Error)
Agree, done. Solved on ws_handle.go - sendWsCloseMessage()
Generic error is returned and the original error is being logged, I didn't use prepareError since we check other type of errors in there.

2021-01-12 22:23 UTC, dvaldivia approved these changes

2021-01-13 00:21 UTC, Alevsk approved these changes
LGTM

2021-01-13 20:00 UTC, bexsoft approved these changes
LGTM, Please merge after #549

2021-01-13 20:25 UTC, bexsoft approved these changes
LGTM

2021-01-13 20:27 UTC, Alevsk approved these changes

2021-01-13 20:43 UTC, merged