Fix retention date on object UI
minio/console pull request #556
Opened 2021-01-15 23:22 UTC by cesnietor

fixes https://github.com/minio/console/issues/513
If retention is set on an object already, display it when clicking 'edit'  on retention of an object.

<img width="782" alt="Screen Shot 2021-01-15 at 5 16 50 PM" src="https://user-images.githubusercontent.com/11819101/104787811-3735aa80-5756-11eb-9901-e38b669f5f6c.png">

2021-01-15 23:45 UTC, dvaldivia approved these changes

2021-01-15 23:56 UTC, dvaldivia approved these changes

2021-01-16 01:16 UTC, bexsoft requested changes

2021-01-16 01:16 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetRetention.tsx
> +        const month = valueDate.getMonth() + 1;
Please prepend a 0 when months are smaller than 10.

<img width="1009" alt="Screen Shot 2021-01-15 at 19 15 56" src="https://user-images.githubusercontent.com/33497058/104792985-1e34f580-5766-11eb-846f-e4983463b4af.png">

2021-01-18 21:38 UTC, cesnietor commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/SetRetention.tsx
> +        const month = valueDate.getMonth() + 1;
done

2021-01-18 22:06 UTC, dvaldivia approved these changes

2021-01-18 22:21 UTC, bexsoft approved these changes

2021-01-18 22:25 UTC, merged