Added error notifications to console
minio/console pull request #557
Opened 2021-01-15 23:25 UTC by bexsoft

fixes #99 

## What does this do?

Implements new error snackbars in console

## How does it look?

<img width="2056" alt="Screen Shot 2021-01-15 at 17 22 33" src="https://user-images.githubusercontent.com/33497058/104787890-73690b00-5756-11eb-9147-153707ed4d29.png">

2021-01-15 23:44 UTC, Alevsk submitted a review, later dismissed
LGTM

2021-01-15 23:45 UTC, dvaldivia submitted a review, later dismissed

2021-01-16 00:01 UTC, cesnietor requested changes

2021-01-16 00:01 UTC, cesnietor commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +        setErrorSnackMessage("An error occurred while uploading the file.");
could you please set this to use `errorMessage`

2021-01-16 00:06 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +        setErrorSnackMessage("An error occurred while uploading the file.");
that's my bad @bexsoft I picked the string when solving merge conficts

2021-01-16 00:15 UTC, belvid submitted a review, later dismissed
Looks good to me

2021-01-16 00:53 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +        setErrorSnackMessage("An error occurred while uploading the file.");
fixed, also changed the next two messages

2021-01-16 00:57 UTC, cesnietor approved these changes

2021-01-16 00:59 UTC, dvaldivia approved these changes

2021-01-16 04:32 UTC, merged