Add loading circle on health info UI
minio/console pull request #566
Opened 2021-01-19 21:55 UTC by cesnietor

fixes: https://github.com/minio/console/issues/558

Also hides the result of health info since it is only valuable when it is downloaded

<img width="889" alt="Screen Shot 2021-01-19 at 3 53 48 PM" src="https://user-images.githubusercontent.com/11819101/105097649-93f2d700-5a6e-11eb-92d0-bc76782c773c.png">

2021-01-19 23:37 UTC, bexsoft requested changes

2021-01-19 23:37 UTC, bexsoft commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> +      paddingLeft: "40px",
Please remove unit as this is using pixels as default:

```suggestion
      paddingTop: 8,
      paddingLeft: 40,
```

2021-01-19 23:37 UTC, bexsoft commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> +          <Grid container justify="flex-start" spacing={2}>
Can we move the justify property into a style?

2021-01-19 23:49 UTC, harshavardhana commented
what happens when the page is refreshed? @cesnietor

2021-01-19 23:51 UTC, cesnietor commented
> what happens when the page is refreshed? @cesnietor

progress is lost, you'll have to do it again since the health diagnostic is not stored anywhere.

2021-01-19 23:53 UTC, cesnietor commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> +          <Grid container justify="flex-start" spacing={2}>
done

2021-01-19 23:54 UTC, cesnietor commented on portal-ui/src/screens/Console/HealthInfo/HealthInfo.tsx
> +      paddingLeft: "40px",
done

2021-01-20 01:06 UTC, bexsoft submitted a review, later dismissed
LGTM

2021-01-20 19:24 UTC, bexsoft approved these changes
LGTM

2021-01-20 21:12 UTC, Alevsk approved these changes

2021-01-20 21:14 UTC, merged