New design for subscription page
minio/console pull request #568
Opened 2021-01-20 07:59 UTC by Alevsk

2021-01-28 18:16 UTC, dvaldivia submitted a review, later dismissed

2021-01-28 19:17 UTC, bexsoft requested changes
Moe comments bellow:

2021-01-28 19:17 UTC, bexsoft commented on portal-ui/src/screens/Console/License/ActivationModal.tsx
> +    licenseKeyField: {},
If it's empty we can remove

2021-01-28 19:19 UTC, bexsoft commented
<img width="1099" alt="Screen Shot 2021-01-28 at 13 01 23" src="https://user-images.githubusercontent.com/33497058/106187425-401d7780-616b-11eb-8174-ccfa6dc2c84f.png">
Can we remove the opacity effect?, also the activate button should be greyed out when one field is empty to have consistency

2021-01-28 19:19 UTC, bexsoft commented
<img width="933" alt="Screen Shot 2021-01-28 at 13 03 07" src="https://user-images.githubusercontent.com/33497058/106187589-722ed980-616b-11eb-97fb-3090f0ed1053.png">
Can we remove the borders & styles for activate button?

2021-01-28 19:20 UTC, bexsoft commented
Can we please make `portal-ui/public/agpl.png` to be a svg file?

2021-02-01 20:14 UTC, dvaldivia approved these changes

2021-02-05 19:58 UTC, bexsoft approved these changes

2021-02-05 20:49 UTC, merged