Upgrade console to use operator v4.0.0
minio/console pull request #581
Opened 2021-01-27 18:59 UTC by dvaldivia

Updates all the usage of the operator to the new v4.0.0 structure which uses Tenant V2 and Pools

2021-01-28 22:06 UTC, cesnietor requested changes

2021-01-28 22:06 UTC, cesnietor commented on go.mod
> +replace github.com/minio/operator v0.0.0-20210127071132-accfa4851396 => github.com/dvaldivia/operator v0.0.0-20210128022015-0ce833ee3034
no no

2021-01-28 22:43 UTC, dvaldivia commented on go.mod
> +replace github.com/minio/operator v0.0.0-20210127071132-accfa4851396 => github.com/dvaldivia/operator v0.0.0-20210128022015-0ce833ee3034
hahaha, it's a "place holder"

2021-01-28 22:44 UTC, dvaldivia commented on go.mod
> +replace github.com/minio/operator v0.0.0-20210127071132-accfa4851396 => github.com/dvaldivia/operator v0.0.0-20210128022015-0ce833ee3034
![tenor-6](https://user-images.githubusercontent.com/18384552/106207842-44e82880-6177-11eb-8532-7743c1df2e44.gif)

2021-01-29 03:56 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/operator v0.0.0-20210127071132-accfa4851396 => github.com/dvaldivia/operator v0.0.0-20210128022015-0ce833ee3034
placeholder can be removed now @dvaldivia

2021-02-01 18:14 UTC, dvaldivia commented on go.mod
> +replace github.com/minio/operator v0.0.0-20210127071132-accfa4851396 => github.com/dvaldivia/operator v0.0.0-20210128022015-0ce833ee3034
@harshavardhana removed

2021-02-01 18:16 UTC, cesnietor approved these changes
LGTM

2021-02-01 18:54 UTC, Alevsk approved these changes

2021-02-01 20:13 UTC, merged