Fix Tenant Details Bugs
minio/console pull request #589
Opened 2021-02-03 14:49 UTC by dvaldivia

This fixes #584 by making the expand set a name for the pool
This fixes #585 by making the expand set an affinity for the pool
This fixes #586 by generating a pool name if it's not indicated only

Also adds namespace to the list of columns of  tenant

2021-02-03 16:05 UTC, cesnietor requested changes

2021-02-03 16:05 UTC, cesnietor commented on restapi/admin_tenants.go
> +		log.Println(err)
minSvc and conSvc can be nil, please do the proper validations.

2021-02-03 23:01 UTC, dvaldivia commented on restapi/admin_tenants.go
> +		log.Println(err)
nice catch, fixed

2021-02-04 06:22 UTC, Alevsk submitted a review, later dismissed

2021-02-04 16:45 UTC, bexsoft requested changes

2021-02-04 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/utils.ts
> +// Copyright (c) 2020 MinIO, Inc.
Please change this to be 2021

2021-02-04 16:45 UTC, bexsoft commented on portal-ui/src/screens/Console/Menu/Menu.tsx
> +      group: "Operator",
Why are we changing it to Operator? This would be confusing for customers since they will think that you can access to operator here but it will redirect you to license page

2021-02-04 17:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Menu/Menu.tsx
> +      group: "Operator",
the intention is to remove the line dividir, but i think this also removes license from the regular console, I'll re-add that

2021-02-05 06:18 UTC, bexsoft submitted a review, later dismissed
LGTM

2021-02-05 19:16 UTC, cesnietor approved these changes

2021-02-05 19:18 UTC, cesnietor requested changes
please make assets

2021-02-05 22:25 UTC, Alevsk approved these changes

2021-02-05 22:25 UTC, cesnietor approved these changes

2021-02-05 22:27 UTC, merged