Support for ILM
minio/console pull request #598
Opened 2021-02-11 03:24 UTC by dvaldivia

2021-02-11 17:38 UTC, cesnietor requested changes
Please add some basic tests

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +			return admin_api.NewNotificationEndpointListDefault(int(err.Code)).WithPayload(err)
wrong Response type

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +// getNotificationEndpoints invokes admin info and returns a list of notification endpoints
wrong comments

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +// getNotificationEndpointsResponse returns a list of notification endpoints in the instance
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +	return params.Body, nil
we shouldn't return the same input, we can probably skip returning it and just return error.

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +// getNotificationEndpointsResponse returns a list of notification endpoints in the instance
wrong comments

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +		log.Println("error here")
```suggestion
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +		log.Println("error here")
```suggestion
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +	// add a new notification endpoints
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +	// add a new notification endpoints
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +// getNotificationEndpointsResponse returns a list of notification endpoints in the instance
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +// getNotificationEndpointsResponse returns a list of notification endpoints in the instance
wrong comments

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +	return nil
```suggestion
	return client.editTierCreds(ctx, params.Name, creds)
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/admin_tiers.go
> +		log.Println("error here")
```suggestion
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/client-admin.go
> +// implements madmin.ServerInfo()
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/client-admin.go
> +// implements madmin.ServerInfo()
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +		return user_api.NewAddBucketReplicationCreated()
wrong response?

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +// getListBucketsResponse performs getBucketLifecycle() and serializes it to the handler's output
wrong comment

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +	}
please make this inside `getBucketLifecycle `

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +// getBucketLifecycle() gets lifecycle lists for a bucket from MinIO API and returns their implementations
wrong comments

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +	return nil
```suggestion
	return client.setBucketLifecycle(ctx, params.BucketName, lfcCfg)
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +// getListBucketsResponse performs getBucketLifecycle() and serializes it to the handler's output
wrong commenta

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +	fmt.Println(minioClient.listBucketsWithContext(ctx))
```suggestion
```

2021-02-11 17:38 UTC, cesnietor commented on restapi/user_buckets_lifecycle.go
> +		fmt.Println("zxczxc")
```suggestion
```

2021-02-11 17:38 UTC, cesnietor commented on swagger.yml
> +  /admin/tiers/{type}/{name}:
can the type have a `/`?

2021-02-11 17:38 UTC, cesnietor commented on swagger.yml
> +  addBucketLifecycle:
should all properties be non required? you can potentially create a Lifecycle like `{}`

2021-02-11 23:58 UTC, cesnietor requested changes

2021-02-11 23:58 UTC, cesnietor commented on go.mod
> +)
remove replace

2021-02-12 19:28 UTC, bexsoft commented on swagger.yml
> +  /admin/tiers/{type}/{name}:
no, it can only be gcs, azure or s3. anything else is not supported

2021-02-16 21:13 UTC, cesnietor commented on swagger.yml
> +  addBucketLifecycle:
how did this get resolved?

2021-02-24 04:52 UTC, bexsoft commented on swagger.yml
> +  addBucketLifecycle:
We added a manual validation to this. swagger v2.0 can't handle all the cases that we have for this

2021-02-26 01:25 UTC, closed without merging

2021-02-26 01:32 UTC, bexsoft commented
closed in favor of #615