Added refresh tenant functionality
minio/console pull request #604
Opened 2021-02-17 19:20 UTC by jinapurapu

fixes #475

What does it do? - Adds refresh to reload pool listing when pool is added

2021-02-17 19:21 UTC, dvaldivia submitted a review, later dismissed

2021-02-17 19:24 UTC, kaankabalak submitted a review, later dismissed

2021-02-17 19:25 UTC, cesnietor requested changes
Please remo

2021-02-17 19:25 UTC, cesnietor commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
>        console.log("reload");
please remove the console.log and update assets with `make assets`

2021-02-19 00:33 UTC, bexsoft approved these changes
LGTM

2021-02-19 00:35 UTC, dvaldivia approved these changes

2021-02-19 00:35 UTC, cesnietor approved these changes

2021-02-19 01:33 UTC, merged