New design for License Page
minio/console pull request #608
Opened 2021-02-19 03:21 UTC by Alevsk

## How it looks

<img width="1682" alt="Screen Shot 2021-02-18 at 19 16 36" src="https://user-images.githubusercontent.com/1795553/108453022-7310d380-721e-11eb-849d-58efd19fbb56.png">

## Mockup

https://xd.adobe.com/view/b3c0da08-d238-44dc-8164-a7e413716732-e693/specs/

2021-02-19 22:13 UTC, dvaldivia submitted a review, later dismissed

2021-02-20 04:13 UTC, bexsoft requested changes

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +        marginBottom: "67px",
Please remove the px & leave it as int
```suggestion
        marginBottom: 67,
```

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +      padding: "8px",
Please leave it as int
```suggestion
      padding: 8,
```

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +      // borderTop: "1px solid #e5e5e5",
Please remove comment

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +      // borderTop: "1px solid #e5e5e5",
Please remove comment

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +        // });
We can remove this

2021-02-20 04:13 UTC, bexsoft commented on portal-ui/src/screens/Console/License/License.tsx
> +            style={{ padding: "23px 33px" }}
Please try to add this as a class

2021-02-22 19:04 UTC, bexsoft approved these changes

2021-02-23 00:41 UTC, dvaldivia approved these changes

2021-02-23 00:41 UTC, merged