Disable Users and Groups Menu options when LDAP is enabled on MinIO
minio/console pull request #614
Opened 2021-02-25 18:55 UTC by Alevsk

2021-02-25 19:38 UTC, cesnietor commented on pkg/acl/const.go
> +	ConsoleLDAPEnabled = "CONSOLE_LDAP_ENABLED"
seems this constant is already declared on `pkg/auth/ldap` on `const.go` should we use that instead?

2021-02-25 20:19 UTC, Alevsk commented on pkg/acl/const.go
> +	ConsoleLDAPEnabled = "CONSOLE_LDAP_ENABLED"
the variables are on different namespaces, i don't want to have dependency from that namespace to this one because this can quickly end on circular dependencies x.x

2021-02-25 23:03 UTC, harshavardhana requested changes

2021-02-25 23:03 UTC, harshavardhana commented on restapi/user_service_accounts.go
> +	var iamPolicy *iampolicy.Policy
Add a comment on why it is kept this way? to ensure that we do not initialize `iampolicy.Policy` struct since that is a valid policy?

2021-02-25 23:45 UTC, harshavardhana approved these changes

2021-02-26 01:33 UTC, bexsoft approved these changes
LGTM

2021-02-26 01:36 UTC, cesnietor approved these changes

2021-02-26 19:20 UTC, merged