Tiers & lifecycle implementation
minio/console pull request #615
Opened 2021-02-26 01:28 UTC by bexsoft

## What does this do?

Implements ILM functionality in Console

## How does it look?

<img width="2063" alt="Screen Shot 2021-02-25 at 19 27 22" src="https://user-images.githubusercontent.com/33497058/109241769-8502f100-779f-11eb-9093-926d48a0b1df.png">
<img width="2054" alt="Screen Shot 2021-02-25 at 19 27 13" src="https://user-images.githubusercontent.com/33497058/109241774-87654b00-779f-11eb-90ec-250f4e2ada0c.png">
<img width="810" alt="Screen Shot 2021-02-25 at 19 27 00" src="https://user-images.githubusercontent.com/33497058/109241776-87fde180-779f-11eb-9a2f-9d39968e9315.png">
<img width="1010" alt="Screen Shot 2021-02-25 at 19 26 54" src="https://user-images.githubusercontent.com/33497058/109241778-88967800-779f-11eb-9758-787f44158a08.png">
<img width="2062" alt="Screen Shot 2021-02-25 at 19 26 40" src="https://user-images.githubusercontent.com/33497058/109241781-892f0e80-779f-11eb-97c3-88ec85dd9581.png">

2021-02-26 20:25 UTC, Alevsk requested changes

2021-02-26 20:25 UTC, Alevsk commented on pkg/auth/idp/oauth2/provider.go
> +	if GetIdpURL() == "https://accounts.google.com" {
Mmmm here maybe we should parse the URL to make sure we are dealing with Google IDP, otherwise if the user inputs something like `https://accounts.google.com/` (slash at the end) this validation we fail

2021-02-26 20:25 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +    },*/
we can delete this

2021-02-26 20:25 UTC, Alevsk commented on restapi/error.go
> +		if err[0].Error() == "Specified remote tier already exists" {
This can be changed to something like this:

```suggestion
                 errRemoteTierExists := errors.New("Specified remote tier already exists")
                 if errors.Is(err[0], errRemoteTierExists) {
```

2021-02-27 05:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +    },*/
done

2021-02-27 05:23 UTC, bexsoft commented on restapi/error.go
> +		if err[0].Error() == "Specified remote tier already exists" {
done

2021-02-27 05:24 UTC, bexsoft commented on pkg/auth/idp/oauth2/provider.go
> +	if GetIdpURL() == "https://accounts.google.com" {
Please help me to review solution for this

2021-03-09 19:31 UTC, Alevsk requested changes

2021-03-09 19:31 UTC, Alevsk commented on pkg/auth/idp/oauth2/provider.go
> +	}
```suggestion
	// if google, change scopes
	u, err := url.Parse(GetIdpURL())
	if err != nil {
		return nil, err
	}
	if u.Host == "google.com" {
		scopes = []string{oidc.ScopeOpenID}
	}
```

2021-03-09 20:00 UTC, Alevsk approved these changes
LGTM

2021-03-09 20:36 UTC, dvaldivia approved these changes

2021-03-09 20:36 UTC, merged

2021-03-09 20:37 UTC, cesnietor commented on go.mod
> +)
@dvaldivia  pr is still having this replace cc @bexsoft