add console systemd service
minio/console pull request #627
Opened 2021-03-04 00:25 UTC by harshavardhana

2021-03-04 19:04 UTC, Alevsk requested changes

2021-03-04 19:04 UTC, Alevsk commented on systemd/README.md
> +CONSOLE_MINIO_SERVER=http://ccg13hrzsdsminio01.ccg13.phx.paypalinc.com:9000
Please change this to a generic minio endpoint

2021-03-04 20:16 UTC, Alevsk approved these changes
LGTM

2021-03-05 05:59 UTC, harshavardhana commented
PTAL @cesnietor @dvaldivia

2021-03-05 20:30 UTC, dvaldivia approved these changes

2021-03-05 23:20 UTC, merged