Returning correct error when user is unable to change password
minio/console pull request #635
Opened 2021-03-09 08:09 UTC by Alevsk

2021-03-09 08:10 UTC, dvaldivia submitted a review, later dismissed

2021-03-09 08:12 UTC, kannappanr submitted a review, later dismissed
LGTM

2021-03-09 15:18 UTC, bexsoft approved these changes

2021-03-09 15:59 UTC, bexsoft requested changes
Please fix

2021-03-09 15:59 UTC, bexsoft commented on restapi/error.go
> +	errAccessDenied                       = errors.New("Access Denied")
Please make it lower case
```suggestion
	errAccessDenied                       = errors.New("access Denied")
```

2021-03-09 20:24 UTC, bexsoft approved these changes
LGTM

2021-03-09 20:37 UTC, dvaldivia submitted a review, later dismissed

2021-03-09 20:42 UTC, cesnietor commented
might need to remake assets due to previous merge

2021-03-09 20:49 UTC, bexsoft approved these changes

2021-03-09 20:53 UTC, bexsoft requested changes
on hold

2021-03-09 21:01 UTC, harshavardhana commented
Why not disable the UI element entirely?

2021-03-09 23:45 UTC, Alevsk commented
> Why not disable the UI element entirely?

good idea, adding support to enable/disable specific UI elements and not only options at the menu, with this we will improve UX for console users

2021-03-10 00:01 UTC, bexsoft requested changes
Please change that line, beside of that, looks ok

2021-03-10 00:56 UTC, bexsoft approved these changes

2021-03-10 01:00 UTC, cesnietor approved these changes

2021-03-10 01:32 UTC, merged