Allow to assign multiple policies to to a user or group
minio/console pull request #646
Opened 2021-03-17 01:52 UTC by dvaldivia

Makes it so multiple policies can be assigned to a user or group.

Fixes https://github.com/miniohq/engineering/issues/30

<img width="1210" alt="Screen Shot 2021-03-16 at 6 48 41 PM" src="https://user-images.githubusercontent.com/18384552/111402544-9cd7e180-8688-11eb-897d-6e3137da0b42.png">

2021-03-17 17:38 UTC, Alevsk requested changes

2021-03-17 17:38 UTC, Alevsk commented on portal-ui/src/screens/Console/Policies/PolicySelectors.tsx
> +    console.log(elements);
this can be deleted

2021-03-17 18:20 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicySelectors.tsx
> +    console.log(elements);
done

2021-03-17 19:25 UTC, Alevsk approved these changes

2021-03-22 17:34 UTC, bexsoft approved these changes
LGTM, Test OK

2021-03-22 17:38 UTC, Alevsk approved these changes

2021-03-22 17:45 UTC, merged