Bucket/Replication (feature) if not enough permissions
minio/console pull request #662
Opened 2021-03-23 02:24 UTC by dvaldivia

Fixes https://github.com/miniohq/engineering/issues/33

This introduces an api `/api/v1/has-permission` which reply wether the current user can perform a given action, for example if it can perform `s3:PutReplicationConfiguration` on a given `bucket` of it it can `s3:CreateBucket` at all, is used to show/hide the add buttons and the replication tab

2021-03-24 19:25 UTC, bexsoft requested changes

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +        setLoadingPerms(true);
This is not necessary here as variable is true already when you reach this line

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +        setLoadingPerms(true);
this variable is not needed here

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +      const fetchPerms = () => {
Is better to set this function in a useCallback

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +        setLoadingPerms(true);
Same case

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +      const fetchPerms = () => {
Please add this into a useCallback

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +                <React.Fragment>
Try to import Fragment in react import (1st line) and replace this by 
```suggestion
                <Fragment>
```

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +      const fetchRecords = () => {
Please change this into a useCallback

2021-03-24 19:25 UTC, bexsoft commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +            console.log(res);
Please remove console.log
```suggestion
```

2021-03-24 19:25 UTC, bexsoft commented on restapi/user_account_test.go
> +		name string
Would you please check indentation of this file?

2021-03-24 19:30 UTC, Alevsk requested changes

2021-03-24 19:30 UTC, Alevsk commented on restapi/user_account.go
> +}
You can use the existing `getAccountPolicy` in `user_login.go` and delete this function

2021-03-24 22:10 UTC, dvaldivia commented on restapi/user_account.go
> +}
done

2021-03-24 22:11 UTC, dvaldivia commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +        setLoadingPerms(true);
dne

2021-03-24 22:11 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +        setLoadingPerms(true);
done

2021-03-24 22:12 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +        setLoadingPerms(true);
done

2021-03-24 22:13 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +      const fetchPerms = () => {
mm, we do consts everywhere at the moment for any funciton who is scoped and defined inside `useEffect` since it's not re-usable in the same component I don't think we should use `useCallback`

2021-03-24 22:13 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +      const fetchPerms = () => {
mm, we do consts everywhere at the moment for any funciton who is scoped and defined inside useEffect since it's not re-usable in the same component I don't think we should use useCallback

2021-03-24 22:14 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +                <React.Fragment>
done, `brace yourself for merge conflicts` hahaha

2021-03-24 22:14 UTC, dvaldivia commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +      const fetchRecords = () => {
mm, we do consts everywhere at the moment for any funciton who is scoped and defined inside useEffect since it's not re-usable in the same component I don't think we should use useCallback

2021-03-24 22:15 UTC, dvaldivia commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +            console.log(res);
done

2021-03-24 22:15 UTC, dvaldivia commented on restapi/user_account_test.go
> +		name string
it's `go fmt`ed and the json is idented, What else?

2021-03-24 22:32 UTC, bexsoft requested changes

2021-03-24 22:32 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +      const fetchPerms = () => {
But we usually don't define a function inside a useEffect and then call it in the same, this way you are redefining the function each time loadingPerms changes and it could lead to a memory leak. For this case is better to use a useCallback,

2021-03-25 01:01 UTC, bexsoft approved these changes

2021-03-25 17:08 UTC, Alevsk approved these changes

2021-03-25 17:10 UTC, merged