Adding UI for bucket policies.
minio/console pull request #663
Opened 2021-03-23 18:17 UTC by adfost

2021-03-23 21:23 UTC, bexsoft requested changes
Please squash your PR into a single commit

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +import { connect } from "react-redux";
Please remove this duplicated line

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +import { setErrorSnackMessage } from "../../../../actions";
Please remove this duplicated line

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +  BucketPolicy,
This interface is not defined, please review if all your changes made into the PR

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +  const [bucketPolicy, setBucketPolicy] = useState<BucketPolicy[]
Please run prettier before sending PR to avoid these line jumps, prettier runs when you run `make assets` in root folder (this must be executed before sending any frontend PR

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/AddPolicy.tsx
> +// This file is part of MinIO Kubernetes Cloud
```suggestion
// This file is part of MinIO Console Server
```

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/PolicySelectors.tsx
> +// This file is part of MinIO Kubernetes Cloud
```suggestion
// This file is part of MinIO Console Server
```

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/AddPolicy.tsx
> +// This file is part of MinIO Kubernetes Cloud
Are we sure that we couldn't re-use the original add policy component for this?

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/PolicySelectors.tsx
> +      width: "320px",
When css properties are pixels in JS, we try to just use the number, if it is a composed property or the unit is not pixels, we apply the string with the unit
```suggestion
      width: 320,
```

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/PolicySelectors.tsx
> +      padding: "20px",
```suggestion
      padding: 20,
```

2021-03-23 21:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/PolicySelectors.tsx
> +      maxWidth: "200px",
```suggestion
      maxWidth: 200,
```

2021-03-23 21:39 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/ViewBucket/AddPolicy.tsx
> +// This file is part of MinIO Kubernetes Cloud
Should I just delete that file? Also I'm not completely sure how to squash all of my commits into one

2021-03-23 21:50 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +  BucketPolicy,
I defined the interface.

2021-03-23 22:06 UTC, adfost commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +import { setErrorSnackMessage } from "../../../../actions";
Handled this.

2021-03-23 23:01 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/AddPolicy.tsx
> +// This file is part of MinIO Kubernetes Cloud
If it's not needed, yes, please remove this file

2021-03-24 16:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +  const [loading, setLoading] = useState<boolean>(false);
This loading flag is not being used in this page, we can remove
```suggestion
```

2021-03-24 16:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +  const fetchRecords = () => {
Please change this to fetchPolicies
```suggestion
  const fetchPolicies = () => {
```

2021-03-24 16:30 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +      fetchRecords();
Please change this to fetchPolicies function
```suggestion
      fetchPolicies();
```

2021-03-24 16:31 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +    setLoading(true);
Please set this to update the loadingPolicy state instead the wrong loading state
```suggestion
    setLoadingPolicy(true);
```

2021-03-25 00:12 UTC, dvaldivia requested changes

2021-03-25 00:12 UTC, dvaldivia commented on yarn-error.log
> +PATH:
don't check in this file

2021-03-25 00:12 UTC, dvaldivia commented on yarn.lock
> +# yarn lockfile v1
dont' check in this file

2021-03-25 18:38 UTC, dvaldivia approved these changes

2021-03-25 22:00 UTC, Alevsk requested changes

2021-03-25 22:00 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/types.tsx
> +
The policy interface already exists on `Policies/types.ts` you could try to import that interface from and don't have to maintain same code in both places.

2021-03-25 23:17 UTC, closed without merging