Api bucket policy
minio/console pull request #674
Opened 2021-03-29 21:33 UTC by adfost

2021-03-30 02:28 UTC, Alevsk requested changes

2021-03-30 02:28 UTC, Alevsk commented on restapi/admin_users.go
> +		}
We should log errors in case we need to debug in the feature

```suggestion
		if err != nil {
		    // log error
	            continue    
		}
		parsedPolicy, err := parsePolicy(users[i].Policy, policy)
		if err != nil {
		    // log error
	            continue    
		}
		if policyMatchesBucket(parsedPolicy, bucket) {
			retval = append(retval, users[i].AccessKey)
			seen[users[i].AccessKey] = true
		}
```

2021-03-30 02:28 UTC, Alevsk commented on admin.json
> +{
Do we need this file?, otherwise we can delete i

2021-03-30 02:28 UTC, Alevsk commented on restapi/admin_users.go
> +		}
Same comment as above we should log errors for future debugging

2021-03-30 02:28 UTC, Alevsk commented on restapi/admin_users.go
> +	groups, _ := listGroups(ctx, adminClient)
we should not ignore this error, in case groups is `nil` the `len(* groups)`  will panic with: `panic: runtime error: invalid memory address or nil pointer dereference`

2021-03-30 03:49 UTC, bexsoft requested changes

2021-03-30 03:49 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +                isLoading={loadingEvents}
This loading needs to be related to the loading used to fill this table, in this case loading users
```suggestion
                isLoading={loadingUsers}
```

2021-03-30 03:49 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +    if (loadingPolicy) {
This loading state should be loadingUsers as it is the one required for loading this information
```suggestion
    if (loadingUsers) {
```

2021-03-31 05:27 UTC, dvaldivia requested changes

2021-03-31 05:45 UTC, adfost commented on node_modules/.yarn-integrity
> +{
Done

2021-03-31 15:28 UTC, dvaldivia approved these changes

2021-03-31 22:45 UTC, Alevsk requested changes

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +		console.Println(err)
```suggestion
		return nil, prepareError(err) 
```

Here if you dont have groups you should stop processing the request and just return an error, otherwise `len(*groups)` will still crash the operation

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +			console.Println(err)
```suggestion
			log.Println(err)
```

Here I'm not sure what is console, we usually use the golang `log` package to log errors.

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +				console.Println(err2)
```suggestion
				log.Println(err2)
```

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +			console.Println(err)
```suggestion
			log.Println(err)
```

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +				console.Println(err2)
```suggestion
				log.Println(err2)
```

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +	for i := 0; i < len(users); i++ {
This is just a suggestion, to iterate the array of objects you can also do:
```suggestion
	for _, user := range users {
```

Inside the loop you can just use the `user` object directly, ie : `user.AccessKey` instead of `users[i].AccessKey`

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +						console.Println(err3)
```suggestion
						log.Println(err3)
```

2021-03-31 22:45 UTC, Alevsk commented on restapi/admin_users.go
> +				for j := 0; j < len(info.Members); j++ {
```suggestion
				for _, member := range info.Members {
```

2021-04-02 20:50 UTC, Alevsk submitted a review, later dismissed

2021-04-02 21:17 UTC, bexsoft approved these changes
LGTM

2021-04-02 23:06 UTC, Alevsk approved these changes
LGTM

2021-04-02 23:13 UTC, merged