Adding list of pods
minio/console pull request #715
Opened 2021-05-03 22:13 UTC by adfost

2021-05-04 16:32 UTC, dvaldivia commented
If I run other applications on the same namespace as the Tenant they get listed, please restrict the pods to only Tenant Pods

<img width="992" alt="Screen Shot 2021-05-04 at 9 32 01 AM" src="https://user-images.githubusercontent.com/18384552/117037658-97c40580-acbb-11eb-9c91-d95add321421.png">

2021-05-04 16:32 UTC, dvaldivia requested changes
See screenshot

2021-05-04 16:33 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +                {
The delete action is not yet implemented, please remove this option

2021-05-04 16:44 UTC, dvaldivia commented
Can you also attach a screenshot of the final screen to this ticket

2021-05-04 17:38 UTC, bexsoft requested changes

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/ListTenants/types.ts
> +export interface IPod {
We should call it `IPodListElement` to have more clarity on what does this interface do

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +          console.log(result[i]);
Please remove console.log

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +                {
You can send an empty array to item actions, it is not necessary to have an option here always

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +                {
You can send an empty array to item actions, it is not necessary to have an option here always

2021-05-04 17:38 UTC, bexsoft commented on swagger.yml
> +      timecreated:
Please use camel case:
```suggestion
      timeCreated:
```

2021-05-04 17:38 UTC, bexsoft commented on swagger.yml
> +      podip:
Same camel case here:
```suggestion
      podIP:
```

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +          console.log(currentTime);
Please remove console.log

2021-05-04 17:38 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +            (currentTime - parseInt(result[i].timecreated)).toString()
Not sure if this what is intended, as you are receiving an epoch time from backend and you are substracting the amount of seconds of current time:

<img width="753" alt="Screen Shot 2021-05-04 at 12 37 21" src="https://user-images.githubusercontent.com/33497058/117045883-a7504800-acd5-11eb-83db-dc0650fe52ad.png">

2021-05-04 21:54 UTC, dvaldivia commented on restapi/admin_tenants.go
> +		if pods.Items[i].Name[0:len(params.Tenant)] == params.Tenant {
I broke this logic by deploying a pod for wodpress with the tenant prefix

2021-05-04 23:05 UTC, dvaldivia requested changes

2021-05-04 23:05 UTC, dvaldivia commented on admin.json
> +{
remove this file

2021-05-04 23:05 UTC, dvaldivia commented on restapi/admin_tenants.go
> +		TypeMeta:             metav1.TypeMeta{},
remove all unused fields, also this doesn't filter anything like we discussed

2021-05-07 01:07 UTC, dvaldivia submitted a review, later dismissed

2021-05-07 01:13 UTC, bexsoft requested changes

2021-05-07 01:13 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantDetails.tsx
> +        console.log("Error in loading pods");
Should we show the error alert here?

```suggestion
        setErrorSnackMessage("Error loading pods")
```

2021-05-07 01:53 UTC, bexsoft approved these changes

2021-05-07 01:57 UTC, dvaldivia approved these changes

2021-05-07 01:57 UTC, merged