Hide users tab from bucket view when LDAP is enabled
minio/console pull request #719
Opened 2021-05-04 22:39 UTC by Alevsk

2021-05-04 22:40 UTC, dvaldivia submitted a review, later dismissed

2021-05-05 17:40 UTC, bexsoft requested changes
Beside of that, LGTM

2021-05-05 17:40 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ViewBucket/ViewBucket.tsx
> +    if (loadingUsers && usersEnabled) {
Please add usersEnabled to useEffect dependencies list on line 432

2021-05-08 00:47 UTC, dvaldivia approved these changes

2021-05-08 00:48 UTC, merged