User policies
minio/console pull request #744
Opened 2021-05-14 18:27 UTC by adfost

2021-05-14 20:26 UTC, dvaldivia commented
you should probably squash into a single commit

2021-05-14 20:26 UTC, dvaldivia commented
Can you also attach screenshots of the resulting change?

2021-05-16 01:44 UTC, dvaldivia requested changes
While trying to run the server I get the error
```
2021-05-15 18:42:26.514561 I | 2021/05/15 18:42:26 server.go:97: invalid character '<' looking for beginning of object key string
```
you need to regen swagger and commit the files that are generated

2021-05-16 01:51 UTC, dvaldivia requested changes
There's a react rendering bug which causes the list of users to dance around like crazy 

![ezgif-2-186fbdf46587](https://user-images.githubusercontent.com/18384552/118382881-73670380-b5ae-11eb-84d3-d702c5941337.gif)

2021-05-16 01:51 UTC, dvaldivia commented on admin.json
> +{
Don't commit this file

2021-05-16 01:51 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +  const [replicationModalOpen, setReplicationModalOpen] = useState<boolean>(
update your prettier to `2.3.0` to avoid having this phantom changes

2021-05-16 01:51 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +            <Tab label="Edit Policy" />
I think it's better to move `Edit Policy` to the first place of the tabs, and rename it to `Details` as it's the actual policy

2021-05-16 01:51 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +                  <Grid item xs={12}>
I don't think this is needed anymore, as the header of the page already container the name of the policy, remove this hole grid item

2021-05-16 01:51 UTC, dvaldivia commented on restapi/admin_policies.go
> +		policyResponse, err := getListUsersForPolicyResponse(session, params.Policy)
perhaps this variable should be called `policyUsersResponse` as it's more of a list of users for the policy

2021-05-16 01:52 UTC, dvaldivia requested changes

2021-05-16 01:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +                  type: "delete",
remove this action, we don't need to delete users from  this screen

2021-05-16 01:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +              itemActions={[
Can you add the default action so clicking on any of this users takes us to the route `/users/:userName`

2021-05-16 01:53 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +        <Grid item xs={12}>
it's ok to remove one of these grid items with <br />

2021-05-17 21:20 UTC, dvaldivia commented
Can you put these details inside a `<Paper>` container, so they sit over white background
<img width="1247" alt="Screen Shot 2021-05-17 at 2 19 48 PM" src="https://user-images.githubusercontent.com/18384552/118558119-07ee7480-b71b-11eb-9b4b-d94bf2bde6b5.png">

2021-05-17 22:52 UTC, bexsoft requested changes

2021-05-17 22:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +  }, [policy]);
5.- Process completes, as the policy value has changed, this effect is executed again (Go back to step 1)

2021-05-17 22:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +    if (policy) {
4.- Policy here contains the same value as you have not waiting to all the process to complete

2021-05-17 22:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +    loadPolicyDetails();
1.- You load policy details

2021-05-17 22:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +        setPolicy(result);
3.- You set the values of the policies that you received (I think these values are not sorted), Also values will not be reflected during this render run

2021-05-17 22:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +  const loadPolicyDetails = () => {
2.- Policy details is being requested

2021-05-18 21:47 UTC, dvaldivia requested changes

2021-05-18 21:47 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +        <Grid item xs={12}>
+1

2021-05-18 21:47 UTC, dvaldivia commented on restapi/admin_policies.go
> +		policyResponse, err := getListUsersForPolicyResponse(session, params.Policy)
+1

2021-05-19 04:09 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +      alignItems: "center" as const,
I think we can remove the `as const` conversion as this is only needed for external linked files. Please test if it is not required, if not we can remove

2021-05-19 15:06 UTC, dvaldivia submitted a review, later dismissed

2021-05-19 16:48 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +      alignItems: "center" as const,
should be harmless to keep

2021-05-19 17:27 UTC, bexsoft approved these changes

2021-05-19 17:30 UTC, bexsoft requested changes
.

2021-05-19 17:46 UTC, Alevsk approved these changes

2021-05-19 17:46 UTC, Alevsk commented on portal-ui/src/screens/Console/Policies/ListPolicies.tsx
> +          });
Sort logic can be moved to the backend

2021-05-19 18:27 UTC, bexsoft requested changes
You can see the differences of these changes by enabling the `Highlight updates when components render` checkbox in react tools inspector. 

<img width="1677" alt="Screen Shot 2021-05-19 at 13 23 23" src="https://user-images.githubusercontent.com/33497058/118864589-bde5ca00-b8a5-11eb-8ef5-984181501e77.png">

You'll notice the amount of re-renders in the application (the longest time the boxes appear, more re-renders are happening)

<img width="2560" alt="Screen Shot 2021-05-19 at 13 25 20" src="https://user-images.githubusercontent.com/33497058/118864825-f9809400-b8a5-11eb-9ef7-ad5fdd00a645.png">

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +  }, [policy]);
Please split this effect in two parts because there is still a couple of re-renders present:
```suggestion
useEffect(() => {
    if(loadingUsers) {
api
        .invoke("GET", `/api/v1/policies/${policyName}/users`)
        .then((result: any) => {
          setUserList(result);
          setLoadingUsers(false);
        })
        .catch((err) => {
          console.log("Error in loading users");
        });
    }
    
    if(loadingPolicy) {
      api
        .invoke("GET", `/api/v1/policy?name=${policyName}`)
        .then((result: any) => {
          setPolicy(result);
          setLoadingPolicy(false);
        })
        .catch((err) => {
          console.log("Error in loading policy");
        });
    }
}, [loadingUsers, loadingPolicy, policyName]);

  useEffect(() => {
    if (policy) {
      setPolicyName(policy.name);
      setPolicyDefinition(
        policy ? JSON.stringify(JSON.parse(policy.policy), null, 4) : ""
      );
    }
  }, [policy]);
```

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +import get from "lodash/get";
You can remove this import as it is not being used
```suggestion

```

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +import { Button, LinearProgress, Typography } from "@material-ui/core";
You can remove Typography ad it is not being used
```suggestion
import { Button, LinearProgress } from "@material-ui/core";
```

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +import InputBoxWrapper from "../Common/FormComponents/InputBoxWrapper/InputBoxWrapper";
You can remove this import as it not being used
```suggestion

```

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +  };
These two functions can be removed as queries are now part of the effect that is going to invoke them, an alternative method is to convert these two functions info a [useCallback](https://es.reactjs.org/docs/hooks-reference.html#usecallback) and add them to the dependency array of the effect

2021-05-19 18:27 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +    loadPolicyDetails();
These two can be removed ad the effect if going to perform these queries

2021-05-19 20:42 UTC, dvaldivia approved these changes

2021-05-19 22:18 UTC, bexsoft approved these changes

2021-05-19 22:18 UTC, merged