#616 added modal on icon click
minio/console pull request #747
Opened 2021-05-15 01:53 UTC by jinapurapu

Upon clicking the pencil icon, a modal opens with fields for current password, new password, and to reenter the new password. The modal is largely a copy of the ChangePassword modal, and requires further modification to pass the selected user, and change the selected users password.

![Screenshot from 2021-05-14 18-48-48](https://user-images.githubusercontent.com/65002498/118344868-8c57b200-b4e5-11eb-89f0-48d3859574bc.png)
![Screenshot from 2021-05-14 18-49-26](https://user-images.githubusercontent.com/65002498/118344869-8cf04880-b4e5-11eb-855e-b6be73288af8.png)

2021-05-17 16:10 UTC, dvaldivia requested changes

2021-05-17 16:10 UTC, dvaldivia commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +              <InputBoxWrapper
When an admin is changing someone else's password, the current password is not needed, so we can remove this field

2021-05-17 16:10 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/types.tsx
> +  //selected_user: object;
if this line is not needed, remove it

2021-05-17 16:10 UTC, dvaldivia commented on restapi/user_account.go
> +	if session.AccountSecretKey != currentSecretKey {
we probably don't have the user's current password, so we shouldn't require this field

2021-05-17 18:56 UTC, dvaldivia requested changes

2021-05-17 18:56 UTC, dvaldivia commented on bindata.go
> +
please remove this file

2021-05-17 18:56 UTC, dvaldivia commented on bindata.go
> +
any bindata file mnust be removed from this PR

2021-05-18 20:39 UTC, dvaldivia commented on restapi/user_account.go
> +	if err := client.changePassword(ctx, session.AccountAccessKey, newSecretKey); err != nil {
do use `session.AccountAccessKey`

2021-05-19 04:17 UTC, bexsoft requested changes

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +  // selectedUser: User | null;
We can remove this line

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +  //selectedUser,
We can remove this line if not needed

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +      //selected_user: selectedUser,
We can remove this line

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +        // setSelectedUser("");
We can remove this line

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +                  reNewPassword.length > 0
we can add another condition to disable the button if passwords don't match
```suggestion
                  reNewPassword.length > 0 && newPassword !== reNewPassword
```

2021-05-19 04:17 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/Groups.tsx
> +              placeholder="Search "
I think this label should not be removed

2021-05-19 04:17 UTC, bexsoft commented on swagger.yml
> +      security: []
I think you need to update your prettier too, if you installed it using brew please run this command in a terminal:
`brew upgrade prettier`

The version that we are using right now is `2.3.0`

2021-05-19 04:19 UTC, bexsoft commented
Please review:
```
restapi/admin_users.go:109:2: missing ',' before newline in argument list
restapi/admin_users.go:111:6: expected '(', found listUsers
```

2021-05-28 18:21 UTC, jinapurapu commented on portal-ui/src/screens/Console/Account/ChangeUserPasswordModal.tsx
> +              <InputBoxWrapper
done

2021-06-01 22:20 UTC, dvaldivia requested changes

2021-06-01 22:20 UTC, dvaldivia commented on restapi/admin_users.go
> +	//credentials, err := getConsoleCredentials(ctx, accessKey, newSecretKey)
remove commented code if not needed

2021-06-02 18:31 UTC, dvaldivia commented
![Uploading Screen Shot 2021-06-02 at 11.31.02 AM.png…]()

2021-06-03 22:00 UTC, dvaldivia approved these changes
Tested Works

2021-06-03 22:31 UTC, bexsoft approved these changes

2021-06-03 22:32 UTC, merged