move to madmin-go package
minio/console pull request #765
Opened 2021-05-21 19:24 UTC by harshavardhana

2021-05-31 04:14 UTC, dvaldivia approved these changes

2021-05-31 05:24 UTC, dvaldivia approved these changes

2021-06-01 17:10 UTC, Alevsk approved these changes

2021-06-01 17:16 UTC, bexsoft requested changes
Getting ```# github.com/minio/console/cmd/console
/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
duplicate symbol '_readdrivestat' in:
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000020.o
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000036.o
duplicate symbol '_get_temperature' in:
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000023.o
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000039.o
duplicate symbol '_open_smc' in:
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000023.o
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000039.o
duplicate symbol '_close_smc' in:
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000023.o
    /var/folders/fj/xhr255q51gg8cm67pz5kqz0m0000gn/T/go-link-576402205/000039.o
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)``` during build time, investigating further

2021-06-01 18:08 UTC, bexsoft approved these changes
Works good by adding `CGO_ENABLED=0` & `--tags=kqueue` flags to runtime in case of using MacOS.

2021-06-01 18:34 UTC, merged