Update WriteTimeout in server.go
minio/console pull request #772
Opened 2021-05-27 10:29 UTC by peshoangelov

increase the default of WriteTimeout in server.go in order to allow long downloads of huge files (>700M size)

2021-05-29 00:52 UTC, dvaldivia approved these changes

2021-05-29 01:03 UTC, harshavardhana requested changes
This applies to all upload and downloads for objects @dvaldivia 

If we have an upper limit it won't work. We need to decouple this top level deadline.. 

Or tell users to use `mc` to download files that are bigger.

Any arbitrary timeout is not going to help..

2021-06-02 19:41 UTC, bexsoft requested changes

2021-06-02 19:41 UTC, bexsoft commented on restapi/server.go
> +	WriteTimeout time.Duration `long:"write-timeout" description:"maximum duration before timing out write of the response" default:"1200s"`
In this case, a modification in a swagger auto-generated field is being attempt, I think it would be better to look for a way to modify this value using swagger.yml

2021-06-05 00:21 UTC, dvaldivia commented
@peshoangelov I was testing/integrating your PR and it turns out, swagger supports you passing `--write-timeout 1200` when you start the server and that technically should do it

2021-06-05 00:21 UTC, closed without merging