remove various unexpected features in console
minio/console pull request #782
Opened 2021-06-03 01:03 UTC by harshavardhana

- Unix listeners are removed
- KeepAlive, IdleTimeout etc are removed
- Authorization logic is simplified

2021-06-03 01:25 UTC, dvaldivia commented on restapi/configure_console.go
> -		tokenCookie, err := r.Cookie("token")
we use to be header only authorization, but then we reverted to cookies as it was the only reliable way to authenticate connections being upgraded to web sockets, so we still need this

2021-06-03 02:36 UTC, harshavardhana commented on restapi/configure_console.go
> -		tokenCookie, err := r.Cookie("token")
We don't need it this entire code is moved into single function @dvaldivia

2021-06-03 05:02 UTC, dvaldivia approved these changes

2021-06-03 20:52 UTC, dvaldivia approved these changes

2021-06-03 22:05 UTC, Alevsk requested changes

2021-06-03 22:05 UTC, Alevsk commented on cmd/console/server.go
> +	if acl.GetOperatorMode() {
I was talking with Daniel, we need to discuss with Ab if we want to restrict this refresh license feature to only operator-mode, otherwise we need to remove this line

2021-06-03 23:03 UTC, Alevsk approved these changes

2021-06-03 23:20 UTC, Alevsk approved these changes

2021-06-04 00:31 UTC, dvaldivia approved these changes

2021-06-04 01:04 UTC, merged