Pod Details
minio/console pull request #789
Opened 2021-06-04 15:46 UTC by adfost

2021-06-04 17:31 UTC, dvaldivia requested changes
Put all the content inside a <Paper> container, you can copy the styling of `Trace.tsx` look at it in action https://play.min.io:9443/trace

2021-06-04 23:34 UTC, dvaldivia commented on logs.log
> +Log file created at: 2021/06/02 16:17:26
remove this file

2021-06-04 23:39 UTC, dvaldivia submitted a review, later dismissed

2021-06-05 00:14 UTC, bexsoft requested changes

2021-06-05 00:14 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Affinity.tsx
> +  }, []);
These variables should not be removed as they are required for the effect to work correctly (We just need to run this effect everytime loading changes)

2021-06-05 00:14 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +  }, []);
Please paste the content of the loadInfo() function inside the effect and remove the `// eslint-disable-next-line react-hooks/exhaustive-deps` comment. After that you just need to add the dependencies to the dependences array.

We need to fix this across the application but will be managed in other ticket

2021-06-05 00:22 UTC, dvaldivia requested changes

2021-06-05 00:22 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/Affinity.tsx
> +import { Button, Grid, IconButton } from "@material-ui/core";
I think these were the changes you did by accident? Just download the latest `Affinity.tsx` from master, and replace it in your PR

2021-06-07 16:47 UTC, dvaldivia approved these changes

2021-06-08 01:54 UTC, dvaldivia approved these changes

2021-06-08 01:55 UTC, bexsoft approved these changes

2021-06-08 01:56 UTC, merged