[WIP] Operator UI security
minio/console pull request #804
Opened 2021-06-10 05:22 UTC by Alevsk

<img width="1477" alt="Screen Shot 2021-06-09 at 22 19 08" src="https://user-images.githubusercontent.com/1795553/121469258-04908680-c971-11eb-9b16-dc922c690b5d.png">

Depends on https://github.com/minio/operator/pull/668

2021-06-17 17:18 UTC, bexsoft requested changes

2021-06-17 17:18 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSecurity.tsx
> +      </Dialog>
Please make this a single component

2021-06-17 21:07 UTC, dvaldivia approved these changes
Tested. LGTM

2021-06-17 21:36 UTC, dvaldivia submitted a review, later dismissed

2021-06-17 22:48 UTC, bexsoft submitted a review, later dismissed

2021-06-18 00:04 UTC, bexsoft approved these changes

2021-06-18 00:30 UTC, dvaldivia approved these changes

2021-06-18 00:30 UTC, merged