Pod Events
minio/console pull request #807
Opened 2021-06-10 22:17 UTC by adfost

2021-06-11 03:46 UTC, bexsoft requested changes

2021-06-11 03:46 UTC, bexsoft commented on pkg/acl/endpoints.go
> -	tenantsDetailLicense        = "/namespaces/:tenantNamespace/tenants/:tenantName/license"
These are required for tenant details, please do not remove

2021-06-11 03:46 UTC, bexsoft commented on pkg/acl/endpoints.go
> -	license:              licenseActionSet,
These are required for tenant details, please do not remove

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Console.tsx
> -    },
These are required for tenant details, please do not remove

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +    loadInfo();
Please use the content of loadInfo function inside this effect and remove the `// eslint-disable-next-line react-hooks/exhaustive-deps`. I think this change shouldn't go

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> -  }, [tenantNamespace, tenantName, podName, setErrorSnackMessage]);
Please use the content of loadInfo function inside this effect and remove the `// eslint-disable-next-line react-hooks/exhaustive-deps`. I think this change shouldn't go

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +              to={`/namespaces/${match.params["tenantNamespace"]}/tenants/${match.params["tenantName"]}`}
Please use tenantNamespace & tenantName variables

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +              {match.params["tenantName"]}
please use tenantName var

2021-06-11 03:46 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +            {` > Pods > ${match.params["podName"]}`}
Please use podName var

2021-06-11 03:46 UTC, bexsoft commented on restapi/admin_tenants.go
> +		var restarts int64 = 0
Please check gofmt checks

2021-06-11 17:14 UTC, dvaldivia commented on pkg/acl/endpoints.go
> -	tenantsDetailLicense        = "/namespaces/:tenantNamespace/tenants/:tenantName/license"
I thought we fix this together @adfost , once you fix this, rebase  and squash to avoid this problem

2021-06-12 00:09 UTC, dvaldivia commented
Can you attach a screenshot of how it looks?

2021-06-12 00:20 UTC, dvaldivia commented
Can you sort the events in ascending order (older on top, newer at the bottom) and group them?

2021-06-12 00:23 UTC, dvaldivia requested changes
Please fix all the warnings introduced on `PodDetails.tsx`

```
src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
  Line 19:8:    'get' is defined but never used                      @typescript-eslint/no-unused-vars
  Line 31:3:    'Button' is defined but never used                   @typescript-eslint/no-unused-vars
  Line 32:3:    'IconButton' is defined but never used               @typescript-eslint/no-unused-vars
  Line 33:3:    'Menu' is defined but never used                     @typescript-eslint/no-unused-vars
  Line 34:3:    'MenuItem' is defined but never used                 @typescript-eslint/no-unused-vars
  Line 48:8:    'history' is defined but never used                  @typescript-eslint/no-unused-vars
  Line 49:10:   'LogMessage' is defined but never used               @typescript-eslint/no-unused-vars
  Line 50:10:   'IPolicyItem' is defined but never used              @typescript-eslint/no-unused-vars
  Line 51:10:   'TabPanel' is defined but never used                 @typescript-eslint/no-unused-vars
  Line 167:10:  'selectedTab' is assigned a value but never used     @typescript-eslint/no-unused-vars
  Line 167:23:  'setSelectedTab' is assigned a value but never used  @typescript-eslint/no-unused-vars
  Line 168:19:  'setLoading' is assigned a value but never used      @typescript-eslint/no-unused-vars
  Line 169:10:  'log' is assigned a value but never used             @typescript-eslint/no-unused-vars

```

2021-06-14 17:17 UTC, dvaldivia commented
While doing  `kubectl get event` I'm seeing the last event, `4 minutes ago` but the UI is showing `6 hours ago`
```
➜ k get event -n ns-2 --field-selector involvedObject.name=asdzxczxc-pool-0-3
LAST SEEN   TYPE      REASON             OBJECT                   MESSAGE
4m41s       Warning   FailedScheduling   pod/asdzxczxc-pool-0-3   0/5 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) were unschedulable, 3 node(s) had volume node affinity conflict.
```

<img width="1185" alt="Screen Shot 2021-06-14 at 10 12 24 AM" src="https://user-images.githubusercontent.com/18384552/121932480-c4772e00-ccf9-11eb-889d-2bf1a1cbf025.png">


The problem is also present in pod listing, where the age of pods is not aligned with theUI

```
➜ k get pods -n ns-1
NAME                                     READY   STATUS    RESTARTS   AGE
asdasd-console-5c5f969756-ghd98          1/1     Running   0          12d
asdasd-log-0                             1/1     Running   0          12d
asdasd-log-search-api-657dffbcb8-9ln74   1/1     Running   3          12d
asdasd-pool-0-0                          1/1     Running   0          7m3s
asdasd-pool-0-1                          1/1     Running   0          12d
asdasd-pool-0-2                          1/1     Running   0          12d
asdasd-pool-0-3                          1/1     Running   0          12d
asdasd-prometheus-0                      2/2     Running   0          12d
```

<img width="1701" alt="Screen Shot 2021-06-14 at 10 17 35 AM" src="https://user-images.githubusercontent.com/18384552/121932448-be814d00-ccf9-11eb-90c5-46e5d2b62377.png">

2021-06-14 18:04 UTC, dvaldivia requested changes

2021-06-14 18:04 UTC, dvaldivia commented on swagger.yml
> +      lastseen:
rename this to `last_seen`
Change type to `integer` of `format: int64`

2021-06-14 18:04 UTC, dvaldivia commented on restapi/admin_tenants.go
> +			Lastseen:  fmt.Sprintf("%d", events.Items[i].LastTimestamp.Unix()),
the `.Unix()` already returns `int64`, store the integer that way

2021-06-14 23:01 UTC, dvaldivia requested changes

2021-06-14 23:01 UTC, dvaldivia commented on portal-ui/src/screens/Console/Account/Account.tsx
> +  const [selectedServiceAccount, setSelectedServiceAccount] =
this needs to be formatted with prettier `2.3.1`

2021-06-15 03:52 UTC, bexsoft requested changes

2021-06-15 03:52 UTC, bexsoft commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please remove this file

2021-06-15 03:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +    loadInfo();
Please review this

2021-06-15 17:47 UTC, dvaldivia commented
<img width="1552" alt="Screen Shot 2021-06-15 at 10 46 47 AM" src="https://user-images.githubusercontent.com/18384552/122099571-ff936300-cdc6-11eb-8479-ea2531cade0a.png">

I'm getting events that are not related to the pod in question

2021-06-15 17:57 UTC, dvaldivia requested changes

2021-06-15 17:57 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +        setLog(res);
remove `setLog` since `log` is not used

2021-06-15 19:09 UTC, dvaldivia requested changes

2021-06-15 19:09 UTC, dvaldivia commented on consoleAdmin.json
> +{
please remove this file

2021-06-17 00:13 UTC, dvaldivia requested changes

2021-06-17 00:13 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +  const [log, setLog] = useState<string>("");
remove unused lines

2021-06-17 00:30 UTC, dvaldivia requested changes

2021-06-17 00:30 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PodDetails.tsx
> +              isLoading={false}
do show a loading indicator

2021-06-17 19:00 UTC, dvaldivia submitted a review, later dismissed

2021-06-17 19:30 UTC, dvaldivia requested changes
don't delete md files

2021-06-17 21:10 UTC, dvaldivia submitted a review, later dismissed

2021-06-17 21:11 UTC, dvaldivia approved these changes

2021-06-17 22:25 UTC, bexsoft approved these changes

2021-06-17 23:24 UTC, merged