Add Filtering to Users on Policy Details
minio/console pull request #833
Opened 2021-06-23 18:34 UTC by adfost

Adding filtering to Users on Policy Details <img width="1213" alt="123018790-0bad9080-d384-11eb-98a5-d0fd8ce96497" src="https://user-images.githubusercontent.com/15642172/123150188-ee75d200-d416-11eb-8c9d-4cfd6b835987.png">

2021-06-23 18:51 UTC, dvaldivia requested changes

2021-06-23 18:51 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +            var resultUserArray = result.map((x: string) => {
why not filter on an array of strings? I think it's simpler and needs less code

2021-06-23 22:23 UTC, dvaldivia requested changes

2021-06-23 22:23 UTC, dvaldivia commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +            console.log("Error in loading users");
display the error when loading users.
also se `setLoadingUsers(false);` on error

2021-06-23 22:23 UTC, dvaldivia commented on portal-ui/src/screens/Console/Users/types.tsx
> +  name?: string;
is this change still needed?

2021-06-24 01:40 UTC, dvaldivia approved these changes

2021-06-24 03:03 UTC, bexsoft approved these changes
LGTM

2021-06-24 03:03 UTC, merged