add build tags to separate operator code
minio/console pull request #839
Opened 2021-06-26 19:46 UTC by harshavardhana

2021-06-28 16:15 UTC, harshavardhana commented
I haven't changed the UI side of things here for separation, I am assuming that will be done by @bexsoft @dvaldivia ??

2021-06-28 22:00 UTC, dvaldivia requested changes

2021-06-28 22:00 UTC, dvaldivia commented on restapi/admin_subscription.go
> +// retrieveLicense returns license from the configured CONSOLE_SUBNET_LICENSE environment variable
we probably need this for license APIs to work,let me address that first on another PR

2021-06-29 02:24 UTC, harshavardhana commented on restapi/admin_subscription.go
> +// retrieveLicense returns license from the configured CONSOLE_SUBNET_LICENSE environment variable
oh okay - can you check with the handlers do get registered correctly? - because all I did was attempt curl and check.

2021-09-14 00:59 UTC, dvaldivia commented
I think this is not needed anymore is it?

2021-09-14 04:01 UTC, closed without merging