Responsive License Page via Flex
minio/console pull request #843
Opened 2021-06-29 01:35 UTC by Alevsk

<img width="1097" alt="Screen Shot 2021-06-28 at 18 31 30" src="https://user-images.githubusercontent.com/1795553/123723613-9b998180-d83f-11eb-81c4-72e24df6bc0a.png">
<img width="1656" alt="Screen Shot 2021-06-28 at 18 31 02" src="https://user-images.githubusercontent.com/1795553/123723620-9f2d0880-d83f-11eb-9632-f414fcbec533.png">

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

2021-06-29 17:35 UTC, dvaldivia submitted a review, later dismissed

2021-06-29 21:17 UTC, dvaldivia approved these changes

2021-06-29 21:24 UTC, jinapurapu approved these changes

2021-06-29 21:29 UTC, adfost approved these changes

2021-06-30 01:51 UTC, bexsoft requested changes

2021-06-30 01:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/TenantSecurity.tsx
>  // You should have received a copy of the GNU Affero General Public License
Are these changes correct? I think this is non-related to license page

2021-06-30 02:18 UTC, bexsoft approved these changes
Talked with @Alevsk, File is only formatted, LGTM

2021-06-30 02:18 UTC, merged