Delete pods from tenant pods list
minio/console pull request #844
Opened 2021-07-01 03:39 UTC by adfost

Feature to delete pods from list of pods in tenant
<img width="1309" alt="Screen Shot 2021-06-30 at 8 35 03 PM" src="https://user-images.githubusercontent.com/15642172/124061194-4f874200-d9e3-11eb-9f53-6d0427d32c06.png">

2021-07-01 16:52 UTC, dvaldivia requested changes

2021-07-01 16:52 UTC, dvaldivia commented on restapi/admin_tenants.go
> +	if err = clientset.CoreV1().Pods(params.Namespace).DeleteCollection(ctx, metav1.DeleteOptions{}, metav1.ListOptions{FieldSelector: fmt.Sprintf("metadata.name=%s%s", params.Tenant, params.PodName[len
I can imagine someone can still exploit this to delete other pods that are used by the tenant, or by chance start with the same prefix. A more robust check would be field selector `metadata.name=<POD NAME>` and label selector `v1.min.io/tenant=<TENANT NAME>`

2021-07-01 18:30 UTC, dvaldivia approved these changes

2021-07-06 22:40 UTC, jinapurapu commented on portal-ui/src/screens/Console/Tenants/TenantDetails/DeletePod.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Should this be removed?

2021-07-08 02:02 UTC, Alevsk approved these changes

2021-07-09 16:56 UTC, merged