Add page for Remote buckets
minio/console pull request #850
Opened 2021-07-06 19:22 UTC by adfost

Adding a new page to the menu to view remote buckets.
<img width="1211" alt="Screen Shot 2021-07-01 at 3 25 23 PM" src="https://user-images.githubusercontent.com/15642172/124655480-c0e84a00-de54-11eb-956f-d50d346bdac3.png">

2021-07-08 02:06 UTC, Alevsk commented
@adfost does this new `/remote-buckets` page needs a new entry on the `acl.go` file ?

2021-07-15 17:29 UTC, bexsoft requested changes

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +    },
This style is not needed

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +    },
This style is not needed

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +    },
This style is not needed

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +    },
These styles are not needed

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +interface IListBucketsProps {
Would be better to rename this as `IListRemoteBucketsProps`

```suggestion
interface IListRemoteBucketsProps {
```

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +      )}
This is tied to local bucket creation. I don't think we need this modal here as we are talking of different scopes.

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +      )}
In this case I don't think we can delete remote buckets from local environment

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +      )}
This modal was meant for local buckets to be replicated to remote targets. This screen should list remote targets only so this is not needed here

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +              placeholder="Search Buckets"
```suggestion
              placeholder="Search Remote Buckets"
```

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +              </Button>
These buttons are meant for local targets only, anything you do with these modals will not appear in this module

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +              entityName="RemoteBuckets"
```suggestion
              entityName="Remote Buckets"
```

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListRemoteBuckets.tsx
> +  };
This is not used. Please remove

2021-07-15 17:29 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/RemoteBuckets.tsx
> +        <Route path="/remote-buckets/:bucketName" component={BucketDetails} />
You need to add these paths to endpoints.go.

2021-07-15 17:31 UTC, bexsoft commented
Please remabe with master

2021-07-22 21:10 UTC, closed without merging