PVC Tenants link
minio/console pull request #851
Opened 2021-07-06 19:30 UTC by adfost

Link to Tenants from PVC page

<img width="1224" alt="Screen Shot 2021-07-06 at 12 28 59 PM" src="https://user-images.githubusercontent.com/15642172/124656349-efb2f000-de55-11eb-9b52-247416cebf91.png">

2021-07-08 02:03 UTC, Alevsk approved these changes

2021-07-13 18:29 UTC, dvaldivia requested changes
these need to link to the Tenant who owns the PVC

2021-07-15 17:34 UTC, bexsoft requested changes

2021-07-15 17:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/Storage.tsx
> +            Storage:
Please add an space next to Storage:

```suggestion
            Storage:&nbsp;
```

2021-07-15 17:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/Storage.tsx
> +            <Link to={"/tenants"} className={classes.breadcrumLink}>
Please make this link to point to the tenant who has this PVC attached

2021-07-15 17:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/Storage.tsx
> +              Tenants
I this is better to place the name of the tenant here instead of a `Tenants` label

2021-07-22 21:10 UTC, closed without merging