Integer input for NiceBytes and NiceDays
minio/console pull request #852
Opened 2021-07-07 06:41 UTC by adfost

Added the functions NiceBytesInt and NiceDaysInt in order to use integers instead of strings for input. In order to maintain backwards compatibility, I retained NiceBytes and NiceDays with string input, although I changed them to call the new functions to simplify the code. As this was utility change not sure what image to add.

2021-07-07 07:16 UTC, harshavardhana requested changes

2021-07-07 07:16 UTC, harshavardhana commented on portal-ui/src/common/utils.ts
>    }`;
are there no javascript packages that provide humanize helpers? why are we doing this manually?

2021-07-08 16:10 UTC, adfost commented on portal-ui/src/common/utils.ts
>    }`;
This was the same code I got before.

2021-07-08 16:10 UTC, adfost commented on portal-ui/src/common/utils.ts
>    }`;
just modified the inputs

2021-07-09 16:46 UTC, dvaldivia submitted a review, later dismissed

2021-07-13 18:29 UTC, dvaldivia approved these changes

2021-07-16 23:52 UTC, harshavardhana approved these changes

2021-07-16 23:53 UTC, merged