Delete multiple objects
minio/console pull request #856
Opened 2021-07-08 19:47 UTC by adfost

Delete multiple objects using selectors on object list

<img width="1227" alt="Screen Shot 2021-07-08 at 12 44 02 PM" src="https://user-images.githubusercontent.com/15642172/124981604-99c38100-dfea-11eb-9484-d7ee5a4b1662.png">

2021-07-09 16:53 UTC, dvaldivia commented
When the button for `Delete Selected` becomes enabled, the icon keeps it's original color so it can't be seen, it should flip to white, same for the font, 

<img width="1241" alt="Screen Shot 2021-07-09 at 9 51 40 AM" src="https://user-images.githubusercontent.com/18384552/125111859-452c0e80-e09b-11eb-8f6d-8a6242dc2a02.png">


After deleting an object, the button doesn't reset to it's original state

<img width="1252" alt="Screen Shot 2021-07-09 at 9 52 44 AM" src="https://user-images.githubusercontent.com/18384552/125112007-786e9d80-e09b-11eb-8b7e-dbab22e1351b.png">

2021-07-14 00:05 UTC, dvaldivia approved these changes
testd. lgtm

2021-07-14 00:12 UTC, Alevsk requested changes

2021-07-14 00:12 UTC, Alevsk commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/DeleteMultipleObjects.tsx
> +            }
This will trigger multiple delete object calls, and the `removeRecord` inside has

```
        setDeleteLoading(false);
        closeDeleteModalAndRefresh(true);
```

that will be called multiple times as well, @adfost its better to implement a new endpoint called bulkDelete that receive a list of object IDs and then perform the delete operations on the backend, once all objects are deleted you return operation success to the frontend, that way you will have only 1 call instead of multiple ones

2021-07-15 18:33 UTC, bexsoft requested changes

2021-07-15 18:33 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/DeleteMultipleObjects.tsx
> +        `/api/v1/buckets/${selectedBucket}/delete-multiple?path=${selectedObjects}&recursive=${recursive}`
If we are sending multiple paths to delete, I think it's better so send them in the body of the request as a string array instead of sending them in the query. This may cause troubles in the future.

Please change API accordingly

```suggestion
        `/api/v1/buckets/${selectedBucket}/delete-multiple?recursive=${recursive}`, {path: selectedObjects}
```

2021-07-15 18:33 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +            </Button>
Please change the position of this button as this is not the main action that we want to promote. Please change it before the create folder button:

<img width="1241" alt="125111859-452c0e80-e09b-11eb-8f6d-8a6242dc2a02" src="https://user-images.githubusercontent.com/33497058/125839466-fca43aa8-11ad-4384-8bed-78686f0ef39f.png">

2021-07-19 17:44 UTC, bexsoft submitted a review, later dismissed

2021-07-19 17:57 UTC, dvaldivia requested changes

2021-07-19 17:57 UTC, dvaldivia commented on restapi/user_objects.go
> +		s3Client, err := newS3BucketClient(session, params.BucketName, params.PathName[i])
This is inefficient, initialize the client just once.

2021-07-19 17:57 UTC, dvaldivia commented on swagger.yml
> +  /buckets/{bucket_name}/delete-multiple/{path_name}:
`/buckets/{bucket_name}/delete-objects`

2021-07-20 22:26 UTC, dvaldivia approved these changes
Tested. LGTM

2021-07-21 22:44 UTC, Alevsk approved these changes

2021-07-21 22:45 UTC, dvaldivia submitted a review, later dismissed

2021-07-21 22:45 UTC, dvaldivia approved these changes

2021-07-21 22:48 UTC, bexsoft approved these changes

2021-07-21 22:49 UTC, merged