Fix escape characters in filename.
minio/console pull request #859
Opened 2021-07-09 19:58 UTC by adfost

Automatically convert escape characters in filenames, so there is no problem with deleting such files.

2021-07-14 00:01 UTC, dvaldivia requested changes
This doesn't fix the issue, I have a file called `02%20-%20FLY%20ME%20TO%20THE%20MOON%20.mp3` which I copied to my bucket, that's the actual name of the file, I cannot delete it via browser

example on loading the file:

```
➜ ls 02%20-%20FLY%20ME%20TO%20THE%20MOON%20.mp3 
02%20-%20FLY%20ME%20TO%20THE%20MOON%20.mp3
➜ mc cp 02%20-%20FLY%20ME%20TO%20THE%20MOON%20.mp3 play/000test/
...E%20MOON%20.mp3:  5.90 MiB / 5.90 MiB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  2.25 MiB/s 2s console git:(3b8bbce70) ✗ 
➜ mc ls play/000test                                            
[2021-07-13 17:00:09 PDT] 5.9MiB 02%20-%20FLY%20ME%20TO%20THE%20MOON%20.mp3
```

2021-07-14 02:08 UTC, harshavardhana requested changes
You can't unescape in this style you generally get the object in URL encoded form in the list response.

This needs to be converted on the client side which - minio-go already does.

The way the conversion should happen is such that when the object name is selected to delete the server handler component in console should convert back the file component and send it to DeleteObject()

Note there are several nuances here that needs to be understood so just the UI side fix is not enough.

2021-07-15 18:35 UTC, bexsoft commented
What ticket is this PR fixing?

2021-07-15 18:51 UTC, dvaldivia commented
@bexsoft it's the problem when trying to delete files with weird characters

2021-07-19 19:26 UTC, harshavardhana commented
The fundamental problem we found here is related to swagger marshalling which is causing incompatibilities, swagger marshaller is wrongly detecting filenames and percentage encoded characters incorrectly which leads to completely incorrect values. 

So the correct fix here is we write a custom marshaller for specific structs that populates object names to avoid URL encoding of object key names.

2021-07-19 19:42 UTC, dvaldivia commented
@harshavardhana it's a simpler problem imo, from the client we need to html encode and then decode on the server to avoid the other decoders, this will solve the issue

2021-07-19 19:42 UTC, closed without merging

2021-07-19 19:50 UTC, harshavardhana commented
> @harshavardhana it's a simpler problem imo, from the client we need to html encode and then decode on the server to avoid the other decoders, this will solve the issue

No it is not @dvaldivia there is more context missing first of all swagger should never actually encode and decode values. 

Doing that causes problems for the WebUI and you cannot safely assume escape sequences on the UI since you lack the context on the object names presented.