fix: remove response timeouts for console
minio/console pull request #864
Opened 2021-07-13 22:29 UTC by harshavardhana

2021-07-13 23:47 UTC, dvaldivia requested changes

2021-07-13 23:47 UTC, dvaldivia commented on cmd/console/server.go
> +	// set conservative timesout for uploads
this is an auto-generated file we should see this values on `configure_console.go`

2021-07-14 01:07 UTC, harshavardhana commented on cmd/console/server.go
> +	// set conservative timesout for uploads
`cmd/console/server.go` is not an autogenerated file @dvaldivia

2021-07-14 18:29 UTC, dvaldivia approved these changes

2021-07-14 18:29 UTC, merged