Improve Object Download
minio/console pull request #867
Opened 2021-07-14 20:00 UTC by dvaldivia

Introduces native browser file download behavior 

<img width="426" alt="Screen Shot 2021-07-14 at 12 54 12 PM" src="https://user-images.githubusercontent.com/18384552/125685239-429f8c33-d0a5-4ad2-95ed-f1f144aa918a.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-07-14 20:05 UTC, harshavardhana requested changes

2021-07-14 20:05 UTC, harshavardhana commented on restapi/user_objects.go
> +			stat, err := resp.(*minio.Object).Stat()
```suggestion
			stat, err := resp.(*minio.Object).Stat()
```

Do not ignore the error, log it or return it to the handler

2021-07-14 20:05 UTC, harshavardhana commented on restapi/user_objects.go
> +			rw.Header().Set("Content-Type", "application/octet-stream")
stat.ContentType

2021-07-14 20:08 UTC, dvaldivia commented on restapi/user_objects.go
> +			stat, err := resp.(*minio.Object).Stat()
solved

2021-07-15 18:45 UTC, bexsoft requested changes
Not sure if I have something missing, I downloaded the new code, restarted my server & frontend but when I try to download any file the page reloads and redirects me to dashboard. Not sure if some route is missing in endpoints.go:

![2021-07-15 13-41-39 2021-07-15 13_43_11](https://user-images.githubusercontent.com/33497058/125840884-9c7e9cdc-4d20-4ab4-ac54-41bad82bfb38.gif)

2021-07-15 18:50 UTC, dvaldivia commented
@bexsoft this feature doesn't work through the React development server, try this using the final go server with the commited assets on port `9090`

2021-07-15 19:08 UTC, bexsoft commented
> @bexsoft this feature doesn't work through the React development server, try this using the final go server with the commited assets on port `9090`

I see, please add this information to the PR to avoid confusion

2021-07-15 19:12 UTC, dvaldivia commented
@bexsoft done

2021-07-15 19:17 UTC, bexsoft requested changes
Please reset the state of `downloadingFiles` reducer as it keeps in loading state even when download has already completed

![2021-07-15 14-09-06 2021-07-15 14_14_32](https://user-images.githubusercontent.com/33497058/125844807-60e2f015-8fe5-4ac9-8345-eb7ac6479157.gif)

2021-07-15 19:27 UTC, dvaldivia commented
@bexsoft done

2021-07-15 20:00 UTC, bexsoft approved these changes

2021-07-15 20:25 UTC, harshavardhana approved these changes

2021-07-15 20:26 UTC, merged