Support to Hop into tenants
minio/console pull request #878
Opened 2021-07-20 21:23 UTC by dvaldivia

This adds the capability to browse tenants as an admin from the Tenant Details screen

<img width="1557" alt="Screen Shot 2021-07-20 at 2 15 11 PM" src="https://user-images.githubusercontent.com/18384552/126397177-de191ba9-b093-4d79-b9e9-8621945f79fa.png">
<img width="1557" alt="Screen Shot 2021-07-20 at 2 15 08 PM" src="https://user-images.githubusercontent.com/18384552/126397181-cd724701-c39a-4cc0-b270-85b8cae953f2.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-07-20 23:51 UTC, bexsoft requested changes

2021-07-20 23:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/hop/Hop.tsx
> +          <div style={{ width: "100px", margin: "auto", marginTop: "80px" }}>
Please not hardcode styles, add them as a class in createStyles

2021-07-20 23:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/hop/Hop.tsx
> +      border: "0px",
Please change this to be integer
```suggestion
      border: 0,
```

2021-07-20 23:51 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/hop/Hop.tsx
> +      top: "77px",
Please change this to integer values
```suggestion
      left: 0,
      top: 77,
```

2021-07-21 01:27 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/TenantDetails/hop/Hop.tsx
> +          <div style={{ width: "100px", margin: "auto", marginTop: "80px" }}>
done

2021-07-21 04:30 UTC, bexsoft submitted a review, later dismissed
LGTM

2021-07-21 21:57 UTC, Alevsk submitted a review, later dismissed

2021-07-21 22:08 UTC, bexsoft approved these changes

2021-07-21 22:09 UTC, Alevsk approved these changes

2021-07-21 22:09 UTC, merged