Remove Operator mode references in Console mode
minio/console pull request #884
Opened 2021-07-21 02:20 UTC by dvaldivia

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-07-21 17:18 UTC, bexsoft requested changes
I cannot login to operator using JWT after this change, I'm getting this error:
```
I: 2021/07/21 12:16:53 Serving operator at http://[::]:9090
E: 2021/07/21 12:16:58 Refreshing subnet license failed: no license present
E: 2021/07/21 12:17:00 original error -> (operator_login.go:76: credentials endpoint, access and secret key are mandatory for AssumeRoleSTS)
```

2021-07-21 22:10 UTC, dvaldivia commented
@bexsoft I fixed that, I'm adding latest assets to this PR as well

2021-07-21 22:29 UTC, bexsoft submitted a review, later dismissed

2021-07-21 23:14 UTC, bexsoft approved these changes

2021-07-21 23:17 UTC, bexsoft approved these changes

2021-07-22 17:56 UTC, bexsoft approved these changes

2021-07-22 18:16 UTC, Alevsk approved these changes

2021-07-22 18:17 UTC, merged