New link
minio/console pull request #893
Opened 2021-07-22 22:22 UTC by adfost

Fixed comments from old PVC tenants link PR, adding link to tenant on PVC page 
<img width="1006" alt="Screen Shot 2021-07-22 at 3 22 04 PM" src="https://user-images.githubusercontent.com/15642172/126716813-10a4c364-5459-4c8d-928d-c93931040d45.png">

2021-07-22 22:24 UTC, dvaldivia requested changes

2021-07-22 22:24 UTC, dvaldivia commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
>                label: "Volume",
Change the label to `Tenant`

2021-07-22 22:24 UTC, dvaldivia commented on restapi/embedded_spec.go
>      },
these should not be deleted, please rebase and do `make swagger-gen`

2021-07-22 22:44 UTC, dvaldivia submitted a review, later dismissed

2021-07-22 23:08 UTC, bexsoft requested changes

2021-07-22 23:08 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +  // @ts-ignore
Please, do not use this, this is a bad practice

2021-07-22 23:08 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +          idField="id"
`id` field doesn't exist under `IStoragePVCs` type. Please change this for `name` or other variable

2021-07-23 01:57 UTC, bexsoft requested changes
Beside of that, works & LGTM

2021-07-23 01:57 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +  ];
Please apply prettier to these lines. (You can generate assets)

2021-07-23 01:57 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +              },
Function can be simplified:

```suggestion
              renderFunction: (record: any) => `${record.namespace}/${record.tenant}`,
```

2021-07-23 16:46 UTC, adfost commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +  ];
This is outdated after fix.

2021-07-23 17:17 UTC, dvaldivia approved these changes
LGTM.

2021-07-23 17:34 UTC, bexsoft approved these changes
LGTM

2021-07-23 17:34 UTC, merged