Fixed encoding & URL issues for users & groups pages
minio/console pull request #896
Opened 2021-07-23 23:40 UTC by bexsoft

fixes https://github.com/minio/console/issues/752

## What does this do?

Fixes an issue with encoding & users

## How does it look?

<img width="1162" alt="Screen Shot 2021-07-23 at 18 35 13" src="https://user-images.githubusercontent.com/33497058/126850448-6713fcb2-60a2-43c8-8691-7e6eec612993.png">
<img width="967" alt="Screen Shot 2021-07-23 at 18 34 10" src="https://user-images.githubusercontent.com/33497058/126850450-434389e8-1652-4b2e-a9d9-6e1befdeaabb.png">

2021-07-23 23:49 UTC, dvaldivia requested changes

2021-07-23 23:49 UTC, dvaldivia commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> +    console.log(encodeURI(selectionElement.accessKey));
remove

2021-07-23 23:49 UTC, dvaldivia commented on swagger-console.yml
> +  /user/groups:
I think we should keep `{name}` in the URL, as this is more RESTful, for the resource `{user}` put this or get that

2021-07-24 00:05 UTC, bexsoft commented on swagger-console.yml
> +  /user/groups:
This is causing issues with names that contain slashes, that is why I changed it to be in query instead. Also I changed to be singular to handle this

2021-07-24 00:11 UTC, dvaldivia commented on swagger-console.yml
> +  /user/groups:
ok, that makes sense then

2021-07-24 00:12 UTC, dvaldivia approved these changes

2021-07-24 00:16 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> +    console.log(encodeURI(selectionElement.accessKey));
```suggestion
    
```

2021-07-24 01:07 UTC, Alevsk approved these changes

2021-07-24 01:37 UTC, harshavardhana approved these changes

2021-07-24 01:37 UTC, merged