Changing error for too few nodes
minio/console pull request #899
Opened 2021-07-27 18:18 UTC by adfost

<img width="1001" alt="Screen Shot 2021-07-27 at 11 18 24 AM" src="https://user-images.githubusercontent.com/15642172/127206908-f4214f20-691a-407c-b0fd-9e7fa7989e68.png">
New error message.

2021-07-27 18:50 UTC, dvaldivia requested changes

2021-07-27 18:50 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantSize.tsx
> +    console.log(memoSize)
please remove

2021-07-27 18:50 UTC, dvaldivia commented on operatorapi/operator_nodes.go
> +		return nil, errTooFewNodes
I think you are missing the following scenario

- `When user has enough nodes (4 or more) but not enough nodes are schedulable.` This can be another error

you are already checking for schedulable nodes, so just add a condition for that situation, return the current error if `len(node.Items) < 4` and the other message for when there's not enough schedulable nodes

2021-07-28 16:30 UTC, dvaldivia requested changes

2021-07-28 16:30 UTC, dvaldivia commented on operatorapi/operator_nodes.go
> +	if len(nodes.Items) < int(numNodes) {
```suggestion
	if int(numNodes) < 4 {
```

2021-07-28 16:33 UTC, dvaldivia requested changes

2021-07-28 16:33 UTC, dvaldivia commented on operatorapi/operator_nodes.go
> +	if int(numNodes) < 4 {
move this validation to run before we even get the nodes from the k8s api

2021-07-28 16:56 UTC, adfost commented on operatorapi/operator_nodes.go
> +	if int(numNodes) < 4 {
This is from an old branch, I'm not checking whether numNodes < 4

2021-07-28 16:59 UTC, bexsoft requested changes

2021-07-28 16:59 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantSize.tsx
> +          updateField("memorySize", {error: err});
This change is incorrect, the function is meant only for changing the value of a field. If you want to add an error, you must add it in the `commonFormValidation` effect.

2021-07-29 21:38 UTC, dvaldivia requested changes

2021-07-29 21:38 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantSize.tsx
> +            console.log("here")
remove this console.log

2021-07-29 21:38 UTC, dvaldivia commented on portal-ui/src/screens/Console/Tenants/AddTenant/Steps/TenantSize.tsx
> +          if (err.errorMessage === "at least 4 nodes are required in cluster" || err.errorMessage === "at least 4 schedulable nodes are required in cluster") {
if you are getting this message from the API, just show it, it's detailed enough.

2021-08-02 17:51 UTC, dvaldivia approved these changes

2021-08-02 18:07 UTC, bexsoft approved these changes

2021-08-02 18:33 UTC, merged