Select policies while creating new user
minio/console pull request #928
Opened 2021-08-05 19:41 UTC by dvaldivia

Also removed some duplicate structures in `swagger-operator.yaml`

<img width="784" alt="Screen Shot 2021-08-05 at 12 37 52 PM" src="https://user-images.githubusercontent.com/18384552/128410959-77af84cf-a78c-4af8-a927-835ce510dc15.png">

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

2021-08-05 19:44 UTC, harshavardhana approved these changes

2021-08-05 20:17 UTC, adfost submitted a review, later dismissed

2021-08-06 02:10 UTC, bexsoft requested changes
There is an issue where if I set groups to a user, the policy list is returned as empty in `api/v1/user?name=<user_name>` request. Also during the create user query the policies are not returned in the response

2021-08-06 18:45 UTC, dvaldivia commented
@bexsoft fixed

2021-08-06 19:13 UTC, bexsoft approved these changes
LGTM, Works fine

2021-08-06 23:41 UTC, harshavardhana approved these changes

2021-08-06 23:41 UTC, merged