Prefix policies
minio/console pull request #941
Opened 2021-08-11 22:45 UTC by adfost

<img width="1045" alt="Screen Shot 2021-08-11 at 3 44 22 PM" src="https://user-images.githubusercontent.com/15642172/129113182-e9aea0d9-504c-4518-b500-8963b1b897e2.png">

API and UI for viewing, adding (automatically including editing), and deleting prefix policies. Handling https://github.com/minio/console/issues/907

2021-08-12 04:09 UTC, bexsoft requested changes
Please review go-lint issues

2021-08-12 16:35 UTC, dvaldivia requested changes
The underlying `mc` api used for this feature is referred to as `access`, this feature should be called `Access Rules`.

Please add a description of the feature in the PR description and update the title.

2021-08-12 16:44 UTC, dvaldivia requested changes
after adding a new access rule the list of items does't refresh.

There's no `none` option in the old access rules

<img width="668" alt="Screen Shot 2021-08-12 at 9 43 06 AM" src="https://user-images.githubusercontent.com/18384552/129235482-6b966623-3b4f-46d8-b69d-5d61d74df0c9.png">

Change the title of the add button to `Add Access Rule` since it's not clear how the edit would work

<img width="241" alt="Screen Shot 2021-08-12 at 9 44 30 AM" src="https://user-images.githubusercontent.com/18384552/129235629-9d15e061-cca1-46c5-b5a1-0c5f9701cccf.png">

2021-08-16 18:23 UTC, bexsoft requested changes
Please review assets again as I think there are some unnecessary files here

2021-08-16 18:23 UTC, bexsoft commented on restapi/user_objects.go
> +			//UserMetadata:   lsObj.UserMetadata,
This line should not be removed as it breaks metadata info in object details

2021-08-16 18:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AccessRulePanel.tsx
> +      onClick: (accessRule: any) => {
Please add a confirmation modal before deleting a rule. That is the pattern we are following in other screens

2021-08-16 18:23 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/AddAccessRule.tsx
> +import React, {useCallback, useEffect, useState} from "react";
Please remove unused dependencies
```suggestion
import React, {useState} from "react";
```

2021-08-16 18:24 UTC, bexsoft commented
> after adding a new access rule the list of items does't refresh.
> 
> There's no `none` option in the old access rules
> 
> <img alt="Screen Shot 2021-08-12 at 9 43 06 AM" width="668" src="https://user-images.githubusercontent.com/18384552/129235482-6b966623-3b4f-46d8-b69d-5d61d74df0c9.png">
> 
> Change the title of the add button to `Add Access Rule` since it's not clear how the edit would work
> 
> <img alt="Screen Shot 2021-08-12 at 9 44 30 AM" width="241" src="https://user-images.githubusercontent.com/18384552/129235629-9d15e061-cca1-46c5-b5a1-0c5f9701cccf.png">

This is still missing too

2021-08-16 20:48 UTC, dvaldivia submitted a review, later dismissed
Tested. LGTM

2021-08-16 22:10 UTC, dvaldivia submitted a review, later dismissed

2021-08-16 22:47 UTC, bexsoft requested changes

2021-08-16 22:47 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/DeleteAccessRule.tsx
> +      .invoke("PUT", `/api/v1/bucket/${bucket}/access-rules`, {
I think this call should be a DELETE instead of PUT. Calls should be independent to be RESTful compliant, WDYT? @dvaldivia

2021-08-16 22:52 UTC, dvaldivia commented on portal-ui/src/screens/Console/Buckets/BucketDetails/DeleteAccessRule.tsx
> +      .invoke("PUT", `/api/v1/bucket/${bucket}/access-rules`, {
agree

2021-08-16 23:54 UTC, bexsoft approved these changes
LGTM

2021-08-17 02:41 UTC, dvaldivia approved these changes

2021-08-17 02:41 UTC, merged