Added pre validation of prometheus URL
minio/console pull request #956
Opened 2021-08-17 04:57 UTC by bexsoft

## What does this do?

Adds a pre-validation to prometheus URL, so we can avoid long timeouts & unnecessary requests that will fail if URL is unreachable

## How does it look?
<img width="1967" alt="Screen Shot 2021-08-16 at 23 45 18" src="https://user-images.githubusercontent.com/33497058/129665997-8f09f15f-95d8-4d1c-ac14-03a3bd5930a0.png">

2021-08-17 05:06 UTC, harshavardhana commented on restapi/admin_info.go
> +
Do not attempt a non-TLS dial @bexsoft we should do a full HTTP call such as make a call to 

```
ctx, cancel := context.WithTimeout(context.Background(), 2 * time.Second)
defer cancel()
...
req, err := http.NewRequestWithTimeout(ctx, http.MethodGet, URL+"/-/healthy", nil)
...

then use 
GetConsoleHTTPClient().Do(req)
```

2021-08-17 05:49 UTC, dvaldivia approved these changes

2021-08-17 17:44 UTC, bexsoft commented on restapi/admin_info.go
> +
Sounds good, changes applied

2021-08-17 17:45 UTC, dvaldivia approved these changes

2021-08-17 17:47 UTC, harshavardhana requested changes

2021-08-17 17:47 UTC, harshavardhana commented on restapi/admin_info.go
> +	return false
```suggestion
        return response.StatusCode == http.StatusOK
```

2021-08-17 17:47 UTC, harshavardhana commented on restapi/admin_info.go
> +	response, err2 := GetConsoleHTTPClient().Do(req)
```suggestion
	response, err := GetConsoleHTTPClient().Do(req)
```
Simplify

2021-08-17 17:47 UTC, harshavardhana commented on restapi/admin_info.go
> +	if err2 != nil {
```suggestion
	if err != nil {
```

2021-08-17 18:00 UTC, bexsoft commented on restapi/admin_info.go
> +	return false
done

2021-08-17 18:00 UTC, bexsoft commented on restapi/admin_info.go
> +	if err2 != nil {
done

2021-08-17 18:00 UTC, bexsoft commented on restapi/admin_info.go
> +	response, err2 := GetConsoleHTTPClient().Do(req)
done

2021-08-17 18:17 UTC, dvaldivia approved these changes

2021-08-17 19:02 UTC, harshavardhana approved these changes

2021-08-17 19:02 UTC, merged

2021-08-22 08:10 UTC, wasilak commented
Hey guys, new validation broke integration with [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics), which is Prometheus compatible database, but unfortunately doesn't have `/-/healthy` endpoint.