Edit Access Rules
minio/console pull request #959
Opened 2021-08-17 20:35 UTC by adfost

New Modal for editing access rules
<img width="1045" alt="Screen Shot 2021-08-17 at 1 35 19 PM" src="https://user-images.githubusercontent.com/15642172/129796832-d8fbf59f-ac94-4218-9057-c0211088b023.png">

2021-08-17 21:56 UTC, dvaldivia submitted a review, later dismissed
Tested LGTM.

2021-08-18 00:39 UTC, bexsoft requested changes
Beside of that, LGTM, works fine

2021-08-18 00:39 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/BucketDetails/EditAccessRule.tsx
> +import InputBoxWrapper from "../../Common/FormComponents/InputBoxWrapper/InputBoxWrapper";
Please remove this dependency as it is not needed

2021-08-18 20:58 UTC, dvaldivia approved these changes

2021-08-18 20:58 UTC, merged