Add user service account
minio/console pull request #966
Opened 2021-08-20 19:22 UTC by adfost

Adds a feature to allow service accounts to be created for another user

<img width="873" alt="Screen Shot 2021-08-20 at 12 21 31 PM" src="https://user-images.githubusercontent.com/15642172/130283599-b1e95272-1346-4210-90c9-a300a57338b5.png">

2021-08-21 02:34 UTC, bexsoft requested changes
Please assign the PR to yourself:
<img width="338" alt="Screen Shot 2021-08-20 at 21 25 33" src="https://user-images.githubusercontent.com/33497058/130307681-8c4b917e-c9ac-4f21-9308-bbf9b53ade44.png">

There is a strange issue, where after adding a couple of service accounts, if I try once more, system throws me : `original error -> (user_service_accounts.go:45: The specified user does not exist. (Specified user does not exist))` and logs me out:


https://user-images.githubusercontent.com/33497058/130307876-a5763cf0-6e15-4474-9804-adcc8792b079.mp4

2021-08-21 02:34 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/AddUserServiceAccount.tsx
> +  }, [
Please add `user` to dependency array

2021-08-22 06:34 UTC, adfost commented on portal-ui/src/screens/Console/Users/AddUserServiceAccount.tsx
> +  }, [
resolved, also I think this might have resolved the bug.

2021-08-23 18:43 UTC, dvaldivia approved these changes

2021-08-23 19:40 UTC, bexsoft requested changes
Issue still persist after multiple tries

2021-08-23 21:21 UTC, dvaldivia requested changes

2021-08-24 04:32 UTC, dvaldivia approved these changes

2021-08-24 04:35 UTC, bexsoft approved these changes
Reviewing with Daniel, this issue comes when the selected user doesn't have a policy assigned. the error comes from MinIO as 401. This will be fixed un a further version

2021-08-24 04:36 UTC, merged