Added support to object browser for file preview
minio/console pull request #995
Opened 2021-08-31 21:47 UTC by bexsoft

## What does this do?

Adds file preview support to object browser list. Support inside file details will be added in an upcoming PR

## How does it look?

<img width="1621" alt="Screen Shot 2021-08-31 at 15 29 05" src="https://user-images.githubusercontent.com/33497058/131571871-3e9b5b53-7980-443e-9d85-da7bc2ee76b6.png">
<img width="1617" alt="Screen Shot 2021-08-31 at 15 29 56" src="https://user-images.githubusercontent.com/33497058/131571874-73ffad3b-7a19-4e8d-851e-0076d220c7cd.png">
<img width="1617" alt="Screen Shot 2021-08-31 at 15 29 42" src="https://user-images.githubusercontent.com/33497058/131571878-f6e92b93-f273-4f13-a4d9-f7f0f0f7779b.png">
<img width="1427" alt="Screen Shot 2021-08-31 at 15 29 15" src="https://user-images.githubusercontent.com/33497058/131571881-942ae03e-f3af-401d-8f3c-4440e5514cbd.png">

2021-08-31 22:24 UTC, dvaldivia submitted a review, later dismissed
Tested. LGTM.

2021-08-31 23:20 UTC, harshavardhana approved these changes

2021-08-31 23:25 UTC, harshavardhana requested changes

2021-08-31 23:25 UTC, harshavardhana commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
You are downloading the object twice here? and the entire content is read into memory? how will this work?

2021-08-31 23:35 UTC, harshavardhana requested changes

2021-08-31 23:35 UTC, harshavardhana commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
You should never have to do this, you should expect that users have set the correct content-type when they are uploading the content. If they have no there is no reason to add preview's for them by adding this kind of code.

This can lead to memory crash if they click on a big video file.

2021-08-31 23:35 UTC, harshavardhana commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
You should blindly preview without doing this kind of fallback logic, it's not worth the burden for us. It is up to the user to set the correct content-type during upload - which we already do.

2021-08-31 23:41 UTC, bexsoft commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
This is done to get the correct MIME type from buffer, there was an issue with some files uploaded in console with MIME as "application/octet-stream" sometime ago (https://github.com/minio/console/issues/965). If We try to preview these objects, a download starts instead of allowing us to show them inline.

The idea here is to create a new buffer that allow us to read the correct MIME and send them in the inline header. this piece of code is duplicated as the io reader from mc returns a `io.ReadClose`, so once we read the object it is freed from memory.

If we don't do this, once I try to get the bytes response an error is thrown as stream is already closed after this validation.

2021-09-01 00:19 UTC, harshavardhana commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
No you cannot do that - you cannot buffer this kind of memory on console - you should simply expect users to have correct content-type. 

If they do not don't preview - it is easier and safer for them to re-upload with content-type instead of we fiddling with the stream.

2021-09-01 00:21 UTC, harshavardhana commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
> The idea here is to create a new buffer that allow us to read the correct MIME and send them in the inline header. this piece of code is duplicated as the io reader from mc returns a `io.ReadClose`, so once we read the object it is freed from memory.

There is no "free" memory in Go, bytes.Buffer grows memory by 2x for N sized buffer - so if you are going to preview 1GiB video file it will buffer 2GiB of pre-allocation. 

This can easily kill the GC and console server - we cannot afford to have such kind of buffer usage in console.

2021-09-01 02:20 UTC, bexsoft commented on restapi/user_objects.go
> +				detectedMIME := http.DetectContentType(buf.Bytes())
Logic changed. need to review a couple of things more

2021-09-01 03:31 UTC, harshavardhana requested changes

2021-09-01 03:31 UTC, harshavardhana commented on restapi/user_objects.go
> +				}
For this there is already something called as `filepath.Ext()` 

All you need is this

```
contentType := stat.ContentType
if contentType == "application/octet-stream" {
        contentType = mimedb.TypeByExtension(filepath.Ext(filename))
}
```

2021-09-01 03:51 UTC, bexsoft commented on restapi/user_objects.go
> +				}
nice!, will implement it, thank you!

2021-09-01 16:37 UTC, bexsoft commented on restapi/user_objects.go
> +				}
done

2021-09-01 16:50 UTC, dvaldivia approved these changes

2021-09-01 17:39 UTC, harshavardhana approved these changes

2021-09-01 17:39 UTC, merged