Upscaled Icons
minio/console pull request #996
Opened 2021-08-31 22:03 UTC by dvaldivia

<img width="255" alt="Screen Shot 2021-08-31 at 3 02 58 PM" src="https://user-images.githubusercontent.com/18384552/131581615-27aecb3f-e009-418f-a73e-f2dafb1ab06a.png">

2021-08-31 23:52 UTC, bexsoft requested changes

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Account/Account.tsx
> +                    <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/ListBuckets.tsx
> +                    <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ListObjects/ListObjects.tsx
> +                  <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Buckets/ListBuckets/Objects/ObjectDetails/ObjectDetails.tsx
> +                            <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/ConfigurationPanels/WebhookPanel.tsx
> +                  <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/NotificationEndpoints/ListNotificationEndpoints.tsx
> +                                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Configurations/TiersConfiguration/ListTiersConfiguration.tsx
> +                                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/DirectCSI/DirectCSIDrives.tsx
> +                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/DirectCSI/DirectCSIVolumes.tsx
> +                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/Groups.tsx
> +                    <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Groups/UsersSelectors.tsx
> +                        <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/pods/PodLogs.tsx
> +                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/GroupsSelectors.tsx
> +                      <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Users/ListUsers.tsx
> +                    <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Tenants/TenantDetails/PoolsSummary.tsx
> +                  <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Storage/StoragePVCs.tsx
> +                <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicySelectors.tsx
> +                      <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/PolicyDetails.tsx
> +                          <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Policies/ListPolicies.tsx
> +                    <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/ObjectBrowser/BrowseBuckets.tsx
> +                  <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-08-31 23:52 UTC, bexsoft commented on portal-ui/src/screens/Console/Logs/ErrorLogs/ErrorLogs.tsx
> +                  <SearchIcon style={{ width: 16, height: 16 }} />
Avoid using inline styling. Please try to use a class instead.

2021-09-01 22:03 UTC, bexsoft approved these changes
LGTM

2021-09-01 22:08 UTC, Alevsk approved these changes

2021-09-01 22:09 UTC, merged